<footer>
    <a href='http://www.sdis62.fr' >SDIS62 R&amp;D</a> &amp; <a href='http://www.interieur.gouv.fr' >Ministère de l'intérieur</a> &#183;
    <a href="/about/tos" >Conditions d’utilisation</a> &#183;
    <a href="/about" >À propos de</a> &#183;
    <a href="/about/dev" >Développeurs</a> &#183;
    <a href="/about/support" >Aide</a> &#183;
    © <?php echo date('Y') ?> Prevarisc
    <a style='text-decoration: none; border-bottom: 1px dotted #ccc;' href="https://github.com/SDIS62/prevarisc/commit/<?php echo $this->revision_prevarisc ?>">
        <?php echo $this->version_prevarisc ?>
    </a>
</footer>
