<footer>
    <a href='http://www.sdis62.fr' >SDIS62 R&amp;D</a> &amp; <a href='http://www.interieur.gouv.fr' >Ministère de l'intérieur</a> &#183;
    <a href="/about/tos" >Conditions d’utilisation</a> &#183;
    <a href="/about" >À propos de</a> &#183;
    <a href="/about/dev" >Développeurs</a> &#183;
    <a href="/about/support" >Aide</a> &#183;
    © <?php echo date('Y') ?> Prevarisc
    <?php $git = new SebastianBergmann\Git\Git(APPLICATION_PATH . DS . '..'); ?>
    <a style='text-decoration: none; border-bottom: 1px dotted #ccc;' href="https://github.com/SDIS62/prevarisc/commit/<?php echo end($git->getRevisions())['sha1'] ?>">
        <?php echo $git->getCurrentBranch() . '@' . substr((string)end($git->getRevisions())['sha1'], 0, 7) ?>
    </a>
</footer>
