<footer>
    <a href='http://www.sdis62.fr' >SDIS62 R&amp;D</a> &amp; <a href='http://www.interieur.gouv.fr' >Ministère de l'intérieur</a> &#183; 
    <a href="#" >Conditions d’utilisation</a> &#183; 
    <a href="https://github.com/SDIS62/prevarisc/blob/master/README.md#-propos" >À propos de</a> &#183; 
    <a href="https://github.com/SDIS62/prevarisc" >Développeurs</a> &#183; 
    <a href="#" >Aide</a> &#183; 
    © <?php echo date('Y') ?> Prevarisc
</footer>