<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/"><img src='/images/layout-header-logo.png' alt='Prevarisc'  /></a>
            <div class="nav-collapse collapse">
                <ul class='nav'>
                    <li><a href='/'><i class="icon-home grey-icn-plus" title="Accueil"></i></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Établissements
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href='/search/etablissement?label=&page=1'><i class="icon-th-list"></i> Rechercher</a></li>
                            <li><a href='/etablissement/add'><i class="icon-plus"></i> Ajouter</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Dossiers
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href='/search/dossier?objet=&page=1'><i class="icon-th-list"></i> Rechercher</a></li>
                            <li><a href='/dossier/add'><i class="icon-plus"></i> Ajouter</a></li>
                        </ul>
                    </li>
                    <li><a href='/calendrier-des-commissions'>Calendrier</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-plus grey-icn-plus" title="Plus"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href='/statistiques'>Statistiques</a></li>
                            <li><a href='/admin'>Administration</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class='nav pull-right'>
                    <li class="li-searched">
                        <form class="navbar-search" action="/search/etablissement" method="get">
                            <div class="input-append" id="research-input">
                                <input name="label" class="input-medium" id="nav-main-search-field" type="text" placeholder="Rechercher ..." style='margin-top: 10px' />
                                <input name="page" type="hidden" value="1"  />
                                <button class="btn btn_search" type="submit" style='margin-top: 10px'><i class="icon-search"></i></button>
                                <a class="btn" href="/search/etablissement?&statuts%5B%5D=2&statuts%5B%5D=4" >Avancée »</a>
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("#nav-main-search-field").autocomplete("/api/1.0/search/etablissements?format=json", {
            extraParams: {
                label: function() {
                    return $("#nav-main-search-field").val().trim();
                }
            },
            minChars: 3,
            cacheLength: 0,
            width: 500,
            parse: function(data) {
                return $.map(data["response"]["results"], function(row) {
                    return {
                        data: row,
                        value: row.LIBELLE_ETABLISSEMENTINFORMATIONS,
                        result: row.LIBELLE_ETABLISSEMENTINFORMATIONS
                    }
                });
            },
            formatItem: function(item) {
                var LIBELLE_COMMUNE = "non localisée";
                switch(item.ID_GENRE) {
                    case "1":
                        LIBELLE_COMMUNE = item.LIBELLE_COMMUNE_ADRESSE_SITE;
                        break;

                    case "3":
                        LIBELLE_COMMUNE = item.LIBELLE_COMMUNE_ADRESSE_CELLULE;
                        break;

                    default:
                        LIBELLE_COMMUNE = item.LIBELLE_COMMUNE_ADRESSE_DEFAULT;
                }

                if (LIBELLE_COMMUNE) {
                    return "[" + item.LIBELLE_GENRE + "] " + item.LIBELLE_ETABLISSEMENTINFORMATIONS + " (" + LIBELLE_COMMUNE + ")";
                }
                else {
                    return "[" + item.LIBELLE_GENRE + "] " + item.LIBELLE_ETABLISSEMENTINFORMATIONS;
                }
            }
        }).result(function(e, item) {
            window.location.href= "/etablissement/index/id/" + item.ID_ETABLISSEMENT;
        });
    });
</script>
