<!-- Onglet -->
<div id='tabs'>
	<ul>
		<li id='general'><a href='#tabs-1'>Général</a></li>
		<li id='prev'><a href='#tabs-2'>Préventionnistes affectés</a></li>
		<li id='coordonnee'><a href='#tabs-3'>Coordonnées</a></li>
		<li id='contact' ><a href='#tabs-4'>Contacts liés au groupement</a></li>
	</ul>

	<!-- Partie générale -->
	<div id="tabs-1">
	
		<dl>
			<!-- Libellé du groupement -->
			<dt>Libellé du groupement</dt>
			<dd><input type='text' id='nom_groupement' name='nom_groupement' value='<?php echo htmlspecialchars($this->libelle, ENT_QUOTES) ?>' size=30 /></dd>

			<!-- Type du groupement-->
			<dt>Type</st>
			<dd>
				<select id='type_groupement' name='type_groupement'>
				<?php
					foreach($this->types as $value)
						echo "<option id='".$value["ID_GROUPEMENTTYPE"]."' value='".$value["ID_GROUPEMENTTYPE"]."' ".( ($value["ID_GROUPEMENTTYPE"] == $this->type)?"selected":"" )." >".$value["LIBELLE_GROUPEMENTTYPE"]."</option>";
				?>
				</select>
			</dd>
		
			<!-- Liste des villes -->
			<dt>Villes du groupement</dt>
			<dd>
				<select id='liste_villes' class='grid_5 alpha' multiple size=20 style='height: 300px; width: 45%;'>
					<?php
                            foreach($this->villes as $value) {
						
                                echo "<option id='".$value["NUMINSEE_COMMUNE"]."' value='".$value["NUMINSEE_COMMUNE"]."'>".$value["NUMINSEE_COMMUNE"]." ".$value["LIBELLE_COMMUNE"]."</option>";
                            }
					?>
				</select>

				<div class='grid_1' style='text-align: center;'>
					<button id='add_ville'>Ajouter</button><br/><br/>
					<button id='remove_ville'>Supprimer</button>
				</div>

				<select id='villes_groupement' name='villes[]' class='grid_5 omega' multiple size=20 style='height: 300px; width: 45%;'>
					<?php
                        if(is_array($this->ville_du_groupement))
                        {
                            foreach($this->ville_du_groupement as $value) {
					
                                echo "<option id='".$value["NUMINSEE_COMMUNE"]."' value='".$value["NUMINSEE_COMMUNE"]."' >".$value["NUMINSEE_COMMUNE"]." ".$value["LIBELLE_COMMUNE"]."</option>";
                            }
                        }
					?>
				</select>
			</dd>
		</dl>
		
	</div>

	<!-- Partie des préventionnistes -->
	<div id="tabs-2">
	
		<br />
	
		<!-- Ajouter un préventionniste -->
		<input type='text' size='60' id='preventionnistes-autocomplete' value=''  />
		
		<hr class='clear' />
		
		<!-- Afficher la liste des prev. -->
		<ul class='liste_informations' id='liste_prev'>
		
			<?php foreach($this->preventionnistes as $preventionniste) : ?>
			
				<li id='prev_<?php echo $preventionniste["ID_UTILISATEUR"] ?>'>
					<span ><a href='/user/profile/uid/<?php echo $preventionniste["ID_UTILISATEUR"]; ?>'><?php echo $preventionniste["NOM_UTILISATEURINFORMATIONS"]." ".$preventionniste["PRENOM_UTILISATEURINFORMATIONS"] ?></a></span>
					<span class='action' style='float: right' ><a style='text-decoration: none;' href='javascript:void(0)' onclick=" $(this).parent().parent().remove() ">&times;</a></span>
					<input type='hidden' name='prev[]' value='<?php echo $preventionniste["ID_UTILISATEUR"]; ?>' />
				</li>
				
			<?php endforeach	?>
			
		</ul>

	</div>
	
	<!-- Coordonnées -->
	<div id='tabs-3'>

		<?php echo $this->action('form', 'contact', null, array("item" => "groupement_coord")) ?>
	
	</div>

	<!-- Partie contact -->
	<div id="tabs-4"></div>
	
	<hr class='clear' />

</div>

<script type="text/javascript">

	// Onglets
	$( "#tabs" ).tabs();
		
	// Sauvegarde de l'adresse
	/*
	$("#dialog-adresse").dialog({
		title: "Ajout d'adresse",
		autoOpen: false,
		autoResize: true,
		width: 600,
		position: 'center',
		draggable: false,
		resizable: false,
		buttons: {
			"Ajouter cette adresse": function() {

				var geocoder = new GClientGeocoder();
				geocoder.getLatLng (
					$("#adresse-numero").val() + " " + $("#adresse-voie option:selected").text() + " " + $("#adresse-code_postal").val() + " " + $("#adresse-ville option:selected").text(),
					function(point) {
						if (point) {
						
							$n = $("#prototype_adresses").clone().appendTo( $("#prototype_adresses").parent() ).removeClass('ui-helper-hidden').attr('id', '');
							$n.find("input[name='LAT_ETABLISSEMENTADRESSE[]']").val( point.lat() );
							$n.find("input[name='LON_ETABLISSEMENTADRESSE[]']").val( point.lng() );
							$n.find("input[name='NUMERO_ADRESSE[]']").val( $("#adresse-numero").val() );
							$n.find("input[name='ID_RUE[]']").val( $("#adresse-voie option:selected").val() );
							$n.find("input[name='NUMINSEE_COMMUNE[]']").val( $("#adresse-ville option:selected").val() );
							$n = $n.find("input[name='COMPLEMENT_ADRESSE[]']").val( $("#adresse-complement_adresse").val() );
							$n.next().append( $("#adresse-numero").val() + " " + $("#adresse-voie option:selected").text() + " " + $("#adresse-code_postal").val() + " " + $("#adresse-ville option:selected").text() + " " + $("#adresse-complement_adresse").val() );
						}
					}
				);
				
				$( this ).dialog( "close" );
			},
			"Annuler": function() {
				$("#adresse-voie-ac, #adresse-code_postal, #adresse-voie-ac, #adresse-numero, #adresse-complement_adresse").val("").blur();
				$("#adresse-ville, #adresse-voie").find("option").remove();
				$( this ).dialog( "close" );
			}
		}
	});
	*/
	// Ajouter une ville
	$("#add_ville").button({
		icons: { primary: "ui-icon-arrowthick-1-e" }, text: false, disabled: true
	}).click(function() {
		$('#liste_villes option:selected').each( function() {
			$("#villes_groupement").append( $("<option></option>").val( $(this).val() ).html( $(this).text() ) );
			$(this).attr("disabled","disabled").attr("selected", "");
		});
		$('#liste_villes').change();
		return false;
	});
	
	// Enlever une ville
	$("#remove_ville").button({
		icons: { primary: "ui-icon-arrowthick-1-w" }, text: false, disabled: true
	}).click(function() {
		$('#villes_groupement option:selected').each( function() {
			$(this).remove();
			$("#liste_villes option[value=" + $(this).val() + "]").attr("disabled","").attr("selected", "selected");
		});
		$('#liste_villes').change();
		$('#villes_groupement').change();
		return false;
	});
	
	// Gestion des boutons du milieux
	$("#liste_villes, #villes_groupement").change(function() {
		if( $(this).children(":selected").size() == 0 )
			$( (($(this).attr("id") == "liste_villes") ? "#add_ville" : "#remove_ville") ).button("disable");
		else
			$( (($(this).attr("id") == "liste_villes") ? "#add_ville" : "#remove_ville") ).button("enable");
	});

	// Partie prev ----------------------------------------------------------------------------------------------------------------
	
	// Texte de l'auto complete utilisateurs
	$("#preventionnistes-autocomplete").toggleText("Saisissez le nom d'un préventionniste ...");
	$("#preventionnistes-autocomplete").autocomplete("/user/getpreventionniste?format=json", {
		minChars: 3,
		max: 100,
		parse: function(data) {
			return $.map(data["resultats"], function(row) {
				return {
					data: row,
					value: row.NOM_UTILISATEURINFORMATIONS,
					result: row.NOM_UTILISATEURINFORMATIONS
				}
			});
		},
		formatItem: function(item) {
			return item.NOM_UTILISATEURINFORMATIONS + " " + item.PRENOM_UTILISATEURINFORMATIONS;
		}
	}).result(function(e, item) {
		$("#liste_prev").append("<li><span class='action' style='float: right'><a style='text-decoration: none;' href='' onclick='$(this).parent().parent().remove(); return false;'>&times;</a></span>"
							 +"<span class='valeur'><a href='/user/profile/uid/"  + item.uid + "'>" + item.NOM_UTILISATEURINFORMATIONS + " " + item.PRENOM_UTILISATEURINFORMATIONS + "</a></span>"
							 +"<input type='hidden' name='prev[]' value='" + item.uid + "' /></li>");
		$("#preventionnistes-autocomplete").val("");
	});
	
	// Partie Contact ----------------------------------------------------------------------------------------------------------------
	$("#tabs-4").load("/contact?item=groupement&id=<?php echo $_GET["id"] ?>");
	
	// On cache les villes déjà selectionnées
	$("#villes_groupement option").each( function() {
		$( "#liste_villes option[id='" + $(this).attr("id")  + "']" ).attr("disabled","disabled");
	});
	
</script>