<!-- Onglet -->
<div id='tabs'>
	<ul>
		<li id='general'><a href='#tabs-1'>Général</a></li>
		<li id='prev'><a href='#tabs-2'>Préventionnistes affectés</a></li>
		<li id='coordonnee'><a href='#tabs-3'>Coordonnées</a></li>
		<li id='contact' ><a href='#tabs-4'>Contacts liés au groupement</a></li>
	</ul>

	<!-- Partie générale -->
	<div id="tabs-1">

		<dl class='dl-horizontal'>

			<!-- Libellé du groupement -->
			<dt>Libellé du groupement</dt>
			<dd><input type='text' id='nom_groupement' name='nom_groupement' value='<?php echo htmlspecialchars($this->libelle, ENT_QUOTES) ?>' size=30 /></dd>

			<!-- Type du groupement-->
			<dt>Type</st>
			<dd>
				<select id='type_groupement' name='type_groupement'>
				<?php
					foreach($this->types as $value)
						echo "<option id='".$value["ID_GROUPEMENTTYPE"]."' value='".$value["ID_GROUPEMENTTYPE"]."' ".( ($value["ID_GROUPEMENTTYPE"] == $this->type)?"selected":"" )." >".$value["LIBELLE_GROUPEMENTTYPE"]."</option>";
				?>
				</select>
			</dd>

			<!-- Liste des villes -->
			<dt>Villes du groupement</dt>
			<dd>
				<select id='liste_villes' multiple size=20 class='pull-left' style='height: 300px; width: 30%;'>
					<?php
                    foreach($this->villes as $value) {

                        echo "<option id='".$value["NUMINSEE_COMMUNE"]."' value='".$value["NUMINSEE_COMMUNE"]."'>".$value["NUMINSEE_COMMUNE"]." ".$value["LIBELLE_COMMUNE"]."</option>";
                    }
					?>
				</select>

                <div class="pull-left btn-group btn-group-vertical" style='padding: 20px;'>
                    <button id='add_ville' type="button" class="btn"><i class="icon-chevron-right"></i></button>
                    <button id='remove_ville' type="button" class="btn"><i class="icon-chevron-left"></i></button>
                </div>

				<select id='villes_groupement' name='villes[]' class='pull-left' multiple size=20 style='height: 300px; width: 30%;'>
					<?php
                        if(is_array($this->ville_du_groupement))
                        {
                            foreach($this->ville_du_groupement as $value) {

                                echo "<option id='".$value["NUMINSEE_COMMUNE"]."' value='".$value["NUMINSEE_COMMUNE"]."' >".$value["NUMINSEE_COMMUNE"]." ".$value["LIBELLE_COMMUNE"]."</option>";
                            }
                        }
					?>
				</select>
			</dd>

		</dl>

	</div>

	<!-- Partie des préventionnistes -->
	<div id="tabs-2">

		<br />

		<!-- Ajouter un préventionniste -->
		<input type='text' size='60' id='preventionnistes-autocomplete' value='' class='input-xlarge' placeholder="Saisissez le nom d'un préventionniste ..."  />

		<hr class='clear' />

		<!-- Afficher la liste des prev. -->
		<ul class='liste_informations' id='liste_prev'>

			<?php foreach($this->preventionnistes as $preventionniste) : ?>

				<li id='prev_<?php echo $preventionniste["ID_UTILISATEUR"] ?>'>
					<span ><a href='/user/profile/uid/<?php echo $preventionniste["ID_UTILISATEUR"]; ?>'><?php echo $preventionniste["GRADE_UTILISATEURINFORMATIONS"]." ".$preventionniste["NOM_UTILISATEURINFORMATIONS"]." ".$preventionniste["PRENOM_UTILISATEURINFORMATIONS"] ?></a></span>
					<span class='action' style='float: right' ><a style='text-decoration: none;' href='javascript:void(0)' onclick=" $(this).parent().parent().remove() ">&times;</a></span>
					<input type='hidden' name='prev[]' value='<?php echo $preventionniste["ID_UTILISATEUR"]; ?>' />
				</li>

			<?php endforeach	?>

		</ul>

	</div>

	<!-- Coordonnées -->
	<div id='tabs-3'>
		<?php echo $this->action('form', 'contact', null, array("item" => "groupement_coord")) ?>
	</div>

	<!-- Partie contact -->
	<div id="tabs-4"></div>

</div>

<script type="text/javascript">

	// Onglets
	$( "#tabs" ).tabs();

	// Ajouter une ville
	$("#add_ville").click(function() {
		$('#liste_villes option:selected').each( function() {
			$("#villes_groupement").append( $("<option></option>").val( $(this).val() ).html( $(this).text() ) );
			$(this).attr("disabled","disabled").removeAttr("selected");
		});
		$('#liste_villes').change();
		return false;
	});

	// Enlever une ville
	$("#remove_ville").click(function() {
		$('#villes_groupement option:selected').each( function() {
			$(this).remove();
			$("#liste_villes option[value=" + $(this).val() + "]").removeAttr("disabled");
		});
		$('#liste_villes').change();
		$('#villes_groupement').change();
		return false;
	});

	// Gestion des boutons du milieux
	$("#liste_villes, #villes_groupement").change(function() {
		if( $(this).children(":selected").size() == 0 )
			$( (($(this).attr("id") == "liste_villes") ? "#add_ville" : "#remove_ville") ).button("disable");
		else
			$( (($(this).attr("id") == "liste_villes") ? "#add_ville" : "#remove_ville") ).button("enable");
	});

	// Partie prev ----------------------------------------------------------------------------------------------------------------

	// Auto-complétion des préventionnistes
	$("#preventionnistes-autocomplete").typeahead({
		minLength: 3,
		source: function(query, process) {
			return $.ajax({
				url: "/api/1.0/search/users",
				type: 'post',
				data: {
					name: query,
					fonctions: 13,
					limit: 100,
				},
				success: function (result) {
					preventionnistes = [];
					$.each(result.response.results, function (i, preventionniste) {
						preventionnistes.push("<span data-id='" + preventionniste.uid + "'>" + preventionniste.NOM_UTILISATEURINFORMATIONS + " " + preventionniste.PRENOM_UTILISATEURINFORMATIONS + "</span>");
					});

					process(preventionnistes);
				}
			});
		},
		highlighter: function (item) {
			libelle = $($.parseHTML(item)).last().text();
			libelle = libelle.replace( new RegExp( '(' + this.query + ')', 'gi' ), "<strong>$1</strong>" );
			html = $.parseHTML(item);
			$(html).last().text(libelle);
			html = $(html).text();
			return item.replace( item, html );
		},
		updater: function (item) {
			var nom = $($.parseHTML(item)).last().text();
			var id = $($.parseHTML(item)).last().data('id');

			$("#liste_prev").append("<li><span class='action' style='float: right'><a style='text-decoration: none;' href='' onclick='$(this).parent().parent().remove(); return false;'>&times;</a></span>"
				+"<span class='valeur'><a href='/user/profile/uid/"  + id + "'>" + nom + "</a></span>"
				+"<input type='hidden' name='prev[]' value='" + id + "' /></li>");

			return;
		}
	});

	// Partie Contact ----------------------------------------------------------------------------------------------------------------
	$("#tabs-4").load("/contact?item=groupement&id=<?php echo $_GET["id"] ?>");

	// On cache les villes déjà selectionnées
	$("#villes_groupement option").each( function() {
		$( "#liste_villes option[id='" + $(this).attr("id")  + "']" ).attr("disabled","disabled");
	});

</script>
