<h3 float='left' >Descriptif de l'établissement</h3>

<!-- Boutons -->
<div float='right' >
	
	<button id='modifier_button'>Modifier</button>
	<button id='back_button'>Revenir au mode lecture</button>
	<button id='cancel_button'>Annuler</button>
	<button style='margin: 0; border-right: none' id='save_button'>Sauvegarder</button><button style='margin: 0' id='save_historique_button'>Sauvegarder & historiser</button>
	
	<p id='notification_wait' class='ui-helper-hidden' style='margin-top: 0.7em; float: right; '>
		<img src='/images/template/load/load.gif' alt='' />
	</p>
	
	<p id='notification_sauvegarde' class='ui-state-highlight <?php if( !$_GET["confirm"] ) echo "ui-helper-hidden"; ?>' style='padding: .5em; margin-bottom: 1em; float: right; '>
		La fiche établissement à bien été sauvegardé.
	</p>
	
	<p id='notification_erreur' class='ui-state-error ui-helper-hidden' style='padding: .5em; margin-bottom: 1em; float: right; '>
		L'enregistrement ne s'est pas effectué correctement.
	</p>
</div>

<br class='clear' />

<h4>Descriptif général</h4>
<textarea name='' id='descriptif_general' cols='' rows='' style='width: 100%' ></textarea>

<h4>Descriptif technique</h4>

<?php if(  Zend_Json::decode($this->genre) == "Établissement"
		|| Zend_Json::decode($this->genre) == "Cellule"
		|| Zend_Json::decode($this->genre) == "IGH" ) : ?>
<h4>Tableau des effectifs</h4>

<h5>Théorique</h5>
<form>
	<?php echo $this->partial("etablissement/partials/partial-tableau-effectifs.phtml") ?>
</form>

<h5>Réél</h5>
<?php echo $this->partial("etablissement/partials/partial-tableau-effectifs.phtml") ?>

<?php endif ?>

<script type="text/javascript">
	
	$("#descriptif_general").elastic();
	$("#save_button").button().hide();
	$("#save_historique_button").button().hide();
	$("#modifier_button").button();
	$("#back_button").button().hide();
	$("#cancel_button").button().hide();
	
</script>