<div class='pull-right' >
    <a data-toggle="modal" data-target="#reponse-modal" class='btn' href="<?php echo $this->url(array('action' => 'edit-descriptif')) ?>">Modifier les descriptifs</a>
</div>

<h3>Descriptif de l'établissement</h3>

<h4>Historique de l'établissement</h4>
<p><?php echo empty($this->historique) ? "Aucun historique disponible pour cet établissement." : nl2br($this->historique) ?></p>

<h4>Descriptif général</h4>
<p><?php echo empty($this->descriptif) ? "Aucun descriptif disponible pour cet établissement." : nl2br($this->descriptif) ?></p>

<h4>Dérogations accordées</h4>
<p><?php echo empty($this->derogations) ? "Aucunes dérogations accordées pour cet établissement." : nl2br($this->derogations) ?></p>

<h4>Descriptif technique</h4>
<div class='row-fluid'>
	<?php
		$i = 0;

	    foreach($this->champs_descriptif_technique as $title => $champ_destech)
	    {
	    	$j = 0;
	    	echo '<div class="span4">';
	        echo "<h5 class='lead'>".$title."</h5>";
	        echo "<dl>";

	        foreach($champ_destech as $key => $value)
	        {
	            if(!$value['value'] == null && !$value['value'] == 0)
	            {
	            	echo "<dt>".$key."</dt>";
	                echo "<dd>" . $value['type'] == 'tinyint' ? ( $value['value'] == 1 ? 'Oui' : 'Non') : $value['value'] . "</dd>";
	                $j++;
	            }
	        }

	        echo "</dl>";
	       
	        if($j == 0) {
	        	echo "<p class='muted'>Aucune donnée disponible</p>";
	        }
        	$j = 0;

        	 echo '</div>';

	        $i++;
            
            if($i == 3) {
            	echo "</div> <div class='row-fluid' >";
            	$i = 0;
            }
	    }
	?>
</div>

<!-- Blocs pour les contenus ajax -->
<div id="reponse-modal" class="modal hide fade"></div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        $("a[data-toggle='modal']").click(function() {
            var target = $(this).attr("data-target");
            var url = $(this).attr("href");
            $(target).load(url);
        });
    }, false);
</script>