<h3 class='pull-left' >Descriptif de l'établissement</h3>

<!-- Boutons -->
<div class='pull-right' >
	
	<div class="read">
		<button id='modifier_button' class='btn'>Modifier</button>
	</div>
	
	<div class="edit">
		<button id='cancel_button' class='btn'>Annuler</button>
		<button id='save_button' class="save btn" >Sauvegarder</button>
	</div>
	
</div>

<div style='clear: both' ></div>

<h4>Descriptif général</h4>

<div class="read">
	<p><?php echo empty($this->DB_etablissement->DESCRIPTIF_ETABLISSEMENT) ? "Aucun descriptif disponible pour cet établissement." : nl2br($this->DB_etablissement->DESCRIPTIF_ETABLISSEMENT) ?></p>
</div>

<form class="edit" id="descriptif" action="" method="POST" >
	<textarea name='DESCRIPTIF_ETABLISSEMENT' id='descriptif_general' cols='' rows='' style='width: 100%; height: 250px;' ><?php echo $this->DB_etablissement->DESCRIPTIF_ETABLISSEMENT ?></textarea>
</form>

<h4>Descriptif technique</h4>
    <?php
        foreach($this->champs_descriptif_technique as $title => $champ_destech)
        {
            echo "<h5>".$title."</h5>";
            echo "<dl>";
            foreach($champ_destech as $key => $value)
            {
                echo "<dt>".$key."</dt>";
                if($value['value'] == null)
                {
                    echo "<dd class='muted'>Aucune donnée</dd>";
                }
                else
                {
                    echo "<dd>" . $value['type'] == 'tinyint' ? ( $value['value'] == 1 ? 'Oui' : 'Non') : $value['value'] . "</dd>";
                }
            }
            echo "</dl>";
        }
    ?>
<form class="edit" id="descriptif_technique" action="" method="POST" >
    
    <h5></h5>
</form>

<script type="text/javascript">

	$("#descriptif_general").elastic();
	
	$("#modifier_button").click(function() {
		$(".read").hide();
		$(".edit").show();
	});
	
	$("#cancel_button").click(function() {
		window.location.reload();
	});
	
	$("#save_button").click(function() {
		$("#descriptif").submit();
	});
	
	$(".edit").hide();
	
</script>