<div class='pull-right' >
    <a class='btn' href="<?php echo $this->url(array('controller' => 'dossier', 'action' => 'add', 'id_etablissement' => $this->etablissement['general']['ID_ETABLISSEMENT']), null, true) ?>">Ajouter un dossier</a>
</div>

<h3>Liste des dossiers</h3>

<?php if(count($this->visites) == 0 && count($this->etudes) == 0 && count($this->autres) == 0) : ?>
    <div class='well well-large text-center'>
        <p class='lead'>Il n'y a pas de dossier.</p>
        <p><a href='<?php echo $this->url(array('controller' => 'dossier', 'action' => 'add', 'id_etablissement' => $this->etablissement['general']['ID_ETABLISSEMENT']), null, true) ?>' class='btn btn-large'>Ajouter un dossier</a></p>
    </div>
<?php else : ?>

<div id="content_visites_ets">
<?php if( count($this->visites) > 0 ) : ?>
    <h4>Visites</h4>
    <ul class='recherche_liste'>
    <?php echo $this->partialLoop('search/results/dossier.phtml', $this->visites); ?>
    </ul>
<?php endif ?>
</div>

<div id="content_etudes_ets">
<?php if( count($this->etudes) > 0 ) : ?>
    <?php if( count($this->visites) > 0 ) echo "<hr />"; ?>
    <h4>Études</h4>
    <ul class='recherche_liste'>
    <?php echo $this->partialLoop('search/results/dossier.phtml', $this->etudes);  ?>
    </ul>
<?php endif ?>
</div>

<div id="content_autres_ets">
<?php if( count($this->autres) > 0 ) : ?>
    <?php if( count($this->visites) > 0 || count($this->etudes) > 0) echo "<hr />"; ?>
    <h4>Autres</h4>
    <ul class='recherche_liste'>
    <?php echo $this->partialLoop('search/results/dossier.phtml', $this->autres);  ?>
    </ul>
<?php endif ?>
</div>
<?php endif ?>

<script>
    $(document).ready(function() {
        // Affichage des dossiers enfants
        $("ul.recherche_liste li.slide").live("click", function() {
            var container = this;
            if( $(this).hasClass("active") ) {
                $(this).next().slideUp(400, function() {$(container).next().remove()});
                $(this).toggleClass("active");
            }
            else {
                $(container).find(".load").show();
                $.post("/search/display-ajax-search-dossier", {parent: $(this).attr("id")}, function(html) {
                    $(container).toggleClass("active").find(".load").hide();
                    $(container).after("<li class='ui-helper-hidden' style='overflow: auto; height: auto;' >" + html + "</li>").next().slideDown();
                });
            }
        });
    });
</script>
