<p style='float: right;'><a href='/dossier?id_etablissement=<?php echo $this->DB_etablissement["ID_ETABLISSEMENT"] ?>'>+ Créer un nouveau dossier</a></p>

<hr class='clear' />

<div id="content_dossiers_ets">
<?php if( count($this->dossiers) > 0 ) : ?>
    <ul id="liste_doss">
    <?php
	echo $this->partialLoop('search/results/dossier.phtml', $this->dossiers); 
    ?>
    </ul>
<?php endif ?>
</div>