<div class='pull-right' >
    <a class='btn' href="<?php echo $this->url(array('controller' => 'dossier', 'id_etablissement' => $this->etablissement['general']['ID_ETABLISSEMENT']), null, true) ?>">Ajouter un dossier</a>
</div>

<h3>Liste des dossiers</h3>

<?php if(count($this->visites) == 0 && count($this->etudes) == 0 && count($this->autres) == 0) : ?>
    <div class='well well-large text-center'>
        <p class='lead'>Il n'y a pas de dossiers pour cet établissement.</p>
        <p><a href='<?php echo $this->url(array('controller' => 'dossier', 'id_etablissement' => $this->etablissement['general']['ID_ETABLISSEMENT']), null, true) ?>' class='btn btn-large'>Ajouter un dossier</a></p>
    </div>
<?php else : ?>

<div id="content_visites_ets">
<?php if( count($this->visites) > 0 ) : ?>
    <h4>Visites</h4>
    <ul class='recherche_liste'>
    <?php echo $this->partialLoop('search/results/dossier.phtml', $this->visites); ?>
    </ul>
<?php endif ?>
</div>

<div id="content_etudes_ets">
<?php if( count($this->etudes) > 0 ) : ?>
    <?php if( count($this->visites) > 0 ) echo "<hr />"; ?>
    <h4>Études</h4>
    <ul class='recherche_liste'>
    <?php echo $this->partialLoop('search/results/dossier.phtml', $this->etudes);  ?>
    </ul>
<?php endif ?>
</div>

<div id="content_autres_ets">
<?php if( count($this->autres) > 0 ) : ?>
    <?php if( count($this->visites) > 0 || count($this->etudes) > 0) echo "<hr />"; ?>
    <h4>Autres</h4>
    <ul class='recherche_liste'>
    <?php echo $this->partialLoop('search/results/dossier.phtml', $this->autres);  ?>
    </ul>
<?php endif ?>
</div>
<?php endif ?>

<script>
    $(document).ready(function() {
        $(".slide").live("click", function() {       
            var container = this;
            if( $(this).hasClass("active") ) {
                $(container).next().slideUp(400, function() {$(container).next().remove()});
                $(container).toggleClass("active");
            }
            else {
                $.ajax({
                    url: "/search/search-child-doss?format=json&id="+$(this).attr("id"),
                    beforeSend: function() {
                        $(container).find(".load").show();
                    },
                    success: function( result ) {
                        $(container).find(".load").hide();
                        $(container).after("<li class='ui-helper-hidden' >" + result.html + "</li>").next().slideDown();
                        $(container).toggleClass("active");
                    }
                });
            }
        });
    });
</script>