<form action='<?php echo $this->url(array('action' => 'edit-descriptif')) ?>' method='post'>

    <div class='pull-right' >
        <div class="btn-group">
            <a class='btn' href="<?php echo $this->url(array('action' => 'descriptif')) ?>">Annuler la modification</a>
            <input type='submit' class="btn btn-success" value='Sauvegarder'>
        </div>
    </div>

    <h3>Modification des descriptifs</h3>

    <h4 class='h4_subtitle'>Historique de l'établissement</h4>
    <textarea name='historique' cols='' rows='' style='width: 100%; height: 100px;' ><?php echo $this->historique ?></textarea>

    <h4 class='h4_subtitle'>Descriptif</h4>
    <textarea name='descriptif' cols='' rows='' style='width: 100%; height: 100px;' ><?php echo $this->descriptif ?></textarea>

    <h4 class='h4_subtitle'>Dérogations accordées</h4>
    <textarea name='derogations' cols='' rows='' style='width: 100%; height: 100px;' ><?php echo $this->derogations ?></textarea>

    <h4 class='h4_subtitle'>Descriptif technique</h4>
    <?php
        foreach($this->champs_descriptif_technique as $title => $champ_destech) {
            echo "<h5 class='lead'>".$title."</h5>";
            echo "<dl>";
            foreach($champ_destech as $key => $value) {
                echo "<dt>".$key."</dt>";
                echo "<dd>";

                switch($value['type']) {
                    case 'tinyint':
                        echo "<input type='hidden' name='descriptifs_techniques[" . $value['key'] . "]' value='0' />";
                        echo "<input type='checkbox' name='descriptifs_techniques[" . $value['key'] . "]' " . ($value['value'] == 1 ? 'checked' : '') . " value='1' />";
                        break;

                    case 'int':
                        echo "<input type='number' name='descriptifs_techniques[" . $value['key'] . "]' value='" . ($value['value'] == '' ? '0' : $value['value']) . "' />";
                        break;

                    case 'text':
                        echo "<textarea name='descriptifs_techniques[" . $value['key'] . "]' cols='' rows='' style='width: 100%; height: 50px;' >" . $value['value'] . "</textarea>";
                        break;

                    default:
                        echo "<input type='text' name='descriptifs_techniques[" . $value['key'] . "]' value='" . $value['value'] . "' />";
                }

                echo "</dd>";
            }
            echo "</dl>";
        }
    ?>
    <script type="text/javascript">
         // Ajouter les exemples de risques naturels et technologiques
         
       
         // Recherche des risques naturels et technologiques en variables d'environnement
         <?php 
         if (getenv('PREVARISC_RISQUES_NATURELS_EXEMPLES') != false){
            $risques_naturels = getenv('PREVARISC_RISQUES_NATURELS_EXEMPLES');
         } else $risques_naturels = "Avalanche, Cyclonique, Feux de Forêt, Inondation, Mouvement de terrain, Sismique, Submersion marine, Tempête, Volcanique";
         $risques_naturels = "<i>Exemples de risques naturels : " . $risques_naturels . "</i>";
         if (getenv('PREVARISC_RISQUES_TECHNOLOGIQUES_EXEMPLES') != false){
            $risques_technologiques = getenv('PREVARISC_RISQUES_TECHNOLOGIQUES_EXEMPLES');
         } else $risques_technologiques = "Industriel, Nucléaire, Rupture de barrage, Transport de matières dangereuses";
         $risques_technologiques = "<i>Exemples de risques technologiques : " . $risques_technologiques . "</i>";
          
         ?>
         $('textarea[name="descriptifs_techniques[DESCTECH_RISQUES_NATURELS_ETABLISSEMENT]"]').after("<?php echo $risques_naturels ?>");
         $('textarea[name="descriptifs_techniques[DESCTECH_RISQUES_TECHNOLOGIQUES_ETABLISSEMENT]"]').after("<?php echo $risques_technologiques ?>");
    </script>
</form>