<form class="modal" action='<?php echo $this->url(array('action' => 'edit-textes-applicables')) ?>' method='post'>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Modification des Textes applicables</h3>
    </div>
    <div class="modal-body">
        <?php foreach($this->textes_applicables as $titre => $textes_applicables) : ?>
            <h4><?php echo $titre ?></h4>
            <?php foreach($textes_applicables as $texte_applicable) : ?>
                <p>
                    <input type="hidden" name="textes_applicables[<?php echo $texte_applicable['ID_TEXTESAPPL'] ?>]" value='0' />
                    <input type="checkbox" name="textes_applicables[<?php echo $texte_applicable['ID_TEXTESAPPL'] ?>]" value='1' <?php echo in_array($texte_applicable, $this->textes_applicables_de_etablissement) ? "checked" : ""  ?> />
                    <span style="<?php echo in_array($texte_applicable, $this->textes_applicables_de_etablissement) ? "font-weight: bold" : ""  ?>">
                        <?php echo $texte_applicable['LIBELLE_TEXTESAPPL'] ?>
                    </span>
                </p>
            <?php endforeach ?>
        <?php endforeach ?>
    </div>
    <div class="modal-footer">
        <a href="#" data-dismiss="modal" class="btn">Annuler</a>
        <input type='submit' id='submit' value='Sauvegarder' class='btn btn-success' />
    </div>
</div>