<form action='<?php echo $this->url(array('action' => 'edit-descriptif')) ?>' method='post'>

    <div class='pull-right' >
        <div class="btn-group">
            <a class='btn' href="<?php echo $this->url(array('action' => 'descriptif')) ?>">Annuler la modification</a>
            <input type='submit' class="btn btn-success" value='Sauvegarder'>
        </div>
    </div>

    <h3>Modification des descriptifs</h3>

    <h4 class='h4_subtitle'>Historique de l'établissement</h4>
    <textarea name='historique' cols='' rows='' style='width: 100%; height: 100px;' ><?php echo $this->historique ?></textarea>

    <h4 class='h4_subtitle'>Descriptif</h4>
    <textarea name='descriptif' cols='' rows='' style='width: 100%; height: 100px;' ><?php echo $this->descriptif ?></textarea>

    <h4 class='h4_subtitle'>Dérogations accordées</h4>
    <textarea name='derogations' cols='' rows='' style='width: 100%; height: 100px;' ><?php echo $this->derogations ?></textarea>

    <h4 class='h4_subtitle'>Descriptif technique</h4>
    <?php
        foreach($this->champs_descriptif_technique as $title => $champ_destech) {
            echo "<h5 class='lead'>".$title."</h5>";
            echo "<dl>";
            foreach($champ_destech as $key => $value) {
                echo "<dt>".$key."</dt>";
                echo "<dd>";

                switch($value['type']) {
                    case 'tinyint':
                        echo "<input type='hidden' name='descriptifs_techniques[" . $value['key'] . "]' value='0' />";
                        echo "<input type='checkbox' name='descriptifs_techniques[" . $value['key'] . "]' " . ($value['value'] == 1 ? 'checked' : '') . " value='1' />";
                        break;

                    case 'int':
                        echo "<input type='number' name='descriptifs_techniques[" . $value['key'] . "]' value='" . ($value['value'] == '' ? '0' : $value['value']) . "' max='2147483647' required />";
                        break;

                    case 'text':
                        echo "<textarea name='descriptifs_techniques[" . $value['key'] . "]' cols='' rows='' style='width: 100%; height: 50px;' maxlength='65535' >" . $value['value'] . "</textarea>";
                        break;
                    
                    case 'char':
                        echo "<input type='text' name='descriptifs_techniques[" . $value['key'] . "]' value='" . $value['value'] . "' maxlength='" . $value['length'] . "' />";
                        break;

                    default:
                        echo "<input type='text' name='descriptifs_techniques[" . $value['key'] . "]' value='" . $value['value'] . "' />";
                }
                
                switch($value['key']) {
                    
                    case 'DESCTECH_RISQUES_NATURELS_ETABLISSEMENT': 
                        $risques_naturels = "Avalanche, Cyclonique, Feux de Forêt, Inondation, Mouvement de terrain, Sismique, Submersion marine, Tempête, Volcanique";
                        echo "<i>Exemples de risques naturels : $risques_naturels</i>";
                        break;
                        
                    case 'DESCTECH_RISQUES_TECHNOLOGIQUES_ETABLISSEMENT': 
                        $risques_technologiques = "Industriel, Nucléaire, Rupture de barrage, Transport de matières dangereuses";
                        echo "<i>Exemples de risques technologiques : $risques_technologiques</i>";
                        break;
                }

                echo "</dd>";
            }
            echo "</dl>";
        }
    ?>
</form>
