<div id='index-left' class='grid_3 alpha' />
	<ul>
		<li class='active'><a href='' id='a_all' >Voir tout</a></li>
	</ul>
	
	<fieldset>
		<ul>
			<li><a href='' id='a_libelle' >Historique du libellé</a></li>
			<li><a href='' id='a_statut' >Historique du statut</a></li>
			<li><a href='' id='a_avis' >Historique de l'avis</a></li>
			
			<?php if( in_array("categorie", $this->classement) ) : ?>
			<li><a href='' id='a_categorie' >Historique de la catégorie</a></li>
			<?php endif ?>
			
			<?php if( in_array("famille", $this->classement) ) : ?>
			<li><a href='' id='a_famille' >Historique de la famille</a></li>
			<?php endif ?>
			
			<?php if( in_array("classe", $this->classement) ) : ?>
			<li><a href='' id='a_classe' >Historique de la classe</a></li>
			<?php endif ?>
			
			<li><a href='' id='a_type' >Historique du type principal</a></li>
		</ul>
	</fieldset>
</div>

<script type="text/javascript">
	$("#index-left a").click(function() {
	
		$("#index-left ul li").removeClass("active");
		$(this).parent().addClass("active");
		
		var array = $(this).attr("id").split('_');
		
		if(array[1] == "all") {
			$("#content_historique > div").show();
		}
		else {
			$("#content_historique > div").hide();
			$("#content_historique > div#div_" + array[1]).show();
		}
		
		return false;
	});
	
</script>

<div id='content_historique' class='grid_13 omega' />

	<div id='div_libelle'>
		<h3>Historique du libellé</h3>
		<?php
			echo $this->partial(
				"etablissement/partials/partial-historique.phtml",
				array(
					"array" => $this->historique["LIBELLE_ETABLISSEMENTINFORMATIONS"]
				)
			);
		?>
	</div>
	
	<div id='div_statut'>
		<h3>Historique du statut</h3>
		<?php
			echo $this->partial(
				"etablissement/partials/partial-historique.phtml",
				array(
					"array" => $this->historique["ID_STATUT"]
				)
			);
		?>
	</div>
	
	<div id='div_avis'>
		<h3>Historique de l'avis</h3>
		<?php
			echo $this->partial(
				"etablissement/partials/partial-historique.phtml",
				array(
					"array" => $this->historique["ID_AVIS"]
				)
			);
		?>
	</div>

	<?php if( in_array("categorie", $this->classement) ) : ?>
		<div id='div_categorie' >
			<h3>Historique de la catégorie</h3>
			<?php
				echo $this->partial(
					"etablissement/partials/partial-historique.phtml",
					array(
						"array" => $this->historique["ID_CATEGORIE"]
					)
				);
			?>
		</div>
	<?php endif ?>

	<?php if( in_array("classe", $this->classement) ) : ?>
		<div id='div_classe' >
			<h3>Historique de la classe</h3>
			<?php
				echo $this->partial(
					"etablissement/partials/partial-historique.phtml",
					array(
						"array" => $this->historique["ID_CLASE"]
					)
				);
			?>
		</div>
	<?php endif ?>

	<?php if( in_array("famille", $this->classement) ) : ?>
		<div id='div_famille'>
			<h3>Historique de la famille</h3>
			<?php
				echo $this->partial(
					"etablissement/partials/partial-historique.phtml",
					array(
						"array" => $this->historique["ID_FAMILLE"]
					)
				);
			?>
		</div>
	<?php endif ?>
	
	<div id='div_type' >
		<h3>Historique du type principal</h3>
		<?php
			echo $this->partial(
				"etablissement/partials/partial-historique.phtml",
				array(
					"array" => $this->historique["ID_TYPE"]
				)
			);
		?>
	</div>
	
</div>