<h3>Historique de l'établissement</h3>

<h4>Historique du libellé</h4>
<?php
    echo $this->partial("etablissement/partials/partial-historique.phtml", array(
        "array" => $this->historique["LIBELLE_ETABLISSEMENTINFORMATIONS"]
    ));
?>

<h4>Historique du statut</h4>
<?php
    echo $this->partial("etablissement/partials/partial-historique.phtml", array(
        "array" => $this->historique["ID_STATUT"]
    ));
?>

<h4>Historique de la catégorie</h4>
<?php
    echo $this->partial("etablissement/partials/partial-historique.phtml",array(
        "array" => $this->historique["ID_CATEGORIE"]
    ));
?>

<h4>Historique de la classe</h4>
<?php
    echo $this->partial("etablissement/partials/partial-historique.phtml", array(
        "array" => $this->historique["ID_CLASSE"]
    ));
?>


<h4>Historique de la famille</h4>
<?php
    echo $this->partial("etablissement/partials/partial-historique.phtml", array(
        "array" => $this->historique["ID_FAMILLE"]
    ));
?>

<h4>Historique du type d'activité</h4>
<?php
    echo $this->partial("etablissement/partials/partial-historique.phtml", array(
        "array" => $this->historique["ID_TYPE"]
    ));
?>
