<div id='etablissement'>

    <div class='pull-right' >
        <a class='btn' href="<?php echo $this->url(array('action' => 'edit')) ?>">Modifier la fiche</a>
    </div>

    <h3>Fiche d'informations générales</h3>

    <div class='row-fluid'>
        <!-- Informations générales de l'établissement -->
        <div class='span6'>

            <!-- Classement de l'établissement -->
            <h4 class='h4_subtitle'>Classement</h4>
            <dl class='dl-horizontal'>
                <dt>Genre</dt>
                <dd>
                    <p>
                        <strong><?php echo $this->etablissement['informations']['LIBELLE_GENRE'] ?></strong>
                        <?php if( $this->etablissement['informations']["ICPE_ETABLISSEMENTINFORMATIONS"] ) echo "<span class='badge badge-info'>ICPE</span>" ?>
                    </p>
                </dd>

                <?php if(in_array($this->etablissement['informations']['ID_GENRE'], array(2, 3))) : ?>
                <dt>Catégorie</dt>
                <dd>
                    <p><?php echo $this->etablissement['informations']['LIBELLE_CATEGORIE'] ?></p>
                </dd>
                <?php endif ?>

                <?php if($this->etablissement['informations']['ID_GENRE'] == 4) : ?>
                <dt>Famille</dt>
                <dd>
                    <p><?php echo $this->etablissement['informations']['LIBELLE_FAMILLE'] ?></p>
                </dd>
                <?php endif ?>

                <?php if($this->etablissement['informations']['ID_GENRE'] == 5) : ?>
                <dt>Classe</dt>
                <dd>
                    <p><?php echo $this->etablissement['informations']['LIBELLE_CLASSE'] ?></p>
                </dd>
                <?php endif ?>

                <?php if(in_array($this->etablissement['informations']['ID_GENRE'], array(2, 3, 5))) : ?>
                <dt>Périodicité</dt>
                <dd>
                    <p><?php echo $this->etablissement['informations']['PERIODICITE_ETABLISSEMENTINFORMATIONS'] ?> mois</p>
                </dd>
                <?php endif ?>
            </dl>

            <!-- Activités de l'établissement -->
            <?php if(in_array($this->etablissement['informations']['ID_GENRE'], array(2, 3))) : ?>
            <h4 class='h4_subtitle'>Activités <?php if( $this->etablissement['informations']["LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS"] && $this->etablissement['informations']['ID_GENRE'] == 2) echo "<span class='badge badge-info pull-right'>Présence de locaux à sommeil</span>" ?></h4>
            <dl class='dl-horizontal'>
                <!-- Type et activités -->
                <dt>Types & activités</dt>
                <dd>
                    <ul class='unstyled'>
                        <li>
                            <strong><?php echo $this->etablissement['informations']['LIBELLE_TYPE_PRINCIPAL'] ?> - <?php echo $this->etablissement['informations']['LIBELLE_TYPEACTIVITE_PRINCIPAL'] ?></strong>
                        </li>
                        <?php foreach($this->etablissement['types_activites_secondaires'] as $type_activite) : ?>
                            <li><?php echo $type_activite['LIBELLE_TYPE'] ?> - <?php echo $type_activite['LIBELLE_ACTIVITE'] ?></li>
                       <?php endforeach ?>
                    </ul>
                    <?php if($this->etablissement['informations']['R12320_ETABLISSEMENTINFORMATIONS']) : ?>
                        <p>Le <strong>R123-20</strong> est appliqué sur cet établissement.</p>
                    <?php endif ?>
                </dd>
            </dl>
            <?php endif ?>
            
            <!-- Rubriques -->
            <?php if($this->etablissement['informations']["ICPE_ETABLISSEMENTINFORMATIONS"]) : ?>
            <h4 class='h4_subtitle'>Rubriques ICPE</h4>
            <?php if(count($this->etablissement['rubriques']) == 0) : ?>
            <p class='muted text-center'>Pas de rubriques disponible</p>
            <?php else : ?>
            <table class='table table-condensed'>
                <thead>
                    <tr>
                        <th>Rubrique</th>
                        <th>Numéro</th>
                        <th>Nom</th>
                        <th>Valeur</th>
                        <th>Classement</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->etablissement['rubriques'] as $rubrique) : ?>
                        <tr>
                            <td><?php echo $rubrique["ID_RUBRIQUE"] == 1 ? 'Substance' : 'Activité' ?></td>
                            <td><?php echo $rubrique["NUMERO_ETABLISSEMENTINFORMATIONSRUBRIQUE"] ?></td>
                            <td><?php echo $rubrique["NOM_ETABLISSEMENTINFORMATIONSRUBRIQUE"] ?></td>
                            <td><?php echo $rubrique["VALEUR_ETABLISSEMENTINFORMATIONSRUBRIQUE"] ?></td>
                            <td><?php echo $rubrique["CLASSEMENT_ETABLISSEMENTINFORMATIONSRUBRIQUE"] ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
            <?php endif ?>
            <?php endif ?>
 
            <!-- Les effectifs -->
            <?php if(in_array($this->etablissement['informations']['ID_GENRE'], array(2, 3, 5, 6))) : ?>
            <h4 class='h4_subtitle'>Les effectifs</h4>
            <dl class='dl-horizontal'>
                <!-- Effectif public -->
                <?php if(in_array($this->etablissement['informations']['ID_GENRE'], array(2, 3, 5))) : ?>
                <dt>Public</dt>
                <dd>
                    <p><?php echo $this->etablissement['informations']['EFFECTIFPUBLIC_ETABLISSEMENTINFORMATIONS'] ?></p>
                </dd>
                <?php endif ?>

                <!-- Effectif personnel -->
                <dt>Personnel</dt>
                <dd>
                    <p><?php echo $this->etablissement['informations']['EFFECTIFPERSONNEL_ETABLISSEMENTINFORMATIONS'] ?></p>
                </dd>

                <!-- Effectif hebergé -->
                <?php if($this->etablissement['informations']['LOCALSOMMEIL_ETABLISSEMENTINFORMATIONS'] && $this->etablissement['informations']['ID_GENRE'] == 2) : ?>
                <dt>Dont hebergé</dt>
                <dd>
                    <p><?php echo $this->etablissement['informations']['EFFECTIFHEBERGE_ETABLISSEMENTINFORMATIONS'] ?></p>
                </dd>
                <?php endif ?>

                <dt>&nbsp;</dt><dd><hr></dd>

                <!-- Effectif total -->
                <dt>Total</dt>
                <dd>
                    <p><?php echo (int) $this->etablissement['informations']['EFFECTIFPUBLIC_ETABLISSEMENTINFORMATIONS'] + (int) $this->etablissement['informations']['EFFECTIFPERSONNEL_ETABLISSEMENTINFORMATIONS'] ?></p>
                </dd>

                <!-- Effectif justifant le classement (que pour les 5ème catégorie) -->
                <?php if($this->etablissement['informations']['ID_CATEGORIE'] == 5) : ?>
                <dt>Justifiant le classement</dt>
                <dd>
                    <p><?php echo $this->etablissement['informations']['EFFECTIFJUSTIFIANTCLASSEMENT_ETABLISSEMENTINFORMATIONS'] ?></p>
                </dd>
                <?php endif ?>
            </dl>
            <?php endif ?>
            
            <!-- Plan -->
            <?php if(in_array($this->etablissement['informations']['ID_GENRE'], array(2, 3, 5, 6))) : ?>
            <h4 class='h4_subtitle'>Plans d'intervention</h4>
            <?php if(count($this->etablissement['plans']) == 0) : ?>
            <p class='muted text-center'>Pas de plans disponible</p>
            <?php else : ?>
            <table class='table table-condensed'>
                <thead>
                    <tr>
                        <th>Type de plan</th>
                        <th>Numéro du plan</th>
                        <th>Date</th>
                        <th>A mettre à jour</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->etablissement['plans'] as $plan) : ?>
                        <tr>
                            <td><?php echo $plan["LIBELLE_TYPEPLAN"] ?></td>
                            <td><?php echo $plan["NUMERO_ETABLISSEMENTPLAN"] ?></td>
                            <td><?php echo date_format(new DateTime($plan["DATE_ETABLISSEMENTPLAN"]), 'd/m/Y') ?></td>
                            <td><?php echo $plan["MISEAJOUR_ETABLISSEMENTPLAN"] ? 'A jour' : 'Pas à jour' ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
            <?php endif ?>
            <?php endif ?>
            
            <!-- Etablissement lié -->
            <?php if(count($this->etablissement['etablissement_lies']) > 0) : ?>
            <h4 class='h4_subtitle'>Établissements liés <small><?php echo count($this->etablissement['etablissement_lies']) > 0 ? "(" . count($this->etablissement['etablissement_lies']) . " établissements)" : "" ?></small></h4>
            <ul class='recherche_liste unstyled'>
                <?php echo $this->partialLoop('search/results/etablissement.phtml', $this->etablissement['etablissement_lies']); ?>
            </ul>
            <?php endif ?>
        </div>

        <!-- Carte de l'emplacement de l'établissement / informations  -->
        <div class='span6'>
            <!-- Cartes et diaporama -->
            <ul id='menu_nav' class="nav nav-tabs" style="margin: 0; padding: 0; border-bottom: none;">
                <?php if( count($this->etablissement['diapo_plans']) > 0 ) : ?> <li class='tabs-right' ><a href='#plans-tab-pane' data-toggle="tab">Plans</a></li>             <?php endif ?>
                <?php if( count($this->etablissement['diapo']) > 0 ) : ?>       <li class='tabs-right' ><a href='#diaporama-tab-pane' data-toggle="tab">Diaporama</a></li>     <?php endif ?>
                <?php if( count($this->etablissement['adresses']) > 0) : ?>     <li class='tabs-right' ><a href='#geoportail' data-toggle="tab">Carte</a></li>                 <?php endif ?>
            </ul>
            <div class="tab-content">
                <?php if( count($this->etablissement['adresses']) > 0) : ?>
                <div id='geoportail' class="tab-pane in" style="height: 350px; max-height: 350px;">
                    <div id='geoportail-container'  style="height: 100%; max-height: 100%;"></div>
                    <script type="text/javascript" src="http://api.ign.fr/geoportail/api/js/latest/GeoportalExtended.js"></script>
                    <script>
                        $(document).ready(function() {
                            viewer = Geoportal.load("geoportail-container", "i4d3km958rzoesb7thga4f59", {
                                lat: <?php echo $this->etablissement['adresses'][0]['LAT_ETABLISSEMENTADRESSE'] ?>,
                                lon: <?php echo $this->etablissement['adresses'][0]['LON_ETABLISSEMENTADRESSE'] ?>
                            }, 17, OpenLayers.Util.extend({
                                controls: [new OpenLayers.Control.NavToolbar(), new OpenLayers.Control.LayerSwitcher()]
                            }));
                        });
                    </script>
                </div>
                <?php endif ?>

                <?php if( count($this->etablissement['diapo']) > 0 ) : ?>
                <div id='diaporama-tab-pane' class='tab-pane'>
                    <div id='diaporama' class="carousel slide">
                        <ol class="carousel-indicators">
                            <?php foreach($this->etablissement['diapo'] as $key => $item) : ?>
                            <li class="<?php if($key == 0 ) echo 'active' ?>" data-target="#<?php echo $value ?>" data-slide-to="<?php echo $key ?>"></li>
                            <?php endforeach ?>
                        </ol>
                        <!-- Carousel items -->
                        <div class="carousel-inner" style="background-color: #333">
                            <?php foreach($this->etablissement['diapo'] as $key => $item) : ?>
                            <div class="item <?php if($key == 0 ) echo 'active' ?>"  >
                                <img style="margin: 0 auto; width: auto; height: 350px; max-height: 350px;" src="/data/uploads/pieces-jointes/miniatures/<?php echo $item["ID_PIECEJOINTE"].".jpg" ?>" alt="" />
                                <div class="carousel-caption">
                                  <h4><?php echo $item['NOM_PIECEJOINTE'] ?></h4>
                                  <p><?php echo $item['DESCRIPTION_PIECEJOINTE'] ?></p>
                                </div>
                            </div>
                            <?php endforeach ?>
                        </div>
                        <!-- Carousel nav -->
                        <a class="carousel-control left" href="#diaporama" data-slide="prev" style="box-sizing: content-box;">&lsaquo;</a>
                        <a class="carousel-control right" href="#diaporama" data-slide="next" style="box-sizing: content-box;">&rsaquo;</a>
                    </div>
                </div>
                <?php endif ?>

                <?php if( count($this->etablissement['diapo_plans']) > 0 ) : ?>
                <div id='plans-tab-pane' class='tab-pane'>
                    <div id='plans' class="carousel slide">
                        <ol class="carousel-indicators">
                            <?php foreach($this->etablissement['diapo_plans'] as $key => $item) : ?>
                            <li class="<?php if($key == 0 ) echo 'active' ?>" data-target="#<?php echo $value ?>" data-slide-to="<?php echo $key ?>"></li>
                            <?php endforeach ?>
                        </ol>
                        <!-- Carousel items -->
                        <div class="carousel-inner" style="background-color: #333">
                            <?php foreach($this->etablissement['diapo_plans'] as $key => $item) : ?>
                            <div class="item <?php if($key == 0 ) echo 'active' ?>" >
                                <img style="margin: 0 auto; width: auto; height: 350px; max-height: 350px;" src="/data/uploads/pieces-jointes/miniatures/<?php echo $item["ID_PIECEJOINTE"].".jpg" ?>" alt="" />
                                <div class="carousel-caption">
                                  <h4><?php echo $item['NOM_PIECEJOINTE'] ?></h4>
                                  <p><?php echo $item['DESCRIPTION_PIECEJOINTE'] ?></p>
                                </div>
                            </div>
                            <?php endforeach ?>
                        </div>
                        <!-- Carousel nav -->
                        <a class="carousel-control left" href="#plans" data-slide="prev" style="box-sizing: content-box;">&lsaquo;</a>
                        <a class="carousel-control right" href="#plans" data-slide="next" style="box-sizing: content-box;">&rsaquo;</a>
                    </div>
                </div>
                <?php endif ?>
            </div>

            <?php if(count($this->etablissement['adresses']) > 0) : ?>
            <h4 class='h4_subtitle'>Adresse</h4>
            <dl class='dl-horizontal'>
                <dt>Adresses</dt>
                <dd>
                    <table class='table table-condensed champ_adresse champs'>
                        <thead>
                            <tr>
                                <th>Localisation</th>
                                <th>Type</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach( $this->etablissement['adresses'] as $adresse ) : ?>
                                <tr>
                                    <td><?php echo strtolower($adresse["NUMERO_ADRESSE"]." ".$adresse["LIBELLE_RUE"]." ".$adresse["CODEPOSTAL_COMMUNE"]). " " .$adresse["LIBELLE_COMMUNE"] ?></td>
                                    <td>Adresse postale</td>
                                </tr>
                            <?php endforeach ?>
                        </tbody>
                    </table>
                </dd>

                <?php if(count($this->groupements_de_communes) > 0) : ?>
                <dt>Groupements</dt>
                <dd>
                    <ul class='unstyled'>
                        <?php foreach($this->groupements_de_communes as $groupement) : ?>
                        <li>
                            <a href="/groupement/view?id=<?php echo $groupement["ID_GROUPEMENT"] ?>"><?php echo $groupement["LIBELLE_GROUPEMENT"] ?> (<?php echo $groupement["LIBELLE_GROUPEMENTTYPE"] ?>)</a>
                        </li>
                        <?php endforeach ?>
                    </ul>
                </dd>
                <?php endif ?>  
            </dl>
            <?php endif ?>

            <?php if(!empty($this->etablissement['general']['TELEPHONE_ETABLISSEMENT']) || !empty($this->etablissement['general']['FAX_ETABLISSEMENT']) || !empty($this->etablissement['general']['COURRIEL_ETABLISSEMENT'])) : ?>
            <h4 class='h4_subtitle'>Coordonnées</h4>
            <dl class='dl-horizontal'>
                <!-- Téléphone -->
                <?php if(!empty($this->etablissement['general']['TELEPHONE_ETABLISSEMENT'])) : ?>
                <dt>Téléphone</dt>
                <dd>
                    <p><?php echo $this->etablissement['general']['TELEPHONE_ETABLISSEMENT'] ?></p>
                </dd>
                <?php endif ?>
                
                <!-- Fax -->
                <?php if(!empty($this->etablissement['general']['FAX_ETABLISSEMENT'])) : ?>
                <dt>Fax</dt>
                <dd>
                    <p><?php echo $this->etablissement['general']['FAX_ETABLISSEMENT'] ?></p>
                </dd>
                <?php endif ?>
                
                <!-- Courriel -->
                <?php if(!empty($this->etablissement['general']['COURRIEL_ETABLISSEMENT'])) : ?>
                <dt>Courriel</dt>
                <dd>
                    <p>
                        <a href='mailto:<?php echo $this->etablissement['general']['COURRIEL_ETABLISSEMENT'] ?>'><?php echo $this->etablissement['general']['COURRIEL_ETABLISSEMENT'] ?></a>
                    </p>
                </dd>
                <?php endif ?>
            </dl>
            <?php endif ?>

            <h4 class='h4_subtitle'>Données prévention</h4>
            <dl class='dl-horizontal'>
                <!-- Commission compétente -->
                <?php if(in_array($this->etablissement['informations']['ID_GENRE'], array(2, 5))) : ?>
                <dt>Commission</dt>
                <dd>
                    <p><?php echo $this->etablissement['informations']['LIBELLE_COMMISSION'] ?></p>
                </dd>
                <?php endif ?>

                <!-- Préventionnistes -->
                <dt>Préventionnistes</dt>
                <dd>
                    <?php if(count($this->etablissement['preventionnistes']) == 0) : ?>
                        <p class='muted'>Aucun préventionniste lié.</p>
                    <?php else : ?>
                        <?php echo $this->partialLoop('users/embedded/user.phtml', $this->etablissement['preventionnistes'] ) ?>
                        <div style='clear: both; margin-bottom: 10px;'></div>
                    <?php endif ?>
                </dd>

                <!-- Date de dernière visite -->
                <?php if(!empty($this->etablissement['last_visite']) ) : ?>
                <dt>Dernière VP</dt>
                <dd><p><?php echo $this->etablissement['last_visite'] ?></p></dd>
                <?php endif ?>

                <!-- Date de prochaine visite-->
                <?php if(!empty($this->etablissement['next_visite']) ) : ?>
                <dt>Prochaine VP</dt>
                <dd><p><?php echo $this->etablissement['next_visite'] ?></p></dd>
                <?php endif ?>

                <!-- Date de PC initial -->
                <?php if(!empty($this->etablissement['pc_initial']) ) : ?>
                <dt>Date PC Initial</dt>
                <dd><p><?php echo $this->etablissement['pc_initial'] ?></p></dd>
                <?php endif ?>

                <!-- Données pratiques -->
                <?php if(in_array($this->etablissement['informations']['ID_GENRE'], array(1, 2, 3, 5))) : ?>
                <dt>Données pratiques</dt>
                <dd>
                    <p>
                        <?php if($this->etablissement['informations']['ID_GENRE'] != 1 ) : ?>
                        Nb. de préventionnistes/visite : <?php echo $this->etablissement['donnees_pratiques']['NBPREV_ETABLISSEMENT'] ?><br/>
                        <?php endif ?>
                        <?php if(isset($this->etablissement['donnees_pratiques']['DUREEVISITE_ETABLISSEMENT'])) : ?>
                        Durée d'une visite : <?php echo date_format(new DateTime($this->etablissement['donnees_pratiques']['DUREEVISITE_ETABLISSEMENT']), 'H:i') ?>
                        <?php else: ?>
                        Durée d'une visite : -
                        <?php endif ?>
                    </p>
                </dd>
                <?php endif ?>
            </dl>
        </div>
    </div>

</div>

<script type="text/javascript">
    $(document).ready(function() {
        // Par défaut, on montre le premier onglet disponible (carte, diapo, ou plans) sinon rien
        $('#menu_nav a:last').tab('show');

        // Slide des établissements enfants contenant d'autres établissements
        $("ul.recherche_liste li.slide").live("click", function() {
            var container = this;
            if( $(this).hasClass("active") ) {
                $(this).next().slideUp(400, function() {$(container).next().remove()});
                $(this).toggleClass("active");
            }
            else {
                $(container).find(".load").show();
                $.getJSON("/api/1.0/search/etablissements", {parent: $(this).attr("id"), count: 100}, function(data) {
                    $(container).toggleClass("active").find(".load").hide();
                    $.post("/search/display-ajax-search", {items: 'etablissement', data: data.response.results}, function(html) {
                        $(container).after("<li class='ui-helper-hidden' >" + html + "</li>").next().slideDown();
                    });
                });
            }
        });
    });
</script>