<div class='pull-right' >
    <a class='btn' href="<?php echo $this->url(array('action' => 'edit-pieces-jointes')) ?>">Gestion des pièces jointes</a>
</div>

<h3>Pièces jointes</h3>

<?php if(count($this->pieces_jointes) == 0) : ?>

    <div class='well well-large text-center'>
        <p class='lead'>Il n'y a pas de pièce jointe.</p>
        <p><a href='<?php echo $this->url(array('action' => 'edit-pieces-jointes')) ?>' class='btn btn-large'>Ajouter une pièce jointe</a></p>
    </div>

<?php else : ?>

	<h4>Documents</h4>

	<table class='table table-bordered table-condensed table-striped'> 
		<thead> 
			<tr>
				<th>Nom</th> 
				<th>Description</th>
				<th>Date d'ajout</th>
			</tr> 
		</thead> 
		<tbody>
			<?php foreach ($this->pieces_jointes as $piecejointe) : ?>
				<?php if(!in_array($piecejointe['EXTENSION_PIECEJOINTE'], array(".jpg", ".jpeg", ".png", ".gif"))) : ?>
				<tr>   
					<td>
						<a href='<?php echo $this->url(array('controller' => 'piece-jointe', 'action' => 'get', 'idpj' => $piecejointe['ID_PIECEJOINTE'], 'type' => 'etablissement')) ?>' target='_blank' >
							<?php echo $piecejointe['NOM_PIECEJOINTE'].$piecejointe['EXTENSION_PIECEJOINTE']  ?>
						</a>
					</td>
					<td>
						<?php echo empty($piecejointe['DESCRIPTION_PIECEJOINTE']) ? 'Aucune description.' : nl2br(str_replace("<br />", "" ,$piecejointe['DESCRIPTION_PIECEJOINTE'])) ?>
					</td>
					<td>
						<?php echo date_format(new DateTime($piecejointe['DATE_PIECEJOINTE']), 'd/m/Y') ?>
					</td>
				</tr>
				<?php endif ?>
			<?php endforeach ?>
		</tbody>
	</table>

	<h4>Images</h4>

	<ul class="thumbnails">
		<?php foreach ($this->pieces_jointes as $piecejointe) : ?>
			<?php if(in_array($piecejointe['EXTENSION_PIECEJOINTE'], array(".jpg", ".jpeg", ".png", ".gif"))) : ?>
			<li class="span3">
				<a href='<?php echo $this->store->getURLPath($piecejointe, 'etablissement', $this->etablissement['general']['ID_ETABLISSEMENT']); ?>' class="thumbnail">
                                        <?php $piecejointe['EXTENSION_PIECEJOINTE'] = '.jpg'; ?> 
					<img src="<?php echo $this->store->getURLPath($piecejointe, 'etablissement_miniature', $this->etablissement['general']['ID_ETABLISSEMENT']); ?>" alt="">
					<h5><?php echo $piecejointe['NOM_PIECEJOINTE'] ?></h5>
					<p><?php echo $piecejointe['DESCRIPTION_PIECEJOINTE'] ?></p>
				</a>
			</li>
			<?php endif ?>
		<?php endforeach ?>
	</ul>

<?php endif ?>

<script>
	$(document).ready(function() {
		$('a[href$=png], a[href$=jpg], a[href$=jpeg]').fancybox({
            'transitionIn'	:	'elastic',
            'transitionOut'	:	'elastic',
            'speedIn'		:	600, 
            'speedOut'		:	200, 
        });
	});
</script>