<div class='pull-right' >
    <a class='btn' href="<?php echo $this->url(array('action' => 'edit-textes-applicables')) ?>">Modifier les textes applicables</a>
</div>

<h3>Textes applicables</h3>

<div class='row-fluid'>
    <?php foreach($this->textes_applicables as $titre => $textes_applicables) : ?>
        <h4><?php echo $titre ?></h4>
        <ul class='unstyled'>
            <?php foreach($textes_applicables as $texte_applicable) : ?>
                <li class="<?php echo !in_array($texte_applicable, $this->textes_applicables_de_etablissement) ? "muted" : ""  ?>">
                    <?php echo in_array($texte_applicable, $this->textes_applicables_de_etablissement) ? "✓" : ""  ?>
                    <span style="<?php echo in_array($texte_applicable, $this->textes_applicables_de_etablissement) ? "font-weight: bold" : ""  ?>"><?php echo $texte_applicable['LIBELLE_TEXTESAPPL'] ?></span>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endforeach ?>
</div>