<div class='pull-right' >
    <a data-toggle="modal" data-target="#reponse-modal" class='btn' href="<?php echo $this->url(array('action' => 'edit-textes-applicables')) ?>">Modifier les textes applicables</a>
</div>

<h3>Textes applicables</h3>

<div class='row-fluid'>
    <?php foreach($this->textes_applicables as $titre => $textes_applicables) : ?>
        <h4><?php echo $titre ?></h4>
        <?php foreach($textes_applicables as $texte_applicable) : ?>
            <p class="<?php echo !in_array($texte_applicable, $this->textes_applicables_de_etablissement) ? "muted" : ""  ?>">
                <span style="<?php echo in_array($texte_applicable, $this->textes_applicables_de_etablissement) ? "font-weight: bold" : ""  ?>"><?php echo $texte_applicable['LIBELLE_TEXTESAPPL'] ?></span>
            </p>
        <?php endforeach ?>
    <?php endforeach ?>
</div>

<!-- Blocs pour les contenus ajax -->
<div id="reponse-modal" class="modal hide fade"></div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        $("a[data-toggle='modal']").click(function() {
            var target = $(this).attr("data-target");
            var url = $(this).attr("href");
            $(target).load(url);
        });
    }, false);
</script>