<div id="text_app_div">
<?php
    $idTypeMarq = "";
    foreach($this->listeTextesAppl as $val => $ue){
        $idType = $ue['ID_TYPETEXTEAPPL'];
        if($idTypeMarq != $idType){
            echo "
                <h3>".$ue['LIBELLE_TYPETEXTEAPPL']."</h3>			
            ";
            $idTypeMarq = $idType;
        }
        echo "
            <div class='grid_1'>
                <input type='checkbox' name='texte' id='".$ue['ID_TEXTESAPPL']."' ".( (in_array($ue['ID_TEXTESAPPL'],$this->listeIdTexte))? "checked" : "" )."/>
            </div>
            <div class='grid_12 alpha'>".nl2br($ue['LIBELLE_TEXTESAPPL'])."</div>
            <hr class='clear'>
        ";
    }
?>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("#text_app_div input[type=checkbox]").click(function() {
        
            var idTexte = $(this).attr('id');
            
            if($(this).is(':checked')) {
                var toDo = "save";			
            }else{
                var toDo = "delete";
            }

            $.ajax({
                type: "POST",
                url: "/etablissement/textes-applicables",
                data: "&id=<?php echo $this->id_etablissement ?>&texteApplicable&toDo="+toDo+"&idTexte="+idTexte,
                success: function(msg){
                    
                }
            });
            
        });
        
    });
</script>