<div id="<?php echo $this->id ?>" class="panel panel-default <?php echo $this->width != 'small' ? 'w2' : '' ?> loading">
  <div class="panel-heading">
    <?php echo $this->title ?>
    <a class='btn btn-small pull-right' data-toggle="modal" data-target="#reponse-modal" href='<?php echo $this->url(array('controller' => 'index', 'action' => 'add-message')) ?>'>Ajouter un message</a>
  </div>
  <div class="panel-body">
      <img src="/images/load.gif" />
  </div>
</div>