<?php
	$actual = new Zend_Date();
	$d = new Zend_Date($this->ID_NEWS, Zend_Date::TIMESTAMP);

	$in = array(
		'`((?:https?|ftp)://\S+[[:alnum:]]/?)`si',
		'`((?<!//)(www\.\S+[[:alnum:]]/?))`si'
	);

	$out = array(
		'<a href="$1">$1</a>',
		'<a href="http://$1">$1</a>'
	);

	$this->TEXTE_NEWS = preg_replace($in, $out, $this->TEXTE_NEWS);
	$date = (( $d->get(Zend_Date::DATES) != $actual->get(Zend_Date::DATES) ) ? $d->get(Zend_Date::WEEKDAY." ".Zend_Date::DAY_SHORT." ".Zend_Date::MONTH_NAME_SHORT)." ".$d->get(Zend_Date::TIME_SHORT) : $d->get(Zend_Date::TIME_SHORT));
?>

<tr>
	<td style='width: 80px; vertical-align: top; border: none;'>
		<?php $this->avatar($this->ID_UTILISATEUR, 'medium', array('style' => "float: left; width: 40px; border: 1px solid #dfdfdf; border-radius: 50%; margin-right: 15px;")) ?>
	</td>

	<td style="border: none">
			<small style="float: right" class='muted'><?php echo $date ?> - <?php echo $this->TYPE_NEWS ?> - <a href='<?php echo $this->url(array('controller' => 'index', 'action' => 'delete-message', 'id' => $this->ID_NEWS)) ?>'>Supprimer</a></small>
			<a href="#"><strong><?php echo $this->PRENOM_UTILISATEURINFORMATIONS . ' ' . $this->NOM_UTILISATEURINFORMATIONS ?></strong></a><br>
			<p><?php echo $this->TEXTE_NEWS ?></p>
	</td>
</tr>
