<p style='float: right; margin-left: 20px;'>
	<img src='/images/about.jpg' alt='SDIS - jQuery - Zend - 960' />
</p>

<h3>Mentions</h3>

<p style='text-align: justify;'>
	Le site Prevarisc est la propriété du SDIS du Pas-de-Calais.<br/>
	Il a été conçu et réalisé par <a href='http://kevindubuc.fr'>Kévin DUBUC</a> &amp; Rémi KINOWSKI, en lien avec le Service Prévention et le Service Informatique du SDIS 62.<br/><br/>
	Infographie : ESAD.<br/><br/>
	La maintenance technique et l'hébergement sont assurés par le service informatique du SDIS 62.
</p>

<br/>

<h3>Droit d'auteur - Copyright</h3>
<p style='text-align: justify;'>
	L'ensemble de ce site relève de la législation française et internationale sur le droit d'auteur et la propriété intellectuelle.<br/><br/>
	Tous les droits de reproduction sont réservés, y compris pour les documents téléchargeables et les représentations iconographiques et photographiques. Sauf mentions contraires, les photographies utilisées dans le site appartiennent au SDIS 62. Toute représentation, reproduction, modification, utilisation commerciale, ainsi que tout transfert vers un autre site sont interdits, sauf autorisation expresse du directeur de la publication.<br/><br/>
	Les marques apparaissant ou citées sur ce site sont déposées par les sociétés qui en sont propriétaires.
</p>

<br/>

<h3>Dysfonctionnement et virus</h3>
<p style='text-align: justify;'>
	Le SDIS du Pas-de-Calais ne pourra être tenu responsable de dommages directs ou indirects, pertes ou frais, résultant de l'utilisation de ce site web, ou de l'impossibilité pour un tiers de l'utiliser, ou d'un mauvais fonctionnement, d'une interruption, d'un virus, ou encore d'un problème de ligne ou de système.
</p>