    <div class="panel panel-default">
       <div class="panel-heading">
       Alertes
       </div>
        <ul class="list-group">
          <?php
          
            //var_dump($this->etablissementsanspreventionniste);
             foreach($this->etablissementsanspreventionniste as $erpsansprev)
                { ?>
                  <li class="list-group-item">
                  <i class="icon-pencil icon-black" ></i>    
                  <span class="badge badge-important">Important</span>
                  <?php
                       if($erpsansprev['LIBELLE_ETABLISSEMENTINFORMATIONS']!=null)
                       {
                           echo "<a href='etablissement/index/id/".$erpsansprev['ID_ETABLISSEMENT']."'>   L'établissement &quot; ".$erpsansprev['LIBELLE_ETABLISSEMENTINFORMATIONS']." &quot; est sans préventionnistes </a>";
                       }
                       
                       else 
                       {
                       $datedemodif = new DateTime($erpsansprev['DATE_ETABLISSEMENTINFORMATIONS']);    
                       echo "<a href='etablissement/index/id/".$erpsansprev['ID_ETABLISSEMENT']."'>   L'établissement du &quot; ".$datedemodif->format('d/m/y')." &quot; est sans préventionnistes </a>";
                       }
                     ?>   
                  </li>   
        
                <?php 
         
                }
                ?>
            
            <?php
            foreach($this->courrier as $courrier)
                { ?>
                   <li class="list-group-item">
                    
                   <span class="badge badge-important">Important</span>
                   <i class="icon-pencil icon-black" > </i>
                  <?php
                       if($courrier['DATEREP_DOSSIER']==null)
                       { 
                           echo "<a href='/dossier/index/id/".$courrier['ID_DOSSIER']."'>  Le courrier/courriel  &quot; ".$courrier['OBJET_DOSSIER']." &quot; est sans réponse depuis plus de 5 jours </a>";
                       }
                        ?> 
                   
                  </li>   
        
                <?php 
         
                }
                ?>
             
            
              <?php
               foreach($this->dossiercommissionechu as $dossier)
                { ?>
                  <li class="list-group-item">
                      <i class="icon-pencil icon-black" ></i>   
                  <span class="badge badge-info">Info</span>
                  <?php
                       if($dossier['OBJET_DOSSIER']!=null)
                       {
                       echo "<a href='/dossier/index/id/".$dossier['ID_DOSSIER']."'>  Le dossier  &quot; ".$dossier['OBJET_DOSSIER']." &quot; de la commission échue &quot; ".$dossier['LIBELLE_DATECOMMISSION']." &quot; est sans avis d'exploitation</a>";
                       
                       }
                       else
                       {
                           $datecreation = new DateTime($dossier['DATEINSERT_DOSSIER']);
                           echo "<a href='/dossier/index/id/".$dossier['ID_DOSSIER']."'>  Le dossier du ".$datecreation->format('d/m/y')." (".$dossier['LIBELLE_DOSSIERTYPE'].") de la commission échue &quot; ".$dossier['LIBELLE_DATECOMMISSION']." &quot; est sans avis d'exploitation</a>";
                          
                       }
                       ?>      
                  </li>   
        
                <?php 
         
                }
                ?>
                
          
          
               <?php
                foreach($this->etablissementavisdefavorable as $avis)
                { ?>
                  
                  <li class="list-group-item">
                    
                   <span class="badge badge-important">Important</span>
                   <i class="icon-pencil icon-black" > </i>
                    <?php 
                       if($avis['LIBELLE_ETABLISSEMENTINFORMATIONS']!=null)
                       {
                       echo "<a href='etablissement/index/id/".$avis['ID_ETABLISSEMENT']."'> L'établissement &quot; ".$avis['LIBELLE_ETABLISSEMENTINFORMATIONS']." &quot; est sous un avis défavorable depuis dix jours</a>";
                       }
                       else 
                       {
                       $datedemodif = new DateTime($avis['DATE_ETABLISSEMENTINFORMATIONS']);    
                       echo "<a href='etablissement/index/id/".$avis['ID_ETABLISSEMENT']."'> L'établissement du &quot; ".$datedemodif->format('d/m/y')." &quot; est sous un avis défavorable depuis dix jours</a>";
                       }
                       ?>  
                  
                  </li>   
                
                <?php 
         
                }
                ?>
     </ul>  
    </div>

     <div class="panel panel-default">
     <div class="panel-heading">
     Prochaines commissions
     </div>
         <ul class="list-group">
     <?php  
     $nbrcommission=0;    
     
     if($this->firstcommission!=NULL)
     {   
         foreach($this->commissionsListe as $commission)
         {
               foreach($this->firstcommission as $commissiondujour)
             {             
                if($commission['ID_COMMISSION']==$commissiondujour['COMMISSION_CONCERNE'])
                {
                    $nbrcommission++;
                    $datec = new DateTime($commissiondujour['DATE_COMMISSION']);
                    if ($commissiondujour['ID_COMMISSIONTYPEEVENEMENT'] == 1) {
                        $class="badge-info";
                        $message="En salle";
                    } else if ($commissiondujour['ID_COMMISSIONTYPEEVENEMENT'] == 2) {
                        $class="badge-success";
                        $message="Visite de sécurité";
                    } else {
                        $class="badge-warning";
                        $message="Groupe de visite";
                    }
                   
                ?>
        <li class='list-group-item'>
        <i class="icon-pencil icon-black" ></i>     
        <span class='badge <?php echo $class ?>'><?php echo $message ?></span>      
         
            <a href="/calendrier-des-commissions/gestionodj/dateCommId/<?php echo $commissiondujour['ID_DATECOMMISSION'];?>"
            >
                <?php
                
                   $date = new DateTime($commissiondujour['DATE_COMMISSION'].' '.$commissiondujour['HEUREDEB_COMMISSION']);
                   echo "Le ".$date->format('d/m à H:i');
                   echo " : ".$commission['LIBELLE_COMMISSION'];
                   echo '-'.$commissiondujour['LIBELLE_DATECOMMISSION'];
                ?> 
             
            </a> 
       
       </li>
                    
                <?php
                }   
             }  
         }
     }
     else
     {
      ?>
     <p class='well text-center pasnotification'>
       <a>
     <?php
         echo 'Aucune commission'; 
     ?>
       </a>
     </p>
     <?php
     }    
     ?>
    </ul>                
    </div>

<div class="grid-sizer"></div>
<div class="grid-gutter"></div>


<!-- Messages -->
<div class="panel panel-default">
  <div class="panel-heading">
    Messages
    <a class='btn btn-small pull-right' data-toggle="modal" data-target="#reponse-modal" href='<?php echo $this->url(array('controller' => 'news', 'action' => 'add')) ?>'>Ajouter un message</a>
  </div>
  <div class="panel-body">
    <?php if( count($this->flux) == 0 ) : ?>
        <p class='muted'><small>Aucun message disponible.</small></p>
    <?php else : ?>
        <table class='table table-condensed'>
         <?php echo $this->partialLoop('news/partials/partial-display.phtml', $this->flux); ?>
        </table>
    <?php endif ?>
  </div>
</div>

<!-- Etablissements suivis -->
<?php if( count($this->etablissements) > 0 ) : ?>
<div class="panel panel-default">
  <div class="panel-heading">
    Etablissements suivis
  </div>
  <div class="panel-body" style="font-size: .85em">
      <ul class='recherche_liste unstyled no_slide'>
      <?php echo $this->partialLoop('search/results/etablissement.phtml', $this->etablissements ) ?>
      </ul>
      <div style='clear: both'></div>
      <?php echo $this->etablissements ?>
  </div>
</div>
<?php endif ?>

<!-- Dossiers avec un avis différé -->
<?php if( count($this->dossiers) > 0 ) : ?>
<div class="panel panel-default">
  <div class="panel-heading">
    Dossiers avec un avis différé
  </div>
  <div class="panel-body" style="font-size: .85em">
      <ul class='recherche_liste unstyled no_slide'>
      <?php echo $this->partialLoop('search/results/dossier.phtml', $this->dossiers ) ?>
      </ul>
      <div style='clear: both'></div>
      <?php echo $this->dossiers ?>
  </div>
</div>
<?php endif ?>

<!-- Ordre du jour -->
<?php if( count($this->commissions) > 0 ) : ?>
<div class="panel panel-default w2">
  <div class="panel-heading">
    Ordre du jour
  </div>
  <div class="panel-body" style="font-size: .85em">
    <?php foreach($this->commissions as $commission) : ?>
      <p class="lead" style="font-size:1.2em; margin-bottom: 0px;"><?php echo strtoupper($commission["name"]) . " du " . $commission["date"] . " (" . $commission["heure"] . ")" ?></p>
      <?php if(count($commission["odj"]) == 0 ) : ?>
        <p class="muted">Pas de dossier affecté.</p>
      <?php else : ?>
        <ul class='recherche_liste unstyled no_slide'>
          <?php echo $this->partialLoop('search/results/dossier.phtml', $commission["odj"] ) ?>
        </ul>
      <?php endif ?>
    <?php endforeach ?>
    <div style='clear: both'></div>
</div>
<?php endif ?>

<div id="reponse-modal" class="modal hide fade" ></div>

<script type="text/javascript">
    $(document).ready(function() {

        // Gestion des boites modales
        $("a[data-toggle='modal']").click(function() {
            var target = $(this).attr("data-target");
            var url = $(this).attr("href");
            $(target).load(url);
        });

        // Grid !
        var $container = $('.dashboard');

        $container.packery({
          itemSelector: '.panel',
          columnWidth: '.grid-sizer',
          gutter: '.grid-gutter'
        });

        var $itemElems = $( $container.packery('getItemElements') );
        $itemElems.draggable();
        $container.packery( 'bindUIDraggableEvents', $itemElems );

    });
</script>
