<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="brand" href="/" style="padding: 7px 15px 3px 20px"><img src='/favicon.ico' alt='Prevarisc' width="37px" /></a>
            <div class="nav-collapse collapse">
                <ul class='nav'>
                    <li>
                        <a href='/'>
                            Tableau de bord
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Établissements
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href='/search/etablissement?label=&page=1'><i class="icon-th-list"></i> Rechercher</a></li>
                            <li><a href='/etablissement/add'><i class="icon-plus"></i> Ajouter</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Dossiers
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href='/search/dossier?objet=&page=1'><i class="icon-th-list"></i> Rechercher</a></li>
                            <li><a href='/dossier/add'><i class="icon-plus"></i> Ajouter</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Commissions <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <?php if(count($this->commissions) > 0): ?>
                                <?php foreach($this->commissions as $commission): ?>
                                    <?php if (isset($commission["ARRAY"]) && count($commission["ARRAY"]) > 0): ?>
                                        <li class="nav-header">
                                            <?php echo htmlspecialchars($commission["LIBELLE"], ENT_QUOTES) ?>
                                        </li>
                                        <?php foreach($commission["ARRAY"] as $item) : ?>
                                            <?php if(Zend_Controller_Front::getInstance()->getParam('bootstrap')->getResource('acl')->isAllowed(Zend_Auth::getInstance()->getIdentity()['group']['LIBELLE_GROUPE'], "gestion_parametrages", "gestion_commissions"))  : ?>
                                                <li>
                                                    <a href="/calendrier-des-commissions?idComm=<?php echo $item["ID_COMMISSION"] ?>" >
                                                        <?php echo htmlspecialchars($item["LIBELLE_COMMISSION"], ENT_QUOTES) ?>
                                                    </a>
                                                </li>
                                            <?php endif ?>
                                        <?php endforeach ?>
                                    <?php endif ?>
                                <?php endforeach ?>
                            <?php endif ?>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-plus grey-icn-plus" title="Plus"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="nav-header">Paramétrage</li>
                            <li><a href='/tableau-des-periodicites'>Tableau des périodicités</a></li>
                            <li><a href='/groupement'>Groupements de communes</a></li>
                            <li class="nav-header">Gestion des entités</li>
                            <li><a href='/couches-cartographiques/list'>Gestion des couches cartographiques</a></li>
                            <li><a href='/users'>Gestion des utilisateurs</a></li>
                            <li><a href='/gestion-des-communes'>Gestion des communes</a></li>
                            <li><a href='/gestion-prescriptions'>Gestion des prescriptions</a></li>
                            <li><a href='/gestion-des-commissions'>Gestion des commissions</a></li>
                            <li><a href='/gestion-textes-applicables'>Gestion des textes applicables</a></li>
                            <li><a href='/gestion-des-documents'>Gestion des documents</a></li>
                            <li class="nav-header">Général</li>
                            <li><a href='/admin'>À propos</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class='nav pull-right'>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->avatar(Zend_Auth::getInstance()->getIdentity()['ID_UTILISATEUR'], 'medium', array('style' => "width: 27px; border: 1px solid #dfdfdf; border-radius: 50%; margin-right: 5px;")) ?>
                            <?php echo Zend_Auth::getInstance()->getIdentity()['infos']['PRENOM_UTILISATEURINFORMATIONS']." ".Zend_Auth::getInstance()->getIdentity()['infos']['NOM_UTILISATEURINFORMATIONS'] ?>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('controller' => 'session', 'action' => 'logout'), null, true) ?>"><i class="icon-off"></i> Déconnexion</a></li>
                        </ul>
                    </li>
                    <li class="divider-vertical" style="height: 50px"></li>
                    <li class="li-searched">
                        <form class="navbar-search" action="/search/etablissement" method="get">
                            <div class="input-append" id="research-input">
                                <input name="label" class="input-medium" id="nav-main-search-field" type="text" placeholder="Rechercher ..." style='margin-top: 10px' />
                                <input name="page" type="hidden" value="1"  />
                                <button class="btn btn_search" type="submit" style='margin-top: 10px'><i class="icon-search"></i></button>
                                <a class="btn" href="/search/etablissement?&statuts%5B%5D=2&statuts%5B%5D=4" >Avancée »</a>
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("#nav-main-search-field").autocomplete("/api/1.0/search/etablissements?format=json", {
            extraParams: {
                label: function() {
                    return $("#nav-main-search-field").val().trim();
                }
            },
            minChars: 3,
            width: 500,
            parse: function(data) {
                return $.map(data["response"]["results"], function(row) {
                    return {
                        data: row,
                        value: row.LIBELLE_ETABLISSEMENTINFORMATIONS,
                        result: row.LIBELLE_ETABLISSEMENTINFORMATIONS
                    }
                });
            },
            formatItem: function(item) {
                var LIBELLE_COMMUNE = "non localisée";
                switch(item.ID_GENRE) {
                    case "1":
                        LIBELLE_COMMUNE = item.LIBELLE_COMMUNE_ADRESSE_SITE;
                        break;

                    case "3":
                        LIBELLE_COMMUNE = item.LIBELLE_COMMUNE_ADRESSE_CELLULE;
                        break;

                    default:
                        LIBELLE_COMMUNE = item.LIBELLE_COMMUNE_ADRESSE_DEFAULT;
                }
                return "[" + item.LIBELLE_GENRE + "] " + item.LIBELLE_ETABLISSEMENTINFORMATIONS + " (" + LIBELLE_COMMUNE + ")";
            }
        }).result(function(e, item) {
            window.location.href= "/etablissement/index/id/" + item.ID_ETABLISSEMENT;
        });
    });
</script>
