<!-- Titre -->
<span style="float: right">
	<button id='button-aud' >Ajouter un document</button>
</span>

<h2 class='grid_xx'>
	<i class='sprite sprite-application_view_columns' ></i>
	Gestion des commissions
</h2>
<span>
	Liste des documents pouvant être générés depuis la partie dossiers<br/><br/>
</span>

<?
	$dir_nom = './data/uploads/documents'; // dossier listé (pour lister le répertoir courant : $dir_nom = '.'  --> ('point')
	$dir = opendir($dir_nom) or die('Erreur de listage : le répertoire n\'existe pas'); // on ouvre le contenu du dossier courant
	$fichier= array(); // on déclare le tableau contenant le nom des fichiers
	$dossier= array(); // on déclare le tableau contenant le nom des dossiers

	while($element = readdir($dir)) {
		if($element != '.' && $element != '..') {
			if (!is_dir($dir_nom.'/'.$element)) {$fichier[] = $element;}
			else {$dossier[] = $element;}
		}
	}
	closedir($dir);

	if(!empty($fichier)){
		echo "
			<table>
			<tr>
				<th>
					Nom du fichier
				</th>
				<th>
					Supprimer
				</th>
			</tr>
		";
		sort($fichier);// pour le tri croissant, rsort() pour le tri décroissant
		foreach($fichier as $lien) {
			echo "
				<tr>
					<td>
						<a href=\"$dir_nom/$lien \">$lien</a>
					</td>
					<td>
					</td>
				</tr>
			";
		}
		echo "</table>";
	 }else{
		echo "Actuellement aucun document disponible";
	 }

?>

<script type="text/javascript">

	// Ajout d'un type
	$("#button-aud").button({
		icons: { primary: "ui-icon-plus" }
	}).click(function() {
		dialog_aud();
	});
	
	function dialog_aud() {
		$('#dialog-aud').dialog("destroy");
		$("#dialog-aud").remove();
		var dialog_aud = $("<div id='dialog-aud'></div>").appendTo("body");
		dialog_aud.dialog({
			title: "Ajouter un document type",
			width: 650,
			draggable: false,
			resizable: false,
			modal: true,
			create: function() {
				dialog_aud.load( "/gestion-des-documents/form" );
			},
			buttons: {
				"Envoyer" : function() {
					if(!$("#fichier").val()){
						$("#fichier").click();
					}else{
					
						//alert('Enregistrement de la pj');
						$.ajax({
							url: "/gestion-des-documents/add",
							data: $("#form-gdc").serialize(),
							type: "POST",
							success: function () {
								dialog_aud.dialog("destroy");
								$("#index-left ul li.active a").click();
							}
						});
					}
					
				},
				"Annuler": function() {
					dialog_aud.dialog("destroy");
				}
			}
		});
	}	