<form method='post' id='formDocType' name='formDocType' enctype='multipart/form-data' action='/gestion-des-documents/add' target='hiddeniframe' >
	<dl>
		<dt>Fichier à envoyer</dt>
		<dd>
			<p>
				<input type='file' name='fichier' id='fichier' size='30'  style='filter :alpha(opacity=0);' />
			</p>
		</dd>
	</dl>
	<dl>
	<!--
		Ici rappeler les différents champs qui peuvent être insérés dans les documents
	-->
	</dl>
</form>