<!-- Titre -->
<span style="float: right">
	<a id='button-aud' class='btn' >Ajouter un document</a>
</span>

<h3 class='page-header'>Gestion des documents</h3>
<div id='infosGdd'></div>



<?php

	$nbFichier = count($this->fichierVer);
	echo "<h2>Visible après vérrouillage  (".( ($nbFichier > 0)? "<a id='num_0' href='' >".$nbFichier."</a>" : "0").")</h2>" ;
	echo "<div class='span12'>";
	echo "
    	<table id='file_0' class='table table-bordered' >
		    <thead>
		        <tr style='height:20px;'>
		            <th>
		                Nom du fichier
		            </th>
		            <th>
		            </th>
		        </tr>
		    </thead>
		    <tbody>
    ";
	if($nbFichier > 0){
		foreach($this->fichierVer as $fichier){
	        echo "
	        	<tr style='height:20px;'>
			        <td>
			            <a href='".$this->path . DS ."0". DS . htmlspecialchars($fichier, ENT_QUOTES) ."'>".$fichier."</a>
			        </td>
			        <td>
			            <a href='#' class='supp' id='".htmlspecialchars($fichier, ENT_QUOTES)."'>Suppression du document</a>
			        </td>
			    </tr>
        	";
		}
	}else{
    	echo "
    		<tr>
			        <td colspan='2'>
			        	Aucun fichier
			        </td>
			    </tr>
        	";
    }
    echo "
    		</tbody>
    		</table>
    	</div>
    ";

	foreach($this->liste_commission as $commission){
		if(!isset($id_type) || isset($id_type) && $id_type != $commission['ID_COMMISSIONTYPE']){
			echo "<h2>".$commission['LIBELLE_COMMISSIONTYPE']." </h2>" ;
			$id_type = $commission['ID_COMMISSIONTYPE'];
		}

        echo "<div class='span12'>";
        $nbFichier = count($commission['listeFichier']);
        if($nbFichier > 0){
        	echo "<a href='' id='".$commission['ID_COMMISSION']."' class='commission'>".$commission['LIBELLE_COMMISSION']."</a> (<a id='num_".$commission['ID_COMMISSION']."' >".$nbFichier."</a>)";
        }else{
        	echo $commission['LIBELLE_COMMISSION'];
        }
        echo "</div><br/>";

        if($nbFichier > 0){
	        echo "
	        	<table id='file_".$commission['ID_COMMISSION']."' class='table table-bordered' style='display:none;'>
				    <thead>
				        <tr style='height:20px;'>
				            <th>
				                Nom du fichier
				            </th>
				            <th>
				            </th>
				        </tr>
				    </thead>
				    <tbody>
	        ";
	        foreach($commission['listeFichier'] as $file){
	        	echo "
	        		
	        			<tr style='height:20px;'>
				        <td>
				            <a href='".$this->path . DS . $commission['ID_COMMISSION']. DS . htmlspecialchars($file, ENT_QUOTES) ."'>".$file."</a>
				        </td>
				        <td>
				            <a href='#' class='supp' id='".htmlspecialchars($file, ENT_QUOTES)."'>Suppression du document</a>
				        </td>
				    </tr>
	        	";
	        }
	        echo "
	        	</tbody>
	        	</table>
	        ";
	    }
    }
?>

<script type="text/javascript">

$(document).ready(function() {

    $("body").append("<iframe name='hiddeniframe' id='hiddeniframe' src='about:blank' style='width:0px; height:0px' >");

    // Ajout d'un type
    $("#button-aud").click(function() {
        dialog_aud();
    });

    function dialog_aud() {
        $('#dialog-aud').html("");
        $('#dialog-aud').dialog("destroy");
        $("#dialog-aud").remove();

        var dialog_aud = $("<div id='dialog-aud'></div>").appendTo("body");

        dialog_aud.dialog({
            title: "Ajouter un document type",
            width: 650,
            draggable: false,
            resizable: false,
            modal: true,
            create: function() {
                dialog_aud.load( "/gestion-des-documents/form" );
            },
            buttons: {
                "Envoyer" : function() {
                    if(!$("#fichier").val()){
                        $("#fichier").click();
                    }else{
                        $("#formDocType").submit();

                        $(this).dialog('close'); 

                        // On ouvre la barre de chargement
                        $("<div id='load' style='text-align: center'><img src='/images/bar.gif' alt='Upload en cours' /></div>").dialog({
                            resizable: false,
                            height: 28,
                            width: 250,
                            modal: true,
                            dialogClass: 'noTitleStuff'
                        });
                    }
                },
                "Annuler": function() {
                        $(this).dialog('close'); 
                }
            }
        });

    }

    $(".supp").click(function(){
        //alert($(this).attr('id'));

        dialog_supp($(this));
        //alert($("#nnnn.jpg").attr('class'));
        return false;
    });


    function dialog_supp(elementDoc) {
        var nomFichier = elementDoc.attr('id');

        $('#dialog-supp').dialog("destroy");
        $("#dialog-supp").remove();

        var dialog_supp = $("<div id='dialog-supp'></div>").appendTo("body");

        dialog_supp.html("Vous êtes sur le point de supprimer le fichier \""+nomFichier+"\".<br/> Une fois ce fichier supprimé il ne pourra plus être utilisé lors de la génération des rapports.");

        dialog_supp.dialog({
            title: "Suppression document",
            width: 650,
            draggable: false,
            resizable: false,
            modal: true,
            buttons: {
                "Supprimer" : function() {
                    var infoComm = elementDoc.parent().parent().parent().parent().attr('id');
                    var tabIdComm = infoComm.split("_");
                    var idComm = tabIdComm[1];

                    $.ajax({
                        type: "POST",
                        url: "/gestion-des-documents/suppdoc",
                        data:{
                            name:nomFichier,
                            idCommission:idComm
                        },
                        success: function(msg){
                            
                            if (msg != "") window.location.reload();
                            
                            //suppression de la ligne
                            elementDoc.parent().parent().remove();
                            
                            var num = $("#num_"+idComm).html();
                            if(num == 1){
                                $("#file_"+idComm).hide();
                                $("#num_"+idComm).html('0');
                            }else{
                                num--;
                                $("#num_"+idComm).html(num);
                            }
                        }
                    });

                    dialog_supp.dialog("close");
                    $("#dialog-supp").html('');
                    return false;
                },
                "Annuler": function() {
                    dialog_supp.dialog("close");
                    $("#dialog-supp").html('');
                }
            }
        });

    }

    $(".commission").click(function(){
        $("#file_"+$(this).attr('id')).toggle();
        return false;
    });
});
</script>
