<!-- Titre -->
<span style="float: right">
	<a id='button-aud' class='btn' >Ajouter un document</a>
</span>

<h3 class='page-header'>Gestion des documents</h3>
<div id='infosGdd'></div>

<?php if(empty($this->listeFichiers)) : ?>
<p><strong>Aucun document disponible.</strong></p>
<?php else : ?>
<table id='documentType' class='table table-bordered'>
    <thead>
        <tr style='height:20px;'>
            <th>
                Nom du fichier
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->listeFichiers as $lien) : ?>
    <tr style='height:20px;'>
        <td>
            <a href="<?php echo $this->path . "/" . $lien ?>"><?php echo $lien ?></a>
        </td>
        <td>
            <a href='#' class='supp' id="<?php echo $lien ?>">Suppression du document</a>
        </td>
    </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif ?>


<script type="text/javascript">

$(document).ready(function() {
	
	$("body").append("<iframe name='hiddeniframe' id='hiddeniframe' src='about:blank' style='width:0px; height:0px' >");

	// Ajout d'un type
	$("#button-aud").click(function() {
		dialog_aud();
	});
	
	function dialog_aud() {
		$('#dialog-aud').html("");
		$('#dialog-aud').dialog("destroy");
		$("#dialog-aud").remove();
		
		var dialog_aud = $("<div id='dialog-aud'></div>").appendTo("body");

		dialog_aud.dialog({
			title: "Ajouter un document type",
			width: 650,
			draggable: false,
			resizable: false,
			modal: true,
			create: function() {
				dialog_aud.load( "/gestion-des-documents/form" );
			},
			buttons: {
				"Envoyer" : function() {
					if(!$("#fichier").val()){
						$("#fichier").click();
					}else{
						$("#formDocType").submit();
						
						$(this).dialog('close'); 
						
						// On ouvre la barre de chargement
						$("<div id='load' style='text-align: center'><img src='/images/bar.gif' alt='Upload en cours' /></div>").dialog({
							resizable: false,
							height: 28,
							width: 250,
							modal: true,
							dialogClass: 'noTitleStuff'
						});
					}
					
				},
				"Annuler": function() {
					dialog_aud.dialog("destroy");
				}
			}
		});

	}
	
	$(".supp").click(function(){
		//alert($(this).attr('id'));
		
		dialog_supp($(this));
		//alert($("#nnnn.jpg").attr('class'));
		return false;
	});
	
	
	function dialog_supp(elementDoc) {
		var nomFichier = elementDoc.attr('id');
	
		$('#dialog-supp').dialog("destroy");
		$("#dialog-supp").remove();

		var dialog_supp = $("<div id='dialog-supp'></div>").appendTo("body");
		
		dialog_supp.html("Vous êtes sur le point de supprimer le fichier \""+nomFichier+"\".<br/> Une fois ce fichier supprimé il ne pourra plus être utilisé lors de la génération des rapports.");

		dialog_supp.dialog({
			title: "Suppresion document",
			width: 650,
			draggable: false,
			resizable: false,
			modal: true,
			buttons: {
				"Supprimer" : function() {

					$.ajax({
						type: "POST",
						url: "/gestion-des-documents/suppdoc",
						data:{
                                                    name:nomFichier
                                                },
						success: function(msg){					
							//suppression de la ligne
							elementDoc.parent().parent().remove();
							//alert(msg);
						}
					});


					
					dialog_supp.dialog("close");
                    $("#dialog-supp").html('');
					return false;
				},
				"Annuler": function() {
					dialog_supp.dialog("close");
                    $("#dialog-supp").html('');
				}
			}
		});

	}
	
});

// Si un fichier est bien uploadé, on l'ajoute à la liste
function callback(nomFich) {
	$.ajax({
		url: "/gestion-des-documents/check",
		data: {
			"format": "json",
			"nomFich": nomFich
		},
		type: "post",
		success: function(result) {
			// On détruit la fenetre de load
			$("#load").remove();
			
			if( result.exists ) {
				window.location.reload();
			} else {
				alert('fail');				
			}
		}
	});
}

</script>
