<?php foreach ($this->listePj as $pj) : ?>
    <tr>
        <!-- Lien de la pièce jointe -->
        <td>
            <a
                class="file <?php echo substr(strtolower($pj['EXTENSION_PIECEJOINTE']), 1, 3) ?>"
                href='<?php echo $this->url(array('controller' => 'piece-jointe', 'action' => 'get', 'id' => $this->id, 'idpj' => $pj['ID_PIECEJOINTE'], 'type' => $this->type)) ?>'
                <?php if ($pj['DESCRIPTION_PIECEJOINTE']): ?> title="<?php echo $pj['DESCRIPTION_PIECEJOINTE'] ?>" <?php endif ?>
                target='_blank' >
                    <?php echo $pj['NOM_PIECEJOINTE'].$pj['EXTENSION_PIECEJOINTE'] ?>
                </a>
        </td>

        <!-- Description -->
        <td><?php echo nl2br(str_replace("<br />", "" ,$pj['DESCRIPTION_PIECEJOINTE'])) ?></td>

        <!-- Date de création -->
        <td>
            <?php
                $date = new Zend_Date($pj['DATE_PIECEJOINTE'], Zend_Date::DATES);
                echo $date->get( Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR );
            ?>
        </td>

        <td class="checkbox">
            <?php switch ($pj['NOM_STATUT']):
                case 'not_exported': ?>
                    <input type="checkbox" name="export-pj-platau" data-id="<?= $pj['ID_PIECEJOINTE'] ?>" value="0" />
            <?php break;
                case 'to_be_exported': ?>
                    <div class="label label-info">En attente d'envoi</div>
            <?php break;
                case 'exported': ?>
                    <div class="label label-success">Envoyé</div>
            <?php break;
                case null:
                default: ?>
                    <div class="label label-warning">Statut inconnu</div>
            <?php endswitch ?>
        </td>

        <!-- Action -->
        <td>
            <?php if($this->verrou != 1): ?>
                <a class='delete' href='/piece-jointe/delete?id_pj=<?php echo $pj["ID_PIECEJOINTE"] ?>&type=<?php echo $this->type ?>&id=<?php echo $this->id ?>'>
                    <i class="icon-trash"></i>
                </a>
            <?php endif ?>
        </td>
    </tr>
<?php endforeach ?>
