<?php foreach ($this->listePj as $pj) : ?>
<tr>   
    <!-- Lien de la pièce jointe -->
    <td><a href='<?php echo $this->path . $pj['ID_PIECEJOINTE'] . $pj['EXTENSION_PIECEJOINTE'] ?>' title='<?php echo $pj['DESCRIPTION_PIECEJOINTE'] ?>' target='_blank' ><?php echo $pj['NOM_PIECEJOINTE'] ?></a></td>
    
    <!-- Description -->
    <td><?php echo nl2br(str_replace("<br />", "" ,$pj['DESCRIPTION_PIECEJOINTE'])) ?></td>
    
    <!-- date de création-->
    <td>
        <?php
            $date = new Zend_Date($pj['DATE_PIECEJOINTE'], Zend_Date::DATES);
            echo $date->get( Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR );
        ?>
    </td>
    
    <?php if($this->type == 'dossier') echo "<td><input type='checkbox' id='select_".$pj['ID_PIECEJOINTE']."' class='select' ".( ($pj['PJ_COMMISSION'] == '1')? "checked='checked'" : "" )." /></td>"; ?>	
    
    <!-- Action-->
    <td>
        <a id='delete' href='/piece-jointe/delete?id_pj=<?php echo $pj["ID_PIECEJOINTE"] ?>&type=<?php echo $this->type ?>&id=<?php echo $this->id ?>' style='text-decoration: none' >&times;</a>
    </td>
</tr>
<?php endforeach ?>