<input type='hidden' name='typePJ' id='typePJ' value='<?php echo $this->type ?>' />
<input type='hidden' name='idLinkPJ' id='idLinkPJ' value='<?php echo $this->identifiant ?>' />

<h3>Liste de pièces jointes</h3>

<button id='addPJ' class='btn' style='float: right; margin-left: 1em;' >Ajouter une piece jointe</button>
<div id='formAddPJ' title='Ajouter une pièce jointe' class='ui-helper-hidden' ></div>		


<div id='listePieceJointe' class='<?php if(count($this->listePj)==0) echo "ui-helper-hidden"?>' >
	<table id='tabPieceJointe' class='table'> 
		<thead> 
			<tr>
				<th>Nom</th> 
				<th>Description</th>
				<th>Date d'ajout</th>
                <?php if($this->type == 'dossier') echo "<th>Rapport validé</th>"?>
				<th></th>
			</tr> 
		</thead> 
		<tbody>
			<?php echo $this->partial("piece-jointe/display.phtml", array("path" => $this->path, "listePj" => $this->listePj, "type" => $this->type, "id" => $this->identifiant)) ?>
		</tbody>
	</table>
</div>

<script type="text/javascript">

	$(document).ready(function() {

		$("body").append("<iframe name='hiddeniframe' id='hiddeniframe' src='about:blank' style='width:0px; height:0px' >");

		// Bouton de la pièce jointe
		$("#addPJ").button({
		
			icons: {
				primary: 'ui-icon-pin-s'
			},
			text: true
			
		}).click(function() {

			// Dialogue du formulaire
			$.ajax({
				url: "/piece-jointe/form",
				data: "id=" + $("#idLinkPJ").val() + "&type=" + $("#typePJ").val(),
				type: "post",
				success: function(result) {
					
					$("#formAddPJ").html(result).dialog({
						resizable: false,
						height: 500,
						width: 580,
						modal: true,
						buttons: {
							'Ajouter la pièce jointe': function() {
								
								// Envoi du formulaire dans form
								$("#formUpload").submit();
								
								// On ferme la boite de dialogue
								$(this).dialog('close'); 
								
								// On ouvre la barre de chargement
								$("<div id='load' style='text-align: center'><img src='/images/bar.gif' alt='Upload en cours' /></div>").dialog({
									resizable: false,
									height: 45,
									width: 250,
									modal: true,
									dialogClass: 'noTitleStuff'
								});
							}
						}
					});
				}
			});
		});

		// Supp. d'une pièce jointe
		$("a#delete").live("click", function() {
		
			var a = this;
			$.ajax({
				url: a.href,
				data: "&type=<?php echo $this->type ?>",
				type: "post",
				success: function(result) {
					$(a).parent().parent().remove();
				}
			});
			return false;
		});
		
        $('a[href$=png], a[href$=jpg], a[href$=jpeg]').fancybox({
            'transitionIn'	:	'elastic',
            'transitionOut'	:	'elastic',
            'speedIn'		:	600, 
            'speedOut'		:	200, 
        });
        
        $(".select").live('click',function(){
            var idAvantSplit = $(this).attr('id');
            var tabId = idAvantSplit.split('_');
            var id = tabId[1];
            var checked = $(this).attr('checked');
            $.ajax({
                url: "/dossier/fonction",
                data: "do=pjPassageCommission&idPjCommission="+id+"&idDossier="+$("#idDossier").val()+"&checked="+checked,
                type:"POST",
                beforeSend: function(){
                    
                },
                success: function(affichageResultat){
                    //alert(checked);
                    if(checked == true){
                        $(".select").each(function(){
                            $(this).attr('disabled','disabled');
                        });
                        $("#"+idAvantSplit).attr('disabled','');
                    }else{
                        $(".select").each(function(){
                            $(this).attr('disabled','');
                        });
                    }
                },
                error: function()	{

                    return false;
                }
            });
        });
        
        function disabledTest(){
            var test = 0;
            $(".select").each(function(){
                if($(this).attr('checked')){
                    test = 1;
                }
                
            });
            if(test == 1){
                $(".select").each(function(){
                    if(!$(this).attr('checked')){
                        $(this).attr('disabled','disabled');
                    }			
                });
            }
        
        }
        disabledTest();
		
	});
	
	// Si un fichier est bien uploadé, on l'ajoute à la liste
	function callback(id, ext) {

		$.ajax({
			url: "/piece-jointe/check",
			data: {
				"format": "json",
				"idpj" : id,
				"ext" : ext,
				"type" : "<?php echo $this->type ?>",
				"id" : "<?php echo $this->identifiant ?>"
			},
			type: "post",
			success: function(result) {
			
				// On détruit la fenetre de load
				//$("#load").dialog('destroy');
				$("#load").remove();
			
				if( result.exists ) {
					// Message d'info
					$("#uploadSucces").show();
					setTimeout( function() { $(".message").fadeOut(); }, 2500);
					
					// Ajout d'une ligne
					$("#tabPieceJointe tbody").prepend(result.html);
					
					// Mise à jour
					$("#listePieceJointe table").trigger("update");
					$("#listePieceJointe table").trigger("sorton", [[3,1]]);
				}
				else {
					// Message d'information
					$("#uploadError").show();
					setTimeout( function() { $(".message").fadeOut(); }, 2500);
				}
				
				$("#listePieceJointe").show();
				$("#listePieceJointe-no").hide();
			}
		});
	}

</script>