<?php if($this->droit_ecriture) : ?>
<script type="text/javascript">

	$(document).ready(function() {

		$("body").append("<iframe name='hiddeniframe' id='hiddeniframe' src='about:blank' style='width:0px; height:0px' >");

		// Bouton de la pièce jointe
		$("#addPJ").button({
		
			icons: {
				primary: 'ui-icon-pin-s'
			},
			text: true
			
		}).click(function() {

			// Dialogue du formulaire
			$.ajax({
				url: "/piece-jointe/form",
				data: "id=" + $("#idLinkPJ").val() + "&type=" + $("#typePJ").val(),
				type: "post",
				success: function(result) {
					
					$("#formAddPJ").html(result).dialog({
						resizable: false,
						height: 500,
						width: 580,
						modal: true,
						buttons: {
							'Ajouter la pièce jointe': function() {
								
								// Envoi du formulaire dans form
								$("#formUpload").submit();
								
								// On ferme la boite de dialogue
								$(this).dialog('close'); 
								
								// On ouvre la barre de chargement
								$("<div id='load' style='text-align: center'><img src='/images/bar.gif' alt='Upload en cours' /></div>").dialog({
									resizable: false,
									height: 28,
									width: 250,
									modal: true,
									dialogClass: 'noTitleStuff'
								});
							}
						}
					});
				}
			});
		});

		// Supp. d'une pièce jointe
		$("a#delete").live("click", function() {
		
			var a = this;
			$.ajax({
				url: a.href,
				data: "&type=<?php echo $this->type ?>",
				type: "post",
				success: function(result) {
					$(a).parent().parent().remove();
				}
			});
			return false;
		});
		
		
	});
	
	// Si un fichier est bien uploadé, on l'ajoute à la liste
	function callback(id, ext) {

		$.ajax({
			url: "/piece-jointe/check",
			data: {
				"format": "json",
				"idpj" : id,
				"ext" : ext,
				"type" : "<?php echo $this->type ?>",
				"id" : "<?php echo $this->identifiant ?>"
			},
			type: "post",
			success: function(result) {
			
				// On détruit la fenetre de load
				//$("#load").dialog('destroy');
				$("#load").remove();
			
				if( result.exists ) {
					// Message d'info
					$("#uploadSucces").show();
					setTimeout( function() { $(".message").fadeOut(); }, 2500);
					
					// Ajout d'une ligne
					$("#tabPieceJointe tbody").prepend(result.html);
					
					// Mise à jour
					$("#listePieceJointe table").trigger("update");
					$("#listePieceJointe table").trigger("sorton", [[3,1]]);
				}
				else {
					// Message d'information
					$("#uploadError").show();
					setTimeout( function() { $(".message").fadeOut(); }, 2500);
				}
				
				$("#listePieceJointe").show();
				$("#listePieceJointe-no").hide();
			}
		});
	}

</script>
<?php endif ?>

<input type='hidden' name='typePJ' id='typePJ' value='<?php echo $this->type ?>' />
<input type='hidden' name='idLinkPJ' id='idLinkPJ' value='<?php echo $this->identifiant ?>' />

<h3 float='left'>Liste de pièces jointes</h3>

<?php if($this->droit_ecriture) : ?>
<!-- Boutons -->
<div float='right' >
	
	<button id='addPJ' style='float: right; margin-left: 1em;' >Ajouter une piece jointe</button>

	<span style='padding: .5em; margin-bottom: 1em; float: right;' id='uploadSucces' class='message ui-state-highlight ui-helper-hidden'>
		Le document à bien été envoyé.
	</span>
	
	<span style='padding: .5em; margin-bottom: 1em; float: right;' id='uploadError' class='message ui-state-error ui-helper-hidden'>
		Échec pendant le chargement du fichier.
	</span>
	
	<div id='formAddPJ' title='Ajouter une pièce jointe' class='ui-helper-hidden' ></div>		
	
</div>
<?php endif ?>

<br class='clear' />

<?php if(count($this->listePj) == 0) : ?>
	<p id='listePieceJointe-no' ><strong>Aucune pièce jointe ajoutée.</strong></p>
<?php endif ?>

<div id='listePieceJointe' class='<?php if(count($this->listePj)==0) echo "ui-helper-hidden"?>' >
    <!--
	<div id='pager' >
		<form>
			<div id='img_button' float='left'>
				<i class='sprite sprite-resultset_first first' ></i>
				<i class='sprite sprite-resultset_previous prev' ></i>
				<input type='text' class='pagedisplay' size='6' disabled style='text-align: center' />
				<i class='sprite sprite-resultset_next next' ></i>
				<i class='sprite sprite-resultset_last last' ></i>
			</div>
			
			<div float='right'>
				<select class='pagesize'>
					<option value='10'>10 par page</option>
					<option value='20' selected='selected'>20 par page</option>
					<option value='50'>50 par page</option>
					<option value='100'>100 par page</option>
				</select>
			</div>
		</form>
	</div>
	
	<hr class='clear' />
    -->
	
	<table id='tabPieceJointe' class='tablesorter'> 
		<thead> 
			<tr>
				<th style='width: 50px;'>Type</th>
				<th>Nom</th> 
				<th>Description</th>
				<th>Date d'ajout</th>
<?php
	if($this->type == 'dossier'){
		echo "<th>Rapport final</th>";
	}
?>
				<th>&nbsp;</th>
			</tr> 
		</thead> 
		<tbody>
			<?php echo $this->partial("piece-jointe/display.phtml", array("path" => $this->path, "listePj" => $this->listePj, "droit_ecriture" => $this->droit_ecriture, "type" => $this->type, "id" => $this->identifiant)) ?>
		</tbody>
	</table>
</div>