<?php
echo "
	<form name='formTexteAppl' id='formTexteAppl' action='' method='POST'>
";
if($this->idTexteAppl)
{
	echo "<input type='hidden' name='idTexteAppl' id='idTexteAppl' value='".$this->texteEdit[0]['ID_TEXTESAPPL']."' />";
}
echo "	
		<select name='type' id='type'>
";
	foreach($this->listeType as $var => $ue)
	{
		echo "<option value='".$ue['ID_TYPETEXTEAPPL']."' ".( ($this->idTexteAppl && $this->texteEdit[0]['ID_TYPETEXTEAPPL'] == $ue['ID_TYPETEXTEAPPL'])? "selected='selected'" : "" ).">".$ue['LIBELLE_TYPETEXTEAPPL']."</option>";
	}		
echo "
		</select>
		<hr class='clear'>
		<textarea name='libelle' cols='150' rows='5'>".( ($this->idTexteAppl && $this->texteEdit[0]['LIBELLE_TEXTESAPPL'] != '')? $this->texteEdit[0]['LIBELLE_TEXTESAPPL'] : "" )."</textarea>
		<hr class='clear'>
		<select name='visible' id='visible'>
			<option value='1' ".( ($this->idTexteAppl && $this->texteEdit[0]['VISIBLE_TEXTESAPPL'] == 1)? " selected": "" ).">Afficher</option>
			<option value='0' ".( ($this->idTexteAppl && $this->texteEdit[0]['VISIBLE_TEXTESAPPL'] == 0)? " selected": "" ).">Masquer</option>
		</select>
		<br/><br/>
		Rendre ce texte disponible pour les prescriptions
		<div class='row'>
			<div class='span2'>
				<input type='radio' name='defPrescription' value='yes' />&nbsp;Oui
			</div>
			<div class='span2'>
				<input type='radio' name='defPrescription' value='no' checked />Non
			</div>
			<div class='span8'></div>
		</div>
	</form>
";