<?php
echo "
    <h3 class='page-header'>Gestion des textes applicables</h3>
	<button id='createTexteAppl' class='btn'><i class='icon-plus'></i>&nbsp;Ajouter un texte applicable</button><br/><br/>
";

$idTypeMarq = "";
$marqueur = 1;

foreach($this->listeTextesAppl as $val => $ue){
	$idType = $ue['ID_TYPETEXTEAPPL'];
	if($idTypeMarq != $idType){
		//Pour l'affichage par catégorie
		if($marqueur != 1){
			echo "</ul>";
		}
		echo "
			<div class='row-fluid'>
			<div class='span12' style='font-weight:bold;font-size:25px;' >".$ue['LIBELLE_TYPETEXTEAPPL']."</div>
			</div>
		";
		$idTypeMarq = $idType;
		echo "<ul class='sortTexteAppl unstyled' id='liste_".$ue['ID_TYPETEXTEAPPL']."'>";
		$marqueur = 0;
	}
	echo "
		<li class='row-fluid' style='margin-top:15px;margin-bottom:10px;' id='".$ue['ID_TEXTESAPPL']."'>
			<div class='span10'>".nl2br($ue['LIBELLE_TEXTESAPPL'])."</div>
			<div class='span1'><button class='editTexteAppl btn' id='".$ue['ID_TEXTESAPPL']."' ><i class='icon-pencil'></i>&nbsp;Editer</button></div>
			<div class='span1'>".( ($ue['VISIBLE_TEXTESAPPL'] == 1 )? "<img src='/images/visible.gif' alt='visible' />" : "<img src='/images/nonvisible.gif' alt='non visible' />")."</div>
		</li>
	";
}

?>
<script type='text/javascript' >
$(document).ready(function() {
	$(".sortTexteAppl").sortable({
		update: function(event, ui) {
			var id = $(this).attr('id');
			var listeTexteApplUpdate = new Array();
			var listeOrder = "";
			$("#"+id+" > li").each(function(){
				//on parcour les li pour récolter les changements et mettre à jour dans la base
				//on recupere id du li en cours
				var liId = $(this).attr('id');
				listeOrder += liId+",";
				listeTexteApplUpdate.push(liId);
			});			
			$.ajax({
				url: "/gestion-textes-applicables/updateorder",
				data: "tableUpdate="+listeTexteApplUpdate,
				type:"POST",
				beforeSend: function(){

				},
				success: function(affichageResultat){
					return false;
				},
				error: function()	{
					return false;
				}
			});
		}
	});

	var dialogEditTexteAppl = $('<div style="display:none"></div>').appendTo('body');
	
	$(".editTexteAppl").click(function(){
		//On ouvre la boite de dialogue
		var id = $(this).attr('id');
		$.ajax({
			type: "POST",
			url: "/gestion-textes-applicables/formtexteappl",
			data: "&id="+id,
			success: function(msg){
				dialogEditTexteAppl.html(msg);
				dialogEditTexteAppl.dialog("open");
			}
		});
	});
	
	$("#createTexteAppl").click(function(){
		$.ajax({
			type: "POST",
			url: "/gestion-textes-applicables/formtexteappl",
			success: function(msg){
				dialogEditTexteAppl.html(msg);
				dialogEditTexteAppl.dialog("open");
			}
		});
	});
	
	dialogEditTexteAppl.dialog({
		title: "Modification texte applicable",
		modal: true,
		autoOpen: false,
		width: 'auto',
		height: 'auto',
		buttons: {
			"Sauvegarder": function() {
				$.ajax({
					type: "POST",
					url: "/gestion-textes-applicables/save",
					data: $("#formTexteAppl").serialize(),
					success: function(msg){
						dialogEditTexteAppl.html("");
						dialogEditTexteAppl.dialog("close");
						if($("#gestionTextesAppl").length){
							$("#gestionTextesAppl").click();
						}else{
							window.location='/gestion-textes-applicables';
						}
						
					}
				});
				return false;
			},
			"Annuler": function() {
				dialogEditTexteAppl.dialog("close");
			}
		},
		close: function(event, ui){
			
		}

	});

});
</script>