<?php
echo "
    <h3 class='page-header'>Gestion des textes applicables</h3>
	<button id='createTexteAppl' class='btn'><i class='icon-plus'></i>&nbsp;Ajouter un texte applicable</button><br/><br/>
";

$idTypeMarq = "";
foreach($this->listeTextesAppl as $val => $ue){
	$idType = $ue['ID_TYPETEXTEAPPL'];
	if($idTypeMarq != $idType){
		//Pour l'affichage par catégorie
		echo "
			<div class='row-fluid'>
			<div class='span12' style='font-weight:bold;font-size:25px;'>".$ue['LIBELLE_TYPETEXTEAPPL']."</div>
			<hr class='clear'>
			</div>
		";
		$idTypeMarq = $idType;
	}
	echo "
		<div class='row-fluid' style='margin-top:10px;margin-bottom:10px;'>
		<div class='span10'>".nl2br($ue['LIBELLE_TEXTESAPPL'])."</div>
		<div class='span1'><button class='editTexteAppl btn' id='".$ue['ID_TEXTESAPPL']."'><i class='icon-pencil'></i>&nbsp;Editer</button></div>
		<div class='span1'>".( ($ue['VISIBLE_TEXTESAPPL'] == 1 )? "<img src='/images/visible.gif' alt='visible' />" : "<img src='/images/nonvisible.gif' alt='non visible' />")."</div>
		<hr class='clear'>
		</div>
	";

}

?>
<script type='text/javascript' >
$(document).ready(function() {
	var dialogEditTexteAppl = $('<div style="display:none"></div>').appendTo('body');
	
	$(".editTexteAppl").click(function(){
		//On ouvre la boite de dialogue
		var id = $(this).attr('id');
		$.ajax({
			type: "POST",
			url: "/gestion-textes-applicables/formtexteappl",
			data: "&id="+id,
			success: function(msg){
				//alert(msg);
				dialogEditTexteAppl.html(msg);
				dialogEditTexteAppl.dialog("open");
			}
		});
	});
	
	$("#createTexteAppl").click(function(){
		$.ajax({
			type: "POST",
			url: "/gestion-textes-applicables/formtexteappl",
			success: function(msg){
				//alert(msg);
				dialogEditTexteAppl.html(msg);
				dialogEditTexteAppl.dialog("open");
			}
		});
	});
	
	dialogEditTexteAppl.dialog({
		title: "Modification texte applicable",
		modal: true,
		autoOpen: false,
		width: 'auto',
		height: 'auto',
		buttons: {
			"Sauvegarder": function() {
				$.ajax({
					type: "POST",
					url: "/gestion-textes-applicables/save",
					data: $("#formTexteAppl").serialize(),
					success: function(msg){
						//alert(msg);
						dialogEditTexteAppl.html("");
						dialogEditTexteAppl.dialog("close");
						if($("#gestionTextesAppl").length){
							$("#gestionTextesAppl").click();
						}else{
							window.location='/gestion-textes-applicables';
						}
						
					}
				});
				return false;
			},
			"Annuler": function() {
				dialogEditTexteAppl.dialog("close");
			}
		},
		close: function(event, ui){
			
		}

	});

});
</script>