<?php
	echo "
		<form name='formArticleEdit' id='formArticleEdit' action='/gestion-prescriptions/gestion-articles' method='POST'>
			<input type='hidden' name='id_article' id='id_article' value='".$this->articleInfo['ID_ARTICLE']."' />
			<input type='hidden' name='action' id='action' value='".$this->action."' />
			<div class='row'>
				<div class='span12' >
					<a href='/gestion-prescriptions'>Gestion des prescriptions types</a> <i class='icon-chevron-right'></i> <a href='/gestion-prescriptions/gestion-articles'>Gestion des articles</a>
					<i class='icon-chevron-right'></i>
	";
	if($this->action == 'add'){
		echo "Ajout d'un nouvel article";
	}else if($this->action == 'edit'){
		echo "Modification d'un article existant";
	}
	echo "
				</div>
			</div>
			<h3 class='page-header'>
	";
	if($this->action == 'add'){
		echo "Ajout d'un nouvel article";
	}else if($this->action == 'edit'){
		echo "Modification d'un article existant";
	}
	echo "
			</h3>
			<div class='row'>
				<div class='span12' style='text-align:right;'>
					<a class='btn btn-default' href='/gestion-prescriptions/gestion-articles'>
	";
	if($this->action == 'add'){
		echo "Retourner à la liste des articles";
	}else if($this->action == 'edit'){
		echo "Annuler la modification";
	}
	echo "</a>
					<input type='submit' class='btn btn-success' value='Sauvegarder' />
				</div>
			</div>
			<br/><br/>
			<div class='row'>
				<div class='span2'>
					Libellé de l'article
				</div>
				<div class='span10'>
	";
	echo '
				<input type="text" name="LIBELLE_ARTICLE" id="LIBELLE_ARTICLE" value="'.$this->articleInfo['LIBELLE_ARTICLE'].'" style="width:100%;"/>
	';
	echo "
				</div>
			</div>
			<div class='row'>
				<div class='span2'>
					Visibilité de l'article
				</div>
				<div class='span10'>
					<select name='VISIBLE_ARTICLE'>
						<option value='1' ".( ($this->articleInfo['VISIBLE_ARTICLE'] == 1)? "selected": "" )." >Afficher</option>
						<option value='0' ".( ($this->articleInfo['VISIBLE_ARTICLE'] == 0)? "selected": "" ).">Masquer</option>
					</select>
				</div>
			</div>
			<br/>
			<div class='row' ".( ( $this->action != 'edit' )? "style='display:none;'" : "" ).">
				<div class='span12' style='text-align:center;' >
					<a class='btn btn-warning' id='del-prescription' href='".$this->url(array('controller'=>'gestion-prescriptions', 'action' => 'gestion-articles-replace'))."'>
						Supprimer l'article et le remplacer par un autre
					</a>
				</div>
			</div>
		</form>
	";

