<?php
	echo "
		<div class='row'>
			<div class='span3'>
				<!--
					<a href='/gestion-prescriptions/gestion-rappel-reg' >Gestion des prescriptions type</a>
				-->
			</div>
			<div class='span3'>
				<a href='/gestion-prescriptions/gestion-rappel-reg' >Gestion des rappels réglementaires</a>
			</div>
			<div class='span2'>
				<a href='/gestion-prescriptions/gestion-textes' >Gestion des textes</a>
			</div>
			<div class='span2'>
				<a href='/gestion-prescriptions/gestion-articles' >Gestion des articles</a>
			</div>
			<div class='span2'>
			</div>
		</div>
		<h3 class='page-header'>Gestion des prescriptions types</h3>
		<br/>
	";
	
	echo "
		<form id='FormPrescriptioncat_".$this->idCategorie."' >
			<input type='hidden' name='type' value='categorie' />
			<ul class='prescriptioncat unstyled classement'>
	";
	foreach($this->listePrescriptionCat as $val => $ue)
	{
		echo "
			<li id='categorie_".$ue['ID_PRESCRIPTION_CAT']."'>
				<span style='font-size:17px;font-weight:bold;'>
					<input type='hidden' name='categorie[]' value='".$ue['ID_PRESCRIPTION_CAT']."' />
					".$ue['LIBELLE_PRESCRIPTION_CAT']."
				</span>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<button class='showDetailCat btn' id='showtexte_".$ue['ID_PRESCRIPTION_CAT']."' >Afficher les détails</button>
				<button class='hideDetailCat btn' id='hidetexte_".$ue['ID_PRESCRIPTION_CAT']."' style='display:none;'>Masquer les détails</button>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<button class='editCategorie btn' id='".$ue['ID_PRESCRIPTION_CAT']."' ><i class='icon-pencil'></i>&nbsp;Modifier</button>
				<br/>
				<div style='margin-left:30px;padding-left:10px;border-left:1px solid black;' id='texte_".$ue['ID_PRESCRIPTION_CAT']."'></div>
				<div style='margin-left:30px;padding-left:10px;border-left:1px solid black;' id='prescriptionCat_".$ue['ID_PRESCRIPTION_CAT']."'></div>
				<br/>
			</li>
		";
	}
	echo "
			</ul>
		</form>
		<ul class='prescriptiontypeWithoutCat' class='unstyled'>
	";
	$nbPrescType = count($this->prescriptionType);
	for($i=0; $i < $nbPrescType; $i++)
	{
		echo "
			<li id='prescriptiontype_".$this->prescriptionType[$i][0]['ID_PRESCRIPTIONTYPE']."' style='border-bottom:1px solid grey;'>
				<table class='row-fluid'>
		";

		$nbAssoc = count($this->prescriptionType[$i]);
		$cpt = true;
		for($j=0; $j < $nbAssoc; $j++)
		{
			$article = $this->prescriptionType[$i][$j]['LIBELLE_ARTICLE'];
			$texte = $this->prescriptionType[$i][$j]['LIBELLE_TEXTE'];
			echo "
				<tr >
					<td class='span3' style='vertical-align:top;'>".$texte."</td>
					<td class='span3' style='vertical-align:top;'>".$article."</td>
			";
			if($cpt)
			{
				echo "<td rowspan='".$nbAssoc."' class='span5'>".nl2br($this->prescriptionType[$i][0]['PRESCRIPTIONTYPE_LIBELLE'])."</td>";
				echo "<td rowspan='".$nbAssoc."' class='span1' style='vertical-align:top;'><button class='editPrescriptionType btn' id='' >Editer</button></td>";
				$cpt = false;
			}
			echo "
				</tr>
			";
		}
		echo "
				</table>
			</li>
		";
	}	
	echo "
		</ul>
		<button class='categorie btn' >Ajouter</button>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<br/>
	";
?>


 
<!-- Modal -->
<div id="myModal" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style='width:1000px;margin-left:-500px;' >
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Gestion prescription type</h3>
	</div>
	<div class="modal-body">
	</div>
	<div class="modal-footer">
		<img id='loading' src='/images/load.gif' style='display:none;'/>
		<button class="btn btn-primary savePrescription">Sauvegarder</button>
		<button class="btn closemodal" data-dismiss="modal" aria-hidden="true">Annuler</button>	
	</div>
</div>

<script type="text/javascript">

$(document).ready(function(){
	
//Affiche les textes appartenant à la catégorie
	$(".showDetailCat").live('click',function(){
		//requete ajax pour trouver les prescriptions faisant partie de cette catégorie
		var tabId = $(this).attr('id').split('_');
		var idCat = tabId[1];
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/showprescriptiontexte/id/"+idCat,
			success: function(msg){
				$("#texte_"+idCat).html(msg);
				$("#showtexte_"+idCat).hide();
				$("#hidetexte_"+idCat).show();
				return false;
			}
		});
		return false;
	});
	
	//Masque les textes appartenant à la catégorie
	$(".hideDetailCat").live('click',function(){
		var tabId = $(this).attr('id').split('_');
		var idCat = tabId[1];
		$("#texte_"+idCat).html('');
		$("#hidetexte_"+idCat).hide();
		$("#showtexte_"+idCat).show();
		return false;
	});

	$(".showDetailTexte").live('click',function(){
		//requete ajax pour trouver les prescriptions faisant partie de cette catégorie
		var tabId = $(this).attr('id').split('_');
		var idTexte = tabId[1];
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/showprescriptionarticle/idTexte/"+idTexte,
			success: function(msg){
				$("#article_"+idTexte).html(msg);
				$("#showarticle_"+idTexte).hide();
				$("#hidearticle_"+idTexte).show();
				return false;
			}
		});
		return false;
	});

	$(".hideDetailTexte").live('click',function(){
		var tabId = $(this).attr('id').split('_');
		var idTexte = tabId[1];
		$("#article_"+idTexte).html('');
		$("#hidearticle_"+idTexte).hide();
		$("#showarticle_"+idTexte).show();
		return false;
	});

	$(".showDetailArticle").live('click',function(){
		//requete ajax pour trouver les prescriptions faisant partie de cette catégorie
		var tabId = $(this).attr('id').split('_');
		var idArticle = tabId[1];
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/showarticlecontenu/idArticle/"+idArticle,
			success: function(msg){
				$("#articleDetail_"+idArticle).html(msg);
				$("#showDetailArticle_"+idArticle).hide();
				$("#hideDetailArticle_"+idArticle).show();
				return false;
			}
		});
		return false;
	});
	
	$(".hideDetailArticle").live('click',function(){
		var tabId = $(this).attr('id').split('_');
		var idArticle = tabId[1];
		$("#articleDetail_"+idArticle).html('');
		$("#showDetailArticle_"+idArticle).show();
		$("#hideDetailArticle_"+idArticle).hide();
		return false;
	});
	//Gestion des catégories
	
	var dialogCategorie = $('<div style="display:none;"></div>').appendTo('body');
	
	$(".categorie").live('click',function(){
		//On ouvre la boite de dialogue
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/formcategorie",
			success: function(msg){
				dialogCategorie.html(msg);
				dialogCategorie.dialog("open");
				return false;
			}
		});
		return false;
	});
	
	$(".editCategorie").live('click',function(){
		//On ouvre la boite de dialogue
		var id = $(this).attr('id');
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/formcategorie",
			data: "&id="+id,
			success: function(msg){
				dialogCategorie.html(msg);
				dialogCategorie.dialog("open");
				return false;
			}
		});
		return false;
	});	
	
	dialogCategorie.dialog({
		title: "Gestion",
		modal: true,
		autoOpen: false,
		width: 'auto',
		height: 'auto',
		buttons: {
			"Sauvegarder": function() {
				$.ajax({
					type: "POST",
					url: "/gestion-prescriptions/savecategorie",
					data: $("#formCategorie").serialize(),
					success: function(msg){
						if($("#idCat").val()){
							$("#categorie_"+$("#idCat").val()).html(msg);
						}else{
							$(".prescriptioncat").append(msg);
						}
						dialogCategorie.html("");
						dialogCategorie.dialog("close");
					}
				});
				return false;
			},
			"Annuler": function() {
				dialogCategorie.html("");
				dialogCategorie.dialog("close");
			}
		},
		close: function(event, ui){
			
		}
	});
	
//Gestion des textes
	var dialogTexte = $('<div style="display:none;"></div>').appendTo('body');
		
	$(".addTexteCat").live('click',function(){
		//On ouvre la boite de dialogue
		//On commence par récuperer l'id de la catégorie dans laquelle on va inserer le texte
		var tabId = $(this).parent().attr('id').split('_');
		var idCat = tabId[1];
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/formtexte",
			data: "&idCat="+idCat,
			success: function(msg){
				//alert(msg);
				dialogTexte.html(msg);
				dialogTexte.dialog("open");
				return false;
			}
		});
		return false;
	});
	
	$(".editTexte").live('click',function(){
		//On ouvre la boite de dialogue
		//On commence par récuperer l'id de la catégorie dans laquelle on va inserer le texte
		var idTexte = $(this).attr('id');
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/formtexte",
			data: "&idTexte="+idTexte,
			success: function(msg){
				//alert(msg);
				dialogTexte.html(msg);
				dialogTexte.dialog("open");
				return false;
			}
		});
		return false;
	});
	
	dialogTexte.dialog({
		title: "Gestion texte",
		modal: true,
		autoOpen: false,
		width: 'auto',
		height: 'auto',
		buttons: {
			"Sauvegarder": function() {
				$.ajax({
					type: "POST",
					url: "/gestion-prescriptions/savetexte",
					data: $("#formTexte").serialize(),
					success: function(msg){
						if($("#idCategorie").val()){
							//cas d'un création
							$("#prescriptiontexte_"+$("#idCategorie").val()).append(msg);
						}else{
							$("#texteid_"+$("#idTexte").val()).html(msg);
						}
						dialogTexte.html("");
						dialogTexte.dialog("close");
					}
				});
				return false;
			},
			"Annuler": function() {
				dialogTexte.html("");
				dialogTexte.dialog("close");
			}
		},
		close: function(event, ui){
			
		}
	});
	
//Gestion des articles
	var dialogArticle = $('<div style="display:none;"></div>').appendTo('body');

	$(".addArticleTexte").live('click',function(){
		//On ouvre la boite de dialogue
		//On commence par récuperer l'id de la catégorie dans laquelle on va inserer le texte
		var tabId = $(this).parent().attr('id').split('_');
		var idTexte = tabId[1];
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/formarticle",
			data: "&idTexte="+idTexte,
			success: function(msg){
				dialogArticle.html(msg);
				dialogArticle.dialog("open");
				return false;
			}
		});
		return false;
	});

	dialogArticle.dialog({
		title: "Gestion article",
		modal: true,
		autoOpen: false,
		width: 'auto',
		height: 'auto',
		buttons: {
			"Sauvegarder": function() {
				$.ajax({
					type: "POST",
					url: "/gestion-prescriptions/savearticle",
					data: $("#formArticle").serialize(),
					success: function(msg){
						if($("#idTexte").val()){
							//cas d'un création
							$(".prescriptionarticle_"+$("#idTexte").val()).append(msg);
						}else{
							//cas d'une édition					
							$("#article_"+$("#idArticle").val()).html(msg);
						}
						dialogArticle.html("");
						dialogArticle.dialog("close");
					}
				});
				return false;
			},
			"Annuler": function() {
				dialogArticle.html("");
				dialogArticle.dialog("close");
			}
		},
		close: function(event, ui){
			
		}
	});
	
	$(".editArticle").live('click',function(){
		//On ouvre la boite de dialogue
		//On commence par récuperer l'id de la catégorie dans laquelle on va inserer le texte
		var idArticle = $(this).attr('id');
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/formarticle",
			data: "&idArticle="+idArticle,
			success: function(msg){
				dialogArticle.html(msg);
				dialogArticle.dialog("open");
				return false;
			}
		});
		return false;
	});

//Gestion des prescriptions type
	$(".prescription").live('click',function(){
		var tabId = $(this).attr('id').split('_');
		var typePresc = tabId[0];
		var idEmpl = tabId[1];
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/formprescription",
			data: "&typePresc="+typePresc+"&empl="+idEmpl,
			beforeSend: function(){
				$(".modal-body").html("<img src='/images/load.gif' />");
			},
			success: function(msg){
				$(".modal-body").html(msg);
				$.ajax({
					type: "POST",
					url: "/gestion-prescriptions/emplacement",
					data: $("#formPrescription").serialize(),
					beforeSend: function(){
						$("#selectEmplacement").html("<img src='/images/load.gif' />");
					},
					success: function(msg){
						$("#selectEmplacement").html(msg);
						return false;
					}
				});
			}
		});
		return false;
	});

	$(".selectCategorie").live('click',function(){
		$("#PRESCRIPTIONTYPE_CATEGORIE").val($(this).attr('id'));
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/emplacement",
			data: $("#formPrescription").serialize(),
			success: function(msg){
				$("#selectEmplacement").html(msg);
			}
		});
		return false;
	});
	
	$(".selectTexte").live('click',function(){
		$("#PRESCRIPTIONTYPE_TEXTE").val($(this).attr('id'));
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/emplacement",
			data: $("#formPrescription").serialize(),
			success: function(msg){
				$("#selectEmplacement").html(msg);
			}
		});
		return false;
	});
	
	$(".selectArticle").live('click',function(){
		$("#PRESCRIPTIONTYPE_ARTICLE").val($(this).attr('id'));
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/emplacement",
			data: $("#formPrescription").serialize(),
			success: function(msg){
				$("#selectEmplacement").html(msg);
			}
		});
		return false;
	});
	
	$(".retour").live('click',function(){
		if($(this).attr('id') == 'retourCategorie'){
			$("#PRESCRIPTIONTYPE_CATEGORIE").val('');
		}else if($(this).attr('id') == 'retourTexte'){
			$("#PRESCRIPTIONTYPE_TEXTE").val('');
		}else if($(this).attr('id') == 'retourArticle'){
			$("#PRESCRIPTIONTYPE_ARTICLE").val('');
		}
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/emplacement",
			data: $("#formPrescription").serialize(),
			success: function(msg){
				$("#selectEmplacement").html(msg);
			}
		});
		return false;
	});

	$(".savePrescription").live('click',function(){
		var compteurTA = 0;
		$("input[name='texte[]']").each(function(){
			compteurTA++;
		});
		var data = $("#formPrescription").serialize();
		if(compteurTA > 0 && $("#LIBELLE_PRESCRIPTIONTYPE").val() != '')
		{
			$.ajax({
				type: "POST",
				url: "/gestion-prescriptions/saveprescriptiontype",
				data: data,
				beforeSend: function(){
					$("#loading").show();
				},
				success: function(msg){
					if($("#ID_PRESCRIPTIONTYPE").val() != '')
					{
						$("#prescriptiontype_"+$("#ID_PRESCRIPTIONTYPE").val()).remove();
					}
					
					if($("#PRESCRIPTIONTYPE_CATEGORIE").val() == '')
					{
						//dans le cas ou la prescription n'appartient à aucune catégorie
						$(".prescriptiontypeWithoutCat").append(msg);							
					}
					else if($("#PRESCRIPTIONTYPE_TEXTE").val() == '' && $("#PRESCRIPTIONTYPE_ARTICLE").val() == '')
					{
						//dans le cas ou on ajouter une prescription dans une catégorie
						if($("#texte_"+$("#PRESCRIPTIONTYPE_CATEGORIE").val()).html())
						{
							$("#prescriptiontypeCat_"+$("#PRESCRIPTIONTYPE_CATEGORIE").val()).append(msg);
						}
					}
					else if($("#PRESCRIPTIONTYPE_ARTICLE").val() == '')
					{
						//dans le cas ou on ajouter une prescription dans un texte
						if($("#article_"+$("#PRESCRIPTIONTYPE_TEXTE").val()).html())
						{
							$(".prescriptiontypeTexte_"+$("#PRESCRIPTIONTYPE_TEXTE").val()).append(msg);
						}
					}
					else
					{
						//cas ou on ajoute une prescription directement dans un article
						if($(".prescriptiontypeArticle_"+$("#PRESCRIPTIONTYPE_ARTICLE").val()).html())
						{
							$(".prescriptiontypeArticle_"+$("#PRESCRIPTIONTYPE_ARTICLE").val()).append(msg);
						}
					}
					$('.closemodal').click();
					$("#loading").hide();
					return false;
				}
			});
		}
		return false;
	});
	
	$(".suppAssoc").live('click',function(){
		$(this).parent().parent().remove();
		return false;
	});
	
	$(".editPrescriptionType").live('click',function(){
		var tabId = $(this).parent().parent().parent().parent().parent().attr('id').split('_');
		var idPrescType = tabId[1];
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/formprescription",
			data: "&idPrescType="+idPrescType,
			beforeSend: function(){
				$(".modal-body").html("<img src='/images/load.gif' />");
			},
			success: function(msg){
				$(".modal-body").html(msg);
				$.ajax({
					type: "POST",
					url: "/gestion-prescriptions/emplacement",
					data: $("#formPrescription").serialize(),
					beforeSend: function(){
						$("#selectEmplacement").html("<img src='/images/load.gif' />");
					},
					success: function(msg){
						$("#selectEmplacement").html(msg);						
					}
				});
			}
		});
		return false;
	});


});

$(".classement").sortable({
	update: function(event, ui) {
		var formId = $(this).parent();
		var data = formId.serialize();
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/move",
			data: data,
			beforeSend: function(){
				$(this).disableSelection();
			},
			success: function(msg){
				$(this).enableSelection();
			}
		});
	}
});

</script>