<?php
if($this->do == 'new')
	echo "<li id='categorie_".$this->categorie['ID_PRESCRIPTION_CAT']."'>";
	
echo "	
	<span style='font-size:17px;font-weight:bold;'>
		<input type='hidden' name='categorie[]' value='".$this->categorie['ID_PRESCRIPTION_CAT']."' />
		".$this->categorie['LIBELLE_PRESCRIPTION_CAT']."
	</span>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<button class='showDetailCat btn' id='showtexte_".$this->categorie['ID_PRESCRIPTION_CAT']."' >Afficher les détails</button>
	<button class='hideDetailCat btn' id='hidetexte_".$this->categorie['ID_PRESCRIPTION_CAT']."' style='display:none;'>Masquer les détails</button>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<button class='editCategorie btn' id='".$this->categorie['ID_PRESCRIPTION_CAT']."' >Modifier</button>
	<br/>
	<div style='margin-left:30px;padding-left:10px;border-left:1px solid black;' id='texte_".$this->categorie['ID_PRESCRIPTION_CAT']."'></div>
	<div style='margin-left:30px;padding-left:10px;border-left:1px solid black;' id='prescriptionCat_".$this->categorie['ID_PRESCRIPTION_CAT']."'></div>
	<br/>
";
if($this->do == 'new')
	echo "</li>";
	
?>