<?php

	echo "<li id='prescriptiontype_".$this->idPrescriptionType."'  style='border-bottom:1px solid grey;'>";

	echo "
			<table class='row-fluid' >
	";

	$nbAssoc = count($this->textes);
	$cpt = true;
	for($j=0; $j < $nbAssoc; $j++)
	{
		$article = $this->articles[$j];
		$texte = $this->textes[$j];
		echo "
			<tr >
				<td class='span3' style='vertical-align:top;'>".$texte."</td>
				<td class='span3' style='vertical-align:top;'>".$article."</td>
		";
		if($cpt)
		{
			echo "<td rowspan='".$nbAssoc."' class='span5'>".nl2br($this->libelle)."</td>";
			echo "<td rowspan='".$nbAssoc."' class='span1' style='vertical-align:top;'><button class='editPrescriptionType btn' id='' >Editer</button></td>";
			$cpt = false;
		}
		echo "
			</tr>
		";
	}
	echo "
			</table>
	";

		echo "</li>";

?>

<script type="text/javascript">
$(document).ready(function(){
	
});
</script>