<?php

	echo "
		<li id='prescriptiontype_".$this->idPrescriptionType."'  style='border-bottom:1px solid grey;'>
			<table class='row-fluid' >
	";

	$nbAssoc = count($this->prescriptionType);
	$cpt = true;
	foreach($this->prescriptionType as $presc){
		echo "
			<tr >
				<td class='span3' style='vertical-align:top;'>".$presc['LIBELLE_TEXTE']."</td>
				<td class='span3' style='vertical-align:top;'>".$presc['LIBELLE_ARTICLE']."</td>
		";
		if($cpt)
		{
			echo "
				<td rowspan='".$nbAssoc."' class='span5'>
					<input type='hidden' name='prescType[]' value='".$presc['ID_PRESCRIPTIONTYPE']."' />
					".nl2br($presc['PRESCRIPTIONTYPE_LIBELLE'])."
				</td>";
			echo "<td rowspan='".$nbAssoc."' class='span1' style='vertical-align:top;'><a href='#myModal' role='button' class='editPrescriptionType btn' data-toggle='modal'>Editer</a></td>";
			$cpt = false;
		}
		echo "
			</tr>
		";
	}
	echo "
			</table>
		</li>
	";

?>