<?php
if($this->do == 'new')
	echo "<li id='texteid_".$this->texte['ID_PRESCRIPTIONTEXTE']."'>";
	
echo "	
	<span style='font-size:15px;'>
		<input type='hidden' name='texte[]' value='".$this->texte['ID_PRESCRIPTIONTEXTE']."' />
		".$this->texte['LIBELLE_PRESCRIPTIONTEXTE']."
	</span>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<button class='showDetailTexte btn' id='showarticle_".$this->texte['ID_PRESCRIPTIONTEXTE']."' >Afficher les détails</button>
	<button class='hideDetailTexte btn' id='hidearticle_".$this->texte['ID_PRESCRIPTIONTEXTE']."' style='display:none;'>Masquer les détails</button>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<button class='editTexte btn' id='".$this->texte['ID_PRESCRIPTIONTEXTE']."' >Modifier</button>
	<br/>
	<div style='margin-left:30px;padding-left:10px;border-left:1px solid black;' id='article_".$this->texte['ID_PRESCRIPTIONTEXTE']."'></div>
	<br/>
";
if($this->do == 'new')
	echo "</li>";
	
?>