<?php
if($this->do == 'new')
	echo "<li id='article_".$this->article['ID_PRESCRIPTIONARTICLE']."'>";
	
echo "	
	<span style='font-style:italic;'>
		<input type='hidden' name='article[]' value='".$this->article['ID_PRESCRIPTIONARTICLE']."' />
		".$this->article['LIBELLE_PRESCRIPTIONARTICLE']."
	</span>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<button class='showDetailArticle btn' id='showDetailArticle_".$this->article['ID_PRESCRIPTIONARTICLE']."' >Afficher les détails</button>
	<button class='hideDetailArticle btn' id='hideDetailArticle_".$this->article['ID_PRESCRIPTIONARTICLE']."' style='display:none;'>Masquer les détails</button>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<button class='editArticle btn' id='".$this->article['ID_PRESCRIPTIONARTICLE']."' >Modifier</button>
	<br/>
	<div style='margin-left:30px;padding-left:10px;border-left:1px solid black;' id='articleDetail_".$this->article['ID_PRESCRIPTIONARTICLE']."'></div>
	<br/>
";
if($this->do == 'new')
	echo "</li>";
	
?>

<script type="text/javascript">
$(document).ready(function(){
	
});
</script>