<?php
echo "
	<br/><br/>
	<ul class='prescriptiontypeArticle_".$this->idArticle." unstyled'>
";
$nbPrescType = count($this->prescriptionType);
for($i=0; $i < $nbPrescType; $i++)
{
	if(isset($this->prescriptionType[$i][0]['ID_PRESCRIPTIONTYPE']))
	{
		echo "
			<li id='prescriptiontype_".$this->prescriptionType[$i][0]['ID_PRESCRIPTIONTYPE']."'  style='border-bottom:1px solid grey;'>
				<table  class='row-fluid'>
		";

		$nbAssoc = count($this->prescriptionType[$i]);
		$cpt = true;
		for($j=0; $j < $nbAssoc; $j++)
		{
			$article = $this->prescriptionType[$i][$j]['LIBELLE_ARTICLE'];
			$texte = $this->prescriptionType[$i][$j]['LIBELLE_TEXTE'];
			echo "
				<tr>
					<td class='span3' style='vertical-align:top;'>".$texte."</td>
					<td class='span3' style='vertical-align:top;'>".$article."</td>
			";
			if($cpt)
			{
				echo "<td rowspan='".$nbAssoc."' class='span5'>".nl2br($this->prescriptionType[$i][0]['PRESCRIPTIONTYPE_LIBELLE'])."</td>";
				echo "<td rowspan='".$nbAssoc."' class='span1' style='vertical-align:top;'><a href='#myModal' role='button' class='editPrescriptionType btn' data-toggle='modal'>Editer</a></td>";
				$cpt = false;
			}
			echo "
				</tr>
			";
		}
		echo "
				</table>
			</li>
		";
	}
}	
echo "
	</ul>
	<br/>
	<a href='#myModal' role='button' class='prescription btn' id='addPrescriptionArticle_".$this->idArticle."' data-toggle='modal'>Ajouter une prescription</a>
";
?>