<?php
echo "
	<br/>
	<button class='prescription' class='addPrescriptionArticle_'>Ajouter une prescription</button>
	<br/><br/>
	<ul class='prescriptiontypeArticle_".$this->idArticle."'>
";
$nbPrescType = count($this->prescriptionType);
for($i=0; $i < $nbPrescType; $i++)
{
	echo "
		<li id='prescriptiontype_".$this->prescriptionType[$i][0]['ID_PRESCRIPTIONTYPE']."'>
			<table style='width:900px;'>
	";

	$nbAssoc = count($this->prescriptionType[$i]);
	$cpt = true;
	for($j=0; $j < $nbAssoc; $j++)
	{
		$article = $this->prescriptionType[$i][$j]['LIBELLE_ARTICLE'];
		$texte = $this->prescriptionType[$i][$j]['LIBELLE_TEXTE'];
		echo "
			<tr>
				<td style='width:15%;'>".$texte."</td>
				<td style='width:15%;'>".$article."</td>
		";
		if($cpt)
		{
			echo "<td rowspan='".$nbAssoc."' style='width:70%;'>".nl2br($this->prescriptionType[$i][0]['PRESCRIPTIONTYPE_LIBELLE'])."</td>";
			echo "<td rowspan='".$nbAssoc."'><button class='editPrescriptionType' id='' >Editer</button></td>";
			$cpt = false;
		}
		echo "
			</tr>
		";
	}
	echo "
			</table>
		</li>
	";
}	
echo "
	</ul>
";
?>

<script type="text/javascript">
$(document).ready(function(){
	$(".editPrescriptionType").button({
		icons: {
			primary: 'ui-icon-pencil'
		}
	});
	
	$(".prescription").button({
		icons: {
			primary: 'ui-icon-circle-plus'
		}
	});
});
</script>