<?php
echo "
	<br/><br/>
	<form id='FormPrescriptiontypeArticle_".$this->idArticle."' >
		<input type='hidden' name='type' value='prescriptionType' />
		<ul class='unstyled classement prescriptiontypeArticle_".$this->idArticle."' >
";
$nbPrescType = count($this->prescriptionType);
for($i=0; $i < $nbPrescType; $i++)
{
	if(isset($this->prescriptionType[$i][0]['ID_PRESCRIPTIONTYPE']))
	{
		echo "
			<li id='prescriptiontype_".$this->prescriptionType[$i][0]['ID_PRESCRIPTIONTYPE']."'  style='border-bottom:1px solid grey;'>
				<table  class='row-fluid'>
		";

		$nbAssoc = count($this->prescriptionType[$i]);
		$cpt = true;
		for($j=0; $j < $nbAssoc; $j++)
		{
			$article = $this->prescriptionType[$i][$j]['LIBELLE_ARTICLE'];
			$texte = $this->prescriptionType[$i][$j]['LIBELLE_TEXTE'];
			echo "
				<tr>
					<td class='span3' style='vertical-align:top;'>".$texte."</td>
					<td class='span3' style='vertical-align:top;'>".$article."</td>
			";
			if($cpt)
			{
				echo "
					<td rowspan='".$nbAssoc."' class='span5'>
						<input type='hidden' name='prescType[]' value='".$this->prescriptionType[$i][0]['ID_PRESCRIPTIONTYPE']."' />
						".nl2br($this->prescriptionType[$i][0]['PRESCRIPTIONTYPE_LIBELLE'])."
					</td>";
				echo "<td rowspan='".$nbAssoc."' class='span1' style='vertical-align:top;'><a href='#myModal' role='button' class='editPrescriptionType btn' data-toggle='modal'>Editer</a></td>";
				$cpt = false;
			}
			echo "
				</tr>
			";
		}
		echo "
				</table>
			</li>
		";
	}
}	
echo "
		</ul>
	</form>
	<br/>
	<a href='#myModal' role='button' class='prescription btn' id='addPrescriptionArticle_".$this->idArticle."' data-toggle='modal'>Ajouter une prescription</a>
";
?>

<script type="text/javascript">

	$(".classement").sortable({
		update: function(event, ui) {
			var formId = $(this).parent();
			var data = formId.serialize();
			$.ajax({
				type: "POST",
				url: "/gestion-prescriptions/move",
				data: data,
				beforeSend: function(){
					$(this).disableSelection();
				},
				success: function(msg){
					$(this).enableSelection();
				}
			});
		}
	});

</script>