<?php
	echo "<br/><br/>";	

	echo "<ul class='prescriptiontexte unstyled' id='prescriptiontexte_".$this->idCategorie."' >";
	
	foreach($this->listePrescriptionTexte as $val => $ue){
		echo "
			<li id='texteid_".$ue['ID_PRESCRIPTIONTEXTE']."'>
				<span style='font-size:15px;'>".$ue['LIBELLE_PRESCRIPTIONTEXTE']."</span>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<button class='showDetailTexte btn' id='showarticle_".$ue['ID_PRESCRIPTIONTEXTE']."' >Afficher les détails</button>
				<button class='hideDetailTexte btn' id='hidearticle_".$ue['ID_PRESCRIPTIONTEXTE']."' style='display:none;'>Masquer les détails</button>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<button class='editTexte btn' id='".$ue['ID_PRESCRIPTIONTEXTE']."' ><i class='icon-pencil'></i>&nbsp;Modifier</button>
				<br/>
				<div style='margin-left:30px;padding-left:10px;border-left:1px solid black;' id='article_".$ue['ID_PRESCRIPTIONTEXTE']."'></div>
				<br/>
			</li>
		";
	}
	
	echo "</ul>";
	echo "
		</ul>
		<ul id='prescriptiontypeCat_".$this->idCategorie."' class='unstyled'>
	";
	$nbPrescType = count($this->prescriptionType);
	for($i=0; $i < $nbPrescType; $i++)
	{
		if(isset($this->prescriptionType[$i][0]['ID_PRESCRIPTIONTYPE']))
		{
			echo "
				<li id='prescriptiontype_".$this->prescriptionType[$i][0]['ID_PRESCRIPTIONTYPE']."'  style='border-bottom:1px solid grey;'>
					<table  class='row-fluid' >
			";

			$nbAssoc = count($this->prescriptionType[$i]);
			$cpt = true;
			for($j=0; $j < $nbAssoc; $j++)
			{
				$article = $this->prescriptionType[$i][$j]['LIBELLE_ARTICLE'];
				$texte = $this->prescriptionType[$i][$j]['LIBELLE_TEXTE'];
				echo "
					<tr>
						<td class='span3' style='vertical-align:top;'>".$texte."</td>
						<td class='span3' style='vertical-align:top;'>".$article."</td>					
				";
				if($cpt)
				{
					echo "<td rowspan='".$nbAssoc."' class='span5'>".nl2br($this->prescriptionType[$i][0]['PRESCRIPTIONTYPE_LIBELLE'])."</td>";
					echo "<td rowspan='".$nbAssoc."' class='span1' style='vertical-align:top;'><a href='#myModal' role='button' class='editPrescriptionType btn' data-toggle='modal'>Editer</a></td>";
					$cpt = false;
				}
				echo "
					</tr>
				";
			}
			echo "
					</table>
				</li>
			";
		}
	}	
	echo "
		</ul>
	";
	echo "<br/>";	
	echo "
		<button class='addTexteCat btn' >Ajouter un type de disposition</button>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<a href='#myModal' role='button' class='prescription btn' id='addPrescriptionCat_".$this->idCategorie."' data-toggle='modal'>Ajouter une prescription à la catégorie</a>
	";
?>