<!-- Titre -->
<h2>
	<i class='sprite sprite-application_view_columns' ></i>
	Tableau des périodicités
</h2>

<form id='form_periodicite' >

	<h3>ERP</h3>
	<!-- Tableaux -->
	<?php foreach( array_chunk($this->array_types, 7) as $array_types ) : ?>
	<table class='table-custom' >
		<thead>
			<tr>
				<th rowspan="2"></th>
				<?php foreach( $array_types as $type) : ?>
					<th colspan='2' ><?php echo $type["ID_TYPE"] ?></th>
				<?php endforeach ?>
			</tr>
			<tr>
				<?php for($i = 0; $i < count($array_types); $i++) : ?>
					<th style='height: 16px; background: url(/css/images/avec_sans_local.gif) center -16px no-repeat' ></th>
					<th style='height: 16px; background: url(/css/images/avec_sans_local.gif) center 0 no-repeat' ></th>
				<?php endfor ?>
			</tr>
		</thead>
		<tbody>
			<?php foreach( $this->array_categories as $categorie) : ?>
			<tr>
				<td style='width: 150px;' ><?php echo $categorie["LIBELLE_CATEGORIE"] ?></td>
				
				<?php foreach( $array_types as $type) : ?>
				
					<?php $periodicite = $this->tableau[$categorie["ID_CATEGORIE"]][$type["ID_TYPE"]]; ?>
				
					<td style='text-align: center' >
						<?php // if( $type["ID_TYPE"] != "O" ) : ?>
							<input type='text' size='3' maxlength='3' value='<?php echo ( isset($periodicite[0]) ) ? $periodicite[0] : 0 ?>' name='<?php echo $categorie["ID_CATEGORIE"]."_".$type["ID_TYPE"]."_0" ?>' />
						<?php //else : ?>
							<!-- <input type='text' size='3' style='visibility: hidden' />-->
						<?php //endif ?>
					</td>
					
					<td style='text-align: center' >
						<?php // if( $categorie["ID_CATEGORIE"] == 5 || $type["ID_TYPE"] == "R" || $type["ID_TYPE"] == "J" || $type["ID_TYPE"] == "U" || $type["ID_TYPE"] == "O" ) : ?>
							<input type='text' size='3' maxlength='3' value='<?php echo ( isset($periodicite[1]) ) ? $periodicite[1] : 0 ?>' name='<?php echo $categorie["ID_CATEGORIE"]."_".$type["ID_TYPE"]."_1" ?>' />
						<?php //else : ?>
							<!-- <input type='text' size='3' style='visibility: hidden' />-->
						<?php //endif ?>
					</td>
					
				<?php endforeach ?>
			</tr>
			<?php endforeach ?>
		</tbody>
	</table>
	<?php endforeach ?>
	
	<h3>IGH</h3>
	<table class='table-custom' >
		<thead>
			<tr>
				<?php foreach($this->array_classes as $classe) : ?>
					<th ><?php echo $classe["LIBELLE_CLASSE"] ?></th>
				<?php endforeach ?>
			</tr>
		</thead>
		<tbody>
			<tr>
				
				<?php foreach( $this->array_classes as $classe) : ?>
				
					<?php $periodicite = $this->tableau[0][$classe["ID_CLASSE"]]; ?>
				
					<td style='text-align: center' >
						<input type='text' size='3' maxlength='3' value='<?php echo ( isset($periodicite[0]) ) ? $periodicite[0] : 0 ?>' name='<?php echo "0_".$classe["ID_CLASSE"]."_0" ?>' />
					</td>
					
				<?php endforeach ?>
			</tr>
		</tbody>
	</table>
	
	
	<div id="save_div" style="text-align: center">
		<button id='save' class="save">Sauvegarder le tableau des périodicités</button>
		<span id='notif' class='ui-state-highlight ui-helper-hidden' style='padding: .5em;'>Le tableau des périodicités a bien été sauvegardé.</span>
	</div>
	
</form>

<script type="text/javascript">

	// Boutons
	$( "#save" ).button({
		icons: { primary: "ui-icon-disk" }
	}).click( function() {
	
		$.ajax({
			url: "/periodicite/save",
			data: $("#form_periodicite").serialize(),
			type: "post",
			beforeSend: function() {
				$("#save").button("disable");
			},
			success: function() {
				$("#save").button("enable");
				$("#notif").show();
				setTimeout( function() { $("#notif").fadeOut(); }, 2500);
			}
		});
	
		return false;
	} );
	
	$("input[type=text]").change(function() {
		if($(this).val() == "0") {
			$(this).css("opacity", .5);
		}else {
			$(this).css("opacity", 1);
		}
	}).change();
	
</script>