<?php if(count($this->rowset_commissions) == 0) : ?>

<p style="text-align: center" ><strong>Aucun résultat.</strong></p>

<?php else : ?>

<div id="accordion">

	<?php foreach($this->rowset_commissions as $row_commission) : ?>
    
	<h3><a style='margin-left: 1em'><?php echo $row_commission["LIBELLE_COMMISSION"] ?></a></h3>
	<div>
    
        <div id="<?php echo $row_commission["ID_COMMISSION"] ?>_tabs">
            <ul>
                <li><a href="/commission/competences?id_commission=<?php echo $row_commission["ID_COMMISSION"] ?>"><span>Champ de compétence de la commission</span></a></li>
                <li><a href="/commission/membres?id_commission=<?php echo $row_commission["ID_COMMISSION"] ?>"><span>Membres de la commission</span></a></li>
                <li><a href="/commission/contacts?id_commission=<?php echo $row_commission["ID_COMMISSION"] ?>"><span>Contacts de la commission</span></a></li>
                <li><a href="/commission/courriers?id_commission=<?php echo $row_commission["ID_COMMISSION"] ?>"><span>Courriers types envoyés aux membres</span></a></li>
                <li><a href="/commission/documents?id_commission=<?php echo $row_commission["ID_COMMISSION"] ?>"><span>Documents types de la commission</span></a></li>
            </ul>
        </div>
        
        <script type="text/javascript">
            $("#<?php echo $row_commission["ID_COMMISSION"] ?>_tabs").tabs({heightStyle: "content", history: false, load: function(event, ui) { init_checkboxes(<?php echo $row_commission["ID_COMMISSION"] ?>); }});
        </script>
    
	</div>
	<?php endforeach ?>
	
</div>

<?php endif ?>

<script type="text/javascript">

	$("#accordion").accordion({
		autoHeight: true,
		navigation: false,
        heightStyle: "content"
	});

	// On met en place la structure pour les checkbox area
	function init_checkboxes(id) {
	
		$("#" + id + "_tabs .checkbox_area").each(function() {
			
			// On place le contenu dans checkbox_area_content
			$(this).html("<div class='checkbox_area_content'><a href='' class='close' onclick=\"return check_checkboxes($('td:hover'), false)\" >&times;</a>"+$(this).html()+"</div>")
			
			// On append le code HTML du delta
			$(this).append("<p class='checkbox_area_lambda ui-helper-hidden'>&lambda; (<a href='' onclick=\"return check_checkboxes($('td:hover'), false)\" >modifier ?</a>)</p>");
			
			// On check si on affiche le tout ou pas
			check_checkboxes($(this), true);
		});
	}
	
	function check_checkboxes(conteneur, change) {
		// Si toutes les cases sont cochées
		if( conteneur.find("input[type=checkbox]:checked:not(.ignore_check)").length == conteneur.find("input[type=checkbox]:not(.ignore_check)").length) {
			// Si on est en mode changement
			if(change == true) {
				// Si on veut tout cocher
				conteneur.find(".checkbox_area_content").hide();
				conteneur.find("input[type=checkbox]:not(.ignore_check)").attr("checked", "checked");
				conteneur.find(".checkbox_area_lambda").show();
			} else if(change == false) {
				// Si on veut modifier
				conteneur.find(".checkbox_area_content").show();
				conteneur.find("input[type=checkbox]:not(.ignore_check)").attr("checked", "");
				conteneur.find(".checkbox_area_lambda").hide();
			}
		}
		else if(!change) {
			// Si on veut tout cocher
			conteneur.find(".checkbox_area_content").hide();
			conteneur.find("input[type=checkbox]:not(.ignore_check)").attr("checked", "checked");
			conteneur.find(".checkbox_area_lambda").show();
		}
		return false;
	}

</script>