<!-- Titre -->
<span style="float: right">
	<button id='button-gdc' >Gestion des commissions</button>
</span>

<h2 class='grid_xx'>
	<i class='sprite sprite-application_view_columns' ></i>
	Gestion des commissions
</h2>

<!-- Liste des types de commissions -->
<ul id="gestionCommissionMenu" class='grid_16'>
	<?php foreach($this->rowset_typesDesCommissions as $row_typeDesCommissions) : ?>
	<li <?php if( $row_typeDesCommissions["ID_COMMISSIONTYPE"] == 1 ) echo "class='active'" ?> >
		<a href='/gestion-des-commissions/get-commissions?id_type_des_commissions=<?php echo $row_typeDesCommissions["ID_COMMISSIONTYPE"] ?>' class='display' ><?php echo $row_typeDesCommissions["LIBELLE_COMMISSIONTYPE"] ?></a>
	</li>
	<?php endforeach ?>
</ul>

<!-- Liste des commissions -->
<div id='content_commissions' class='grid_16'>
	<?php echo $this->action("get-commissions", "gestion-des-commissions", null, array("id_type_des_commissions" => 1)); ?>
</div>

<script type="text/javascript">

	// Ajout d'un type
	$("#button-gdc").button({
		icons: { primary: "ui-icon-pencil" }
	}).click(function() {
		dialog_gdc();
	});
	
	function dialog_gdc() {

		$('#dialog-gdc').dialog("destroy");
		$("#dialog-gdc").remove();
		
		var dialog_gdc = $("<div id='dialog-gdc'></div>").appendTo("body");
	
		dialog_gdc.dialog({
			title: "Gestions des commissions",
			width: 650,
			draggable: false,
			resizable: false,
			modal: true,
			create: function() {
				dialog_gdc.load( "/gestion-des-commissions/form" );
			},
			buttons: {
				"Sauvegarder" : function() {
					$.ajax({
						url: "/gestion-des-commissions/save",
						data: $("#form-gdc").serialize(),
						type: "POST",
						success: function () {
							dialog_gdc.dialog("destroy");
							$("#index-left ul li.active a").click();
						}
					});
				},
				Cancel: function() {
					dialog_gdc.dialog("destroy");
				}
			}
		});
	}

	// Affichage des commissions
	$("ul#gestionCommissionMenu a").click(function() {
		
		$("#content_commissions").load( $(this).attr("href") );
		$("ul#gestionCommissionMenu li").removeClass("active");
		$(this).parent().addClass("active");
		return false;
	});

</script>