<?php echo $this->partial('users/partials/menu_admin_user.phtml') ?>

<form enctype='multipart/form-data' method='post'>

    <?php if($this->add) : ?>
        <div class='pull-right' >
            <input type='submit' class="btn btn-success" value="Ajouter l'utilisateur">
        </div>
        <h4>Ajout d'un utilisateur</h4>
    <?php else : ?>
        <div class='pull-right' >
            <div class="btn-group">
                <a class='btn' href="<?php echo $this->url(array('action' => 'index')) ?>">Annuler la modification</a>
                <input type='submit' class="btn btn-success" value='Sauvegarder'>
            </div>
        </div>
        <h4>Modification de l'utilisateur <?php echo $this->user['infos']["NOM_UTILISATEURINFORMATIONS"] . ' ' . $this->user['infos']["PRENOM_UTILISATEURINFORMATIONS"] ?></h4>
    <?php endif ?>

    <dl class='dl-horizontal well'>
    	<dt>Photo</dt>
        <dd>
        	<p>
        		<?php $this->avatar($this->user["ID_UTILISATEUR"]) ?>
        		<input name='avatar' type='file' />
    		</p>
    	</dd>

        <dt>Login</dt>
        <dd>
        	<p>
        		<input placeholder='Login de connexion ...' name='USERNAME_UTILISATEUR' value='<?php if(isset($this->user["USERNAME_UTILISATEUR"])) echo $this->user["USERNAME_UTILISATEUR"] ?>' type='text' />
			</p>
    	</dd>

        <dt>Mot de passe</dt>
        <dd>
            <p>
                <?php if( $this->add ) : ?>
                    <input placeholder='Mot de passe' name='PASSWD_INPUT' type='password' />
                    <?php if($this->params["LDAP_ACTIF"]) : ?> Connexion via LDAP/CAS/NTLM ? <input type='checkbox' class='ldap' value='1' /><?php endif ?>
                <?php else : ?>
                    <input placeholder='Mot de passe' name='PASSWD_INPUT' type='password' disabled value='<?php echo $this->user["PASSWD_UTILISATEUR"] ?>' />
                    <a href='#' id='change_passwd' >Changer le mot de passe</a>
                    <?php if($this->params["LDAP_ACTIF"]) : ?> Connexion via LDAP/CAS/NTLM ? <input type='checkbox' class='ldap' value='1' <?php if($this->user["PASSWD_UTILISATEUR"] == null) echo "checked"?> /><?php endif ?>
                <?php endif ?>
            </p>
            <?php if (getenv('PREVARISC_ENFORCE_SECURITY') == 1): ?>
            <p id="password_instructions" style="<?php echo $this->add ? '' : 'display:none' ?>">
                Le mot de passe doit contenir au moins 8 caractères 
                dont 1 minuscule, 1 majuscule, 1 chiffre et 1 caractère spécial.
            </p>
            <?php endif ?>
            
        </dd>

        <dt>Groupe</dt>
        <dd>
        	<p>
	            <select name='ID_GROUPE'>
	                <?php foreach($this->groupes as $groupe) : ?>
	                <option value="<?php echo $groupe['ID_GROUPE'] ?>" <?php if( $groupe['ID_GROUPE'] == $this->user['ID_GROUPE'] ) echo "selected" ?>><?php echo $groupe['LIBELLE_GROUPE'] ?></option>
	                <?php endforeach ?>
	            </select>
            </p>
        </dd>

        <dt>Utilisateur actif ?</dt>
        <dd>
            <p>
                <input type='hidden' value='0' name='ACTIF_UTILISATEUR' />
                <input type='checkbox' name='ACTIF_UTILISATEUR' value='1' <?php if( !isset($this->user) || $this->user['ACTIF_UTILISATEUR'] ) echo "checked" ?> />
            </p>
        </dd>
        
        <dt>Dernière IP authentifiée</dt>
        <dd>
            <p>
                <input type='text'  class="input-medium" name='IP_UTILISATEUR' maxlength="45" value='<?php echo $this->user["IP_UTILISATEUR"] ?>' />
            </p>
        </dd>
        
        <dt>Connexions en échec</dt>
        <dd>
            <input type='number' min="0" class="input-mini" name='FAILED_LOGIN_ATTEMPTS_UTILISATEUR' value='<?php echo $this->user["FAILED_LOGIN_ATTEMPTS_UTILISATEUR"] ? : '0' ?>' />
            <?php if(getenv('PREVARISC_ENFORCE_SECURITY') == 1 && $this->user["FAILED_LOGIN_ATTEMPTS_UTILISATEUR"] >= 2): ?>
            <a href='#' id='unlock' >Débloquer</a> les connexions autres qu'avec l'IP ci-dessus.
            <?php endif ?>
        </dd>
    </dl>

    <h4>Informations de l'utilisateur</h4>
    <dl class='dl-horizontal'>
    	<dt>Prénom</dt>
		<dd>
			<input type='text' name='PRENOM_UTILISATEURINFORMATIONS' value='<?php echo $this->user['infos']["PRENOM_UTILISATEURINFORMATIONS"] ?>' />
		</dd>

		<dt>Nom</dt>
		<dd>
			<input type='text' name='NOM_UTILISATEURINFORMATIONS' value='<?php echo $this->user['infos']["NOM_UTILISATEURINFORMATIONS"] ?>' />
		</dd>

    	<dt>Fonction</dt>
		<dd>
			<select name='ID_FONCTION' >
				<?php foreach($this->fonctions as $fonction) : ?>
					<option value='<?php echo $fonction["ID_FONCTION"] ?>' <?php if(($fonction["ID_FONCTION"] == $this->user['infos']["ID_FONCTION"])) echo "selected" ?> >
						<?php echo $fonction["LIBELLE_FONCTION"] ?>
					</option>
				<?php endforeach ?>
			</select>
		</dd>

		<dt class='grade_user' >Grade</dt>
		<dd class='grade_user' >
			<input type='text' name='GRADE_UTILISATEURINFORMATIONS' value='<?php echo $this->user['infos']["GRADE_UTILISATEURINFORMATIONS"] ?>' />
		</dd>

		<dt>Téléphones</dt>
		<dd>
			<input type='text' name='TELFIXE_UTILISATEURINFORMATIONS' placeholder='Téléphone fixe ...' value='<?php echo $this->user['infos']["TELFIXE_UTILISATEURINFORMATIONS"] ?>' /><br/>
			<input type='text' name='TELPORTABLE_UTILISATEURINFORMATIONS' placeholder='Portable ...' value='<?php echo $this->user['infos']["TELPORTABLE_UTILISATEURINFORMATIONS"] ?>' />
			<input type='text' name='TELFAX_UTILISATEURINFORMATIONS' placeholder='Fax ...' value='<?php echo $this->user['infos']["TELFAX_UTILISATEURINFORMATIONS"] ?>' /><br/>
		</dd>

		<dt>Courriel</dt>
		<dd>
			<input type='text' name='MAIL_UTILISATEURINFORMATIONS' value='<?php echo $this->user['infos']["MAIL_UTILISATEURINFORMATIONS"] ?>' />
		</dd>

		<dt>Site Web</dt>
		<dd>
			<input type='text' name='WEB_UTILISATEURINFORMATIONS' value='<?php echo $this->user['infos']["WEB_UTILISATEURINFORMATIONS"] ?>' />
		</dd>

		<dt>Adresse</dt>
		<dd>
			<textarea name='OBS_UTILISATEURINFORMATIONS' style="width: 100%"><?php if(isset($this->user['infos']["OBS_UTILISATEURINFORMATIONS"])) echo $this->user['infos']["OBS_UTILISATEURINFORMATIONS"] ?></textarea>
		</dd>
	</dl>

    <h4>Domaines de compétences</h4>
    <dl class='dl-horizontal'>
        <dt>Commune</dt>
        <dd>
        	<p>
	            <select name='NUMINSEE_COMMUNE'>
	                <option value="null">Définir une commune ..</option>
	                <?php foreach($this->communes as $commune) : ?>
	                <option value="<?php echo $commune['NUMINSEE_COMMUNE'] ?>" <?php if( $commune['NUMINSEE_COMMUNE'] == $this->user['NUMINSEE_COMMUNE'] ) echo "selected" ?>><?php echo $commune['LIBELLE_COMMUNE'] ?></option>
	                <?php endforeach ?>
	            </select>
            </p>
        </dd>

        <dt>Commissions</dt>
        <dd>
        	<p>
	            <select name='commissions[]' class="chosen input-xxlarge" data-placeholder="Commissions" multiple="multiple">
	                <?php $previous_type = null ?>
                        <?php foreach($this->commissions as $commission) : ?>
                            <?php if (!$previous_type): ?>
                                <optgroup label="<?php echo $commission['LIBELLE_COMMISSIONTYPE'] ?>">
                            <?php elseif ($previous_type != $commission['ID_COMMISSIONTYPE']): ?>
                                </optgroup>
                                <optgroup label="<?php echo $commission['LIBELLE_COMMISSIONTYPE'] ?>">
                            <?php endif ?>
                            <option value="<?php echo $commission['ID_COMMISSION'] ?>" <?php if( $this->user['commissions'] != null && in_array($commission, $this->user['commissions']) ) echo "selected" ?>>
                                <?php echo $commission['LIBELLE_COMMISSION'] . " (".$commission['LIBELLE_COMMISSIONTYPE'].")" ?>
                            </option>
                            <?php $previous_type = $commission['ID_COMMISSIONTYPE'] ?>
	                <?php endforeach ?>
                        <?php if ($previous_type): ?>
                            </optgroup>
                        <?php endif ?>
	            </select>
            </p>
        </dd>

        <dt>Groupements</dt>
        <dd>
        	<p>
	            <select name='groupements[]' class="chosen input-xxlarge" data-placeholder="Groupements" multiple="multiple">
                        <?php $previous_type = null ?>
	                <?php foreach($this->groupements as $groupement) : ?>
                            <?php $selected = false; ?>
                            <?php if ($this->user['groupements'] != null): ?>
                                <?php foreach($this->user['groupements'] as $user_groupement): ?>
                                    <?php if ($groupement['ID_GROUPEMENT'] == $user_groupement['ID_GROUPEMENT']): ?>
                                        <?php $selected = true; ?>
                                        <?php break; ?>
                                    <?php endif ?>
                                <?php endforeach ?>
                            <?php endif ?>
                            <?php if (!$previous_type): ?>
                                <optgroup label="<?php echo $groupement['LIBELLE_GROUPEMENTTYPE'] ?>">
                            <?php elseif ($previous_type != $groupement['ID_GROUPEMENTTYPE']): ?>
                                </optgroup>
                                <optgroup label="<?php echo $groupement['LIBELLE_GROUPEMENTTYPE'] ?>">
                            <?php endif ?>
                            <option value="<?php echo $groupement['ID_GROUPEMENT'] ?>" <?php echo $selected ? "selected" : '' ?>>
                                <?php echo $groupement['LIBELLE_GROUPEMENT'] . " (" . $groupement['LIBELLE_GROUPEMENTTYPE'] . ") " ?>
                            </option>
                            <?php $previous_type = $groupement['ID_GROUPEMENTTYPE'] ?>
	                <?php endforeach ?>
                        <?php if ($previous_type): ?>
                            </optgroup>
                        <?php endif ?>
	            </select>
            </p>
        </dd>
    </dl>

</form>


<script>
    $(document).ready(function() {


    	// Gestion du changement du mot de passe et de la case à cocher LDAP
    	$('#change_passwd').click(function(e) {
            e.preventDefault();
            $('input[name="PASSWD_INPUT"]').attr('disabled', false).val('').focus();
            $('input.ldap').attr('checked', false);
            $(this).hide();
            $('#password_instructions').show();
    	});

    	$('input.ldap').change(function(e) {
            if( $(this).attr('checked') ) {
                $('input[name="PASSWD_INPUT"]').attr('disabled', false).val('').hide();
                $('#change_passwd').hide();
                $('#password_instructions').hide();
            }
            else {
                $('input[name="PASSWD_INPUT"]').show();
                $('#password_instructions').show();
                $('#change_passwd').click();
            }
    	});

        $("select[name='ID_FONCTION']").change(function() {
            if($(this).find('option:selected').val() == "13") {
                $('.grade_user').show();
            }
            else {
                $('.grade_user').hide();
                $('.grade_user').find('input').val(null);
            }
        }).change();

        // Gestion des select et multiselect
        $(".chosen").chosen({
            search_contains : true
        });
        
        $('#unlock').click(function(e) {
            e.preventDefault();
            $('input[name="FAILED_LOGIN_ATTEMPTS_UTILISATEUR"]').val(0);
    	});

    });
</script>
