<!-- Titre -->
<h2 class='page-header'>Administration système</h2>

<?php echo $this->partial('menu_admin.phtml') ?>

<?php echo $this->partial('menu_admin_user.phtml') ?>

<div class='row-fluid'>

    <div class="tabbable tabs-left span2">
        <ul class='nav nav-tabs' style='width: 100%'>
            <li <?php if(!isset($_GET['gid'])) echo "class='active'" ?>><a href='/users/list' >Tous les utilisateurs</a></li>
            <?php foreach($this->groupes as $groupe) : ?>
            <li <?php if(isset($_GET['gid']) && $_GET['gid'] == $groupe['ID_GROUPE']) echo "class='active'" ?> >
                <a href='/users/list?gid=<?php echo $groupe["ID_GROUPE"] ?>' ><?php echo $groupe["LIBELLE_GROUPE"] ?></a>
            </li>
            <?php endforeach ?>
        </ul>
    </div>

    <div id='content_group' class='span10'>
    
        <?php if(array_key_exists('gid', $_GET)) : ?>
        <a href='/users/add-group?gid=<?php echo $_GET['gid'] ?>' class='btn pull-right' >Modifier le groupe</a>
        <?php endif ?>
        
        <!-- Liste des utilisateurs -->
        <?php if($this->users != null) : ?>
        <table class='table table-condensed table-striped'>

            <thead>
                <tr>
                    <th>Identifiant</th>
                    <th>Nom et prénom</th>
                    <th>Fonction</th>
                    <th style='width: 150px' >Etat</th>
                    <th style='width: 150px' >Actions</th>
                </tr>
            </thead>
            
            <tbody>
                <?php foreach( $this->users as $user ) : ?>
                <tr <?php if(!$user["ACTIF_UTILISATEUR"]) echo "style='color:silver'" ?> >
                    <td style='font-style: italic' ><?php echo $user["USERNAME_UTILISATEUR"] ?></td>
                    <td><a href='/user/profile?uid=<?php echo $user["ID_UTILISATEUR"] ?>' ><?php echo $user["NOM_UTILISATEURINFORMATIONS"] . " " . $user["PRENOM_UTILISATEURINFORMATIONS"] ?></a></td>
                    <td><?php echo $user["LIBELLE_FONCTION"] ?></td>
                    <td>
                        <?php echo ( time() - strtotime($user["LASTACTION_UTILISATEUR"]) < ini_get('session.gc_maxlifetime') ) ? "<span class='label label-success'>En ligne</span>" : "<span class='label'>Hors ligne</span>" ?>
                    </td>
                    <td>
                        <a href='/users/edit/uid/<?php echo $user["ID_UTILISATEUR"] ?>' class="edit">Modifier</a> ou 
                        <a class='act_deact' href='/users/actived?uid=<?php echo $user["ID_UTILISATEUR"] ?>' ><?php echo ($user["ACTIF_UTILISATEUR"]) ? "Désactiver" : "Activer" ?></a>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
            
        </table>

        <?php else : ?>
        <p class='lead' ><strong>Aucun résultat.</strong></p>
        <?php endif ?>
    </div>

    <div id='dialog-add-groupe'></div>
    
</div>


<script type="text/javascript">

	
	function dialog_groupe( gid ) {

		$('#dialog-add-groupe').dialog("destroy");
	
		$("#dialog-add-groupe").dialog({
			title: gid ? "Modification du groupe" : "Ajout d'un groupe",
			height: 300,
			width: 650,
			draggable: false,
			resizable: false,
			create: function() {
				$('#dialog-add-groupe').load( "/users/add-group" + ( gid ? "?gid=" + gid : "" ) );
				$("#dialog-add-groupe input").val("");
			},
			buttons: {
				"Sauvegarder" : function() {
					$.ajax({
						url: "/users/save-group?format=json",
						data: $("#formulaire_groupe").serialize(),
						type: "POST",
						success: function () {
							window.location.reload() ;
						}
					});
				},
				Cancel: function() {
					$('#dialog-add-groupe').dialog("destroy");
				}
			}
		});
	}

</script>