<?php echo $this->partial('users/partials/menu_admin_user.phtml') ?>

<form method='post' action='/users/matrice-des-droits'>

    <?php foreach($this->rowset_groupes as $groupe) : ?>

    <h4><?php echo $groupe->LIBELLE_GROUPE ?></h4>

    <table class="table table-condensed" >
        <thead>
            <tr>
                <th>Ressources</th>
                <th>Privilèges</th>
            </tr>
        </thead>
        
        <tbody>

            <?php foreach($this->rowset_resources as $resource) : ?>
            <tr>
                <td><?php echo $resource->text ?> <small>(<?php echo $resource->name ?>)</small></td>
                <td>
                <?php foreach($resource->findModel_DbTable_Privilege()->toArray() as $privilege) : ?>
                <?php echo $this->partial('users/partials/partial-droit.phtml', array('text' => $privilege['text'], 'name' => $privilege['name'], 'name_input' => 'groupe[' . $groupe->ID_GROUPE . '][' . $privilege['id_privilege'] . ']', 'value' => (int) in_array(array('ID_GROUPE' => (string) $groupe->ID_GROUPE, 'id_privilege' => (string) $privilege['id_privilege']), $this->rowset_groupes_privilege))) ?>
                <?php endforeach ?>
                </td>
            <tr>
            <?php endforeach ?>
            
        </tbody>
    </table>

    <?php endforeach ?>
    
    <input type='submit' value='Sauvegarder' class='btn btn-success' />
    
</form>