<!-- Sous menu -->
<ul class="nav nav-tabs">
    <li <?php if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'admin' && Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'index') echo "class='active'" ?>>
        <a href="/admin">Général</a>
    </li>
    <li <?php if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'users' || Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'matrice-des-droits') echo "class='active'" ?>>
        <a href="/users/list">Gestion des utilisateurs</a>
    </li>
    <li <?php if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'couches-cartographiques') echo "class='active'" ?>>
        <a href="/couches-cartographiques/list">Gestion des couches cartographiques</a>
    </li>
</ul>