<!-- Titre -->
<h2 class='page-header'>Administration système</h2>

<?php echo $this->partial('menu_admin.phtml') ?>

<?php echo $this->partial('menu_admin_user.phtml') ?>

<form method='post' action='/matrice-des-droits/save'>

    <?php foreach($this->rowset_groupes as $groupe) : ?>

    <h3><?php echo $groupe->LIBELLE_GROUPE ?></h3>

    <table class="table table-condensed" >
        <thead>
            <tr>
                <th>Ressources</th>
                <th>Privilèges</th>
            </tr>
        </thead>
        
        <tbody>

            <?php foreach($this->rowset_resources as $resource) : ?>
            <tr>
                <td><?php echo $resource->name ?></td>
                <td>
                <?php foreach($resource->findModel_DbTable_Privilege()->toArray() as $privilege) : ?>
                <?php echo $this->partial('matrice-des-droits/partial_droit.phtml', array('text' => $privilege['name'], 'name' => 'groupe[' . $groupe->ID_GROUPE . '][' . $privilege['id_privilege'] . ']', 'value' => (int) in_array(array('ID_GROUPE' => (string) $groupe->ID_GROUPE, 'id_privilege' => (string) $privilege['id_privilege']), $this->rowset_groupes_privilege))) ?>
                <?php endforeach ?>
                </td>
            <tr>
            <?php endforeach ?>
            
        </tbody>
    </table>

    <?php endforeach ?>
    
    <input type='submit' value='Sauvegarder' class='btn btn-success' />
    
</form>