<p>
	<strong><?php echo $this->resume ?></strong> ; 
	Nombre total d'établissements concernés : <?php echo count($this->results) ?> ; 
	Requête effectuée le : <?php echo date("d/m/Y", time()) ?>
</p>
<table class="table" >
	<thead>
		<tr>
			<?php foreach($this->columns as $column => $db) : ?>
			<th><?php echo $column ?></th>
			<?php endforeach ?>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->results as $row) : ?>
		<tr>
			<?php foreach($this->columns as $column => $db) : ?>
			<td>
				<?php
				if(is_array($db)) {
					while (list($key, $val) = each($db)) {
						
						echo $row[$val] . " ";
					}
				}
				else if(preg_match('/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/', $row[$db])) {
					$date = new Zend_Date($row[$db], Zend_Date::DATES);
					echo $date->get( Zend_Date::WEEKDAY." ".Zend_Date::DAY_SHORT." ".Zend_Date::MONTH_NAME_SHORT." ".Zend_Date::YEAR );
				}
				else echo $row[$db];
				?>
			</td>
			<?php endforeach ?>
		</tr>
		<?php endforeach ?>
	</tbody>
</table>