SET NAMES 'utf8';
use `PRV_prevarisc_v2`;

ALTER TABLE etablissement ADD COLUMN `DESCTECH_RISQUES_NATURELS_ETABLISSEMENT` TEXT NULL DEFAULT NULL;
ALTER TABLE etablissement ADD COLUMN `DESCTECH_RISQUES_TECHNOLOGIQUES_ETABLISSEMENT` TEXT NULL DEFAULT NULL;
