ALTER TABLE`etablissementinformations` ADD COLUMN `EFFECTIFCARAVANE__ETABLISSEMENTINFORMATIONS` int(11) NULL DEFAULT NULL;
ALTER TABLE`etablissementinformations` ADD COLUMN `EFFECTIFHABITATION_ETABLISSEMENTINFORMATIONS` int(11) NULL DEFAULT NULL;
ALTER TABLE`etablissementinformations` ADD COLUMN `EFFECTIFEMPLACEMENTNU_ETABLISSEMENTINFORMATIONS` int(11) NULL DEFAULT NULL;
ALTER TABLE`etablissementinformations` ADD COLUMN `EFFECTIFTOTALCAMPING_ETABLISSEMENTINFORMATIONS` int(11) NULL DEFAULT NULL;
