<script type='text/javascript'>
	$("[name=validation]").click(function(){
		var data = $("#FormAddEvent").serialize();
		var dateEvent = $("#idJour").val();
		var tabEscape = dateEvent.split('-');		
		$.ajax({
			data: "do=validEventForm&dateEvent="+dateEvent+"&"+data,
			type:"POST",
			async: false,	
			beforeSend: function(){

			},
			success: function(affichageResultat){
				if($("#FormAddEvent").valid()){
					$("#divFormEvent").slideUp();
					$("#agendaMois").majAgendaMois("#"+tabEscape[2]);
				}
			},
			error: function(){
				return false;
			}
		});
		return false;
	});	
	
	
	(function($) {
		$.fn.majAgendaMois = function(test) {
			alert(test);
		};
	})(jQuery);
	
	
	$("[name=annulation]").click(function(){
		$("#divFormEvent").hide();
		$("#ajoutEvenement").fadeIn();
		$("#FormAddEvent")[0].reset();
		return false;
	});	

	$("#FormAddEvent").validate({
		rules: {
			commEvent: {
				required: true
			}
		}
	});
</script>
<?php
$baseURL = "/images/template/icons";
echo "
	<div id='liste_informations'>
		<h4>Ajout d'un événement</h4>
		<form name='FormAddEvent' id='FormAddEvent' method='POST'>
			<ul>
				<li>
					<span>Indiquez le type d'action correspondant à cet évenement</span>
					<span class='valeur'>
						<select id='typeEvenement' name='typeEvenement'>
";
foreach ($this->listeTypeEvent as $value){
		echo "<option value='".$value["ID_TYPE_EVENEMENT"]."' >".$value["LIBELLE_EVENEMENT"]."</option>";
}
echo"
						</select>
					</span>
				</li>
				<li>
					<span>Saisissez un commentaire</span>
					<span class='valeur'><textarea name='commEvent' id='commEvent' ></textarea></span>
				</li>
			</ul>
";
echo '<input type="button" name="validation" id="validationEvent" value="Créer l\'évenement"/>';

echo "
			<input type='button' name='annulation' id='annulationEvent' value='Annuler' />
			<!--
				<a href='' name='validation' id='valid_infoGenerales'>
					<img src='".$baseURL."/valid_14x14.png' title='Valider' alt='Valider' />
				</a>
				<a href='' name='annulation' id='annule_infoGenerales'>
					<img src='".$baseURL."/cancel_14x14.png' title='Annuler' alt='Annuler' />
				</a>
			-->
		</form>
	</div>
";