<h3 float='left' >Descriptif de l'établissement</h3>

<!-- Boutons -->
<?php if(($this->DB_informations != null && $this->droits->ID_GENRE[$this->DB_informations["ID_GENRE"]]["DROITECRITURE_GROUPEGENRE"] == 1)) : ?>
<div float='right' >
	
	<div class="read">
		<button id='modifier_button'>Modifier</button>
	</div>
	
	<div class="edit">
		<button id='cancel_button'>Annuler</button>
		<button id='save_button' class="save" >Sauvegarder</button>
	</div>
	
</div>
<?php endif ?>

<br class='clear' />

<h4>Descriptif général</h4>
<div class="read">
	<p><?php echo empty($this->DB_etablissement->DESCRIPTIF_ETABLISSEMENT) ? "Aucun descriptif disponible pour cet établissement." : nl2br($this->DB_etablissement->DESCRIPTIF_ETABLISSEMENT) ?></p>
</div>

<?php if(($this->DB_informations != null && $this->droits->ID_GENRE[$this->DB_informations["ID_GENRE"]]["DROITECRITURE_GROUPEGENRE"] == 1)) : ?>

<form class="edit" id="descriptif" action="" method="POST" >
	<textarea name='DESCRIPTIF_ETABLISSEMENT' id='descriptif_general' cols='' rows='' style='width: 100%; height: 500px;' ><?php echo $this->DB_etablissement->DESCRIPTIF_ETABLISSEMENT ?></textarea>
</form>

<script type="text/javascript">

	$("#descriptif_general").elastic();
	
	$("#modifier_button").button().click(function() {
		$(".read").hide();
		$(".edit").show();
	});
	
	$("#cancel_button").button().click(function() {
		window.location.reload();
	});
	
	$("#save_button").button().click(function() {
		$("#descriptif").submit();
	});
	
	$(".edit").hide();
	
</script>

<?php endif ?>