<script type="text/javascript">
	$(document).ready(function(){
		$("#generate").button({
			icons: {
				primary: 'ui-icon-circle-check'
			},
			text: true,
			//disabled: true
		});
	});
</script>	

<div id='listeEtabGenRapp'>
    <h3>Selectionnez les établissements pour lesquels vous souhaitez générer les rapports</h3>
    <form name='etabRapport' id='etabRapport'>
        Selectionnez le rapport que vous souhaitez générer : &nbsp;
        <select name='fichierSelect' id='fichierSelect'>
            <?php foreach ($this->files as $file_path => $filename): ?>
                <option value="<?php echo htmlentities($file_path, ENT_QUOTES) ?>"><?php echo $filename ?></option>
           <?php endforeach; ?>
	</select>
        <br/><br/>
	
	<?php if(count($this->listeEtablissement) == 0): ?>
            Aucun établissement rattaché à ce dossier.
        <?php elseif(count($this->listeEtablissement) == 1): ?>
            Génération du rapport pour l'établissement suivant :
	<?php else: ?>
            Selectionnez les établissements pour lesquels vous souhaitez générer les rapports :
	<?php endif ?>
            
        <br/><br/>
        <div class='checkbox_generate' >
            <?php foreach($this->listeEtablissement as $etab): ?>
                <input type='checkbox' class='etabCheck' name='idEtab[]' checked value="<?php echo $etab['ID_ETABLISSEMENT'] ?>">
                [<?php echo $etab['LIBELLE_GENRE'] ?>] <?php echo $etab['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?> &nbsp; 
                <br/>
            <?php endforeach ?>
        </div>
    </form>
    <br/><br/>
    <button id='generate'>Generation</button>
</div>