<script type="text/javascript">
	$(document).ready(function(){
		$("#generate").button({
			icons: {
				primary: 'ui-icon-circle-check'
			},
			text: true,
			//disabled: true
		});
	});
</script>	
<?php
	echo "
		<div id='listeEtabGenRapp' >
		<h3>Selectionnez les établissements pour lesquels vous souhaitez générer les rapports</h3>
		<form name='etabRapport' id='etabRapport'>
	";
	echo "Selectionnez le rapport que vous souhaitez générer : &nbsp;";	
	$dirname = "./data/uploads/documents/";
	$dir = opendir($dirname); 

	echo "<select name='fichierSelect' id='fichierSelect' >";
	while($file = readdir($dir)) {
		if($file != '.' && $file != '..' && !is_dir($dirname.$file))
		{
			//echo '<a href="'.$dirname.$file.'">'.$file.'</a>';
			echo "<option value='/data/uploads/documents/".$file."'>".$file."</option>";
		}
	}
	echo "</select><br/><br/>";
	closedir($dir);
	
	
	if(count($this->listeEtablissement) <= 1){
		echo "Selectionnez l'établissement pour lequel vous souhaitez générer le dossier";
	}else{
		echo "Selectionnez les établissements pour lesquels vous souhaitez générer les dossiers";
	}
	echo "	
		<br/><br/>
		<div class='checkbox_generate' >
	";
	foreach($this->listeEtablissement as $etab){
		echo "
			
				<input type='checkbox' class='etabCheck' name='idEtab[]' value='".$etab['ID_ETABLISSEMENT']."'>
				".$etab['LIBELLE_ETABLISSEMENTINFORMATIONS']." &nbsp; (".$etab['LIBELLE_GENRE'].")<br/>
				<!--
					<input type='hidden' name='idEtablissementDossier' value='".$etab['ID_ETABLISSEMENTDOSSIER']."' />
				-->
		";
	}
	echo "
		</div>
		</form>
		<br/><br/>
		<button id='generate' >Generation</button>
		</div>
	";