<?php echo $this->render('dossier/partials/header.phtml') ?>

<script type="text/javascript">

$.fn.hideModif = function(idPasCacher) {
	var idModif = "modif_"+idPasCacher;
	$(".modif").each(function(){
		if($(this).attr('id') != idModif){
			$("#"+$(this).attr('id')).hide();
		}
	});
	$("#docAjout").hide();
}

$.fn.showModif = function(idPasCacher) {
	var idModif = "modif_"+idPasCacher;
	$(".modif").each(function(){
		if($(this).attr('id') != idModif){
			$("#"+$(this).attr('id')).show();
		}
	});
	$("#docAjout").show();
}

$.fn.blockCheck = function(idPasCacher) {
	$(".divDocConsulte input:checkbox").each(function(){
		if($(this).attr('id') != 'check_'+idPasCacher && $(this).attr('checked') == false){
			$(this).attr('disabled','disabled');
		}
	});
}

$.fn.activeCheck = function(idPasCacher) {
	$(".divDocConsulte input:checkbox").each(function(){
		if($(this).attr('id') != 'check_'+idPasCacher && $(this).attr('checked') == false){
			$(this).removeAttr('disabled');
		}
	});
}

//permet l'enregistrement du document consulté ajouté
$.fn.ajoutDocDialog = function(idNatureDoc) {
	$.ajax({
		url: "/dossier/ajoutdocvalid",
		data: "idDossier="+$("#idDossier").val()+"&"+$("#formNewDoc").serialize(),
		type:"POST",
		beforeSend: function(){

		},
		success: function(affichageResultat){
			if($("#listeDocs_"+idNatureDoc).html() != '')
			{
				$("#listeDocs_"+idNatureDoc+" > li:last").after(affichageResultat);
			}else{
				$("#listeDocs_"+idNatureDoc).append(affichageResultat);
			}

			$("#libelleNewDoc").attr('value','');
			$("#dossier_Pdroite").activeCheck('qsd');

			return false;
		},
		error: function(){
			return false;
		}
	});
	return false;
}

$('.divDocConsulte input:checkbox').live('click',function(){
	var idcheckbox = $(this).attr("id");
	var nomTab = $(this).attr('id').split('_');

	if(nomTab.length == 3){
		var nom = nomTab[1]+"_"+nomTab[2];
	}else if(nomTab.length == 4){
		var nom = nomTab[1]+"_"+nomTab[2]+"_aj";
	}
	if($(this).attr('checked'))
	{
		$("#ref_"+nom).removeAttr('readonly');
		$("#date_"+nom).removeAttr('readonly');
		$("#modif_"+nom).hide();
		$("#div_input_"+nom).fadeIn();
		$("#tmp").attr('value','new');

		$("#libelleView_"+nom).hide();
		$("#libelle_"+nom).show();

		$("#dossier_Pdroite").hideModif(nom);
		$("#dossier_Pdroite").blockCheck(nom);
	}else{
		$("#div_input_"+nom).hide();
		$("#modif_"+nom).fadeIn();
		$("#ref_"+nom).attr('readonly','true').attr('value','');
		$("#date_"+nom).attr('readonly','true').attr('value','');

		$("#dossier_Pdroite").showModif(nom);
		$("#dossier_Pdroite").activeCheck(nom);
	}
});

$(".validDoc").live('click',function(){

	var ref = $(this).parent().parent().prev().prev().children("input");
	var date = $(this).parent().parent().prev().children("input");

	var data = $("#docConsulteForm").serialize();
	var idTab = $(this).parent().attr('id').split('_');

	var valRef = $(this).parent().parent().prev().prev().children("input[type=text]").val();
	var valDate = $(this).parent().parent().prev().children("input[type=text]").val();

	if(idTab.length == 3){
		var idValid = idTab[1]+"_"+idTab[2];
	}else if(idTab.length == 4){
		var idValid = idTab[1]+"_"+idTab[2]+"_aj";
	}

	$.ajax({
		url: "/dossier/validdoc",
		data: "do=validDoc&idValid="+idValid+"&"+data+"&id="+$("#idDossier").val(),
		type:"POST",
		beforeSend: function(){
			//VERIFICATION SUR L'integrité des données
		},
		success: function(affichageResultat){
			$("#dossier_Pdroite").showModif(idValid);
			$("#dossier_Pdroite").activeCheck(idValid);

			$("#modif_"+idValid).show();
			$("#valid_"+idValid).hide();
			$("#ref_"+idValid).attr('readonly','true');
			$("#date_"+idValid).attr('readonly','true').attr('disabled','disabled');
			$("#check_"+idValid).attr('disabled','disabled');

			$("#tmpRef").attr('value','');
			$("#tmpDate").attr('value','');

			var libelle = $("#libelle_"+idValid).val();
			$("#libelleView_"+idValid).html(libelle);
			$("#libelleView_"+idValid).show();
			$("#libelle_"+idValid).hide();

			return false;
		},
		error: function(){
			return false;
		}
	});
	return false;

});

$(document).ready(function(){
	var idDiv = $(".nature").attr('id');

	$($(".divDoc").get().reverse()).each(function(){
		var valeurDiv;
		var idLi;
		var idLiTab;
		if($(this).find("input:checkbox").prop('checked'))
		{
			idLi = "";
			idLiTab = "";

			valeurDiv = $(this).html();
			idLiTab = $(this).find("input:checkbox").attr('id').split("_");
			if(idLiTab.length == 3)
			{
				idLi = idLiTab[1]+"_"+idLiTab[2];
			}else if(idLiTab.length == 4){
				idLi = idLiTab[1]+"_"+idLiTab[2]+"_"+idLiTab[3];
			}else{
				return false;
			}

			$(this).next().remove();
			$(this).remove();
			$("#listeDocs_"+idDiv).prepend('<li id="'+idLi+'" class="divDoc row-fluid span12" style="display: block; margin: 0 15px 15px 15px;" name="divDoc">'+valeurDiv+'</li><br class="clear">');
		}
	});
});
</script>
<?php


echo "
	<div id='dossier_Pdroite' class='divDocConsulte'>
		<form name='docConsulteForm' id='docConsulteForm' method='post' action='' class='grid_15'>
		<input type='hidden' name='action' id='action' value='view' />
		<input type='hidden' name='tmp' id='tmp' value='' />
		<input type='hidden' name='tmpRef' id='tmpRef' value='' />
		<input type='hidden' name='tmpDate' id='tmpDate' value='' />
		<input type='hidden' name='idDossier' id='idDossier' value='".$this->idDossier."' />
";

foreach($this->listeNatures as $index => $nature){
	echo "
		<div id='".$nature["ID_NATURE"]."' class='nature row-fluid'>
			<h4 class='hideDocConsulte' >Liste des documents consultés concernant la nature '".$nature["LIBELLE_DOSSIERNATURE"]."'</h4>
			<p class='span5' style='padding-left:20px;'><strong>Libelle</strong></p>
			<p class='span2'><strong>Reférence</strong></p>
			<p class='span2'><strong>Date</strong></p>
			<br class='clear' />
			<ul id='listeDocs_".$nature["ID_NATURE"]."'>";


	//on boucle sur les documents ajoutés à afficher
	foreach($this->listeDocsAjout[$nature["ID_NATURE"]] as $documentAjout)
		echo $this->afficheDoc($this->infosDossier['VERROU_DOSSIER'],$nature["ID_NATURE"],$documentAjout['ID_DOCAJOUT'],$documentAjout['LIBELLE_DOCAJOUT'],$documentAjout['REF_DOCAJOUT'],$documentAjout['DATE_DOCAJOUT'],"_aj");


	//on boucle sur les documents de base à afficher
	if(count($this->listeDocs[$nature["ID_NATURE"]]) > 0)
	{
		$cpt = 0;
		foreach($this->listeDocs[$nature["ID_NATURE"]] as $document){
			$exist = false;
			foreach($this->dossierDocConsutle[$nature["ID_NATURE"]] as $docExistant){
				if($docExistant['ID_DOC'] == $document['ID_DOC']){
					$exist = true;
					$ref = $docExistant['REF_CONSULTE'];
					$date = $docExistant['DATE_CONSULTE'];
				}
			}

			if($exist){
				echo $this->afficheDoc($this->infosDossier['VERROU_DOSSIER'],$nature["ID_NATURE"],$document['ID_DOC'],$document['LIBELLE_DOC'],$ref,$date);
			}else{
				echo $this->afficheDoc($this->infosDossier['VERROU_DOSSIER'],$nature["ID_NATURE"],$document['ID_DOC'],$document['LIBELLE_DOC']);
			}

			$cpt++;
		}
	}


	if($this->infosDossier['VERROU_DOSSIER'] == 0){
		echo "</ul>
				<hr class='clear' />
				<p><a href='' id='docAjout_".$nature["ID_NATURE"]."' class='docAjout' >+ Ajouter un nouveau document</a></p>
			</div>
			<hr class='clear' />
		";
	}
}

echo "
		</form>
	</div>
	<div id='dialogDocConsulte' style='display:none;'>
		<form id='formNewDoc' name='formNewDoc'>
				<input type='hidden' name='natureDocAjout' id='natureDocAjout' value='' />
				Saisir le libellé du document :<br/>
				<textarea name='libelleNewDoc' id='libelleNewDoc' cols='100' rows='3' ></textarea>
		</form>
	</div>
	<div id='dialogConfirmSuppDoc' style='display:none;'>
		<form id='confirmSuppDoc' name='confirmSuppDoc'>
				<input type='hidden' name='docInfos' id='docInfos' value='' />
				<span id='affichageDocSupp'></span><br/>
				Référence :
				<span id='refDocSupp'></span><br/>
				Date :
				<span id='dateDocSupp'></span><br/>
		</form>
	</div>
";
?>

<script>
	$(document).ready(function(){

		$('.date').live('click', function() {
			$(this).datepicker({showOn:'focus', dateFormat: 'dd/mm/yy', firstDay: 1}).focus();
		});


		$(".cancelDoc").live('click',function(){
			var nomTab = $(this).parent().attr('id').split('_');
			if(nomTab.length == 3){
				var nom = nomTab[1]+"_"+nomTab[2];
			}else{
				var nom = nomTab[1]+"_"+nomTab[2]+"_aj";
			}
			switch($("#tmp").val()){
				case "new":
					$("#div_input_"+nom).fadeOut();
					$("#div_edit_"+nom).fadeIn();
					$("#check_"+nom).removeAttr('checked');
					$("#ref_"+nom).attr('readonly','true').attr('value','');
					$("#date_"+nom).attr('readonly','true').attr('value','');
				break;
				case "edit":
					$("#modif_"+nom).fadeIn();
					$("#valid_"+nom).hide();
					$("#date_"+nom).attr('readonly','true').attr('disabled','disabled').attr('value',$("#tmpDate").val());
					$("#ref_"+nom).attr('readonly','true').attr('value',$("#tmpRef").val());
				break;
				case "ajoutDoc":
					$("#formNewDoc").fadeOut(function(){
						$("#docAjout").fadeIn();
					});
					$("#libelleNewDoc").attr('value','');
				break;
			}
			$("#dossier_Pdroite").showModif(nom);
			$("#dossier_Pdroite").activeCheck(nom);
			$("#tmpRef").attr('value','');
			$("#tmpDate").attr('value','');
			$("#tmp").attr('value','');
			return false;
			//return false;
		});

		//déclaration de la boite de dialog pour l'ajout d'un document ne faisant pas parti de la liste de base
		$("#dialogDocConsulte").dialog({
			resizable: false,
			height:300,
			width:900,
			autoOpen: false,
			modal: true,
			title: 'Ajouter un document consulté',
			buttons: {
				'Enregistrer le document': function() {
					if($("#libelleNewDoc").val() == ''){
						$("#libelleNewDoc").focus();
						return false;
					}else{
						$(this).ajoutDocDialog($("#natureDocAjout").val());
						$(this).dialog('close');
					}
					$(this).dialog('close');
					//ici sauvegarder et afficher en ajax le doc qui a été ajouté
				},
				'Annuler': function() {
					$(this).dialog('close');
					//ici réinitialiser les champs à vide
				}
			},
			close: function(event, ui){

				$("body").css('overflow','auto');
				$("#libelleNewDoc").val('');
				$("#natureDocAjout").val('');
			}
		});

		//déclaration de la boite de dialog permettant la confirmation de la suppression d'un document ajouté de faisant parti de la liste de base
		$("#dialogConfirmSuppDoc").dialog({
			resizable: false,
			height:200,
			width:450,
			autoOpen: false,
			modal: true,
			title: 'Voulez vous vraiment supprimer ce document ?',
			buttons: {
				'Supprimer': function() {
					//ici on supprime dans la base de données le document lié puis on reinitialise la ligne
					$.ajax({
						url: "/dossier/suppdoc",
						data: "docInfos="+$("#docInfos").val()+"&idDossier="+$("#idDossier").val(),
						type:"POST",
						beforeSend: function(){
							//VERIFICATION SUR L'integrité des données
						},
						success: function(affichageResultat){
							//$("#"+$("#docInfos").val());
							var tabInfos = $("#docInfos").val().split('_');
							if(tabInfos.length == 2){
								//doc de base
								$("#ref_"+$("#docInfos").val()).val('');
								$("#date_"+$("#docInfos").val()).val('');

								$("#div_input_"+$("#docInfos").val()).hide();
								$("#check_"+$("#docInfos").val()).removeAttr('checked');
								$("#check_"+$("#docInfos").val()).removeAttr('disabled');
								$("#dossier_Pdroite").activeCheck('');
								$("#dossier_Pdroite").showModif('');



							}else{
								//doc ajouté
								$("#"+$("#docInfos").val()).remove();
								$("#dossier_Pdroite").showModif('.');
								$("#dossier_Pdroite").activeCheck('');
							}
							return false;
						},
						error: function(){
							return false;
						}
					});

					$(this).dialog('close');

				},
				'Annuler': function() {
					$(this).dialog('close');
					//ici réinitialiser les champs à vide
				}
			},
			close: function(event, ui){
				$("body").css('overflow','auto');
			}
		});

		$(".docAjout").live('click',function(){
			//permet d'afficher la boite de dialogue pour l'ajouter de documents consultés
			var tabNature= $(this).attr('id').split('_');
			var idNature = tabNature[1];
			$("#natureDocAjout").val(idNature);
			$("#dialogDocConsulte").dialog('open');
			return false;
		});

		//utilisé lorsque l'on ajoute un document à la liste des docs.
		$("#AjoutDocValid").click(function(){
			//alert('');
			if($("#libelleNewDoc").val() == ''){
				$("#libelleNewDoc").focus();
				return false;
			}

			$.ajax({
				url: "/dossier/fonction",
				data: "do=ajoutDocValid&libelledoc="+$("#libelleNewDoc").val()+"&idDossier="+$("#idDossier").val()+"&natureDocAjout"+$("#natureDocAjout").val(),
				type:"POST",
				beforeSend: function(){
					//VERIFICATION SUR L'integrité des données
				},
				success: function(affichageResultat){
					//alert($(".divDoc:last").attr('id'));
					$("#listeDocs").append(affichageResultat);
					//affichageResultat.insertAfter(".divDoc:last");
					$("#libelleNewDoc").attr('value','');
					$("#dossier_Pdroite").activeCheck('qsd');

					return false;
				},
				error: function(){
					return false;
				}
			});
			return false;
		});


		$(".editDoc").live('click',function(){
			var nomTab = $(this).parent().attr('id').split('_');
			//alert(nomTab.length);
			var nature = nomTab[1];
			if(nomTab.length == 3){
				var nom = nomTab[2];
			}else{
				var nom = nomTab[2]+"_aj";
			}
			//alert(nom);
			nom = nature+"_"+nom;
			$("#tmpRef").attr('value',$("#ref_"+nom).val());
			$("#tmpDate").attr('value',$("#date_"+nom).val());
			$("#tmp").attr('value','edit');

			$("#ref_"+nom).removeAttr('readonly');
			$("#date_"+nom).removeAttr('readonly').removeAttr('disabled');

			$("#modif_"+nom).hide();
			$("#valid_"+nom).fadeIn();

			$("#libelleView_"+nom).hide();
			$("#libelle_"+nom).show();

			$("#dossier_Pdroite").hideModif(nom);
			$("#dossier_Pdroite").blockCheck(nom);
			return false;
		});

		//gestion de la suppression des documents consultés
		$(".deleteDoc").live('click',function(){
			var idDoc = $(this).attr('name');
			$('#docInfos').val(idDoc);
			$("#dialogConfirmSuppDoc").dialog('open');
			$("#affichageDocSupp").html($("#"+idDoc).children('.libelle').html());
			$("#refDocSupp").html($("#ref_"+idDoc).val());
			$("#dateDocSupp").html($("#date_"+idDoc).val());
			return false;
		});

	});
</script>
