<script type="text/javascript">

	$(document).ready(function(){
				
		$('#listeEtab :input[name=idEtablissement]').each(function(){
			$("#"+$(this).val()).remove();
		});
		
		var dialogDossier = $('<div style="display:none"></div>').appendTo('body');
		
		dialogDossier.dialog({
			title: "Liste des dossiers",
			modal: true,
			width: 700,
			autoOpen: false,
			buttons: {
				"Lier ce dossier aux dossiers selectionnés": function() {
					$.ajax({
						url: "/dossier/fonction",
						data: "do=liaisonDossier&idDossier="+$("#idDossier").val()+"&"+$('#listeDossierCheckBox').serialize(),
						type:"POST",
						beforeSend: function(){
							$("#listeDossier").html("<img alt='chargement' src='/images/load.gif'>");
						},
						success: function(affichageResultat){
							loadDossierLies();
							return false;
						},
						error: function()	{
							return false;
						}
						
					});
					dialogDossier.dialog("close");
				},
				"annuler": function() {
					dialogDossier.dialog("close");
				}
			},
			close: function(event, ui){
				
			}
		});	

		$("#saisieEtab").toggleText("Saisissez le libelle de l'etablissement");
		$("#saisieDossier").toggleText("Saisissez le libelle du dossier");
		
		function loadInfosEtabs(){
			//recharge la page pour afficher les établissements correctement
			window.location='/dossier/liees/id/'+$('#idDossier').val();
		}
		
		$("#add").live('click',function(){
			//on récup le type (dossier ou etablissement)
			var typeAdd = $('[name=linkType]').val();
			if(typeAdd == 'etablissement'){
				$.ajax({
					url: "/dossier/addetablissement",
					data: "idDossier="+$("#idDossier").val()+"&idSelect="+$("#idSelect").val()+"&libelleSelect="+$("#saisieEtab").val(),
					type:"POST",
					beforeSend: function(){
						$(".btn").attr('disabled','disabled');
					},
					success: function(affichageResultat){
						$("#listeEtab").prepend(affichageResultat);
						$("#listeEtab").affichageBoutton();
						loadInfosEtabs();
						return false;
					},
					error: function()	{
						return false;
					}
				});
			}else if(typeAdd == 'dossier'){
			
			}
			$(".form").reinitialiseForm();
		});
		
		(function($) {
		//permet de réinitialiser tous les champs. Suivant le type c'est soit les association soit les type
			$.fn.affichageBoutton = function() {
				$(".deleteChoix").button({
					icons: {
						primary: 'ui-icon-trash'
					},
					text: false
				});
				
				$(".cancelDelete").button({
					icons: {
						primary: 'ui-icon-circle-close'
					},
					text: true
				});
				
				$(".confirmDelete").button({
					icons: {
						primary: 'ui-icon-circle-check'
					},
					text: true
				});
			};
			
			$.fn.reinitialiseForm = function(){
				//alert('');
				$("#saisieEtab").val('').blur();
				$("#saisieDossier").val('').blur();
				$("#saisieEtab").removeAttr('disabled');
				$("#saisieDossier").removeAttr('disabled');
				$("#idSelect").val('');
				$("#add").hide();
				$("#cancelAdd").hide();
			};
		
			
		})(jQuery);
		
		$("#cancelAdd").live('click',function(){
			$(".form").reinitialiseForm();
		});
		
		$(".deleteChoix").live('click',function(){
			//Lorsque l'on clique sur le boutton pour supprimer le lien avec un établissement
			$(this).parent().hide();
			$(this).parent().next().show();
		});

		$(".cancelDelete").live('click',function(){
			$(this).parent().hide();
			$(this).parent().prev().show();
			return false;
		});
		
		//Suppression lien dossier
		$(".deleteLienDossier").live('click',function(){
			//Lorsque l'on clique sur le boutton pour supprimer le lien avec le dossier
			$(this).parent().hide();
			$(this).parent().next().show();
			return false;
		});
				
		$(".cancelDeleteLienDossier").live('click',function(){
			$(this).parent().hide();
			$(this).parent().prev().show();
			return false;
		});
		
		
		$(".confirmDelete").live('click',function(){
			var idEtabDossier = $(this).parent().parent().children("[name=idEtablissementDossier]").val();
			var divDelete = $(this);
			$.ajax({
				url: "/dossier/deleteetablissement",
				data: "idEtabDossier="+idEtabDossier,
				type:"POST",
				beforeSend: function(){
					$(".btn").attr('disabled','disabled');
				},
				success: function(affichageResultat){
					window.location='/dossier/liees/id/'+$('#idDossier').val();
					return false;
				},
				error: function()	{
					return false;
				}
			});
		});
		
		$(".confirmDeleteLienDossier").click(function(){
			//Suppression dans la base du lien avec le dossier
			var idLienDossier = $(this).parent().parent().prev().children("[name=idDossierLie]").val();
			var loadSpan = $(this).parent();
			$.ajax({
				url: "/dossier/deleteliendossier",
				data: "idLienDossier="+idLienDossier,
				type:"POST",
				beforeSend: function(){
					$(".btn").attr('disabled','disabled');
					loadSpan.html("<img src='/images/load.gif' />");
				},
				success: function(affichageResultat){
					window.location='/dossier/liees/id/'+$('#idDossier').val();
					return false;
				},
				error: function()	{
					return false;
				}
			});
			
			return false;
		});
		
		$("#save-liens").live('click',function(){
			$.ajax({
				url: "/dossier/lienmultiple",
				data: $("#listeEnfantEtab").serialize()+"&idDossier="+$("#idDossier").val(),
				type:"POST",
				beforeSend: function(){
					$(".btn").attr('disabled','disabled');
				},
				success: function(affichageResultat){
					window.location='/dossier/liees/id/'+$('#idDossier').val();
					return false;
				},
				error: function()	{
					return false;
				}
			});
			return false;
		});
		
		$("[name=linkType]").live('click',function(){
			var choix = $(this).val();
			if($(this).val() == 'etablissement'){
				$("#saisieEtab").show();
				$("#saisieDossier").hide();
			}else{
				$("#saisieEtab").hide();
				$("#saisieDossier").show();
			}			
		});
		
		$("#saisieEtab").autocomplete("/api/1.0/search/etablissements?format=json", {
            extraParams: {
                label: function() {
                    return $("#saisieEtab").val();
                }
            },
            cacheLength: 0,
            minChars: 3,
            width: 500,
            parse: function(data) {
                return $.map(data["response"]["results"], function(row) {
                    return {
                        data: row,
                        value: row.LIBELLE_ETABLISSEMENTINFORMATIONS,
                        result: row.LIBELLE_ETABLISSEMENTINFORMATIONS
                    }
                });
            },
            formatItem: function(item) {
                var LIBELLE_COMMUNE = "non localisée";
                switch(item.ID_GENRE) {
                    case "1":
                        LIBELLE_COMMUNE = item.LIBELLE_COMMUNE_ADRESSE_SITE;
                        break;

                    case "3":
                        LIBELLE_COMMUNE = item.LIBELLE_COMMUNE_ADRESSE_CELLULE;
                        break;

                    default:
                        LIBELLE_COMMUNE = item.LIBELLE_COMMUNE_ADRESSE_DEFAULT;
                }
                return "[" + item.LIBELLE_GENRE + "] " + item.LIBELLE_ETABLISSEMENTINFORMATIONS + " (" + LIBELLE_COMMUNE + ")";
            }
        }).result(function(e, item) {
            $("#idSelect").val(item.ID_ETABLISSEMENT);
			$(this).attr('disabled','disabled');
			$(".add").show();
			$(".cancelAdd").show();
        });

	});
</script>

<?php


echo "
	<div>
		<h2>Liste des établissements liés au dossier</h2>
			<div id='listeEtab'>
			";
				$idEtabEnCour = null;
				foreach($this->listeEtablissement as $etab){
					if($etab['ID_ETABLISSEMENTDOSSIER'] != $idEtabEnCour){
						$idEtabEnCour = $etab['ID_ETABLISSEMENTDOSSIER'];
						echo "
							<div class='grid_14 alpha'>
								<input type='hidden' name='idEtablissementDossier' value='".$etab['ID_ETABLISSEMENTDOSSIER']."' />
								<a href='/etablissement/index/id/".$etab['ID_ETABLISSEMENT']."' >".$etab['LIBELLE_ETABLISSEMENTINFORMATIONS']." &nbsp; (".$etab['LIBELLE_GENRE'].") ".( (isset($etab['pereInfos']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS']))? " | ".$etab['pereInfos']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'] : "" )."</a>
								<input type='hidden' name='idEtablissement' value='".$etab['ID_ETABLISSEMENT']."' />
								&nbsp;&nbsp;
								<span>
						";
						if($this->infosDossier['VERROU_DOSSIER'] == 0){
							echo "
								<button class='deleteChoix btn' >Supprimer la liaison</button>
							";
						}
						echo "
								</span>
								<span style='display:none;' >
									<button class='confirmDelete btn' >Confirmer la suppression</button>
									<button class='cancelDelete btn' >Annuler</button>
								</span>
							</div>
						";
					}
				}
			if($this->infosDossier['VERROU_DOSSIER'] == 0){
				echo "
					<hr class='clear'/>
					<input type='radio' name='linkType' value='etablissement'>Etablissement&nbsp;&nbsp;
					<input type='text' id='saisieEtab' value='' style='width:500px;display:none;' />
					
					<button class='add btn' id='add' style='display:none;' >Lier l'établissement au dossier</button>
					<button class='cancelAdd btn' id='cancelAdd' style='display:none;' >Choisir un autre établissement</button>
					<input type='hidden' name='idSelect' id='idSelect' value=''  />
				</div>
				";
			}
			echo "<br/><br/>";
			echo "
				<form id='listeEnfantEtab' >
				<ul class='recherche_liste unstyled'>
			";
			if($this->infosDossier['VERROU_DOSSIER'] == 0){
				if(isset($this->etablissement))
				{
					echo $this->partialLoop('dossier/results/etablissement.phtml', $this->etablissement['etablissement_lies']);
					echo "
						</ul>
						<button class='btn' id='save-liens' >Sauvegarder les liaisons</button>
						</form>
						<br/><br/><br/><br/>
					";
				}			
			}
		echo "
		
			<h2>Liste des dossiers liés au dossier</h2>
			<div id='listeDossier'>
			</div>
			<div id='dossiersLies'>
		";

		foreach($this->listeDossierLies as $ref => $dossier){
			echo "
				<div class='row-fluid' style='margin-bottom:10px;'>
                    <div class='span10'>
                    	<a href='/dossier/index/id/".$dossier['dossierInfo'][0]['ID_DOSSIER']."'>
			";
			
			if(isset($dossier['etabInfo']) && count($dossier['etabInfo']) > 0 ){
				$nbEtabConcerne = count($dossier['etabInfo']);

				foreach($dossier['etabInfo'] as $etab){
					echo "[ ".$etab['LIBELLE_ETABLISSEMENTINFORMATIONS'];
					$nbEtabConcerne--;
					if($nbEtabConcerne > 0)
						echo ",";
				}
				echo " ]";
			}

			if(isset($dossier['dossierInfo']) && count($dossier['dossierInfo']) > 0){
				echo " (".$dossier['dossierInfo'][0]['LIBELLE_DOSSIERTYPE']." / ".$dossier['dossierInfo'][0]['LIBELLE_DOSSIERNATURE'].") ";
				echo $dossier['dossierInfo'][0]['OBJET_DOSSIER'];
			}

			echo "</a>";

			if($dossier['dossierInfo'][0]['DATECOMM_DOSSIER'] != null)
            {
                $date = substr($dossier['dossierInfo'][0]['DATECOMM_DOSSIER'], 0, 10);
                if($date != '0000-00-00'){
                    $date = new DateTime(substr($dossier['dossierInfo'][0]['DATECOMM_DOSSIER'],0,10));
                    $date = date_format($date, 'd/m/Y');
                }else{
                    $date = "00/00/0000";
                }
                $date_text = "ayant pour date de passage en commission le";
            }
            elseif($dossier['dossierInfo'][0]['DATEVISITE_DOSSIER'] != null)
            {
                $date = substr($dossier['dossierInfo'][0]['DATEVISITE_DOSSIER'], 0, 10);
                if($date != '0000-00-00'){
                    $date = new DateTime(substr($dossier['dossierInfo'][0]['DATEVISITE_DOSSIER'],0,10));
                    $date = date_format($date, 'd/m/Y');
                }else{
                    $date = "00/00/0000";
                }
                $date_text = "ayant pour date de visite le";
            }
            else
            {
                $date = substr($dossier['dossierInfo'][0]['DATEINSERT_DOSSIER'], 0, 10);
                if($date != '0000-00-00'){
                    $date = new DateTime(substr($dossier['dossierInfo'][0]['DATEINSERT_DOSSIER'],0,10));
                    $date = date_format($date, 'd/m/Y');
                }else{
                    $date = "00/00/0000";
                }
                $date_text = "créé le";
            }
            echo "<small class='muted'>" . $date_text . " " . $date . "</small>";

			if($this->infosDossier['VERROU_DOSSIER'] == 0){
				echo "
					<input type='hidden' value='".$dossier['ID_DOSSIERLIE']."' name='idDossierLie'>
				</div>
				<div class='span2'>
                    <span>
                        <button class='btn deleteLienDossier' ><i class='icon-trash'></i>&nbsp;Supprimer la liaison</button>
                    </span>
                    <span style='display:none;' >
                        <button class='btn confirmDeleteLienDossier btn-warning' >Confirmer la suppression</button>
                        <button class='btn cancelDeleteLienDossier' >Annuler</button>
                    </span>
				";
			}
			echo "
				</div>
				</div>
			";
		}
		echo "	
			</div>
			<br/>
		";
			if($this->infosDossier['VERROU_DOSSIER'] == 0){
				echo "
					<div class='grid_14 alpha form'>
						<a class='btn' href='/dossier/liees-doss/id/".$this->infosDossier['ID_DOSSIER']."' >Lier à un dossier</a>
					</div>
				";
			}
			echo "
			<hr class='clear'/>
		</div>
	</div>
";
?>

<script>
	$(document).ready(function(){
		$('.icone_enfants').remove();
	});
</script>