<?php

//Fonction permettant d'afficher les fichiers contenus dans un repertoire
function listing($repertoire,$id_dossier){

	$fichier = array();
	if (is_dir($repertoire)){
	
		$dir = opendir($repertoire);                              //ouvre le repertoire courant désigné par la variable
		while(false!==($file = readdir($dir))){                             //on lit tout et on récupere tout les fichiers dans $file
		
			if(!in_array($file, array('.','..'))){            //on eleve le parent et le courant '. et ..'
			
				$page = $file;                            //sort l'extension du fichier
				$page = explode('.', $page);
				$nb = count($page);
				$nom_fichier = $page[0];
				for ($i = 1; $i < $nb-1; $i++){
					$nom_fichier .= '.'.$page[$i];
				}
				if(isset($page[1])){
					$ext_fichier = $page[$nb-1];
					if(!is_file($file)) { $file = '/'.$file; }
				}
				else {
					if(!is_file($file)) { $file = '/'.$file; } //on rajoute un "/" devant les dossier pour qu'ils soient triés au début
					$ext_fichier = '';
				}

				if($ext_fichier != 'php' and $ext_fichier != 'html') { //utile pour exclure certains types de fichiers à ne pas lister
					array_push($fichier, $file);
				}
			}
		}
	}
	natcasesort($fichier); //la fonction natcasesort( ) est la fonction de tri standard sauf qu'elle ignore la casse

	echo "<ul>";
	foreach($fichier as $value) {
		//on retire le / qui précéde le nom des fichiers
		$nom = substr($value,1);
		if($value != '/Thumbs.db'){
			$type_fic = explode('.', $nom);
			switch($type_fic[1]){
				case "pdf":
					$classe= "pj_icon pdf";
				break;
				case "jpg":
					$classe= "pj_icon jpg";
				break;
				case "odt":
					$classe= "pj_icon doc";
				break;
				default:
				
				break;				
			}
			echo "
				<li>
					<span class='".$classe."'></span>
					<a href='/pj/dossier/".$id_dossier."/".$nom."' target='_blank' >".$nom."</a>
					<span class='pj_delete' title='supprimer'>
						<a href='' id='".$nom."' class='supprimerPJ'>&times;</a>
					</span>
				</li>
			";
		}
	}
	echo "</ul>";
}

//Si on détecte un upload
if( isset($_POST['upload']) ) // si formulaire soumis
{
    $content_dir = './pj/dossier/'.$this->id_dossier.'/'; // dossier où sera déplacé le fichier
	if (is_dir($content_dir) == true)
	{
		//echo "Le dossier existe déjà<br />";
	}
	else
	{
		mkdir ($content_dir, 0777);
	}
		
    $tmp_file = $_FILES['fichier']['tmp_name'];
    if( !is_uploaded_file($tmp_file) )
    {
        //exit("Le fichier est introuvable");
    }

    // on vérifie maintenant l'extension
    $type_file = $_FILES['fichier']['type'];
    if( !strstr($type_file, 'jpg') && !strstr($type_file, 'jpeg') && !strstr($type_file, 'bmp') && !strstr($type_file, 'gif') && !strstr($type_file, 'png') && !strstr($type_file, 'pdf') && !strstr($type_file, 'odt') && !strstr($type_file, 'doc') && !strstr($type_file, 'sdc') && !strstr($type_file, 'xls'))
    {
        //exit("Le fichier n'est pas une image");
    }

    // on copie le fichier dans le dossier de destination
    $name_file = $_FILES['fichier']['name'];
    
	if( !move_uploaded_file($tmp_file, $content_dir . $name_file) )
    {
        //exit("Impossible de copier le fichier dans $content_dir");
    }

    //echo "Le fichier a bien été uploadé";
}

if( !isset($_POST['do']))
{
	
?>

	<script type="text/javascript">
		$(document).ready(function(){
			$("#bt_add_pj").click(function(){
				$(this).hide();
				$("#ajout_pj").slideDown();		
			});
			$("#bt_cancel_pj").click(function(){
				$("#bt_add_pj").slideDown();
				$("#ajout_pj").hide();		
			});
			
			$(".supprimerPJ").click(function(){
				var toHide = $(this).parents('li');
				$.ajax({
					data: "do=deletePj&section=pj&name="+$(this).attr('id'),
					type:"POST",
					async: false,	
					beforeSend: function(){
						//VERIFICATION SUR L'integrité des données
					},
					success: function(affichageResultat){
						if(affichageResultat == '1'){
							toHide.fadeOut();
						}else{
							//cas erreur sur la suppression
						}
					},
					error: function(){
						return false;
					}
				});
				return false;
			});
			
		});//fin doc ready
	</script>

<?php

	echo "
		<div id='pieces_jointes'>
			<h2>Liste des pièces jointes</h2>
			<h5><a href='#' id='bt_add_pj'>+ Ajouter une pièce jointe</a></h5>
			<div id='ajout_pj'  class='box' style='display:none;margin:5px 0px 30px 0px;'>
				Selectionnez le fichier en cliquant sur parcourir, puis valider l'ajout.
				<form method='post' enctype='multipart/form-data' action=''>
					<p>
						<input type='file' name='fichier' size='30'>
						<input type='submit' name='upload' value='Valider'>
						<h5><a href='#' id='bt_cancel_pj'>Annuler</a></h5>
					</p>
				</form>
			</div>
			<div class='pj_classement'>
				<h6>Classer par</h6>
				<span class='pj_clssmnt_actn'><a class='pasFini' href='javascript:void(0);'>type</a></span>
				<span class='pj_clssmnt_actn'><a class='pasFini' href='javascript:void(0);'>ordre alphabétique</a></span>
				<span class='pj_clssmnt_actn'><a class='pasFini' href='javascript:void(0);'>date</a></span>
			</div>
	";	
	
	//$testHelper = $this->_helper->fctTest('DossierPj');
	//$this->DossierPj('listing');
	
	//echo $this->listing();
	echo listing("pj/dossier/".$this->id_dossier,$this->id_dossier);
	echo "
		</div>
	";

}else{
	if($_POST['do'] == 'deletePj'){
		echo unlink("pj/dossier/".$this->id_dossier."/".$_POST['name']);
	}
}

?>