<?php
/*

TRUNCATE TABLE `prescriptionarticle`;
TRUNCATE TABLE `prescriptionarticleliste`;
TRUNCATE TABLE `prescriptioncat`; 
TRUNCATE TABLE `prescriptiontexte`;	
TRUNCATE TABLE `prescriptiontexteliste`;
TRUNCATE TABLE `prescriptiontype`;
TRUNCATE TABLE `prescriptiontypeassoc`;
TRUNCATE TABLE `prescriptiondossier`;
TRUNCATE TABLE `prescriptiondossierassoc`;

*/
echo "
	<button id='addPrescriptionType' >Ajouter une prescription type</button>
";

?>
<script type="text/javascript">

$(document).ready(function(){
//Ajout prescription type
	
	var dialogPrescType = $('<div style="display:none;"></div>').appendTo('body');
	
	$("#addPrescriptionType").button({
		icons: {
			primary: 'ui-icon-circle-plus'
		}
	});

	$("#addPrescriptionType").live('click',function(){
		//On ouvre la boite de dialogue
		$.ajax({
			type: "POST",
			url: "/dossier/prescriptiontypeform",
			data: "&action=dossier",
			success: function(msg){
				//alert(msg);
				dialogPrescType.html(msg);
				dialogPrescType.dialog("open");
				$.ajax({
					type: "POST",
					url: "/gestion-prescriptions/emplacement",
					data: $("#formPrescription").serialize(),
					success: function(msg){
						//alert(msg);
						$("#selectEmplacement").html(msg);
					}
				});
			}
		});
		return false;
	});
	
	dialogPrescType.dialog({
		title: "Ajout d'une prescription type",
		modal: true,
		autoOpen: false,
		width: 1000,
		height: 'auto',
		buttons: {
			"Sauvegarder": function() {
				
				return false;
			},
			"Annuler": function() {
				dialogPrescType.dialog("close");
			}
		},
		close: function(event, ui){
			
		}
	});
	
	$(".selectCategorie").live('click',function(){
		$("#PRESCRIPTIONTYPE_CATEGORIE").val($(this).attr('id'));
		changeEmplacement();
		return false;
	});

	$(".selectTexte").live('click',function(){
		$("#PRESCRIPTIONTYPE_TEXTE").val($(this).attr('id'));
		changeEmplacement();
		return false;
	});
	
	$(".selectArticle").live('click',function(){
		$("#PRESCRIPTIONTYPE_ARTICLE").val($(this).attr('id'));
		changeEmplacement();
		return false;
	});
	
	$(".retour").live('click',function(){
		if($(this).attr('id') == 'retourCategorie'){
			$("#PRESCRIPTIONTYPE_CATEGORIE").val('');
		}else if($(this).attr('id') == 'retourTexte'){
			$("#PRESCRIPTIONTYPE_TEXTE").val('');
		}else if($(this).attr('id') == 'retourArticle'){
			$("#PRESCRIPTIONTYPE_ARTICLE").val('');
		}
		changeEmplacement();
		return false;
	});
	
	function changeEmplacement()
	{
		$("#listePrescriptionType").html('');
		$.ajax({
			type: "POST",
			url: "/gestion-prescriptions/emplacement",
			data: $("#formPrescription").serialize(),
			success: function(msg){
				$("#selectEmplacement").html(msg);
				affichePrescription();
			}
		});
	}
	
	function affichePrescription()
	{
		$.ajax({
			type: "POST",
			url: "/dossier/prescriptionshowemplacement",
			data: $("#formPrescription").serialize(),
			success: function(msg){
				$("#listePrescriptionType").html(msg);
			}
		});
	}
});
</script>
