<?php
if(!$this->edit)
	echo "<li class='table-responsive' id='prescriptionDossier_".$this->idPrescriptionDossier."' style='list-style-type:none; margin-bottom:15px;'>";

	echo "
			<table class='table'>
	";

	$nbAssoc = count($this->textes);
	$cpt = true;
	for($j=0; $j < $nbAssoc; $j++)
	{
		$article = $this->articles[$j];
		$texte = $this->textes[$j];
		echo "
			<tr>
				<td class='span3'>".$texte."</td>
				<td class='span2'>".$article."</td>
		";
		if($cpt)
		{
			if($this->typePrescDossier != 0){
				echo "<td rowspan='".$nbAssoc."' class='span1 numPresc'>".$this->numPresc."</td>";			
			}

			echo "<td rowspan='".$nbAssoc."' class='".( ( $this->typePrescDossier != 0 )? "span5" :"span6" )."'>".nl2br($this->libelle)."</td>";
			echo "<td class='span1' rowspan='".$nbAssoc."'><button class='btn' id='prescDossier_".$this->idPrescriptionDossier."'>Modifier</button></td>";
			$cpt = false;
		}
		echo "
			</tr>
		";
	}
	echo "
			</table>
	";
if(!$this->edit)
	echo "</li>";

?>