<?php

echo "
	<form name='formPrescriptionEdit' id='formPrescriptionEdit' action='' method='POST'>
	<input type='hidden' name='do' id='do' value='".$this->do."' />
	<input type='hidden' name='idDossier' id='idDossier' value='".$this->idDossier."' />
	<input type='hidden' name='idPrescDossier' id='idPrescDossier' value='".$this->idPrescDossier."' />
	<input type='hidden' name='numPresc' id='numPresc' value='".$this->numPresc."' />
	<div id='selectEmplacement' ></div>
	<br/><br/>
	<span>Texte : </span><span><input type='texte' name='LIBELLE_TEXTE' id='LIBELLE_TEXTE' value='' /></span>
	<span>Article : </span><span><input type='article' name='LIBELLE_ARTICLE' id='LIBELLE_ARTICLE' value='' /></span>
	<button id='addAssoc' >Ajouter</button>
	<br/><br/>
	<div>
		<table id='association' style='width:500px;'>
			<tr>
				<th>Texte</th>
				<th>Article</th>
				<th></th>
			</tr>
";
foreach($this->assoc as $val => $ue)
{
	echo "
		<tr>
			<td><input type='hidden' name='texte[]' value='".$ue['LIBELLE_TEXTE']."' />".$ue['LIBELLE_TEXTE']."</td>
			<td><input type='hidden' name='article[]' value='".$ue['LIBELLE_ARTICLE']."' />".$ue['LIBELLE_ARTICLE']."</td>
			<td><a href='' class='suppAssoc'>&times;</a></td>
		</tr>
	";
}

echo "
		</table>
	</div>
	<br/>
	Contenu : 
	<textarea name='PRESCRIPTIONTYPE_LIBELLE' id='LIBELLE_PRESCRIPTIONTYPE' cols='150' rows='10'>
";
	if($this->do == 'prescDossier')
	{
		echo $this->assoc[0]['LIBELLE_PRESCRIPTION_DOSSIER'];
	}else{
		echo $this->assoc[0]['PRESCRIPTIONTYPE_LIBELLE'];
	}
echo "		
	</textarea>
	</div>
	</form>
	<br/>
	<button class='deletePrescDossier'>Supprimer la prescription</button>
	<div class='deleteOption' style='display:none;'>
		Voulez vous supprimer la prescription ?</br>
		<button class='validDelete' id='delete_".$this->idPrescDossier."' >Oui</button>
		<button class='cancelDelete' >Non</button>
	</div>
";

?>
<script type="text/javascript">
$(document).ready(function(){
	$("#addAssoc").button({
		icons: {
			primary: 'ui-icon-circle-plus'
		}
	});
	
	$("#LIBELLE_TEXTE").live('focus',function(){
		$("#texteId").val('');
	});
	
	$("#LIBELLE_TEXTE").autocomplete("/gestion-prescriptions/selectiontexte?format=json",{
		minChars: 2,
		max: 100,
		parse: function(data) {
			return $.map(data["selectTexte"], function(row) {
				return {
					data: row,
					value: row.LIBELLE_TEXTE,
					result: row.LIBELLE_TEXTE
				}
			});
		},
		formatItem: function(item) {
			return item.LIBELLE_TEXTE;
		}
	}).result(function(e, item) {
		$("#textTemp").val(item.ID_TEXTE);
	});

	$("#LIBELLE_ARTICLE").autocomplete("/gestion-prescriptions/selectionarticle?format=json",{
		minChars: 2,
		max: 100,
		parse: function(data) {
			return $.map(data["selectArticle"], function(row) {
				return {
					data: row,
					value: row.LIBELLE_ARTICLE,
					result: row.LIBELLE_ARTICLE
				}
			});
		},
		formatItem: function(item) {
			//alert(item.LIBELLE_COMMISSION);
			return item.LIBELLE_ARTICLE;
		}
	}).result(function(e, item) {
		$("#articleTemp").val(item.ID_TEXTE);
	});

	$(".deletePrescDossier").button({
		icons: {
			primary: 'ui-icon-trash'
		}
	});
	
});
