<script type='text/javascript' >
	var dialogEditPresc = $('<div style="display:none"></div>').appendTo('body');

	$(".editPresc").button({
		icons: {
			primary: 'ui-icon-pencil'
		},
		text: false
	});

</script>

<?php

if($this->type == "loadPrescriptionAjax"){
	
	for($i = 0; $i < $this->nbPrescription; $i++){
		echo "
			<li id='presc_".$this->listePrescription[$i]['ID_PRESCRIPTIONDOSSIER']."' num='".$this->listePrescription[$i]['NUM_PRESCRIPTIONDOSSIER']."'>
				<div class='grid_2 alpha' >
		";
		
		//if(isset($this->listeTextes[$i])){
			for($t = 0; $t < count($this->listeTextes[$i]); $t++){
				if($this->listeTextes[$i][$t] != NULL){
					echo $this->listeTextes[$i][$t]."<br/>";			
				}else if($this->listeTextes[$i][$t] == NULL && $this->listeArticles[$i][$t] != NULL){
					echo "<br/>";
				}
			}
		//}
		echo "
				</div>
				<div class='grid_2' >
		";
		//if(isset($this->listeArticles[$i])){
			for($a = 0; $a < count($this->listeArticles[$i]); $a++){
				if($this->listeArticles[$i][$a] != NULL){
					echo $this->listeArticles[$i][$a]."<br/>";
				}else if($this->listeArticles[$i][$a] == NULL && $this->listeTextes[$i][$a] != NULL){
					echo "<br/>";
				}
			}
		//}
		
		echo "
				</div>
				<div class='grid_1 numPresc' >
					".$this->listePrescription[$i]['NUM_PRESCRIPTIONDOSSIER']."
				</div>
				<div class='grid_7' >
		";
		echo nl2br(str_replace("<br />", "" ,$this->ListePrescriptionsLibelle[$i]));
		echo "
				</div>
				<div class='grid_2  omega'>
					<input type='checkbox' class='motiveAvisDef' value='".$this->listePrescription[$i]['ID_PRESCRIPTIONDOSSIER']."' ".( ($this->listePrescription[$i]['MAD_PRESCRIPTIONDOSSIER'] == 1)?"checked='checked'":"")." />
				</div>
				<div class='grid_2  button' >
					<button class='editPresc' id='edit_".$this->listePrescription[$i]['ID_PRESCRIPTIONDOSSIER']."'>Editer</button>
				</div>
				<hr class='clear'/>
			</li>
		";
	}
}else{
	//s'il s'agit d'ajouter une presc on lui met l'id correspondant à sont enregistrement dans la base
	if($this->type == "addPrescAssoc")
		echo "<li id='presc_".$this->idPrescDossier."' num='".$this->numPresc."'>";

	echo "
		<div class='grid_2 alpha' >
	";

	foreach($this->listeTextes  as $indTexte => $valTexte){
		echo $valTexte."<br/>";
	}
	echo "
		</div>
		<div class='grid_2'>
	";
	foreach($this->listeArticles  as $indArticle => $valArticle){
		echo $valArticle."<br/>";
	}
	echo "
		</div>
		<div class='grid_1 numPresc' >
			".$this->numPresc."
		</div>
		<div class='grid_7'>
	";
	echo nl2br(str_replace("<br />", "" ,$this->listeLibelles));
	echo "
		</div>
	";
/*
	echo "
		<div class='grid_2  omega'>
			<input type='checkbox' class='motiveAvisDef' value='".$this->idPrescDossier."' />
		</div>
	";
*/
	echo "
		<div class='grid_2  button' >
			<button class='editPresc' id='edit_".$this->idPrescDossier."'>Editer</button>
		</div>
		<hr class='clear'/>
	";

	if($this->type == "addPrescType"){
		echo "<button class='validPrescType' id='addPrescType' >Ajouter à la liste des prescription</button>";
	}

	if($this->type == "addPrescAssoc")
		echo "</li>";

}

