<?php

$idTypeMarq = "";
//echo $this->liste[0];
foreach($this->listeTextesAppl as $val => $ue){
	$idType = $ue['ID_TYPETEXTEAPPL'];
	if($idTypeMarq != $idType){
		//Pour l'affichage par catégorie
		echo "
			<h3>".$ue['LIBELLE_TYPETEXTEAPPL']."</h3>			
		";
		$idTypeMarq = $idType;
	}
	echo "
		<div class='grid_1'>
			<input type='checkbox' name='texte' id='".$ue['ID_TEXTESAPPL']."' ".( (in_array($ue['ID_TEXTESAPPL'],$this->listeIdTexte))? "checked" : "" )."/>
		</div>
		<div class='grid_12 alpha'>".nl2br($ue['LIBELLE_TEXTESAPPL'])."</div>
		<hr class='clear'>
	";

}

?>

<script type='text/javascript' >
$(document).ready(function() {
	$("input[type=checkbox]").click(function(){
		var idDossier = $("#idDossier").val();
		var idTexte = $(this).attr('id');
		if($(this).is(':checked')) {
			var toDo = "save";			
		}else{
			var toDo = "delete";
		}
		
		$.ajax({
			type: "POST",
			url: "/dossier/fonction",
			data: "&do=texteApplicable&toDo="+toDo+"&idTexte="+idTexte+"&idDossier="+idDossier,
			success: function(msg){
				//alert(msg);				
			}
		});
		
	});
	
	/*
	$.ajax({
					type: "POST",
					url: "/gestion-textes-applicables/save",
					data: $("#formTexteAppl").serialize(),
					success: function(msg){
						//alert(msg);
						dialogEditTexteAppl.html("");
						dialogEditTexteAppl.dialog("close");
						if($("#gestionTextesAppl").length){
							$("#gestionTextesAppl").click();
						}else{
							window.location='/gestion-textes-applicables';
						}
						
					}
				});
				*/
	
});
</script>