<?php
echo "
	<input type='hidden' name='idEtablissement' id='idEtablissement' value='".$this->idEtablissement."' />
";
$idTypeMarq = "";
//echo $this->liste[0];
foreach($this->listeTextesAppl as $val => $ue){
	$idType = $ue['ID_TYPETEXTEAPPL'];
	if($idTypeMarq != $idType){
		//Pour l'affichage par catégorie
		echo "
			<h3>".$ue['LIBELLE_TYPETEXTEAPPL']."</h3>			
		";
		$idTypeMarq = $idType;
	}
	echo "
		<div class='row-fluid'>
			<div class='span1'>
				<input type='checkbox' name='texte' ".( ($this->infosDossier['VERROU_DOSSIER'] == 1)? "disabled='disabled'" : "")." id='".$ue['ID_TEXTESAPPL']."' ".( (in_array($ue['ID_TEXTESAPPL'],$this->listeIdTexte))? "checked" : "" )."/>
			</div>
			<div class='span11'>".nl2br($ue['LIBELLE_TEXTESAPPL'])."</div>
			<hr class='clear'>
		</div>
	";
}

?>

<script type='text/javascript' >
$(document).ready(function() {
	$("input[type=checkbox]").click(function(){
		var idDossier = $("#idDossier").val();
		var idTexte = $(this).attr('id');
		if($(this).is(':checked')) {
			var toDo = "save";			
		}else{
			var toDo = "delete";
		}
		
		$.ajax({
			type: "POST",
			url: "/dossier/fonction",
			data: "&do=texteApplicable&toDo="+toDo+"&idTexte="+idTexte+"&idDossier="+idDossier+"&idEtablissement="+$("#idEtablissement").val(),
			success: function(msg){
				//alert(msg);				
			}
		});
		
	});
});
</script>