<?php if($this->key_ign == null) : ?>

    <div class='well well-large text-center'>
        <p class='lead'>La clé IGN n'est pas renseignée.</p>
        <p>Vous devez placer la clé IGN dans votre configuration comme ceci : </p>
        <pre>SetEnv PREVARISC_PLUGIN_IGNKEY XXXXXXXXXXXX</pre>
    </div>

<?php else : ?>
    <div id='geoportail-container'  style="height: 350px; max-height: 350px;"></div>
    
    <script type="text/javascript" src="//api.ign.fr/geoportail/api/js/2.1.2/GeoportalExtended.js"></script>
    <script>
        $(document).ready(function() {
            var points = [];
            points.push({
                lat: 50.4727273438818,
                lon: 2.71490430425517,
                description: "Centre par défaut"
            });

            viewer = initViewer(
                "geoportail-container",
                "<?php echo $this->key_ign ?>",
                points,
                <?php echo json_encode($this->couches_cartographiques) ?>
            );
        });
    </script>

<?php endif ?>

<?php if(count($this->couches_cartographiques) == 0) : ?>

    <div class='well well-large text-center'>
        <p class='lead'>Il n'y a pas de couche cartographique.</p>
        <p><a href='<?php echo $this->url(array('action' => 'add')) ?>' class='btn btn-large'>Ajouter une couche cartographique</a></p>
    </div>

<?php else : ?>

    <p class='text-right'><a class='btn' href='<?php echo $this->url(array('controller' => 'couches-cartographiques', 'action' => 'add'), null, true) ?>'>Ajouter une couche</a></p>

    <table class="table">
        <thead>
            <tr>
                <th>Type</th>
                <th>Nom de la couche</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->couches_cartographiques as $couche_cartographique) : ?>
            <tr>
                <td><?php echo $couche_cartographique['TYPE_COUCHECARTO'] ?></td>
                <td><?php echo $couche_cartographique['NOM_COUCHECARTO'].(($couche_cartographique['ISBASELAYER_COUCHECARTO']) ? " (couche de base)" : "") ?></td>
                <td>
                    <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $couche_cartographique['ID_COUCHECARTO'])) ?>">Éditer la couche</a><br/>
                    <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $couche_cartographique['ID_COUCHECARTO'])) ?>">Supprimer</a>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>

<?php endif ?>
