<p class='text-right'><a class='btn' href='<?php echo $this->url(array('action' => 'add')) ?>'>Ajouter une couche</a></p>

<?php if(count($this->couches_cartographiques) == 0) : ?>

    <div class='well well-large text-center'>
        <p class='lead'>Il n'y a pas de couche cartographique.</p>
        <p><a href='<?php echo $this->url(array('action' => 'add')) ?>' class='btn btn-large'>Ajouter une couche cartographique</a></p>
    </div>

<?php else : ?>

    <div id='geoportail-container'  style="height: 250px; max-height: 250px;"></div>
    <script type="text/javascript" src="http://api.ign.fr/geoportail/api/js/latest/GeoportalExtended.js"></script>
    <script>
        $(document).ready(function() {
            viewer = Geoportal.load("geoportail-container", "i4d3km958rzoesb7thga4f59", {
                lat: 50.4727273438818,
                lon: 2.71490430425517
            }, 8, OpenLayers.Util.extend({
                controls: [new OpenLayers.Control.NavToolbar(), new OpenLayers.Control.LayerSwitcher()],
                overlays:{}
            }));
        });
    </script>

    <table class="table">
        <thead>
            <tr>
                <th>Type</th>
                <th>Nom de la couche</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->couches_cartographiques as $couche_cartographique) : ?>
            <tr>
                <td><?php echo $couche_cartographique->NOM_COUCHECARTOTYPE ?></td>
                <td><?php echo $couche_cartographique->NOM_COUCHECARTO.(($couche_cartographique->ISBASELAYER_COUCHECARTO) ? " (couche de base)" : "") ?></td>
                <td>
                    <a href="/couches-cartographiques/edit?id=<?php echo $couche_cartographique->ID_COUCHECARTO ?>">Éditer la couche</a><br/>
                    <a href="/couches-cartographiques/delete?id=<?php echo $couche_cartographique->ID_COUCHECARTO ?>">Supprimer</a>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>

<?php endif ?>