<?php if ($this->key_ign != null) : ?>
    <div id='geoportail-container'  style="height: 350px; max-height: 350px;"></div>
    
    <script type="text/javascript" src="//api.ign.fr/geoportail/api/js/2.1.2/GeoportalExtended.js"></script>
    <script>
        $(document).ready(function() {
            var points = [];
            points.push({
                lat: <?php echo $this->default_lat ?>,
                lon: <?php echo $this->default_lon ?>,
                description: "Centre par défaut"
            });

            viewer = initViewer(
                "geoportail-container",
                "<?php echo $this->key_ign ?>",
                points,
                <?php echo json_encode($this->couches_cartographiques) ?>
            );
        });
    </script>
<?php elseif ($this->geoconcept_url != null) : ?>
    <div id='geoconcept-container'  style="height: 350px; max-height: 350px;width: 100%"></div>
    <script type="text/javascript" src="/js/geoconcept/OpenLayers.js"></script>
    <script type="text/javascript" src="/js/geoconcept/proj4js.js"></script>
    <script type="text/javascript" src="/js/geoconcept/htc-lite.js"></script>
    <?php if ($projection = getenv('PREVARISC_PLUGIN_GEOCONCEPT_PROJECTION')): ?>
    <script type="text/javascript" src="/js/geoconcept/defs/<?php echo $projection ?>.js"></script>
    <?php endif ?>
    <script type="text/javascript" src="/js/geoconcept/geoconcept.js"></script>
    <link rel="stylesheet" href="/css/geoconcept/htc.css"/>
    <script>
        $(document).ready(function() {
            <?php if ($token = getenv('PREVARISC_PLUGIN_GEOCONCEPT_TOKEN') && $app_id = getenv('PREVARISC_PLUGIN_GEOCONCEPT_APP_ID')): ?>
                initGeoConceptKey('<?php echo $app_id ?>', '<?php echo $token ?>');
            <?php endif ?>
            var points = [];
            points.push({
                lat: <?php echo $this->default_lat ?>,
                lon: <?php echo $this->default_lon ?>,
                description: "Centre par défaut"
            });
            
            map = initGeoConceptViewer('geoconcept-container', 
                "<?php echo $this->geoconcept_url ?>",
                "<?php echo getenv('PREVARISC_PLUGIN_GEOCONCEPT_LAYER') ?>",
                points,
                <?php echo json_encode($this->couches_cartographiques) ?>
            );
        });
    </script>
    
    
<?php elseif ($this->key_googlemap != null) : ?>
    <div id='googlemap-container' style="height: 350px; max-height: 350px;"></div>
    <script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=<?php echo $this->key_googlemap ?>&sensor=false">
    </script>
    <script type="text/javascript">
        function initialize() {
        var point = new google.maps.LatLng(<?php echo $this->default_lat ?>, <?php echo $this->default_lon ?>);
        var map = new google.maps.Map(document.getElementById("googlemap-container"), {
            center: point,
            zoom: 12
        });
          
        var marker = new google.maps.Marker({
            position: point,
            map: map,
            title: "<?php echo $this->etablissement['informations']['LIBELLE_ETABLISSEMENTINFORMATIONS'] ?>"
        });


        google.maps.event.addDomListener(window, 'load', initialize);
     </script>
     
<?php else: ?>

    <div class='well well-large text-center'>
        <p class='lead'>Aucun player cartographique configuré.</p>
        <p>Vous devez configurer comme ceci : </p>
        <pre>SetEnv PREVARISC_PLUGIN_IGNKEY XXXXXXXXXXXX</pre>
        <pre>SetEnv PREVARISC_PLUGIN_GOOGLEMAPKEY XXXXXXXXXXXX</pre>
        <pre>SetEnv PREVARISC_PLUGIN_GEOCONCEPT_URL XXXXXXXXXXXX</pre>
    </div>

    
<?php endif ?>

<?php if(count($this->couches_cartographiques) == 0) : ?>

    <div class='well well-large text-center'>
        <p class='lead'>Il n'y a pas de couche cartographique.</p>
        <p><a href='<?php echo $this->url(array('action' => 'add')) ?>' class='btn btn-large'>Ajouter une couche cartographique</a></p>
    </div>

<?php else : ?>

    <p class='text-right'><a class='btn' href='<?php echo $this->url(array('controller' => 'couches-cartographiques', 'action' => 'add'), null, true) ?>'>Ajouter une couche</a></p>

    <table class="table">
        <thead>
            <tr>
                <th>Type</th>
                <th>Nom de la couche</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->couches_cartographiques as $couche_cartographique) : ?>
            <tr>
                <td><?php echo $couche_cartographique['TYPE_COUCHECARTO'] ?></td>
                <td><?php echo $couche_cartographique['NOM_COUCHECARTO'].(($couche_cartographique['ISBASELAYER_COUCHECARTO']) ? " (couche de base)" : "") ?></td>
                <td>
                    <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $couche_cartographique['ID_COUCHECARTO'])) ?>">Éditer la couche</a><br/>
                    <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $couche_cartographique['ID_COUCHECARTO'])) ?>">Supprimer</a>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>

<?php endif ?>
