<tr>
	<td style='width: 300px'>
        <div class='inner_scroll'>
            <!-- ID de la règle -->
            <input type='hidden' name='ID_REGLE[]' value='<?php echo $this->id_regle ?>' />
        
            <!-- Emplacement géographique (Si c'est une communale, c'est une commune sinon un groupement) -->
            <?php $id_type_commission_communale = getenv('PREVARISC_COMMISSION_COMMUNALE_TYPE') ? getenv('PREVARISC_COMMISSION_COMMUNALE_TYPE') : 2; ?>
            <?php if($this->infos["ID_COMMISSIONTYPE"] == $id_type_commission_communale) : ?>
                <p>
                    Commune
                    <input type='text' class='commune' value='<?php echo $this->commune["LIBELLE_COMMUNE"] ?>' class='bigger' size=25 <?php if($this->commune["NUMINSEE_COMMUNE"]) echo "style='background-color: #EEE'" ?> />
                    <input type='hidden' name='<?php echo $this->id_regle ?>_NUMINSEE_COMMUNE' value='<?php echo $this->commune["NUMINSEE_COMMUNE"] ?>' />
                </p>
            <?php else : ?>
                <?php
                    echo $this->listeGroupement($this->groupement, array(
                        "name" => $this->id_regle . "_ID_GROUPEMENT"
                    ));
                ?>
            <?php endif ?>
        </div>
	</td>
	
	<!-- Catégorie -->
	<td class='checkbox_area'>
        <div class='inner_scroll'>
            <ul class='unstyled'>
                <?php foreach( $this->categories as $categorie ) : ?>
                <li>
                <input name='<?php echo $this->id_regle ?>_ID_CATEGORIE[]' type='checkbox' value='<?php echo $categorie["ID_CATEGORIE"] ?>' <?php if( $categorie["ID_REGLE"] != null ) echo "checked" ?> />
                <?php echo $categorie["LIBELLE_CATEGORIE"] ?>
                </li>
            <?php endforeach ?>
            </ul>
		</div>
	</td>
	
	<!-- Le type -->
	<td class='checkbox_area' >
        <div class='inner_scroll'>
            <ul class='unstyled'>
            <?php foreach( $this->types as $type ) : ?>
                <li>
                    <input name='<?php echo $this->id_regle ?>_ID_TYPE[]' type='checkbox' value='<?php echo $type["ID_TYPE"] ?>' <?php if( $type["ID_REGLE"] != null ) echo "checked" ?> />
                    <?php echo $type["LIBELLE_TYPE"] ?>
                </li>
            <?php endforeach ?>
            </ul>
        </div>
	</td>
	
	<!-- Classes -->
	<td class='checkbox_area' >
        <div class='inner_scroll'>
            <ul class='unstyled'>
            <?php foreach( $this->classes as $classe ) : ?>
                <li>
                <input name='<?php echo $this->id_regle ?>_ID_CLASSE[]' type='checkbox' value='<?php echo $classe["ID_CLASSE"] ?>' <?php if( $classe["ID_REGLE"] != null ) echo "checked" ?> />
                <?php echo $classe["LIBELLE_CLASSE"] ?>
                </li>
            <?php endforeach ?>
            </ul>
        </div>
	</td>
	
	<!-- Local sommeil ou non -->
	<td  class='checkbox_area' >
        <div class='inner_scroll'>
            <ul class='unstyled'>
                <li>
                    <input type='checkbox' name='<?php echo $this->id_regle ?>_LOCALSOMMEIL[]' value='1' <?php if(in_array(1, $this->local_sommeil)) echo "checked" ?> />
                    Oui
                </li>
                <li>
                    <input type='checkbox' name='<?php echo $this->id_regle ?>_LOCALSOMMEIL[]' value='0' <?php if(in_array(0, $this->local_sommeil)) echo "checked" ?> />
                    Non
                </li>
            </ul>
        </div>
	</td>
	
	<!-- Etude et/ou visite -->
	<td class='checkbox_area' >
        <div class='inner_scroll'>
            <ul class='unstyled'>
                <li>
                    <input type='checkbox' name='<?php echo $this->id_regle ?>_ETUDEVISITE[]' value='1' <?php if(in_array(1, $this->etude_visite)) echo "checked" ?> />
                    Étude
                </li>
                <li>
                    <input type='checkbox' name='<?php echo $this->id_regle ?>_ETUDEVISITE[]' value='0' <?php if(in_array(0, $this->etude_visite)) echo "checked" ?> />
                    Visite
                </li>
            </ul>
        </div>
	</td>
	
	<!-- Action -->
	<td style='text-align: center;' >
		<a class='delete-regle' href='/commission/delete-regle?id_regle=<?php echo $this->id_regle ?>' title='Supprimer' >
			Supprimer
		</a>
	</td>
</tr>