<?php

	include_once(APPLICATION_PATH . '/views/helpers/Carte.php');
	
	$markers = array();
	
	// Etablissements liés
	foreach($this->etablissement_lies as $ets_lies) {
		$markers[] = Zend_View_Helper_Carte::Marker($ets_lies['LIBELLE_ETABLISSEMENTINFORMATIONS'], $ets_lies['LAT_ETABLISSEMENTADRESSE'], $ets_lies['LON_ETABLISSEMENTADRESSE'], false, "http://www.google.com/intl/en_us/mapfiles/ms/micons/yellow-dot.png");
	}
	
	// Etablissement
	if(count($this->adresses) > 1) {
		$markers[] = Zend_View_Helper_Carte::Marker($this->libelle, $this->adresses[0]['LAT_ETABLISSEMENTADRESSE'], $this->adresses[0]['LON_ETABLISSEMENTADRESSE'], $this->drag);
	}
	
	// Si il il n'y à pas d'adresse, on centre sur le premiers ets lié
	$center = array();
	if(count($this->adresses) > 1) {
		$center['lon'] = $this->adresses[0]['LON_ETABLISSEMENTADRESSE'];
		$center['lat'] = $this->adresses[0]['LAT_ETABLISSEMENTADRESSE'];
		$this->carte($center['lat'], $center['lon'], $markers);
	}
	elseif(count($this->etablissement_lies) > 1) {
		$center['lon'] = $this->etablissement_lies[0]['LON_ETABLISSEMENTADRESSE'];
		$center['lat'] = $this->etablissement_lies[0]['LAT_ETABLISSEMENTADRESSE'];
		$this->carte($center['lat'], $center['lon'], $markers);
	}