<div id='geoportail-content'></div>

<script type="text/javascript">
	$(document).ready( function initGeoportalMap() {

		try {
			geoportalLoadVISU("geoportail-content", "normal"); // On se positionne sur la France métropolitaine

			// On ajoute les différentes couches à la carte
			if( VISU.getMap().allowedGeoportalLayers ) {

				// Couches de geoportail
				VISU.addGeoportalLayers( [
					'GEOGRAPHICALGRIDSYSTEMS.MAPS:WMSC',
					'ORTHOIMAGERY.ORTHOPHOTOS:WMSC',
					'ADMINISTRATIVEUNITS.BOUNDARIES:WMSC',
					'CADASTRALPARCELS.PARCELS:WMSC',
				], {
					'ORTHOIMAGERY.ORTHOPHOTOS:WMSC': {opacity: 1.0, visibility: true}, 	
					global: {opacity: 0.5, visibility: false}
				});

				// Points d'eau
				VISU.getMap().addLayer (
					"WMS",
					"Poteaux d'eau",
					"http://172.16.4.101:8080/geoserver/SDIS62/wms",
					{
						layers: 'SDIS62:DECI_CORRI',
						tiled: true,
						format: 'image/png',
						transparent: true
					}, {
						projection: "EPSG:4171",
						maxExtent: new OpenLayers.Bounds (
							597257.747, 6991178.413,
							723327.502, 7103523.075
						),
						buffer: 0,
						displayOutsideMaxExtent: true,
						isBaseLayer: false,
						visibility: false
					}
				);

				VISU.openLayersPanel(false); // onglet "couches" développé (true=oui  false=non)
				VISU.setToolsPanelVisibility(false); // onglet outils
				VISU.setInformationPanelVisibility(false); // paneau d'information

				VISU.getMap().setCursor("auto"); // pointer sur la carte

				// COUCHE DE L'ETABLISSEMENT ------------------------------------------------
				<?php
					if($this->adresses != 1) {
						$this->adresses[-1] = null;
					}
				?>
				<?php if( count($this->adresses) != 1 ) : ?>

				// Construction de la couche
				markers = new OpenLayers.Layer.Vector('Établissement');

				VISU.getMap().addLayer(markers);

				// Fonction draggable
				drag = new OpenLayers.Control.DragFeature(markers, { onComplete: function(f) {
					f.geometry.transform(VISU.projection, OpenLayers.Projection.CRS84);
					$(".LON_ETABLISSEMENTADRESSE").text(f.geometry.x).val(f.geometry.x);
					$(".LAT_ETABLISSEMENTADRESSE").text(f.geometry.y).val(f.geometry.y);
				}});
				VISU.getMap().addControl(drag);

				// On centre la carte
				VISU.getMap().setCenterAtLonLat(<?php echo $this->adresses[0]["LON_ETABLISSEMENTADRESSE"]. "," .$this->adresses[0]["LAT_ETABLISSEMENTADRESSE"] ?>, 17);	

				// Style du marqueur
				var style = {
					externalGraphic: "http://www.google.com/intl/en_us/mapfiles/ms/micons/red-dot.png",
					graphicWidth: 32,
					graphicHeight: 32
				};

				// On fixe la position du marqueur
				var position = new OpenLayers.Geometry.Point(<?php echo $this->adresses[0]["LON_ETABLISSEMENTADRESSE"]. "," .$this->adresses[0]["LAT_ETABLISSEMENTADRESSE"] ?>);
				position.transform(OpenLayers.Projection.CRS84, VISU.projection);
				pt = new OpenLayers.Feature.Vector(position, null, style);

				// Ajout sur la carte
				markers.addFeatures([pt]);

				<?php endif ?>

				// COUCHE DES ETABLISSEMENTS LIES ------------------------------------------------
				<?php if( count($this->etablissement_lies) != 0 ) : ?>

				// Construction de la couche
				markers_lies = new OpenLayers.Layer.Vector('Établissements liés');

				VISU.getMap().addLayer(markers_lies);

				// Si il n'y a aucun établissements, on centre la carte sur le premier établissement lié
				<?php if( count($this->adresses) == 1 ) : ?>
					VISU.getMap().setCenterAtLonLat(<?php echo $this->etablissement_lies[0]["LON_ETABLISSEMENTADRESSE"]. "," .$this->etablissement_lies[0]["LAT_ETABLISSEMENTADRESSE"] ?>, 17);	
				<?php endif ?>

				// Style du marqueur
				var style_lies = {
					externalGraphic: "http://www.google.com/intl/en_us/mapfiles/ms/micons/yellow-dot.png",
					graphicWidth: 32,
					graphicHeight: 32
				};

				var position_lies = null;

				<?php foreach($this->etablissement_lies as $ets_lies) : ?>

					<?php if($ets_lies["LON_ETABLISSEMENTADRESSE"] != null) : ?>

					// On fixe la position du marqueur
					position_lies = new OpenLayers.Geometry.Point(<?php echo $ets_lies["LON_ETABLISSEMENTADRESSE"]. "," .$ets_lies["LAT_ETABLISSEMENTADRESSE"] ?>);
					position_lies.transform(OpenLayers.Projection.CRS84, VISU.projection);
					pt = new OpenLayers.Feature.Vector(position_lies, null, style_lies);

					// Ajout sur la carte
					markers_lies.addFeatures([pt]);

					<?php endif ?>

				<?php endforeach ?>

				<?php endif ?>

				try {
					carte_chargee();
				}
				catch(e) {}
			}
		}
		catch(e) {
		//alert(e);
			$("#menu_carte .active").remove();
			$("#menu_carte li:first-child").addClass("active");
			$("#menu_carte .active").click();
			
			if(!$("#menu_carte li").hasClass()) {
				$("#geoportail").remove();
			}
		}
	});
	
</script>