<?php $this->placeholder('before_content')->captureStart(); // Capture du 'before_content' ?>

<!-- Contenu -->
<?php if(!empty($this->etablissement['informations'])) : ?>
<div id='ligne_informations'>

    <!-- Libelle -->
    <h2 class="page-header">
        <?php if( $this->etablissement['parents'] > 0 ) : ?>
            <?php foreach($this->etablissement['parents'] as $etablissement) : ?>
                <a href='/etablissement/index/id/<?php echo  $etablissement["ID_ETABLISSEMENT"] ?>'>
                    <?php echo $etablissement["LIBELLE_ETABLISSEMENTINFORMATIONS"] ?>
                </a> -
            <?php endforeach ?>
        <?php endif ?>
        <?php echo file_exists(APPLICATION_PATH . DS . '..' . DS . 'public' . DS . 'img' . DS . 'types' . DS . 'b' . DS . 'icone-type-' . $this->etablissement['informations']['LIBELLE_TYPE_PRINCIPAL'] . '.png') ? "<img src='/img/types/b/icone-type-" . $this->etablissement['informations']['LIBELLE_TYPE_PRINCIPAL'] . ".png' title='" . $this->etablissement['informations']['LIBELLE_TYPE_PRINCIPAL'] . "' />" : ''; ?>
        <?php echo $this->etablissement['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"] ?>
        <?php if ($this->etablissement['general']['NUMEROID_ETABLISSEMENT']): ?>
            <span class="pull-right">
                <small>
                    #<?php echo $this->etablissement['general']["NUMEROID_ETABLISSEMENT"] ?>
                </small>
            </span>
        <?php endif ?>
    </h2>

    <!-- Avis -->
    <?php if($this->etablissement['presence_avis_differe'] == true && $this->avis == "avisDiff") : ?>
        <p class='label label-info'>
            Présence d'un dossier avec avis differé
        </p>
    <?php elseif($this->etablissement['avis'] != null) : ?>

         <?php if($this->etablissement['avis'] == 1 && $this->avis == "avisDoss") : ?>
            <p class="avis F">Favorable <?php echo $this->etablissement['informations']['ID_GENRE'] == 3 ? '' : " à l'exploitation " ?></p>
         <?php elseif($this->etablissement['avis'] == 2  && $this->avis == "avisDoss") : ?>
            <p class="avis D">
               Défavorable <?php echo $this->etablissement['informations']['ID_GENRE'] == 3 ? '' : " à l'exploitation " ?>
               <?php if($this->etablissement['facteur_dangerosite'] > 0) : ?>
                  &nbsp;-&nbsp;Facteur de criticité : <?php echo $this->etablissement['facteur_dangerosite'] ?>
               <?php endif ?>
            </p>
         <?php else : ?>
            <p class="avis">Avis d'exploitation indisponible</p>
         <?php endif ?>

    <?php endif ?>

    <!-- Présence de risques naturels ou technologiques-->
    <?php if(!empty($this->etablissement['general']['DESCTECH_RISQUES_NATURELS_ETABLISSEMENT'])) : ?>
        <p class='label label-warning'>
            Présence de risques naturels
        </p>
        <br/>
    <?php endif ?>
    <?php if(!empty($this->etablissement['general']['DESCTECH_RISQUES_TECHNOLOGIQUES_ETABLISSEMENT'])) : ?>
        <p class='label label-warning'>
            Présence de risques technologiques
        </p>
        <br/>
    <?php endif ?>

    <!-- Présence d'un dossier échéancier de travaux -->
    <?php if($this->etablissement['presence_echeancier'] == true) : ?>
        <p class='label label-info'>
            Présence d'un échéancier de travaux
        </p>
    <?php endif ?>

    &nbsp;

    <!-- Statut -->
    <p>Statut : <?php echo $this->etablissement['informations']['LIBELLE_STATUT'] ?></p>

</div>
<?php endif ?>

<div id='fiche_etablissement'>

<?php $this->placeholder('before_content')->captureEnd() ?>


<?php $this->placeholder('after_content')->captureStart() // Capture du 'after_content' ?>

</div>

<?php $this->placeholder('after_content')->captureEnd() ?>
