<tr <?php echo $this->preventionniste === null ? "id='prototype_preventionniste' class='hide prototypes'" : "class='preventionniste'" ?> >
    <td>
        <input type='hidden' value='<?php echo $this->preventionniste["ID_UTILISATEUR"] ?>' name='ID_UTILISATEUR[]' />
        <span><?php echo $this->preventionniste["NOM_UTILISATEURINFORMATIONS"]." ".$this->preventionniste["PRENOM_UTILISATEURINFORMATIONS"] ?></span>
    </td>
    <td>
        <small><a href="#" onclick='$(this).parent().parent().parent().remove(); return false;' >Retirer</a></small>
    </td>
</tr>