<table class='table-custom tableauEffectifs'>
	<caption>Niveau 1</caption>
	<thead>
		<tr>
			<th rowspan="2" >Numéro cellule</th>
			<th rowspan="2" >Libellé</th>
			<th colspan="2" >Surface</th>
			<th rowspan="2" >Mode de calcul</th>
			<th rowspan="2" >Article</th>
			<th colspan="3" >Effectifs</th>
		</tr>
		<tr>
			<th>Totale</th>
			<th>Accessible</th>
			<th>Public</th>
			<th>Personnel</th>
			<th>Total</th>
		</tr>
	</thead>
	
	<tbody>
	
		<!-- Numéro cellule -->
		<td></td>
		
		<!-- Libellé -->
		<td></td>
		
		<!-- Surface totale -->
		<td></td>
		
		<!-- Surface accessible -->
		<td></td>
		
		<!-- Mode de calcul -->
		<td></td>
		
		<!-- Article -->
		<td></td>
		
		<!-- Effectifs public -->
		<td></td>
		
		<!-- Effectifs personnel -->
		<td></td>
		
		<!-- Effectifs total -->
		<td></td>
		
	</tbody>
</table>