<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">
	<head>
		<?php
			echo $this->headTitle($this->title);
			echo $this->headMeta();
			echo $this->headLink();
			echo $this->inlineScript();
			echo $this->headScript();
		?>
		<script type='text/javascript'>
			$(document).ready(function(){
				if($("#infosEtabs").html() == ''){
					$.ajax({
						url: "/dossier/fonction",
						data: "do=infosEtabs&idDossier="+$("#idDossier").val(),
						type:"POST",
						//async: false,
						beforeSend: function(){
							
						},
						success: function(affichageResultat){
							//alert(affichageResultat);				
							$("#infosEtabs").html(affichageResultat);
						},
						error: function(){
							return false;
						}
					});
				}else if($("#infosEtablissement").html() == ''){
					//alert($("#idEtablissement").val());
					$.ajax({
						url: "/dossier/fonction",
						data: "do=infosEtabs&idEtablissement="+$("#idEtablissement").val(),
						type:"POST",
						//async: false,
						beforeSend: function(){
							
						},
						success: function(affichageResultat){
							//alert(affichageResultat);				
							$("#infosEtablissement").html(affichageResultat);
						},
						error: function(){
							return false;
						}
					});
				}
			});
		</script>
	</head>
	<body>
		<div id='wrapper'>
			<div id='layout-content' >
				<!-- Header -->
				<?php $this->header(); ?>
				
				<div class='container_16' >	
					<?php if($this->action == "add" || $this->do == "new" ) : ?>
						<h2 class='grid_16'>
							<i class='sprite sprite-folder_add' ></i>
							Création d'un nouveau dossier <div style='margin:10px;' id='infosEtablissement'></div>
						</h2>
					<?php else : ?>
						<h3 class='grid_16' >
							<span style="color: #333333"><?php echo $this->libelleType; ?></span>
							<small><br/><?php echo nl2br($this->objetDossier) ?></small>
							<div style='margin:10px;' id='infosEtabs'></div>
						</h3>
						<ul id='onglets_horizontaux' class='grid_16' >
							<li class='<?php echo ( $this->action == "index" ) ? "selection_onglets_hor" : "read" ?>'>
								<a href='<?php echo $this->url(array("action"=>"index")) ?>'>Informations générales</a>
							</li>
							<li class='<?php echo ( $this->action == "docconsulte" ) ? "selection_onglets_hor" : "read" ?>'>
								<a href='<?php echo $this->url(array("action"=>"docconsulte")) ?>'>Documents consultés</a>
							</li>
							<li class='<?php echo ( $this->action == "prescription" ) ? "selection_onglets_hor" : "read" ?>'>
								<a href='<?php echo $this->url(array("action"=>"prescription")) ?>'>Prescriptions</a>
							</li>
							<li class='<?php echo ( $this->action == "liees" ) ? "selection_onglets_hor" : "read" ?>'>
								<a href='<?php echo $this->url(array("action"=>"liees")) ?>'>Établissements et dossiers liés</a>
							</li>
							<li class='<?php echo ( $this->action == "contact" ) ? "selection_onglets_hor" : "read" ?>' >
								<a href='<?php echo $this->url(array("action"=>"contact")) ?>'>Contacts</a>
							</li>
							<li class='<?php echo ( $this->action == "piece-jointe" ) ? "selection_onglets_hor" : "read" ?>' >
								<a style='border-right: none' href='<?php echo $this->url(array("action"=>"piece-jointe")) ?>'>Pièces jointes</a>
							</li>
						</ul>
					<?php endif ?>
					<!-- Contenu -->
					<div class='grid_16' >
					<?php
						echo "<input type='hidden' name='idDossier' id='idDossier' value='".$this->idDossier."' />";
						echo $this->layout()->content;
					?>
					</div>
				</div>
			</div>
		</div>
		<!-- Footer -->
		<?php $this->footer(); ?>
	</body>
</html>