<!doctype html>
<html lang="fr" >

    <?php echo $this->render("includes/header.phtml"); ?>

    <body>
    
        <div id='wrapper'>
			<div id='layout-content' >
			
				<?php echo $this->render("includes/nav-main.phtml"); ?>
				
				<div class='container_16' >
					<?php echo $this->layout()->content; ?>
				</div>
				
			</div>
		</div>
        
        <?php echo $this->render("includes/footer.phtml"); ?>

    </body>
    
</html>