<!doctype html>
<html lang="fr" >

    <?php echo $this->render("includes/header.phtml"); ?>

    <body>
    
        <div id='wrapper'>
			<div id='layout-content' >
			
				<?php echo $this->render("includes/nav-main.phtml"); ?>
				
				<div class='container_16' >
				
                    <!-- Titre -->
					<h2 class='grid_16' >
						<i class='sprite sprite-zoom' ></i>
						Recherche
					</h2>

                    <!-- Onglets permettant de selectionner les entités à rechercher -->
					<ul id='onglets_horizontaux' class='grid_16' >
						<li class='<?php echo ( $this->action == "etablissement" ) ? "selection_onglets_hor" : "read" ?>'><a href='<?php echo $this->url(array("action"=>"etablissement")) ?>'>Établissement</a></li>
						<li class='<?php echo ( $this->action == "dossier" ) ? "selection_onglets_hor" : "read" ?>'><a href='<?php echo $this->url(array("action"=>"dossier")) ?>'>Dossier</a></li>
						<li class='<?php echo ( $this->action == "utilisateur" ) ? "selection_onglets_hor" : "read" ?>'><a href='<?php echo $this->url(array("action"=>"utilisateur")) ?>'>Utilisateur</a></li>
					</ul>
						
                    <!-- Formulaire de recherche -->
                    <div class="grid_16">
                        <?php echo $this->layout()->content; ?>
                    </div>

                    <!-- Résultats -->
					<div id='content_resultats' class='grid_16' ></div>
                    
                    <hr class="clear" />
                    
                    <!-- Bouton lançant la recherche -->
					<p style="text-align: center">
						<button id='search' href="/search/run" >Rechercher</button>
						<span id='loader' class='ui-helper-hidden' ><img src='/images/load.gif' alt='Chargement' /></span>
					</p>

					<script type="text/javascript">

						$("#search").button({
							icons: {
								primary: "ui-icon-search"
							}
						});
                        
                        $("#search, div.paginationControl a").live("click", function() {
							$.ajax({
								url: $(this).attr("href"),
								data: $("#recherche").serialize(),
								beforeSend: function() {
                                    $('html, body').animate({ scrollTop: 0 }, 'slow');
									$("#loader").show();
									$("#search").hide();
									$("#content_resultats").css("opacity", 0.5);
								},
								success: function( result ) {
									$("#loader").hide();
									$("#search").show();
									$("#content_resultats").css("opacity", 1);
									$("#content_resultats").html( result["html"] );
                                    
                                    if($("form input[name='item']").val() == "etablissement") {
                                        if($("form input[name='par']:checked").val() == "criteres") {
                                            $("#content_resultats").find('li').removeClass("slide");
                                            $("#content_resultats").find('li').find("span.icone_enfants").remove();
                                        }
                                    }
                                    
                                    
								},
								error: function(r) {
									alert(r.responseText);
								}
							});
							
							return false;
						});
                        
                        $("#clear").live("click", function() {
							$("#content_resultats").empty();
							return false;
						});
						
					</script>

				</div>
				
			</div>
		</div>
        
        <?php echo $this->render("includes/footer.phtml"); ?>

    </body>
    
</html>