<!-- Titre -->
<h2>Dossiers</h2>

<a id="dossiers-ajout-dossier" class='btn actions-dispo' href='/dossier/add' >
    <i class="icon-plus"></i> Ajouter un dossier
</a>


<form method='get'>
        <p>Filtrer par : </p>
	<select name='types[]' multiple>
            <?php foreach( $this->DB_type as $type ) : ?>
                <option value='<?php echo $type["ID_DOSSIERTYPE"] ?>' <?php if(isset($_GET["types"]) && in_array($type["ID_DOSSIERTYPE"], (array) $_GET["types"])) echo 'selected' ?>><?php echo $type["LIBELLE_DOSSIERTYPE"] ?></option>
            <?php endforeach ?>
            <input type='submit' id="dossiers-filtrer" class="btn" value="Filtrer"  />
            <input type='hidden' name='page' value="1" />
	</select>

</form>

<hr/>

<?php if( count($this->results) > 0 ) : ?>
    <p class='muted'><small>Nombre total d'éléments : <?php echo $this->results->getTotalItemCount() ?></small></p>
    <ul class='recherche_liste unstyled'>
    <?php echo $this->partialLoop('search/results/dossier.phtml', $this->results ) ?>
    </ul>
    <br/>
    <div style='clear: both'></div>
    <?php echo $this->results ?>
<?php else : ?>
	<p class='muted'><small>Aucun résultat disponible.</small></p>
    <h2 style='color: silver; text-align: center;' ></h2>
<?php endif ?>

<script>
    $(document).ready(function() {

    	// Si le champ de recherche est vide, on empêche l'envoi d'une recherche
    	$("input[name='num_doc_urba']").focus().keyup(function() {$('input[type="submit"]').attr('disabled', $(this).val() == '')}).keyup();

			// Gestion des multiselects
			$("select[name='types[]']").multiselect({header: false, noneSelectedText: "Tous les types"});

      // Affichage des dossiers enfants
      $("ul.recherche_liste li.slide").live("click", function() {
          var container = this;
          if( $(this).hasClass("active") ) {
              $(this).next().slideUp(400, function() {$(container).next().remove()});
              $(this).toggleClass("active");
          }
          else {
              $(container).find(".load").show();
              $.getJSON("/api/1.0/search/dossiers", {parent: $(this).attr("id"), count: 100}, function(data) {
                  $(container).toggleClass("active").find(".load").hide();
                  $.post("/search/display-ajax-search", {items: 'dossier', data: data.response.results}, function(html) {
                      $(container).after("<li class='ui-helper-hidden' >" + html + "</li>").next().slideDown();
                  });
              });
          }
      });
	});
</script>