<h1>
    Aie !
    <small>Une erreur '<?php echo $this->message ?>' est survenue ...</small>
</h1>

<?php if (!$this->showException): ?>
<!--
<?php endif ?>
<div class="well">
    <h3>Exception information:</h3>
    <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?>
    </pre>

    <h3>Request Parameters:</h3>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
    </pre>
</div>
<?php if (!$this->showException): ?>
-->
<?php endif ?>
