<h1>
    Aie !
    <small>Une erreur '<?php echo $this->message ?>' est survenue ...</small>
</h1>

<p class="lead">
    <strong>Ne vous inquiétez pas, tout va bien se passer !</strong> 
    Nous avons été prévenus, nous nous engageons à corriger ce problème dans les plus brefs délais.
</p>

<?php if (!$this->showException): ?>
<!--
<?php endif ?>
<div class="well">
    <h3>Exception information:</h3>
    <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?>
    </pre>

    <h3>Request Parameters:</h3>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
    </pre>
</div>
<?php if (!$this->showException): ?>
-->
<?php endif ?>

<p class='text-center'>
    <a class='btn btn-default' href='/'>Revenir sur l'accueil</a>
</p>