<!-- Onglets permettant de selectionner les entités à rechercher -->
<h2 class="page-header">Courriers</h2>
<form method='get'>
    <div class='navbar-form form-search well well-small' style='margin-bottom: 5px;'>
        <div class="input-append">
            <input type="text" name='objet' class="span6 search-query" placeholder="Objet du courrier, de l'expéditeur, ..." value='<?php if(isset($_GET["objet"])) echo $_GET["objet"] ?>' />
            <input type='submit' class="btn" value="Rechercher dans Prevarisc"  />
            <input type='hidden' name='page' value="1" />
        </div>
    </div>
</form>

<hr/>

<?php if( count($this->results) > 0 ) : ?>
    <p class='muted'><small>Nombre total d'éléments : <?php echo $this->results->getTotalItemCount() ?></small></p>
    <ul class='recherche_liste unstyled'>
    <?php echo $this->partialLoop('search/results/dossier.phtml', $this->results ) ?>
    </ul>
    <br/>
    <div style='clear: both'></div>
    <?php echo $this->results ?>
<?php else : ?>
	<p class='muted'><small>Aucun résultat disponible.</small></p>
    <h2 style='color: silver; text-align: center;' ></h2>
<?php endif ?>

<script>
    $(document).ready(function() {

    	// Si le champ de recherche est vide, on empêche l'envoi d'une recherche
    	$("input[name='num_doc_urba']").focus().keyup(function() {$('input[type="submit"]').attr('disabled', $(this).val() == '')}).keyup();

			// Gestion des multiselects
			$("select[name='types[]']").multiselect({header: false, noneSelectedText: "Tous les types"});

      // Affichage des dossiers enfants
      $("ul.recherche_liste li.slide").live("click", function() {
          var container = this;
          if( $(this).hasClass("active") ) {
              $(this).next().slideUp(400, function() {$(container).next().remove()});
              $(this).toggleClass("active");
          }
          else {
              $(container).find(".load").show();
              $.post("/search/display-ajax-search-dossier", {parent: $(this).attr("id")}, function(html) {
                  $(container).toggleClass("active").find(".load").hide();
                  $(container).after("<li class='ui-helper-hidden' style='overflow: auto; height: auto;' >" + html + "</li>").next().slideDown();
              });
          }
      });
	});
</script>
