<!-- Formulaire -->
<form id='recherche' method='get' action='' >
	
	<!-- Nature -->
	<select id='nature' name='ID_DOSSIERNATURE[]' multiple='multiple'>
		<?php foreach( $this->DB_nature as $nature ) : ?>
		<option value='<?php echo $nature["ID_DOSSIERNATURE"] ?>'><?php echo $nature["LIBELLE_DOSSIERNATURE"] ?></option>
		<?php endforeach ?>
	</select>
	
	<!-- Numéro de doc urba.-->
	<input type='text' id='docurba' name='NUM_DOCURBA' class='bigger' size=32 />

    <input type="hidden" name="format" value="json" />
    <input type="hidden" name="item" value="dossier" />
	
</form>

<script type="text/javascript">
	
	$("#nature").multiselect({
		header: false,
		noneSelectedText: "Nature du dossier",
		selectedList: 1,
		height: "auto",
		minWidth: 150
	});
	
	$("#commune").toggleText("Commune");
	$("#docurba").toggleText("Numéro de document d'urbanisme");
	$("#libelle").toggleText("Libellé de l'établissement");
	
	$("#commune").autocomplete("/adresse/get?format=json", {
		minChars: 3,
		max: 100,
		parse: function(data) {
			return $.map(data["resultats"], function(row) {
				return {
					data: row,
					value: row.LIBELLE_COMMUNE,
					result: row.LIBELLE_COMMUNE
				}
			});
		},
		formatItem: function(item) {
			return item.LIBELLE_COMMUNE;
		}
	}).result(function(e, item) {
	});
	
	$("#libelle").autocomplete("/etablissement/get?format=json", {
		minChars: 3,
		max: 100,
		parse: function(data) {
			return $.map(data["resultats"], function(row) {
				return {
					data: row,
					value: row.LIBELLE_ETABLISSEMENTINFORMATIONS,
					result: row.LIBELLE_ETABLISSEMENTINFORMATIONS
				}
			});
		},
		formatItem: function(item) {
			return item.LIBELLE_ETABLISSEMENTINFORMATIONS;
		}
	}).result(function(e, item) {
	});
	
</script>