<!-- Onglets permettant de selectionner les entités à rechercher -->
<h2 class="page-header">Etablissements</h2>
<form method='get'>

	<div class='navbar-form form-search well well-small' style='margin-bottom: 5px;'>
            <div class="input-append pull-left">
                <input type="text" name='label' class="input-xlarge search-query" placeholder="Libellé de l'établissement ou son #ID ..." value="<?php if(isset($_GET["label"])) echo htmlentities($_GET["label"]) ?>" />
                <input type='submit' class="btn btn_search" value="Rechercher" disabled />
                <input type='hidden' name='page' value="1" />
            </div>

            <div class="pull-left" style='margin: 9px 0 0 5px'>
                <small>
                    <a href="/search/etablissement?label=&page=1">
                        Réinitialiser
                    </a>
                </small>
            </div>

	    <p class='pull-right' style='margin: 9px 0 0 5px'>
                <small>
                    Zone de recherche :
                    <a href='#' id="zone_de_recherche_edit">
                        <strong class='zone_de_recherche_text'>
                            <?php echo array_key_exists('zone_de_recherche_text', $_GET) && $_GET['zone_de_recherche_text'] != '' ? $_GET['zone_de_recherche_text'] : 'Département' ?>
                        </strong>
                    </a>
                    <a href='#' id="zone_de_recherche_reset"><i class="icon-remove"></i></a>
                    <input type='hidden' name='zone_de_recherche_text' value="<?php if(array_key_exists('zone_de_recherche_text', $_GET)) echo $_GET['zone_de_recherche_text'] ?>" />
                    <input type='hidden' name='city' value="<?php if(array_key_exists('city', $_GET)) echo $_GET['city'] ?>" />
                    <input type='hidden' name='street' value="<?php if(array_key_exists('street', $_GET)) echo $_GET['street'] ?>" />
	        </small>
	    </p>
	</div>

        <div id="filterContainer" class="well span12" style="margin-left: 0;">
            <div>
                <select name='statuts[]' multiple>
                    <?php foreach( $this->DB_statut as $statut ) : ?>
                            <option value='<?php echo $statut["ID_STATUT"] ?>' <?php if(isset($_GET["statuts"]) && in_array($statut["ID_STATUT"], (array) $_GET["statuts"])) echo 'selected' ?>><?php echo $statut["LIBELLE_STATUT"] ?></option>
                    <?php endforeach ?>
                </select>

                <select name='presences_local_sommeil[]' multiple>
                    <option value='true' <?php if(isset($_GET["presences_local_sommeil"]) && in_array('true', (array) $_GET["presences_local_sommeil"])) echo 'selected' ?>>Avec</option>
                    <option value='false' <?php if(isset($_GET["presences_local_sommeil"]) && in_array('false', (array) $_GET["presences_local_sommeil"])) echo 'selected' ?>>Sans</option>
                </select>

                <select name='avis[]' multiple>
                    <option value='true' <?php if(isset($_GET["avis"]) && in_array('true', (array) $_GET["avis"])) echo 'selected' ?>>Favorable</option>
                    <option value='false' <?php if(isset($_GET["avis"]) && in_array('false', (array) $_GET["avis"])) echo 'selected' ?>>Défavorable</option>
                </select>
        </div>

        <div id='criteres_plus' style='margin-top: 4px'>
            <select name='genres[]' multiple>
            <?php foreach( $this->DB_genre as $genre ) : ?>
                    <option value='<?php echo $genre["ID_GENRE"] ?>' <?php if(array_key_exists('genres', $_GET) && in_array($genre["ID_GENRE"], (array) $_GET["genres"])) echo 'selected' ?>><?php echo $genre["LIBELLE_GENRE"] ?></option>
            <?php endforeach ?>
            </select>

            <span id='categorie_span' class='hide'>
                    <select name='categories[]' multiple>
                            <?php foreach( $this->DB_categorie as $categorie ) : ?>
                    <option value='<?php echo $categorie["ID_CATEGORIE"] ?>' <?php if(array_key_exists('categories', $_GET) && in_array($categorie["ID_CATEGORIE"], (array) $_GET["categories"])) echo 'selected' ?>><?php echo $categorie["LIBELLE_CATEGORIE"] ?></option>
                    <?php endforeach ?>
                    </select>
            </span>

            <span id='classe_span' class='hide' >
                <select name='classes[]' multiple>
                    <?php foreach( $this->DB_classe as $classe ) : ?>
                        <option value='<?php echo $classe["ID_CLASSE"] ?>' <?php if(array_key_exists('classes', $_GET) && in_array($classe["ID_CLASSE"], (array) $_GET["classes"])) echo 'selected' ?>><?php echo $classe["LIBELLE_CLASSE"] ?></option>
                    <?php endforeach ?>
                </select>
            </span>

            <span id='famille_span' class='hide'>
                <select name='familles[]' multiple>
                    <?php foreach( $this->DB_famille as $famille ) : ?>
                                <option value='<?php echo $famille["ID_FAMILLE"] ?>' <?php if(array_key_exists('familles', $_GET) && in_array($famille["ID_FAMILLE"], (array) $_GET["familles"])) echo 'selected' ?>><?php echo $famille["LIBELLE_FAMILLE"] ?></option>
                    <?php endforeach ?>
                </select>
            </span>

            <span id='type_span' class='hide'>
                <select name='types_activites[]' multiple>
                    <?php foreach( $this->DB_typeactivite as $type ) : ?>
						<optgroup label="<?php echo $type["LIBELLE_TYPE"] ?>">
	                        <option value='<?php echo $type["ID_TYPEACTIVITE"] ?>' <?php if(array_key_exists('types_activites', $_GET) && in_array($type["ID_TYPEACTIVITE"], (array) $_GET["types_activites"])) echo 'selected' ?>><?php echo $type["LIBELLE_TYPE"] . ' - ' . $type["LIBELLE_ACTIVITE"] ?></option>
						</optgroup>
                    <?php endforeach ?>
                </select>
            </span>
        </div>
    </div>
</form>

<hr/>

<?php if( count($this->results) > 0 ) : ?>
    <p class='muted'><small>Nombre total d'éléments : <?php echo $this->results->getTotalItemCount() ?></small></p>
    <ul class='recherche_liste unstyled'>
    <?php echo $this->partialLoop('search/results/etablissement.phtml', $this->results ) ?>
    </ul>
    <br/>
    <div style='clear: both'></div>
    <?php echo $this->results ?>
<?php else : ?>
	<p class='muted'><small>Aucun résultat disponible.</small></p>
    <h2 style='color: silver; text-align: center;' ></h2>
<?php endif ?>

<!-- Boite modale de la zone de recherche -->
<form id='zone_de_recherche_modal' class="modal hide adresse">

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Définir la zone de recherche</h3>
    </div>

    <div class="modal-body">
        <dl class='dl-horizontal'>
            <dt>Ville</dt>
            <dd>
                <input name='commune_ac' type='text' placeholder='Nom de la commune ou code postal ...' />
                <input name='code_insee' type='hidden' />
            </dd>

            <dt>Voie</dt>
            <dd>
                <input type='text' name='voie_ac' placeholder='Nom de la voie ...' disabled />
                <input type='hidden' name='voie' />
            </dd>
        </dl>
    </div>

    <div class="modal-footer">
        <a href="#" data-dismiss="modal" class="btn">Annuler</a>
        <a class='submit btn btn-success' >Définir la zone de recherche</a>
    </div>
</form>

<script>
    $(document).ready(function() {

    	// Si le champ de recherche est vide, on empêche l'envoi d'une recherche
    	// $("input[name='label']").focus().keyup(function() {$('input[type="submit"]').attr('disabled', $(this).val() == '')}).keyup();
    	$("input[name='label']").focus();
    	$('input[type="submit"]').attr('disabled', false);

    	// Gestion des multiselects
    	$("select[name='statuts[]']").multiselect({header: false, noneSelectedText: "Tous les statuts"});
		$("select[name='genres[]']").multiselect({header: false, noneSelectedText: "Tous les genres"});
		$("select[name='categories[]']").multiselect({header: false, noneSelectedText: "Toutes les catégories"});
		$("select[name='classes[]']").multiselect({header: false, noneSelectedText: "Toutes les classes"});
		$("select[name='familles[]']").multiselect({header: false, noneSelectedText: "Toutes les familles"});
		$("select[name='types_activites[]']").multiselect({header: false, noneSelectedText: "Tous les types d'activités"});
		$("select[name='avis[]']").multiselect({header: false, noneSelectedText: "Tous les avis"});
		$("select[name='presences_local_sommeil[]']").multiselect({header: false, noneSelectedText: "Qu'importe la présence de local à sommeil", minWidth: 300});

		// Fonction d'affichage des critères en fonction du genre
		function display_criteres_by_genres() {
			$("#categorie_span, #classe_span, #famille_span, #type_span").hide();
			var array = $("select[name='genres[]']").multiselect("getChecked").each(function() {
				switch(this.value) {
					case '2' : $("#type_span, #categorie_span").show(); break;
					case '3' : $("#type_span, #categorie_span").show(); break;
					case '4' : $("#famille_span").show(); break;
					case '5' : $("#classe_span").show(); break;
				}
			});
		}

		// Affichage des critères en fonction du genre
		$("select[name='genres[]']").bind("multiselectclick", function() {display_criteres_by_genres()});
		display_criteres_by_genres();

		// Slide des établissements enfants contenant d'autres établissements
		$("ul.recherche_liste li.slide").live("click", function() {
			if($(this).is('a')) {
				return;
			}
			var container = this;
			if( $(this).hasClass("active") ) {
				$(this).next().slideUp(400, function() {$(container).next().remove()});
				$(this).toggleClass("active");
			}
			else {
				$(container).find(".load").show();
				$.post("/search/display-ajax-search-etablissement", {parent: $(this).attr("id")}, function(html) {
					$(container).toggleClass("active").find(".load").hide();
					$(container).after("<li class='ui-helper-hidden' style='overflow: auto; height: auto;' >" + html + "</li>").next().slideDown();
				});
			}
		});
        $('#zone_de_recherche_edit').click(function(e){
            e.preventDefault();
            $('#zone_de_recherche_modal').modal();
        });

         $('#zone_de_recherche_reset').click(function(e){
            e.preventDefault();
            $("input[name='zone_de_recherche_text']").val("Département");
            $(".zone_de_recherche_text").text("Département");

            $("input[name='city']").val("");
            $("input[name='street']").val("");
        });


		// Auto complétion de la ville
        $("form#zone_de_recherche_modal input[name='commune_ac']").autocomplete("/api/1.0/adresse/get_communes", {
            minChars: 2,
            cacheLength: 0,
            parse: function(data) {
                return $.map(data["response"], function(row) {return {data: row,value: row.LIBELLE_COMMUNE,result: row.LIBELLE_COMMUNE}});
            },
            formatItem: function(item) {
                return item.LIBELLE_COMMUNE + " (" + item.NUMINSEE_COMMUNE + ")";
            }
        }).result(function(e, item) {
            $("input[name='code_insee']").val( item.NUMINSEE_COMMUNE );
            $("input[name='voie_ac']").removeAttr('disabled');
        }).click(function() {
            $(this).val("");
            $("input[name='voie_ac']").val("").attr("disabled", true).blur();
            $("input[name='voie']").val("").blur();
        });

        // Auto complétion de la rue
        $("form#zone_de_recherche_modal input[name='voie_ac']").autocomplete('/api/1.0/adresse/get_voies', {
            minChars: 2,
            cacheLength: 0,
            extraParams: { code_insee: function(){ return $("input[name='code_insee']").val() } },
            parse: function(data) {
                return $.map(data["response"], function(row) { return {data: row,value: row.LIBELLE_RUE,result: row.LIBELLE_RUE} });
            },
            formatItem: function(item) {
                return item.LIBELLE_RUE;
            }
        }).result(function(e, item) {
            $("input[name='voie']").val( item.ID_RUE );
        }).click(function() {
            $(this).val("");
        });

        // Validation de la zone de recherche
        $('form#zone_de_recherche_modal a.submit').click(function() {
            var text = 'Département';

            if($("input[name='code_insee']").val() != '') {
                    var text = $("input[name='commune_ac']").val();
                    if($("input[name='voie_ac']").val() != '') {
                            var text = $("input[name='commune_ac']").val() + ', ' + $("input[name='voie_ac']").val();
                    }
            }
            $("input[name='zone_de_recherche_text']").val(text);
            $(".zone_de_recherche_text").text(text);

            $("input[name='city']").val($("input[name='code_insee']").val());
            $("input[name='street']").val($("input[name='voie']").val());
            $('form#zone_de_recherche_modal').modal('hide');
        });
	});
</script>
