<?php if($this->pageCount) : ?>

    <div class="pagination pagination-centered" >
        <ul>
            <?php if (isset($this->previous)): ?>
            <li><a href="<?php echo $this->url() . '?' . http_build_query(array_merge($_GET, array("page" => $this->previous))); ?>">&laquo;</a></li>
            <?php else: ?>
            <li class="disabled"><a href="#">&laquo;</a></li>
            <?php endif; ?>

            <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
            <li ><a href="<?php echo $this->url() . '?' . http_build_query(array_merge($_GET, array("page" => $page))); ?>"><?php echo $page; ?></a></li>
            <?php else: ?>
            <li class="disabled"><a href='#'><?php echo $page; ?></a></li>
            <?php endif; ?>
            <?php endforeach; ?>

            <?php if (isset($this->next)): ?>
            <li><a href="<?php echo $this->url() . '?' . http_build_query(array_merge($_GET, array("page" => $this->next))); ?>">»</a></li>
            <?php else: ?>
            <li class="disabled"><a href="#">»</a></li>
            <?php endif; ?>
        </ul>
    </div>

<?php endif ?>