<?php if( count($this->paginator) > 0 ) : ?>
    <p><strong>Nombre total d'éléments : <?php echo $this->paginator->getTotalItemCount() ?></strong> (<a href="" id="clear" >&times; Annuler la recherche</a>)</p>
    <div style="clear: both"></div>
    <?php if($this->item == "etablissement") : ?>
        <ul class='recherche_liste unstyled'>
            <?php echo $this->partialLoop('search/results/etablissement.phtml', $this->paginator ) ?>
        </ul>
    <?php elseif($this->item == "dossier") : ?>
        <ul id="liste_doss" class='unstyled'>
            <?php echo $this->partialLoop('search/results/dossier.phtml', $this->paginator ) ?>
        </ul>
    <?php else : ?>
        <?php echo $this->partialLoop('user/user_medium.phtml', $this->paginator ) ?>
    <?php endif ?>
    <br/>
    <div style='clear: both'></div>
    <?php echo $this->paginator ?>
<?php else : ?>
    <h2 style='color: silver; text-align: center;' >Aucun résultat disponible.</h2>
<?php endif ?>