<?php if( count($this->paginator) > 0 ) : ?>
    <p><strong>Nombre total d'éléments : <?php echo $this->paginator->getTotalItemCount() ?></strong></p>
    <?php if($this->item == "etablissement") : ?>
        <ul class='recherche_liste'>
            <?php echo $this->partialLoop('search/results/etablissement.phtml', $this->paginator ) ?>
        </ul>
    <?php elseif($this->item == "dossier") : ?>
        <ul id="liste_doss">
            <?php echo $this->partialLoop('search/results/dossier.phtml', $this->paginator ) ?>
        </ul>
    <?php else : ?>
        <?php echo $this->partialLoop('user/user_medium.phtml', $this->paginator ) ?>
    <?php endif ?>
    <br/>
    <?php echo $this->paginator ?>
<?php else : ?>
    <hr class='clear' />
    <h2 class='grid_16 alpha' style='color: silver; text-align: center;' >Aucun résultat disponible.</h2>
<?php endif ?>