<!-- Formulaire -->
<form id='recherche' method='get' action='' >
	
	<!-- Nom -->
	<input type='text' id='nom' name='NOM_PRENOM' class='bigger' style="width: 100%; padding: 8px; font-size: 1.5em;" />
    
    <div id="plus_critere_div">
	
        <div class="well text-center">
            <!-- Fonction -->
            <select id='fonction' name='ID_FONCTION[]' multiple='multiple'>
                <?php foreach( $this->DB_fonction as $fonction ) : ?>
                <option value='<?php echo $fonction["ID_FONCTION"] ?>'><?php echo $fonction["LIBELLE_FONCTION"] ?></option>
                <?php endforeach ?>
            </select>
        </div>
        
    </div>
    
    <input type="hidden" name="format" value="json" />
    <input type="hidden" name="item" value="utilisateur" />
	
</form>

<script type="text/javascript">

	$("#nom").toggleText("Nom de l'utilisateur");
	
	$("#fonction").multiselect({
		header: false,
		noneSelectedText: "Fonction de l'utilisateur",
		selectedList: 1,
		height: "auto",
		minWidth: 175
	});
	
</script>