<div class='push_2 grid_12'>

	<!-- En tête-->
	<div>

		<!-- Boutons -->
		<div float='right'>
			<p id='notification_erreur' class='ui-state-error ui-helper-hidden' style='padding: .5em; margin-bottom: 1em; margin-right: 1em; float: left; '>
				L'enregistrement ne s'est pas effectué correctement.
			</p>
			<?php if(!isset($_GET["ajax"]) && !$this->ldap) : ?><button id='cancel' >Retour</button> <?php endif ?>
			<button id='submit' class="save">Sauvegarder</button>
		</div>

		<!-- Titre -->
		<h2>
			<i class='sprite sprite-user_edit' ></i>
			<?php echo $this->title ?>
		</h2>
	
	</div>
	
	<?php if($this->ldap) : ?>
	<div class='ui-state-highlight' style='padding: 0.5em; margin-bottom: 10px; ' >
		<strong>Bienvenue sur Prevarisc !</strong> Veuillez compléter votre profil pour pouvoir profiter pleinement des fonctionnalités du logiciel.
	</div>
	<?php endif ?>
	
	<!-- Formulaire -->
	<div class='fiche_contact' style="min-width: 600px" >

		<h4>Informations de connexion</h4>
		<!-- Avatar -->
		<?php if( $this->user ) : ?>
		<dl>
			<dt><?php $this->avatar($this->user["ID_UTILISATEUR"], "small") ?></dt>
			<dd style='padding-bottom: 25px'><a href='' id='change_avatar' >Modifier l'image de profil</a></dd>
		</dl>
		<?php endif ?>
		
		<!-- Login et mdp -->
		<form id='info_co' >
			<dl>
				<dt>Login</dt>
				<dd><input name='USERNAME_UTILISATEUR' value='<?php if(isset($this->user["USERNAME_UTILISATEUR"])) echo $this->user["USERNAME_UTILISATEUR"] ?>' type='text' /></dd>
				
				<dt>Mot de passe (à remplir 2 fois)</dt>
				<dd>
					<?php if( $this->user ) : ?>
						<input style='display: none' name='PASSWD_INPUT' type='password' disabled value='<?php echo $this->user["PASSWD_UTILISATEUR"] ?>' />
						<input style='display: none' name='PASSWD_INPUT_VERIF' type='password' disabled value='<?php echo $this->user["PASSWD_UTILISATEUR"] ?>' />
						<a href='' id='change_passwd' >Changer votre mot de passe</a>
						<?php if($this->params["LDAP_ACTIF"]) : ?> Connexion via le LDAP ? <input type='checkbox' id='ldap2_checkbox' name="ldap_checkbox" value='1' <?php if($this->user["PASSWD_UTILISATEUR"] == "") echo "checked"?> /><?php endif ?>
					<?php else : ?>
						<input name='PASSWD_INPUT' type='password' />
						<input name='PASSWD_INPUT_VERIF' type='password' />
						<?php if($this->params["LDAP_ACTIF"]) : ?> Connexion via le LDAP ? <input type='checkbox' id='ldap_checkbox' name="ldap_checkbox" value='1' /> <?php endif ?>
					<?php endif ?>
				</dd>
			</dl>
		</form>
		
		<hr class='clear' />
		
		<?php if($this->maire == false) : ?>
			<!-- Infos complémentaires -->
			<h4>Informations de l'utilisateur</h4>
			<?php echo $this->action('form', 'contact', null, array("item" => "user")) ?>
			
			<?php if(!isset($this->droitsSYS) || $this->droitsSYS == 1) : ?>
			<hr class='clear' />
			
			<h4>Domaines de compétences</h4>
			<form id="competences">
			<dl>
				<dt>Commune</dt>
				<dd>
					<input type='text' id='commune' size=25 value='<?php if(isset($this->commune)) echo $this->commune->LIBELLE_COMMUNE ?>' />
					<input type='hidden' name='NUMINSEE_COMMUNE' value='<?php if(isset($this->user["NUMINSEE_COMMUNE"])) echo $this->user["NUMINSEE_COMMUNE"] ?>' />
				</dd>
				
				<dt>Commissions</dt>
				<dd>
					<select id="commission">
						<option value="null">Ajouter une commission ..</option>
						<?php foreach($this->rowset_commissions as $commission) : ?>
						<option value="<?php echo $commission->ID_COMMISSION ?>"><?php echo $commission->LIBELLE_COMMISSION ?></option>
						<?php endforeach ?>
					</select>
					<br /><br />
					<div class='content'>
						<?php if(count($this->rowset_commissionsUser)>0) : ?>
						<?php foreach($this->rowset_commissionsUser as $commission) : ?>
						<span class='ui-state-highlight' style='padding: 2px; margin: 0pt 2px 1em 0pt; display: inline-block;'><input type='hidden' name='commissions[<?php echo $commission->ID_COMMISSION ?>]' value='<?php echo $commission->ID_COMMISSION ?>' /><?php echo $commission->LIBELLE_COMMISSION ?><a href='' onclick='$(this).parent().remove(); return false;'>&times;</a></span>
						<?php endforeach ?>
						<?php endif ?>
					</div>
				</dd>
				
				<dt>Groupements de communes</dt>
				<dd>
					<select id="groupement">
						<option value="null">Ajouter un groupement ..</option>
						<?php foreach($this->rowset_groupements as $groupement) : ?>
						<option value="<?php echo $groupement->ID_GROUPEMENT ?>"><?php echo $groupement->LIBELLE_GROUPEMENT ?></option>
						<?php endforeach ?>
					</select>
					<br /><br />
					<div class='content'>
						<?php if(count($this->rowset_groupementsUser)>0) : ?>
						<?php foreach($this->rowset_groupementsUser as $groupement) : ?>
						<span class='ui-state-highlight' style='padding: 2px; margin: 0pt 2px 1em 0pt; display: inline-block;'><input type='hidden' name='groupements[<?php echo $groupement->ID_GROUPEMENT ?>]' value='<?php echo $groupement->ID_GROUPEMENT ?>' /><?php echo $groupement->LIBELLE_GROUPEMENT ?><a href='' onclick='$(this).parent().remove(); return false;'>&times;</a></span>
						<?php endforeach ?>
						<?php endif ?>
					</div>
				</dd>
			</dl>
			<?php endif ?>
			
			<hr class='clear' />
			
			<!-- Informations de la fonction -->
			<div id="info_plus">
				<h4>Informations particulières</h4>
				<form id="fonction_prev">
					<dl>
						<dt>Date brevet PRV2</dt>
						<dd>
							<input type='text' class='date' name='DATE_PRV2' value='<?php echo $this->user_info["DATE_PRV2"] == "0000-00-00 00:00:00" ? "00/00/0000" : date("d/m/Y", strtotime($this->user_info["DATE_PRV2"])) ?>' size=7 style='text-align: center' readonly />
							<input type="checkbox" name="disable_date" <?php if($this->user_info["DATE_PRV2"] == "0000-00-00 00:00:00") echo "checked='checked'"; ?> /> Pas de date
						</dd>
						
						<dt>Date Recyclage</dt>
						<dd>
							<input type='text' class='date' name='DATE_RECYCLAGE' value='<?php echo $this->user_info["DATE_RECYCLAGE"] == "0000-00-00 00:00:00" ? "00/00/0000" : date("d/m/Y", strtotime($this->user_info["DATE_RECYCLAGE"])) ?>' size=7 style='text-align: center' readonly />
							<input type="checkbox" name="disable_date" <?php if($this->user_info["DATE_RECYCLAGE"] == "0000-00-00 00:00:00") echo "checked='checked'"; ?> /> Pas de date
						</dd>
						
						<dt>Date SID</dt>
						<dd>
							<input type='text' class='date' name='DATE_SID' value='<?php echo $this->user_info["DATE_SID"] == "0000-00-00 00:00:00" ? "00/00/0000" : date("d/m/Y", strtotime($this->user_info["DATE_SID"])) ?>' size=7 style='text-align: center' readonly />
							<input type="checkbox" name="disable_date" <?php if($this->user_info["DATE_SID"] == "0000-00-00 00:00:00") echo "checked='checked'"; ?> /> Pas de date
						</dd>
					</dl>
				</form>
			</div>
		<?php else : ?>
			<h4>Mairie concernée</h4>
			<form id="competences">
			<dl>
				<dt>Commune</dt>
				<dd>
					<input type='text' id='commune' size=25 value='<?php if(isset($this->commune)) echo $this->commune->LIBELLE_COMMUNE ?>' />
					<input type='hidden' name='NUMINSEE_COMMUNE' value='<?php if(isset($this->NUMINSEE_COMMUNE)) echo $this->NUMINSEE_COMMUNE ?>' />
					<input type='hidden' name='maire' value='1' />
				</dd>
			</dl>
			</form>
			<div id="commune_du_maire"></div>
		<?php endif ?>
	
	</div>

</div>

<!-- Dialogue -->
<div id='edit-avatar' >

	<form id='avatar' action='/user/edit-avatar' enctype='multipart/form-data' method='post' target='iframe' >
	
		<iframe float='left' id='iframe' name="iframe" marginheight="0" marginwidth="0" width="150" src="/user/edit-avatar?id=<?php if(isset($this->user["ID_UTILISATEUR"])) echo $this->user["ID_UTILISATEUR"] ?>"></iframe>
		
		<div float='right' id='edit-avatar-right' style='width: 415px; text-align: center;' >
		
			<h3>Modifier l'image de profil</h3>
		
			<div id='edit-avatar-form'>
				<p><input id='edit-avatar-file' type='file' name='AVATAR' /></p>
			</div>
			
			<div id='load' class='ui-helper-hidden' ><img src='/images/bar.gif' alt='Upload en cours' /></div>
			
			<p id='notification_sauvegarde' class='ui-state-highlight ui-helper-hidden' style='padding: .5em; margin-bottom: 1em; '>
				Votre nouvelle image de profil a bien été sauvegardée. Si vous ne la voyez pas, rechargez le cache de votre navigateur (CTRL + F5). Cette fenêtre se fermera automatiquement dans quelques secondes.
			</p>
		
		</div>
		
		<input type='hidden' name='id' value='<?php if(isset($this->user["ID_UTILISATEUR"])) echo $this->user["ID_UTILISATEUR"] ?>' />
		
	</form>

</div>

<script type="text/javascript">

	$("#commission").change(function() {
		if($(this).val() != "null") {
			$(this).parent().find(".content").append("<span class='ui-state-highlight' style='padding: 2px; margin: 0pt 2px 1em 0pt; display: inline-block;'><input type='hidden' name='commissions["+$(this).find("option:selected").val()+"]' value='"+$(this).find("option:selected").val()+"' />"+$(this).find("option:selected").text()+"<a href='' onclick='$(this).parent().remove(); return false;'>&times;</a></span>");
			$(this).find("option:selected").remove();
			$(this).find("option[value=null]").attr("selected", "selected");
		}
	});
	
	$("#groupement").change(function() {
		if($(this).val() != "null") {
			$(this).parent().find(".content").append("<span class='ui-state-highlight' style='padding: 2px; margin: 0pt 2px 1em 0pt; display: inline-block;'><input type='hidden' name='groupements["+$(this).find("option:selected").val()+"]' value='"+$(this).find("option:selected").val()+"' />"+$(this).find("option:selected").text()+"<a href='' onclick='$(this).parent().remove(); return false;'>&times;</a></span>");
			$(this).find("option:selected").remove();
			$(this).find("option[value=null]").attr("selected", "selected");
		}
	});

	$('#edit-avatar').dialog({
		title: "Modifier l'image de profil",
		resizable: false,
		draggable: false,
		autoOpen: false,
		width: 600,
		zIndex: 9999,
		modal: true
	});
	
	$("#commune").autocomplete("/adresse/get?format=json", {
		minChars: 3,
		max: 100,
		parse: function(data) {
			return $.map(data["resultats"], function(row) {
				return {
					data: row,
					value: row.LIBELLE_COMMUNE,
					result: row.LIBELLE_COMMUNE
				}
			});
		},
		formatItem: function(item) {
			return item.LIBELLE_COMMUNE;
		}
	}).result(function(e, item) {
		$("input[name=NUMINSEE_COMMUNE]").val(item.NUMINSEE_COMMUNE);
		
		<?php if($this->maire == true) : ?>
		$("#commune_du_maire").load("/gestion-des-communes/display", {
			"numinsee": item.NUMINSEE_COMMUNE,
			"ext": true
		});
		<?php endif ?>
	});
	
	$("#commune").click(function() {
		$(this).val("");
		$(this).next().val("");
		
		<?php if($this->maire == true) : ?>
		$("#commune_du_maire").empty();
		<?php endif ?>
	});
	
	$("input[name=disable_date]").live("change", function() {

		if($(this).attr("checked")) {
			$(this).prev().val("00/00/0000").attr("disabled", "disabled");
		}
		else {
			$(this).prev().attr("disabled", null).show();
		}
	}).change();
	
	$('#change_avatar').click(function() {
	
		$('#edit-avatar').dialog('open');
		
		var height = document.getElementById('iframe').contentWindow.document.body.scrollHeight;
		
		$('#iframe').height( height + 'px');
		$("#edit-avatar-right").css("margin-top", (height / 2) - 50 );
		$('#edit-avatar').dialog({height: height + 34});
		$('#edit-avatar').dialog('close');
		$('#edit-avatar').dialog('open');
		
		return false;
	});

	$("#edit-avatar-file").change(function() {

		$('#avatar').submit();
		$("#edit-avatar-form").hide();
		$("#load").show();
		
	});
	
	function callback() {
	
		<?php if(isset($_GET["ajax"])) : ?>
			window.location.reload(true);
		<?php else : ?>
			window.location.replace("<?php echo $this->url() . (isset($_GET["ref"]) ? "?ref=" . $_GET["ref"] : "" ) ?>");
		<?php endif ?>
	}

	$("#cancel").button({
		icons: { primary: "ui-icon-triangle-1-w" }
	}).click(function() {
		<?php if(isset($_GET["ref"]) ) : ?>
			window.location = "/user/profile?uid=<?php echo $_GET["ref"] ?>";
		<?php else : ?>
			window.location = "/user";
		<?php endif ?>
		
	});
	
	$("#submit").button({
		icons: { primary: "ui-icon-disk" }
	}).click(function() {
		
		$("input.date").attr("disabled", null);

		if($("input[name=PASSWD_INPUT]").val() != $("input[name=PASSWD_INPUT_VERIF]").val() && !$("#ldap2_checkbox").attr("checked"))
			alert("Les mots de passe ne correspondent pas");
		else {
			$.ajax({
				url: '<?php echo $this->url(array("action" => "process")) ?>',
				type: "POST",
				data: $("#info_co").serialize() + "&" + $("#formulaire_contact").serialize() + "&format=json&" + $("#info_plus form:visible").serialize() + "&" + $("#competences").serialize(),
				success: function() {
				
					<?php if($this->ldap) : ?>
						window.location = "/";
					<?php elseif(isset($_GET["ref"]) ) : ?>
						window.location = "/user/profile?uid=<?php echo $_GET["ref"] ?>";
					<?php else : ?>
						window.location = "/user?confirm=1";
					<?php endif ?>
				},
				error: function(xhr, ajaxOptions, thrownError) {
					
					$("#notification_erreur").show();
					setTimeout( function() { $("#notification_erreur").fadeOut(); }, 2500);
				}
			});
		}
	});
	
	$("#change_passwd").click(function() {
		$("input[name='PASSWD_INPUT'], input[name=PASSWD_INPUT_VERIF]").val("").attr("disabled", false).show();
		$("input[name='PASSWD_INPUT']").focus();
		$(this).hide();
		return false;
	});
	
	$("#ldap_checkbox").click(function() {
		if($(this).attr("checked")) {
			$("input[name='PASSWD_INPUT'], input[name=PASSWD_INPUT_VERIF]").val("").attr("disabled", false).hide();
		}
		else {
			$("input[name='PASSWD_INPUT'], input[name=PASSWD_INPUT_VERIF]").val("").attr("disabled", false).show();
			$("input[name='PASSWD_INPUT']").focus();
		}
	});
	
	$("#ldap2_checkbox").change(function() {
		if($(this).attr("checked")) {
			$("input[name='PASSWD_INPUT'], input[name=PASSWD_INPUT_VERIF]").val("").attr("disabled", false).hide();
			$("#change_passwd").hide();
		}
		else {
			$("#change_passwd").show();
			if($("input[name='PASSWD_INPUT'], input[name=PASSWD_INPUT_VERIF]").val() == "") {
				$("#change_passwd").click();
			}
		}
	}).change();
	
	$('.date').live('click', function() {
		$(this).datepicker({showOn:'focus', dateFormat: 'dd/mm/yy', firstDay: 1}).focus();
	});
	
	$("select[name=ID_FONCTION]").change(function() {

		switch($(this).find("option:selected").val()) {
			case "13":
				$("#info_plus, #info_plus form#fonction_prev").show();
				break;
				
			default:
				$("#info_plus").hide();
				break;
		}
	}).change();

</script>