<div id='user-login'>

	<div id='user-login-content'>
	
		<!-- Logo prevarisc -->
		<p id='user-login-content-logo'>
			<img src='/images/logo_prevarisc_big.jpg' alt='Prevarisc' />
		</p>
		
		<!-- Formulaire de connexion -->
		<div id='user-login-content-box' class='ui-widget-shadow ui-helper-hidden' >
			<form id='user-login-content-form' action='/user/login' method='post' class="ui-widget ui-widget-content ui-corner-all" >

				<p>
					<label>Login</label>
					<input type='text' name='username' />

					<label>Mot de passe</label>
					<input type='password' name='passwd' />
				
					<span id='user-login-content-form-connexion' >
						<input id='login_button' value='Connexion' type='submit' />
						<img src='/images/load.gif' alt='Chargement' />
					</span>
					
				</p>
				
			</form>
		</div>
		
	</div>
	
	<hr class='clear' />
	
	<!-- Affichage des erreurs -->
	<p class="user-login-errors ui-widget ui-state-error <?php if(!$this->error) echo "ui-helper-hidden" ?>">
		<?php echo $this->error ?>
	</p>
	
	<!-- Si javascript n'est pas activé, on le notifie-->
	<noscript>
		<p class="user-login-errors ui-widget ui-state-error">
			Javascript n'est pas activé sur votre navigateur. Prevarisc ne peut fonctionner correctement sans l'activation du Javascript.
		</p>
	</noscript>

</div>

<script type="text/javascript">

	// Gestion de l'envoi du formulaire
	$("span#user-login-content-form-connexion input").button().click( function() {
	
		$.ajax({
			url: $("#user-login-content-form").attr("action"),
			type: $("#user-login-content-form").attr("method"),
			data: $("#user-login-content-form").serialize() + "&format=json",
			beforeSend: function() {
			
				$("span#user-login-content-form-connexion input").hide();
				$("span#user-login-content-form-connexion img").show();
			},
			success: function(messages) {
			
				// Si il n'y a pas d'erreurs, on se connecte
				if( !messages.error ) {

					if(messages.ldap === true)
						window.location = "/user/edit-me/ldap/1";
					else
						window.location.reload(true);
				}
				// Sinon on montre l'erreur
				else {
					$(".user-login-errors").show().html(messages.error);
					$("span#user-login-content-form-connexion input").show();
					$("span#user-login-content-form-connexion img").hide();
				}
			}
		});
		
		return false;
	});

	//Gestion du style
	$(window).bind("resize", function() {
		var height = window.innerHeight / 2 - 220;
		$("#user-login-content").css("margin-top", ( height ) ? height : 250 );
	}).resize();
	
	// Effet en arrivant sur la page
	$(document).ready(function() {
		$("#user-login-content-logo, #user-login-content-box").hide();
		$("#user-login-content-logo").delay(250).fadeIn(3000)
		$("#user-login-content-box").delay(1125).fadeIn(2000)	
		$("body").css("overflow", "hidden");	
	});
	
	// Bouton de recharge
	$("#reload").button({
		icons: { primary: "ui-icon-refresh" }
	}).click(function() {
		window.location = "/";
	});
	
</script>