<div class='row-fluid'>

    <!-- Coté gauche -->
    <div class="span2" >
        
        <!-- Avatar -->
        <p id="avatar_img"><?php $this->avatar($this->user["ID_UTILISATEUR"], "large") ?></p>
        
        <!-- informations utilisateur -->
        <?php if( !empty($this->user_info->TELFIXE_UTILISATEURINFORMATIONS) && !empty($this->user_info->TELPORTABLE_UTILISATEURINFORMATIONS) && !empty($this->user_info->TELFAX_UTILISATEURINFORMATIONS) ) : ?>
        <h4>Coordonnées téléphoniques</h4>
        <p>
            <?php if($this->user_info->TELFIXE_UTILISATEURINFORMATIONS) : ?> <i class='sprite sprite-telephone' ></i> <?php echo $this->user_info->TELFIXE_UTILISATEURINFORMATIONS; ?> <br/> <?php endif ?>
            <?php if($this->user_info->TELPORTABLE_UTILISATEURINFORMATIONS) : ?> <i class='sprite sprite-phone' ></i> <?php echo $this->user_info->TELPORTABLE_UTILISATEURINFORMATIONS; ?> <br/> <?php endif ?>
            <?php if($this->user_info->TELFAX_UTILISATEURINFORMATIONS) : ?> <i class='sprite sprite-printer_empty' ></i> <?php echo $this->user_info->TELFAX_UTILISATEURINFORMATIONS; ?> <br/> <?php endif ?>
        </p>
        <?php endif ?>
        
        <!-- Groupe -->
        <h4>Groupe</h4>
        <p>
            <a href='#' ><?php echo $this->groupe["LIBELLE_GROUPE"] ?></a>
            
            <h5>Autres utilisateurs du groupe</h5>
            <?php echo $this->partialLoop('user/user.phtml', $this->users ); ?>
            <div style='clear: both'></div>
        </p>

        <!-- Date des préventionnistes -->
        <h4>Dates</h4>
        <p>
            Date PRV2: <?php if($this->user_info["DATE_PRV2"] != "0000-00-00 00:00:00") { $date = new Zend_Date($this->user_info["DATE_PRV2"], Zend_Date::DATES); echo $date->get( Zend_Date::WEEKDAY." ".Zend_Date::DAY_SHORT." ".Zend_Date::MONTH_NAME_SHORT." ".Zend_Date::YEAR )."&nbsp;"; }	else echo "Aucune date entrée."	?><br/>
            Date Recyclage: <?php if($this->user_info["DATE_RECYCLAGE"] != "0000-00-00 00:00:00") { $date = new Zend_Date($this->user_info["DATE_RECYCLAGE"], Zend_Date::DATES); echo $date->get( Zend_Date::WEEKDAY." ".Zend_Date::DAY_SHORT." ".Zend_Date::MONTH_NAME_SHORT." ".Zend_Date::YEAR )."&nbsp;"; }	else echo "Aucune date entrée."	?><br/>
            Date SID: <?php if($this->user_info["DATE_SID"] != "0000-00-00 00:00:00") { $date = new Zend_Date($this->user_info["DATE_SID"], Zend_Date::DATES); echo $date->get( Zend_Date::WEEKDAY." ".Zend_Date::DAY_SHORT." ".Zend_Date::MONTH_NAME_SHORT." ".Zend_Date::YEAR )."&nbsp;"; }	else echo "Aucune date entrée."	?>
        </p>
        
    </div>

    <!-- Contenu de l'utilisateur -->
    <div class="span10" >

        <!-- Boutons-->
        <div class='pull-right' >
            <br>
            <?php if($this->user_info["MAIL_UTILISATEURINFORMATIONS"]) : ?><a href='mailto:<?php echo $this->user_info["MAIL_UTILISATEURINFORMATIONS"] ?>' class='btn'><i class='icon-envelope'></i> Envoyer un message</a><?php endif ?>
            <?php if(Zend_Auth::getInstance()->getIdentity()->ID_UTILISATEUR == $this->user["ID_UTILISATEUR"]) : ?>
            <a id='edit-user' href='#' class='btn' >Modifier</a>
            <?php endif ?>
        </div>

        <!-- Nom et prénom -->
        <h2>
            <?php echo $this->user_info["NOM_UTILISATEURINFORMATIONS"] . " " . $this->user_info["PRENOM_UTILISATEURINFORMATIONS"] ?>
            <?php echo ( time() - strtotime($this->user["LASTACTION_UTILISATEUR"]) < ini_get('session.gc_maxlifetime') ) ? "<span class='label label-success'>En ligne</span>" : "<span class='label'>Hors ligne</span>" ?>
        </h2>

        <!-- établissements surveillés -->
        <h4>Etablissements surveillés</h4>
        <ul class='recherche_liste unstyled'>
        <?php echo $this->partialLoop('search/results/etablissement.phtml', $this->etablissements);  ?>
        </ul>

    </div>

</div>

<script type="text/javascript">

	$("#edit-user").fancybox({
		'href': '/user/edit/uid/<?php echo $this->user["ID_UTILISATEUR"] ?>?ref=<?php echo $this->user["ID_UTILISATEUR"] ?>&ajax=1',
	});

</script>