<?php if (count($this->data) > 0): ?>
   <ul class='recherche_liste unstyled no_slide scroll-bloc-medium'>
     <?php echo $this->partialLoop('search/results/dossier.phtml', $this->data) ?>
   </ul>
<?php else: ?>
   <small class='muted'>Aucun dossier.</small>
 <?php endif ?>
<script type="text/javascript">
    $(document).ready(function() {
        $("#<?php echo $this->id ?> .panel-heading").append(' (<?php echo count($this->data) ?>)');
    });
</script>