<div class="fiche_contact pull-left" style="width: 500px; margin: 5px;">

    <p class="fiche_contact_nom">
        <?php echo $this->NOM_UTILISATEURINFORMATIONS ." ".$this->PRENOM_UTILISATEURINFORMATIONS  ?>
        <?php if(!(array_key_exists('verrou', $_GET) && $_GET['verrou'] == 1)): ?>
            <span class="fiche_delete" title="Supprimer"><a class='contact-delete' href="/contact/delete?item=<?php echo $this->partialLoop()->view->item ?>&id=<?php echo $this->ID_UTILISATEURINFORMATIONS  ?>&id_item=<?php echo $this->partialLoop()->view->id ?>">&times;</a></span>
            <span class="fiche_edit" title="Éditer"><a href="/contact/edit?id=<?php echo $this->ID_UTILISATEURINFORMATIONS  ?>"><img src="/images/pen.png" height="9" width="10" alt="Éditer" /></a></span>
        <?php endif ?>
    </p>

    <p class="fiche_contact_fonction"><?php echo $this->LIBELLE_FONCTION  ?> - <?php echo $this->SOCIETE_UTILISATEURINFORMATIONS  ?></p>

    <ul class='unstyled'>
        <li>
            <span>Téléphone</span>
            <span class="valeur">
            <?php
                echo $this->TELFIXE_UTILISATEURINFORMATIONS ;
                if( $this->TELPORTABLE_UTILISATEURINFORMATIONS  != "" )
                 echo " / ".$this->TELPORTABLE_UTILISATEURINFORMATIONS ;
            ?>
            </span>
        </li>
        <li>
            <span>Fax</span>
            <span class="valeur"><?php echo $this->TELFAX_UTILISATEURINFORMATIONS  ?></span>
        </li>
        <li>
            <span>Courriel</span>
            <span class="valeur"><a href='mailto:<?php echo $this->MAIL_UTILISATEURINFORMATIONS  ?>'><?php echo $this->MAIL_UTILISATEURINFORMATIONS  ?></a></span>
        </li>
        <li>
            <span>Site web</span>
            <span class="valeur"><a href="<?php echo $this->WEB_UTILISATEURINFORMATIONS  ?>"><?php echo $this->WEB_UTILISATEURINFORMATIONS  ?></a></span>
        </li>
        <li>
            <span>Adresse</span>
            <span class="valeur">
            <?php
                echo
                    $this->NUMEROADRESSE_UTILISATEURINFORMATIONS  . " "
                    . $this->RUEADRESSE_UTILISATEURINFORMATIONS  . " "
                    . $this->CPADRESSE_UTILISATEURINFORMATIONS  . " "
                    . $this->VILLEADRESSE_UTILISATEURINFORMATIONS  . " ";
            ?>
            </span>
        </li>
        <li>
            <span>Observations</span>
            <span class="valeur"><?php echo $this->OBS_UTILISATEURINFORMATIONS  ?></span>
        </li>
    </ul>
</div>
