<div class="fiche_contact" style="min-width: 250px">
    <p class="fiche_contact_nom"><?php echo $this->NOM_UTILISATEURINFORMATIONS ." ".$this->PRENOM_UTILISATEURINFORMATIONS  ?></p>
    
    <p class="fiche_contact_fonction"><?php echo $this->LIBELLE_FONCTION  ?> - <?php echo $this->SOCIETE_UTILISATEURINFORMATIONS  ?></p>
    
    <ul>
        <li>
            <span>Téléphone</span>
            <span class="valeur">
            <?php
                echo $this->TELFIXE_UTILISATEURINFORMATIONS ;
                if( $this->TELPORTABLE_UTILISATEURINFORMATIONS  != "" )
                 echo " / ".$this->TELPORTABLE_UTILISATEURINFORMATIONS ;
            ?>
            </span>
        </li>
        <li>
            <span>Fax</span>
            <span class="valeur"><?php echo $this->TELFAX_UTILISATEURINFORMATIONS  ?></span>
        </li>
        <li>
            <span>Couriel</span>
            <span class="valeur"><a href='mailto:<?php echo $this->MAIL_UTILISATEURINFORMATIONS  ?>'><?php echo $this->MAIL_UTILISATEURINFORMATIONS  ?></a></span>
        </li>
        <li>
            <span>Site web</span>
            <span class="valeur"><a href="<?php echo $this->WEB_UTILISATEURINFORMATIONS  ?>"><?php echo $this->WEB_UTILISATEURINFORMATIONS  ?></a></span>
        </li>
        <li>
            <span>Adresse</span>
            <span class="valeur">
            <?php
                echo
                    $this->NUMEROADRESSE_UTILISATEURINFORMATIONS  . " "
                    . $this->RUEADRESSE_UTILISATEURINFORMATIONS  . " "
                    . $this->CPADRESSE_UTILISATEURINFORMATIONS  . " "
                    . $this->VILLEADRESSE_UTILISATEURINFORMATIONS  . " ";
            ?>
            </span>
        </li>
        <li>
            <span>Observations</span>
            <span class="valeur"><?php echo $this->OBS_UTILISATEURINFORMATIONS  ?></span>
        </li>
    </ul>
</div>