<!-- Titre -->
<h2 class='page-header'>Administration système</h2>

<?php echo $this->partial('menu_admin.phtml') ?>

<h3><?php echo $this->row ? "Modification d'une couche" : "Ajout d'une couche" ?></h3>

<form action="/couche-cartographique/<?php echo $this->row ? "edit" : "add" ?>" method="post">
	
	<fieldset>
		<legend>Paramètres de base</legend>
		<dl class='dl-horizontal'>

			<!-- Type de la couche -->
			<dt>
				Type de la couche
			</dt>
			<dd>
				<select name="ID_COUCHECARTOTYPE">
					<?php foreach($this->rowset_couchecartotypes as $row) : ?>
					<option value="<?php echo $row->ID_COUCHECARTOTYPE ?>" <?php if(isset($this->row) && $this->row->ID_COUCHECARTOTYPE == $row->ID_COUCHECARTOTYPE) echo "selected" ?> ><?php echo $row->NOM_COUCHECARTOTYPE ?></option>
					<?php endforeach ?>
				</select>
			</dd>
			
		</dl>
	</fieldset>
	
	<fieldset id="param_avances" class="ui-helper-hidden">
		<legend>Paramètres avancés</legend>
		<dl class='dl-horizontal'>
			<!-- Nom de la couche -->
			<dt>
				Nom de la couche
			</dt>
			<dd>
				<input type="text" name="NOM_COUCHECARTO" value="<?php echo $this->row ? $this->row->NOM_COUCHECARTO : "" ?>" />
			</dd>
			
			<!-- URL de la couche -->
			<dt>
				URL du flux
			</dt>
			<dd>
				<input type="text" name="URL_COUCHECARTO" value="<?php echo $this->row ? $this->row->URL_COUCHECARTO : "" ?>" />
			</dd>

			<!-- Base layer ? -->
			<dt>
				Couche de base ?
			</dt>
			<dd>
				<input type="checkbox" name="ISBASELAYER_COUCHECARTO" value="1" <?php if(isset($this->row) && $this->row->ISBASELAYER_COUCHECARTO) echo "checked" ?> />
			</dd>
			
			<!-- Base layer ? -->
			<dt>
				Nom de la couche dans le flux
			</dt>
			<dd>
				<input type="text" name="LAYERS_COUCHECARTO" value="<?php echo isset($this->row) ? $this->row->LAYERS_COUCHECARTO : "" ?>" />
			</dd>

			<!-- Base layer ? -->
			<dt>
				Format de l'image de la couche
			</dt>
			<dd>
				<select name="FORMAT_COUCHECARTO">
					<option value="image/png" <?php if(isset($this->row) && $this->row->FORMAT_COUCHECARTO == "image/png") echo "selected" ?> >image/png</option>
					<option value="image/jpg" <?php if(isset($this->row) && $this->row->FORMAT_COUCHECARTO == "image/jpg") echo "selected" ?> >image/jpg</option>
				</select>
			</dd>

			<!--Transparent ? -->
			<dt>
				Couche transparente ?
			</dt>
			<dd>
				<input type="checkbox" name="TRANSPARENT_COUCHECARTO" value="1" <?php if(isset($this->row) && $this->row->TRANSPARENT_COUCHECARTO) echo "checked" ?> />
			</dd>
			
			<!--Intrecative ? -->
			<dt>
				Interactive ?
			</dt>
			<dd>
				<input type="checkbox" name="INTERACT_COUCHECARTO" value="1" <?php if(isset($this->row) && $this->row->INTERACT_COUCHECARTO) echo "checked" ?> />
			</dd>
		
		</dl>
	</fieldset>
	
	<fieldset id="param_cle" class="ui-helper-hidden">
		<legend>API</legend>
		<dl class='dl-horizontal'>
			<dt>Clé d'API</dt>
			<dd><input type="text" name="API_COUCHECARTO" value="<?php echo $this->row ? $this->row->API_COUCHECARTO : "" ?>" /></dd>
		</dl>
	</fieldset>

    <dl class='dl-horizontal'>
        <dt></dt>
        <dd><input type='submit' class="btn btn-success" value="<?php echo $this->row ? "Modifier" : "Ajouter" ?> la couche" /></dd>
    </dl>
    
	<?php echo $this->row ? '<input type="hidden" name="id" value="' . $_GET["id"] . '" />' : "" ?>
</form>

<script>
	
	$("select[name=ID_COUCHECARTOTYPE]").change(function() {
		if($(this).find("option:selected").val() == 2 || $(this).find("option:selected").val() == 3) { // IGN / OSM
			$("#param_avances").hide();
			$("#param_avances input").val("");
			$("#param_avances input[name=TRANSPARENT_COUCHECARTO]").attr("checked", false);
		}
		else
			$("#param_avances").show();
		
		if($(this).find("option:selected").val() == 3) {
			$("#param_cle").show();
		}
		else {
			$("#param_cle").hide();
			$("#param_cle input").val("");
		}
	}).change();
	
	$("#save").click(function() {$("form").submit()});
	
</script>