<h3 class='page-header'>Panneau d'administration</h3>

<dl class='dl-horizontal' >

    <dt>Clé IGN</dt>
    <dd>
        <p><?php echo $this->key_ign != null ? $this->key_ign : 'Aucune clé' ?></p>
    </dd>

    <dt>Clé Google MAP</dt>
    <dd>
        <p><?php echo $this->key_googlemap != null ? $this->key_googlemap : 'Aucune clé' ?></p>
    </dd>

    <dt>Auth. via LDAP</dt>
    <dd>
        <p><?php echo $this->ldap_enabled != 1 ? 'Désactivé' : 'Activé' ?></p>
    </dd>

    <dt>Base utilisée</dt>
    <dd>
        <p><em><?php echo $this->dbname ?></em> sur <em><?php echo $this->db_url ?></em></p>
    </dd>

</dl>
