<?php
/*
	echo "<h3>Liste des dates :</h3><br/>";
	foreach($this->listeCommQtip as $commInfo){
		$dateC = new Zend_Date($commInfo['DATE_COMMISSION'],'yyyy-MM-dd','en');
		if($this->idParam == $commInfo['ID_DATECOMMISSION'])
			echo "<b>".$dateC->get(Zend_Date::WEEKDAY." ".Zend_Date::DAY_SHORT." ".Zend_Date::MONTH_NAME_SHORT." ".Zend_Date::YEAR,'fr')."</b><br/>";	
		else
			echo $dateC->get(Zend_Date::WEEKDAY." ".Zend_Date::DAY_SHORT." ".Zend_Date::MONTH_NAME_SHORT." ".Zend_Date::YEAR,'fr')."<br/>";
	}
*/