<script type="text/javascript">

	$(document).ready(function() {

		$('.time').live('focus', function() {
			$(this).timeEntry($.timeEntry.regional['fr']);
		});
	});

	/**APPLIQUER DES CLASSES JQUERY SUR LES INPUT DATE ET HEURE
	**/	
	$('.time').live('focus', function() {
		$(this).timeEntry($.timeEntry.regional['fr']);
	});
	$('.date').live('click', function() {
		$(this).datepicker({showOn:'focus', dateFormat: 'dd/mm/yy', firstDay: 1}).focus();
	});

	/**FAIT APPARAITRE LA DIV PERMETTANT D'AJOUTER UNE DATE A UNE COMMISSION
	**/
	$(".addDate").live('click', function(){
		$("#divAddDate").show();
		$("#dialogComm").buttonHide();
		return false;
	});

	/**GESTION DE L'AJOUT DE DATE DANS LA BOITE DE DIALOGUE
	**/
	$('.validAddDate').live('click',function(){
		var dateSelect = $("#addDate").val();
		$("#addDate").attr('value','');
		if(dateSelect != ''){
			//Dans le cas d'une édition on fait l'insertion toute suite sur le calendrier et on le raffraichi
			if($("#dateCommission").val()){
				$.ajax({
					data: "do=addDateS&date="+dateSelect+"&idDateCommLiee="+$("#dateCommission").val(),
					type:"POST",
					url:"/calendrier-des-commissions/dialogcomm",
					beforeSend: function(){
						$("#divAddDate").hide();
					},
					success: function(affichageResultat){
						$("#listeDates").last("ul").append(affichageResultat);
						$("#calendar").fullCalendar('refetchEvents');
					},
					error: function(){
						return false;
					}
				});			
			}else{
				//Dans le cas d'une création on ajoute simplement la ligne
				$.ajax({
					data: "do=addDateN&date="+dateSelect,
					type:"POST",
					url:"/calendrier-des-commissions/dialogcomm",
					beforeSend: function(){
						$("#divAddDate").hide();
					},
					success: function(affichageResultat){
						$("#listeDates").last("ul").append(affichageResultat);
						$(".suppression").last().button({
							icons: {
								primary: 'ui-icon-trash'
							},
							text: false
						});
					},
					error: function(){
						return false;
					}
				});
			}
		}
		$("#dialogComm").buttonShow();
		$("#listeDates").countLigne('add','edit');
		return false;
	});

	$(".cancelAddDate").live('click',function(){
		//Annulation de l'ajout de date 
		$("#addDate").attr('value','');
		$("#divAddDate").hide();
		$("#dialogComm").buttonShow();
		return false;
	});

	$("#repeat").live('click',function(){
		if($(this).attr('checked')){
			$("#planification").fadeIn();
			$("#dialogComm").buttonHide();
		}else{
			$("#planification").fadeOut();
			$("#dateFin").attr('value','');
			$("#periodicite").val("1");
			$("#dialogComm").buttonShow();
		}
	});

	$("#valid_periodicite").live('click',function(){
		$("#dialogComm").buttonShow();
		$("#dialogComm").reapeatHide();
	});
	
	$("#annule_periodicite").live('click',function(){		
		$("#dialogComm").buttonShow();
		$("#dialogComm").reapeatHide();
	});
	
	$("#valid_periodicite").live('click',function(){
		//alert('');
	});

	//Fonction que devra être utlisée si l'on veux pourvoir afficher une periodicitée sur 1 seule date de départ
	(function($){
		//permet de vérifier le nombre de date selectionnées.. Si 1 date alors on peux utiliser la périodicité
		$.fn.countLigne = function(action,type){
			//alert(action+" - "+type+" - "+$("#listeDates ul").length);
			if(action == 'add'){
				$("#addReapeat").hide();
				//$("#repeat").attr('checked',false);	
				$("#planification").hide();
			}else if(action == 'supp'){
				if(type == 'edit'){
					if($("#listeDates ul").length == 3)
						$("#addReapeat").show();
				}else if(type == 'new'){
					if($("#listeDates ul").length == 2)
						$("#addReapeat").show();
				}
			}
		};
		$.fn.buttonHide = function(){
			//alert('');
			$(".edition").hide();
			$(".suppression").hide();
			$(".dateDefaut").hide();
			$(".addDate").hide();
		};
		$.fn.buttonShow = function(){
			//alert('');
			$(".edition").show();
			$(".suppression").show();
			$(".dateDefaut").show();
			$(".addDate").show();
		};
		$.fn.reapeatHide = function(){
			$("#addReapeat").hide();
			$("#planification").hide();
		};
		$.fn.reapeatShow = function(){
			$("#addReapeat").show();
			$("#planification").show();
			$("#listeDates").countLigne('new');		
		};
	})(jQuery);
</script>

<?php

if(isset($this->do) && $this->do == 'edit'){

	echo "
		<form name='formDateComm' id='formDateComm' methode='POST'>
			<input type='hidden' name='dateCommission' id='dateCommission' value='".$this->dateCommission."' />
			<input type='hidden' name='dateClick' id='dateClick' value='".$this->dateClick."' />
			<p>
			<div id='div_libelleCom' >
				".afficheLibelleDateComm($this->libelleDateComm)."
			</div>
			</p>
			<p>
			<div id='div_typeCom' >
				".afficheTypeDateComm($this->typeComLibelle)."
			</div>
			</p>
				".afficheTabListeDates($this->listeDates)."	
			<br/>
				".divAddDate()."
			<br/>
	";
	//Pour la planification elle n'es possible que l'orsque l'on choisi une seule date
	echo "
			</form>
	";
}else if(isset($this->do) && $this->do == 'newComm'){
		/**
		***
		***AFFICHAGE BOITE DIALOGUE PERMETTANT LA CREATION DES COMMISSIONS 
		***
		**/

	$periodicite = array();
	for($i = 1; $i <=4; $i++){
		array_push($periodicite, $i);
	}
	echo "
		<form name='formDateComm' id='formDateComm' methode='POST'>
			<br/>
			<p>
			<div id='div_libelleCom' >
				Saisissez le libellé de la commission
				<input type='text' name='libelle_comm' id='libelle_comm' value=\"".$this->libelleCom."\" style='width:400px;'/>
			</div>
			</p>
			<br/>
			<p>
				<div id='div_typeCom' >
					Veuillez selectionner le type de la commission :
					<select name='typeCom' id='typeCom'>
	";
	foreach($this->listeCommType as $value){
		echo "<option value='".$value['ID_COMMISSIONTYPEEVENEMENT']."' ".( ($this->typeDoss ==  $value['ID_COMMISSIONTYPEEVENEMENT'])? "selected" : "" ).">".$value['LIBELLE_COMMISSIONTYPEEVENEMENT']."</option>";
	}
	echo "
					</select>
				</div>
			</p>
			<br/>
			<div class='container-fluid' id='listeDates'>
				<ul class='unstyled row-fluid' style='text-align:center;font-weight:bold;border-bottom:1px solid black;float:left;padding:3px 0 3px 0;'>
					<li class='span6'>Date</li>
					<li class='span2'>Heure début</li>
					<li class='span2'>Heure fin</li>
					<li class='span2'>
						<button class='addDate btn'><i class='icon-plus'></i>&nbsp;</button>
					</li>
				</ul>
	";
	$paspremier = 0;
	foreach($this->listeDates as $dates){
		if($dates['heureD'] == '00:00' && $dates['heureF'] == '00:00'){
			$HD = '09:00';
			$HF = '18:00';
		}else{
			$HD = $dates['heureD'];
			$HF = $dates['heureF'];
		}
		echo "
					<ul class='unstyled row-fluid' style='text-align: center; font-weight: bold; float: left; padding: 3px 0pt;'>
						<li class='span6'>".$dates['date']."</li>
						<li class='span2'><input type='text' size='8' class='time' id='D_".$dates['inputH']."' name='D_".$dates['inputH']."' value='".$HD."' /></li>
						<li class='span2'><input type='text' size='8' class='time' id='F_".$dates['inputH']."' name='F_".$dates['inputH']."' value='".$HF."'/></li>
						<li class='span2'>
		";
		if($paspremier != 0)
			echo "<button class='suppression btn'><i class='icon-trash'></i>&nbsp;</button>";
		echo "
						</li>
					</ul>
		";
		$paspremier++;
	}
	echo "
				</div>
				".divAddDate()."
			<br/>
	";
	echo afficheDivPeriodicite(count($this->listeDates),$this->do);

	echo "
			</form>
	";
}else{
	switch($this->do){
		case 'addDateN':
			echo "
				<ul class='unstyled row-fluid' style='text-align:center;font-weight:bold;float:left;padding:3px 0 3px 0;'>
					<li class='span6'>".$this->dateAjoutee."</li>
					<li class='span2'><input type='text' size='8' class='time' id='D_".$this->dateAjouteeInput."' name='D_".$this->dateAjouteeInput."' value='09:00'/></li>
					<li class='span2'><input type='text' size='8' class='time' id='F_".$this->dateAjouteeInput."' name='F_".$this->dateAjouteeInput."' value='18:00'/></li>
					<li class='span2'>
						<button class='suppression btn' ><i class='icon-trash'></i>&nbsp;</button>
					</li>
			";
		break;
		case 'libelleCom':
			echo "
				Saisissez le libellé de la commission <input type='text' name='value_libelleCom' id='value_libelleCom' value='".htmlentities($this->libelleDateComm, ENT_QUOTES)."' />
				<button class='validation btn' id='valid_libelleCom'><i class='icon-ok'></i>&nbsp;</button>
				<button class='annulation btn' id='annule_libelleCom'><i class='icon-remove'></i>&nbsp;</button>
			";
		break;
		case 'valid_libelleCom':
			echo afficheLibelleDateComm($this->libelleDateComm);
		break;
		case 'annule_libelleCom':
			echo afficheLibelleDateComm($this->libelleDateComm);
		break;
		case "typeCom":
			echo modifTypeComm($this->listeCommType,$this->typeComSelect);
		break;
		case "valid_typeCom":
			echo afficheTypeDateComm($this->libelleType);
		break;
		case "annule_typeCom":
			echo afficheTypeDateComm($this->libelleType);
		break;
		case 'dateComm':
			echo afficheDateEdit($this->dateCommDetail,$this->first);
		break;
		case 'valid_dateCom':
			echo afficheDateValid($this->updateDateComm,$this->first);
		break;
		case 'annule_dateCom':
			echo afficheDateValid($this->dateCommDetail,$this->first);
		break;
		case 'addDateS':
			echo ajoutDateLiee($this->TabNouvelleDate,$this->nouvelleDate);
		break;
	}
}//FIN DU IF $POST

/**
***
***FONCTIONS GENERIQUES POUR L'AFFICHAGES DES DIFFERENTES DONNEES
***
**/
function afficheLibelleDateComm($libelle){
	//affiche le libelle  de la commission en mode lectude d'infos
	return "
		Libelle de la commission : ".$libelle."
		<button id='edit_libelleCom' class='edition btn'><i class='icon-pencil'></i>&nbsp;</button>
	";
}

function afficheTypeDateComm($libelleCom){
	//affiche le type de la commission en mode lecture d'infos
	$affiche = "
		Le type de commission est :
	".$libelleCom."
		<button id='edit_typeCom' class='edition btn'><i class='icon-pencil'></i>&nbsp;</button>
	";
	return $affiche;
}

function modifTypeComm($listeCommType, $idSelect){
	//affiche le formulaire permettant d'editer le type d'une commission
	$affiche = "
		Veuillez selectionner le type de la commission :
		<select name='typeCom' id='typeCom' >
	";
	foreach($listeCommType as $value){
		if($idSelect == $value['ID_COMMISSIONTYPEEVENEMENT']){
			$select = "selected='selected'";
		}else{
			$select = "";
		}
		$affiche .= "<option value='".$value['ID_COMMISSIONTYPEEVENEMENT']."' ".$select.">".$value['LIBELLE_COMMISSIONTYPEEVENEMENT']."</option>";
	}
	$affiche .= "
		</select>
		<button class='validation btn' id='valid_typeCom'><i class='icon-ok'></i>&nbsp;</button>
		<button class='annulation btn' id='annule_typeCom'><i class='icon-remove'></i>&nbsp;</button>
	";
	return $affiche;
}

function afficheTabListeDates($listeDates){
	//Affiche la liste des dates pour une édition
	$affiche = "
				<div class='container-fluid' id='listeDates'>
					<ul class='unstyled row-fluid' style='text-align:center;font-weight:bold;border-bottom:1px solid black;float:left;padding:3px 0 3px 0;'>
						<li class='span6'>Date</li>
						<li class='span2'>Heure début</li>
						<li class='span2'>Heure fin</li>
						<li class='span2'>
							<button class='addDate btn'><i class='icon-plus'></i>&nbsp;</button>
						</li>
					</ul>
	";
	$paspremier = 0;
	foreach($listeDates as $dates){
		$heureDebut = $chaine=substr($dates['HEUREDEB_COMMISSION'],0,5);
		$heureFin = $chaine=substr($dates['HEUREFIN_COMMISSION'],0,5);
		$date = new Zend_Date($dates['DATE_COMMISSION'],'yyyy.MM.dd','fr');
		$dateLibelle = $date->get(Zend_Date::WEEKDAY." ".Zend_Date::DAY_SHORT." ".Zend_Date::MONTH_NAME_SHORT." ".Zend_Date::YEAR,'fr');
		$affiche .= "
					<ul class='unstyled row-fluid' id='ligne_".$dates['ID_DATECOMMISSION']."' style='text-align:center;font-weight:bold;float:left;padding:3px 0 3px 0;'>
						<li class='span6'>".$dateLibelle."</li>
						<li class='span2'> ".$heureDebut." </li>
						<li class='span2'> ".$heureFin." </li>
						<li class='span2'>
		";
		$affiche .= "
						<button class='edition btn' name='edition' id='edit_dateComm_".$dates['ID_DATECOMMISSION']."'><i class='icon-pencil'></i>&nbsp;</button>
		";
		if($dates['DATECOMMISSION_LIEES']){
			$affiche .= "<button class='suppression btn' id='supp_dateComm_".$dates['ID_DATECOMMISSION']."'><i class='icon-trash'></i>&nbsp;</button>";
			$affiche .= "<button style='float:right;' class='dateDefaut btn' id='defaut_dateComm_".$dates['ID_DATECOMMISSION']."'><i class='icon-check'></i>&nbsp;</button>";
		}
		$affiche .= "
						</li>
					</ul>
		";
		$paspremier++;
	}
	$affiche .= "
				</div>
	";
	return $affiche;
}

function afficheDateEdit($dateInfos,$first=null){
	//affiche la partie formulaire affichée lors de l'ajout d'une date à une commission
	$heureDebut = $chaine=substr($dateInfos['HEUREDEB_COMMISSION'],0,5);
	$heureFin = $chaine=substr($dateInfos['HEUREFIN_COMMISSION'],0,5);
	$date = new Zend_Date($dateInfos['DATE_COMMISSION'],'yyyy.MM.dd','fr');
	$date = $date->get(Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR);
	$affiche = "
		<li class='span6'>
			<input type='text' class='date' value='".$date."' id='date_".$dateInfos['ID_DATECOMMISSION']."' />
		</li>
		<li class='span2'>
			<input type='text' size='8' class='time' id='D_".$dateInfos['ID_DATECOMMISSION']."' name='D_".$dateInfos['ID_DATECOMMISSION']."' value='".$heureDebut."' />
		</li>
		<li class='span2'>
			<input type='text' size='8' class='time' id='F_".$dateInfos['ID_DATECOMMISSION']."' name='F_".$dateInfos['ID_DATECOMMISSION']."' value='".$heureFin."' />
		</li>
		<li class='span2'>
			<button class='validation btn' name='validation' id='annule_dateCom_".$dateInfos['ID_DATECOMMISSION']."'><i class='icon-ok'></i>&nbsp;</button>
			<button class='annulation btn' name='annulation' id='annule_dateCom_".$dateInfos['ID_DATECOMMISSION']."'><i class='icon-remove'></i>&nbsp;</button>
			<input type='hidden' name='first' id='first' value='".$first."' />
		</li>
	";
	return $affiche;
}

function afficheDateValid($date,$first=null){
	//affiche la date après l'avoir inseree dans la base de données cas édition
	$heureDebut = $chaine=substr($date['HEUREDEB_COMMISSION'],0,5);
	$heureFin = $chaine=substr($date['HEUREFIN_COMMISSION'],0,5);
	$dateE = new Zend_Date($date['DATE_COMMISSION'],'yyyy.MM.dd','en');
	$dateLibelle = $dateE->get(Zend_Date::WEEKDAY." ".Zend_Date::DAY_SHORT." ".Zend_Date::MONTH_NAME_SHORT." ".Zend_Date::YEAR,'fr');
	$buttonEdition = $date['ID_DATECOMMISSION'];
	$affiche = "
			<ul class='unstyled row-fluid' id='ligne_".$date['ID_DATECOMMISSION']."' style='text-align:center;font-weight:bold;float:left;padding:3px 0 3px 0;'>
				<li class='span6'>".$dateLibelle."</li>
				<li class='span2'>".$heureDebut." </li>
				<li class='span2'>".$heureFin." </li>
				<li class='span2'>
					<button class='edition btn' id='edit_dateComm_".$buttonEdition."'><i class='icon-pencil'></i>&nbsp;</button>
	";
	if($date['DATECOMMISSION_LIEES']){
		$affiche.= "<button class='suppression btn' id='supp_dateComm_".$buttonEdition."'><i class='icon-trash'></i>&nbsp;</button>";
		$affiche .= "<button style='float:right;' class='dateDefaut btn' id='defaut_dateComm_".$date['ID_DATECOMMISSION']."'><i class='icon-check'></i>&nbsp;</button>";
	}
	$affiche .= "
				</li>
			</ul>
	";
	return $affiche;
}

function ajoutDateLiee($tabDate,$date){
	//ajoute une date à une comm dans le cas d'une édition
	$heureDebut = $chaine=substr($tabDate['HEUREDEB_COMMISSION'],0,5);
	$heureFin = $chaine=substr($tabDate['HEUREFIN_COMMISSION'],0,5);
	$affiche = "
		<ul class='unstyled row-fluid' id='ligne_".$tabDate['ID_DATECOMMISSION']."' style='text-align:center;font-weight:bold;float:left;padding:3px 0 3px 0;'>
			<li class='span6'>".$date."</li>
			<li class='span2'>".$heureDebut."</li>
			<li class='span2'>".$heureFin."</li>
			<li class='span2'>
				<button class='edition btn' id='edit_dateComm_".$tabDate['ID_DATECOMMISSION']."'><i class='icon-pencil'></i>&nbsp;</button>
				<button class='suppression btn' id='supp_dateComm_".$tabDate['ID_DATECOMMISSION']."'><i class='icon-trash'></i>&nbsp;</button>
				<button style='float:right;' class='dateDefaut btn' id='defaut_dateComm_".$tabDate['ID_DATECOMMISSION']."'><i class='icon-check'></i>&nbsp;</button>
			</li>
		</ul>
	";
	return $affiche;
}

function afficheDivPeriodicite($countLigne,$doVal){
	//fonction affichant la div permetant de selectionner les criteres de periodicite
	$periodicite = array();
	for($i = 1; $i <=4; $i++){
		array_push($periodicite, $i);
	}
	if($countLigne > 1)
		$disp = "none";
	else
		$disp = "block";
	$affiche = "
			<p id='addReapeat' style='float:left;display:".$disp."'; >
				Souhaitez vous planifier cette commission sur une période donnée ?<input type='checkbox' name='repeat' id='repeat'/>
			</p>
			<br/>
			<div id='planification' style='display:none;float:left;' class='box'>
				Saisissez la date jusqu'à laquelle vous souhaitez planifier cette commission :<br/><br/>
				<input type='text' class='date' name='dateFin' id='dateFin' />
				<span id='erreurDateFin' style='color:red;'></span>
				<br/>
				La commission a lieu toute les
					<select name='periodicite' id='periodicite'>
	";
	foreach($periodicite as $num => $jour){
			$affiche .= "<option value='".$jour."' >".$jour."</option>";
	}
	$affiche .= "
					</select>&nbsp;semaines
	";
	
	if($doVal == 'edit')
		$affiche . "<button class='validPeriodicite btn'><i class='icon-plus'></i>&nbsp;</button>";
		
	$affiche . "
			</div>
	";
	return $affiche;
}

function divAddDate(){
	//fonction affichant la div permettant d'ajouter une ligne 'date'
	$affiche = "
		<div id='divAddDate'  style='display:none;'>
			&nbsp;&nbsp;
			<ul class='unstyled row-fluid' style='text-align:center;font-weight:bold;float:left;padding:3px 0 3px 0;'>
				<li class='span6'>
					Selectionnez la date <input type='text' class='date' id='addDate' />
				</li>
				<li class='span4'>
					<button class='validAddDate btn'><i class='icon-plus'></i>&nbsp;</button>
					<button class='cancelAddDate btn'><i class='icon-remove'></i>&nbsp;</button>
				</li>
			</ul>
		</div>
	";
	return $affiche;
}