<?php

// PARTIE PRESCRIPTION
function addPrescription($listePrescription,$type,$odf){
    //TYPE_PRESCRIPTION_DOSSIER
    try{

        if($type == 0){
            $prescription = $odf->listeRappelReg;
        }else if ($type == 1){
            $prescription = $odf->listeExploitation;
        }else if ($type == 2){
            $prescription = $odf->listeAmelioration;
        }

        $nbPrescDossier = count($listePrescription);
        
        if($nbPrescDossier)
        {
            for($i=0; $i < $nbPrescDossier; $i++)
            {
                $nbAssoc = count($listePrescription[$i]);
                $cpt = true;
                $article = '';
                $texte = '';
                $textearticle = '';
                for($j=0; $j < $nbAssoc; $j++)
                {
                    $articleT = $listePrescription[$i][$j]['LIBELLE_ARTICLE'];
                    $texteT = $listePrescription[$i][$j]['LIBELLE_TEXTE'];

                    if($texteT != ''){
                        $textearticle .= $texteT." - ";
                    }else{
                        $textearticle .= " - ";
                    }
                    if($nbAssoc > 1){
                        if($articleT != ''){
                            $textearticle .= $articleT.", ";
                        }else{
                            $textearticle .= ", ";
                        }
                    }else{
                        if($articleT != ''){
                            $textearticle .= $articleT." ";
                        }else{
                            $textearticle .= " ";
                        }
                    }
                    if($cpt)
                    {
                        if($type != 0){
                            $prescription->setVars('num', $listePrescription[$i][0]['NUM_PRESCRIPTION_DOSSIER'], true, 'UTF-8');
                        }

                        if( $listePrescription[$i][0]['LIBELLE_PRESCRIPTION_DOSSIER'] == '')
                        {
                            $prescription->setVars('libelle', $listePrescription[$i][0]['PRESCRIPTIONTYPE_LIBELLE'], true, 'UTF-8');
                        }else{
                            $prescription->setVars('libelle', $listePrescription[$i][0]['LIBELLE_PRESCRIPTION_DOSSIER'], true, 'UTF-8');
                        }
                        $cpt = false;
                    }
                    $nbAssoc--;
                }
                $prescription->setVars('textearticle',$textearticle,true,'UTF-8');
                $prescription->merge();
            }

        }else{
            //echo "ploip";
            if($type != 0){
                $prescription->setVars('num', '', true, 'UTF-8');
            }
            $prescription->setVars('libelle', '', true, 'UTF-8');
            $prescription->setVars('textearticle','',true,'UTF-8');
            $prescription->merge();
        }
        //$odf->mergeSegment($prescription);
    } catch (OdfException $e) {
      
    }

}



$consonne = array("a", "e", "i", "o", "u", "y", "A", "E", "I", "O", "U", "Y");
if(count($this->membresFiles) == 0){
	echo "<span id='notif' class='ui-state-error' style='padding: 0.3em;'>Aucun membre n'a été renseigné pour la commission</span><br/><br/><br/>";
	return false;
}
foreach($this->membresFiles as $val => $membre){
	//On boucle sur les membres
	if($membre->ID_GROUPEMENT == NULL){
		$nomFichier = $membre->ID_COMMISSIONMEMBRE."PV_".$membre->COURRIER_PV;
		
		if (file_exists(REAL_DATA_PATH.DIRECTORY_SEPARATOR."uploads".DIRECTORY_SEPARATOR."courriers".DIRECTORY_SEPARATOR.$nomFichier)){
		
			$odf = new Odf(REAL_DATA_PATH.DIRECTORY_SEPARATOR."uploads".DIRECTORY_SEPARATOR."courriers".DIRECTORY_SEPARATOR.$nomFichier);
			$dossInfos = $odf->setSegment('dossierInfos');
			
			foreach($this->dossierComm as $val => $dossierInfos){

				$nbAdresse = count($dossierInfos['infosEtab']['adresses']);
				if($nbAdresse != 0){
					foreach($dossierInfos['infosEtab']['adresses'] as $commune){
					
						$dossInfos->setVars('commissionNom', $this->commissionInfos[0]['LIBELLE_COMMISSION'], true, 'UTF-8');
						if(isset($commune["LIBELLE_COMMUNE"])){
							$dossInfos->setVars('communeDossier', $commune["LIBELLE_COMMUNE"], true, 'UTF-8');
						}
						
						$dossInfos->setVars('objetDossier', $dossierInfos['OBJET_DOSSIER'], true, 'UTF-8');
						//echo $dossierInfos['OBJET_DOSSIER']." <br/>";
						$dossInfos->setVars('natureDossier', $dossierInfos["LIBELLE_DOSSIERNATURE"], true, 'UTF-8');
						
						$dateComm = new Zend_Date($this->dateComm);				
						$dossInfos->setVars('dateCommission', $dateComm->get(Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR), true, 'UTF-8');
						
						
						$dateVisite = new Zend_Date($dossierInfos["DATEVISITE_DOSSIER"]);
						try{
							$dossInfos->setVars('dateVisite', $dateVisite->get(Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR), true, 'UTF-8');
						} catch (Exception $e){

						}

						if(isset($dossierInfos['infosEtab']['parents'][0]["LIBELLE_ETABLISSEMENTINFORMATIONS"]))
							$dossInfos->setVars('nomPereEtab', $dossierInfos['infosEtab']['parents'][0]["LIBELLE_ETABLISSEMENTINFORMATIONS"], true, 'UTF-8');
						else
							$dossInfos->setVars('nomPereEtab', '', true, 'UTF-8');
						
						if(isset($dossierInfos['infosEtab']['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"]))
							$dossInfos->setVars('nomEtab', $dossierInfos['infosEtab']['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"], true, 'UTF-8');
						else
							$dossInfos->setVars('nomEtab', "", true, 'UTF-8');
							
						switch($dossierInfos['AVIS_DOSSIER']){
							case 1:
								$avis = "Favorable";
							break;
							case 2:
								$avis = "Défavorable";
							break;
							default:
								$avis = "";
							break;					
						}
						
						try{
							$dossInfos->setVars('avisDossier', $avis, true, 'UTF-8');
						} catch (Exception $e){

						}

						if(isset($dossierInfos['infosEtab']['informations'])){
							$dossInfos->setVars('categorieEtab', $dossierInfos['infosEtab']['informations']["LIBELLE_CATEGORIE"], true, 'UTF-8');
							//$dossInfos->setVars('typeEtab', $dossierInfos['infosEtab']['informations']["LIBELLE_TYPE_PRINCIPAL"], true, 'UTF-8');
						}else{
							$dossInfos->setVars('categorieEtab', "", true, 'UTF-8');
							//$dossInfos->setVars('typeEtab', "", true, 'UTF-8');
						}
						
						$listeDocUrba = "";
						foreach($dossierInfos["listeDocUrba"] as $va => $docurb){
							$listeDocUrba .= $docurb['NUM_DOCURBA']."    ";
						}
						$dossInfos->setVars('numDocUrba', $listeDocUrba, true, 'UTF-8');


						addPrescription($dossierInfos['prescriptionReglDossier'],0,$dossInfos);
						addPrescription($dossierInfos['prescriptionExploitation'],1,$dossInfos);
						addPrescription($dossierInfos['prescriptionAmelioration'],2,$dossInfos);
						


/*

						//Prescription des dossiers
						if(isset($dossierInfos['prescription']) && count($dossierInfos['prescription']) > 0){
							$nbPrescDossier = count($dossierInfos['prescription']);
							for($i=0; $i < $nbPrescDossier; $i++)
							{
								$nbAssoc = count($dossierInfos['prescription'][$i]);
								$cpt = true;
								$article = '';
								$texte = '';
								$textearticle = '';
								for($j=0; $j < $nbAssoc; $j++)
								{
									$articleT = $dossierInfos['prescription'][$i][$j]['LIBELLE_ARTICLE'];
									$texteT = $dossierInfos['prescription'][$i][$j]['LIBELLE_TEXTE'];

									if($texteT != ''){
										$textearticle .= $texteT." - ";
									}else{
										$textearticle .= " - ";
									}
									
									if($articleT != ''){
										$textearticle .= $articleT.", ";
									}else{
										$textearticle .= ", ";
									}
									if($cpt)
									{
										$dossInfos->listePrescription->setVars('num',$dossierInfos['prescription'][$i][0]['NUM_PRESCRIPTION_DOSSIER'],true,'UTF-8');
										if( $dossierInfos['prescription'][$i][0]['LIBELLE_PRESCRIPTION_DOSSIER'] == '')
										{
											$dossInfos->listePrescription->setVars('libelle',$dossierInfos['prescription'][$i][0]['PRESCRIPTIONTYPE_LIBELLE'],true,'UTF-8');
										}else{
											$dossInfos->listePrescription->setVars('libelle',$dossierInfos['prescription'][$i][0]['LIBELLE_PRESCRIPTION_DOSSIER'],true,'UTF-8');
										}
										$cpt = false;
									}
								}
								
								$dossInfos->listePrescription->setVars('textearticle',$textearticle,true,'UTF-8');
								$dossInfos->listePrescription->merge();
							}

						}else{
							$dossInfos->listePrescription->setVars('num','',true,'UTF-8');
							$dossInfos->listePrescription->setVars('libelle','',true,'UTF-8');
							$dossInfos->listePrescription->setVars('textearticle','',true,'UTF-8');
							$dossInfos->listePrescription->merge();
						}

*/


						
						$dossInfos->merge(); 
					}
				}else{
					//dossier sans adresse indiquer le dossier en question
				}
				
			}
			$odf->mergeSegment($dossInfos);
			$nouvellePJ = savePj($this->idComm,"Le pv a bien été généré");
                        $store = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getResource('dataStore');
                        $path = $store->getFilePath($nouvellePJ, 'dateCommission', $this->idComm, true);
			$odf->saveToDisk($path);	
			//$odf->mergeSegment($dossierLoop);
			echo "<span id='notif' class='ui-state-highlight' style='padding: 0.3em;'>Le PV a été généré avec succes</span><br/><br/><br/>";
		}else{
			echo "<span id='notif' class='ui-state-error' style='padding: 0.3em;'>Le fichier pour le membre : ".$membre->LIBELLE_COMMISSIONMEMBRE." n'a pas été renseigné</span><br/><br/><br/>";
		}
	}else{
		echo "<span id='notif' class='ui-state-error' style='padding: 0.3em;'>Le fichier pour le membre : ".$membre->LIBELLE_COMMISSIONMEMBRE." n'a pas été renseigné</span><br/><br/><br/>";
	}
}


function savePj($dateCommId,$libelleDocument){
	//ENREGISTEMENT DANS PIECE JOINTES
	$dateDuJour = new Zend_Date();
	$DBpieceJointe = new Model_DbTable_PieceJointe;
	$nouvellePJ = $DBpieceJointe->createRow();
	$nouvellePJ->NOM_PIECEJOINTE = "P.V.";
	$nouvellePJ->EXTENSION_PIECEJOINTE = ".odt";
	$nouvellePJ->DESCRIPTION_PIECEJOINTE = "PV : ".$libelleDocument." ".$dateDuJour->get(Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR." à ".Zend_Date::HOUR.":".Zend_Date::MINUTE);
	$nouvellePJ->DATE_PIECEJOINTE = $dateDuJour->get(Zend_Date::YEAR."-".Zend_Date::MONTH."-".Zend_Date::DAY." ".Zend_Date::HOUR.":".Zend_Date::MINUTE.":".Zend_Date::SECOND);
	$nouvellePJ->save();
	//ENREGISTEMENT DANS PIECE JOINTES
	$DBsave = new Model_DbTable_DateCommissionPj;
	$linkPj = $DBsave->createRow();
	$linkPj->ID_DATECOMMISSION = $dateCommId;
	$linkPj->ID_PIECEJOINTE = $nouvellePJ->ID_PIECEJOINTE;
	$linkPj->save();

	return $nouvellePJ;
}
	
?>