<?php

$consonne = array("a", "e", "i", "o", "u", "y", "A", "E", "I", "O", "U", "Y");
if(count($this->membresFiles) == 0){
	echo "<span id='notif' class='ui-state-error' style='padding: 0.3em;'>Aucun membre n'a été renseigné pour la commission</span><br/><br/><br/>";
	return false;
}

$nomFichier = $this->commissionInfos[0]['DOCUMENT_CR'];

if (file_exists(REAL_DATA_PATH.DIRECTORY_SEPARATOR."uploads".DIRECTORY_SEPARATOR."documents_commission".DIRECTORY_SEPARATOR.$nomFichier) && $nomFichier != ''){

	$odf = new Odf(REAL_DATA_PATH.DIRECTORY_SEPARATOR."uploads".DIRECTORY_SEPARATOR."documents_commission".DIRECTORY_SEPARATOR.$nomFichier);
	$dossInfos = $odf->setSegment('dossierInfos');
	
	foreach($this->dossierComm as $val => $dossierInfos){
		$nbAdresse = count($dossierInfos['infosEtab']['adresses']);
		if($nbAdresse != 0){
			foreach($dossierInfos['infosEtab']['adresses'] as $commune){
				$dossInfos->setVars('commissionNom', $this->commissionInfos[0]['LIBELLE_COMMISSION'], true, 'UTF-8');
				if(isset($commune["LIBELLE_COMMUNE"])){
					$dossInfos->setVars('communeDossier', $commune["LIBELLE_COMMUNE"], true, 'UTF-8');
				}
				$dossInfos->setVars('natureDossier', $dossierInfos["LIBELLE_DOSSIERNATURE"], true, 'UTF-8');

				$dateComm = new Zend_Date($this->dateComm);	
				$dossInfos->setVars('dateCommission', $dateComm->get(Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR), true, 'UTF-8');

				$dateVisite = new Zend_Date($dossierInfos["DATEVISITE_DOSSIER"]);
				try{
					$dossInfos->setVars('dateVisite', $dateVisite->get(Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR), true, 'UTF-8');
				} catch (Exception $e){

				}
                                
                                try{
					$dossInfos->setVars('numWinPrev', $dossierInfos['infosEtab']['general']['NUMEROID_ETABLISSEMENT'], true, 'UTF-8');
				} catch (Exception $e){

				}
				
				if(isset($dossierInfos['infosEtab']['parents'][0]["LIBELLE_ETABLISSEMENTINFORMATIONS"])){
					$dossInfos ->setVars('nomPereEtab', $dossierInfos['infosEtab']['parents'][0]["LIBELLE_ETABLISSEMENTINFORMATIONS"], true, 'UTF-8');
				}else{
					$dossInfos ->setVars('nomPereEtab', '', true, 'UTF-8');
				}
				
			
				switch($dossierInfos['AVIS_DOSSIER']){
					case 1:
						$avis = "Favorable";
					break;
					case 2:
						$avis = "Défavorable";
					break;
					default:
						$avis = "";
					break;					
				}
				
				try{
					$dossInfos->setVars('avisDossier', $avis, true, 'UTF-8');
				} catch (Exception $e){

				}
				
				$dossInfos->setVars('objetDossier', $dossierInfos['OBJET_DOSSIER'], true, 'UTF-8');
				
				if(isset($dossierInfos['infosEtab']['informations'])){
					$dossInfos->setVars('nomEtab', $dossierInfos['infosEtab']['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"], true, 'UTF-8');
					$dossInfos->setVars('categorieEtab', $dossierInfos['infosEtab']['informations']["LIBELLE_CATEGORIE"], true, 'UTF-8');
					$dossInfos->setVars('typeEtab', $dossierInfos['infosEtab']['informations']["LIBELLE_TYPE_PRINCIPAL"], true, 'UTF-8');
				}else{
					$dossInfos->setVars('nomEtab', "", true, 'UTF-8');
					$dossInfos->setVars('categorieEtab', "", true, 'UTF-8');
					$dossInfos->setVars('typeEtab', "", true, 'UTF-8');
				}
				
				$listeDocUrba = "";
				foreach($dossierInfos["listeDocUrba"] as $va => $docurb){
					$listeDocUrba .= $docurb['NUM_DOCURBA']."    ";
				}
				$dossInfos->setVars('numDocUrba', $listeDocUrba, true, 'UTF-8');
				$dossInfos->merge(); 
			}
		}
		
		try{
			/*
			$dossInfos->setVars('commissionNom', $this->commissionInfos[0]['LIBELLE_COMMISSION'], true, 'UTF-8');
			if(isset($dossierInfos["infosEtab"]["adresses"][0]["LIBELLE_COMMUNE"])){
				$dossInfos->setVars('communeDossier', $dossierInfos["infosEtab"]["adresses"][0]["LIBELLE_COMMUNE"], true, 'UTF-8');
			}
			$dossInfos->setVars('natureDossier', $dossierInfos["LIBELLE_DOSSIERNATURE"], true, 'UTF-8');

			$dateComm = new Zend_Date($this->dateComm);	
			$dossInfos->setVars('dateCommission', $dateComm->get(Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR), true, 'UTF-8');

			if(isset($dossierInfos['infosEtab']['parents'][0]["LIBELLE_ETABLISSEMENTINFORMATIONS"])){
				$dossInfos ->setVars('nomPereEtab', $dossierInfos['infosEtab']['parents'][0]["LIBELLE_ETABLISSEMENTINFORMATIONS"], true, 'UTF-8');
			}else{
				$dossInfos ->setVars('nomPereEtab', '', true, 'UTF-8');
			}
			
		
			switch($dossierInfos['AVIS_DOSSIER']){
				case 1:
					$avis = "Favorable";
				break;
				case 2:
					$avis = "Défavorable";
				break;
				default:
					$avis = "";
				break;					
			}
			
			try{
				$dossInfos->setVars('avisDossier', $avis, true, 'UTF-8');
			} catch (Exception $e){

			}
			
			$dossInfos->setVars('objetDossier', $dossierInfos['OBJET_DOSSIER'], true, 'UTF-8');
			
			if(isset($dossierInfos['infosEtab']['informations'])){
				$dossInfos->setVars('nomEtab', $dossierInfos['infosEtab']['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"], true, 'UTF-8');
				$dossInfos->setVars('categorieEtab', $dossierInfos['infosEtab']['informations']["LIBELLE_CATEGORIE"], true, 'UTF-8');
				$dossInfos->setVars('typeEtab', $dossierInfos['infosEtab']['informations']["LIBELLE_TYPE_PRINCIPAL"], true, 'UTF-8');
			}else{
				$dossInfos->setVars('nomEtab', "", true, 'UTF-8');
				$dossInfos->setVars('categorieEtab', "", true, 'UTF-8');
				$dossInfos->setVars('typeEtab', "", true, 'UTF-8');
			}
			
			$listeDocUrba = "";
			foreach($dossierInfos["listeDocUrba"] as $va => $docurb){
				$listeDocUrba .= $docurb['NUM_DOCURBA']."    ";
			}
			$dossInfos->setVars('numDocUrba', $listeDocUrba, true, 'UTF-8');

			*/

			//$dossInfos->merge(); 
			//echo "<span id='notif' class='ui-state-highlight' style='padding: 0.3em;'><a href='/data/uploads/pieces-jointes/".$idPj.".odt' >Le PV : ".$dossierInfos['infosEtab']['informations']["LIBELLE_ETABLISSEMENTINFORMATIONS"]." (".$dossierInfos['infosEtab']['parents'][0]["LIBELLE_ETABLISSEMENTINFORMATIONS"].")  a été généré</a></span><br/><br/>";
		} catch (Exception $e){

		}
	}
	$odf->mergeSegment($dossInfos);
	$nouvellePJ = savePj($this->idComm,"Compte rendu du ");
        
        $store = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getResource('dataStore');
        $path = $store->getFilePath($nouvellePJ, 'dateCommission', $this->idComm, true);
	$odf->saveToDisk($path);	
	//$odf->mergeSegment($dossierLoop);
	echo "<span id='notif' class='ui-state-highlight' style='padding: 0.3em;'>Le compte rendu a été généré avec succes</span><br/><br/><br/>";
}else{
	echo "<span id='notif' class='ui-state-error' style='padding: 0.3em;'>Le fichier de compte rendu pour la commission n'existe pas</span><br/><br/><br/>";
}


function savePj($dateCommId,$libelleDocument){
	//ENREGISTEMENT DANS PIECE JOINTES
	$dateDuJour = new Zend_Date();
	$DBpieceJointe = new Model_DbTable_PieceJointe;
	$nouvellePJ = $DBpieceJointe->createRow();
	$nouvellePJ->NOM_PIECEJOINTE = "Compte rendu";
	$nouvellePJ->EXTENSION_PIECEJOINTE = ".odt";
	$nouvellePJ->DESCRIPTION_PIECEJOINTE = $libelleDocument." ".$dateDuJour->get(Zend_Date::DAY."/".Zend_Date::MONTH."/".Zend_Date::YEAR." à ".Zend_Date::HOUR.":".Zend_Date::MINUTE);
	$nouvellePJ->DATE_PIECEJOINTE = $dateDuJour->get(Zend_Date::YEAR."-".Zend_Date::MONTH."-".Zend_Date::DAY." ".Zend_Date::HOUR.":".Zend_Date::MINUTE.":".Zend_Date::SECOND);
	$nouvellePJ->save();
	//ENREGISTEMENT DANS PIECE JOINTES
	$DBsave = new Model_DbTable_DateCommissionPj;
	$linkPj = $DBsave->createRow();
	$linkPj->ID_DATECOMMISSION = $dateCommId;
	$linkPj->ID_PIECEJOINTE = $nouvellePJ->ID_PIECEJOINTE;
	$linkPj->save();

	return $nouvellePJ;
}
	
?>