<?php $this->placeholder('lateral_navigation')->captureStart(); // Capture du 'lateral_navigation' ?>
<input type='hidden' name='idCommission' id='idCommission' value='<?php if($this->idComm){ echo $this->idComm; } ?>'/>
<ul class="nav nav-tabs nav-stacked menu_dashboard" >
    <li>
        <a href="#" id='commissionPj'><i class="icon-share icon-black"></i> Pièces jointes</a>
    </li>
    <li class="nav-header">Actions</li>
    <li>
        <a id='exportCom'  href='/calendrier-des-commissions/exportoutlook/dateCommId/<?php echo $this->infosDateComm['ID_DATECOMMISSION']; ?>' ><i class='icon-calendar'></i> Exporter pour Outlook</a>
    </li>
    <li>
        <a href="#" id='createConvoc'><i class="icon-file"></i> Générer Convocations</a>
    </li>
    <li>
        <a href="#" id='createOdj'><i class="icon-list-alt"></i> Génerer l'ordre du jour</a>
    </li>
    <li>
        <a href="#" id='createPv'><i class="icon-file"></i> Génerer PV</a>
    </li>
    <li>
        <a href="#" id='creationCompteRendu'><i class="icon-book"></i> Génerer le compte rendu</a>
    </li>
    <li>
        <?php if($this->infosDateComm['GESTION_HEURES'] == 1): ?>
                <a href="#" class="heures" id='non' onclick="return confirm('Confirmez vous de ne pas prendre en compte les heures ?');"><i class="icon-time"></i> Ne pas prendre en compte les heures</a>
        <?php else : ?>
                <a href="#" class="heures" id='oui' onclick="return confirm('Confirmez vous de prendre en compte les heures ?');"><i class="icon-time"></i> Prendre en compte les heures</a>
        <?php endif ?>
    </li>
</ul>
<?php $this->placeholder('lateral_navigation')->captureEnd(); ?>
<?php $this->placeholder('page_header')->captureStart();  ?>
    <h2 class="page-header">
    Ordre du jour de la <?php echo $this->infosCommissionType['LIBELLE_COMMISSIONTYPE'] ?> de <a href='/calendrier-des-commissions?idComm=<?php echo $this->infosDateComm["COMMISSION_CONCERNE"] ?>' ><?php echo $this->infosCommission['LIBELLE_COMMISSION'] ?></a> du <?php echo $this->dateFr ?>
    </h2>
<?php $this->placeholder('page_header')->captureEnd(); ?>
<?php $this->placeholder('before_content')->captureStart() // Capture du 'before_content' ?>
<?php $this->placeholder('before_content')->captureEnd() ?>

<script type="text/javascript">
$(document).ready(function() {

	$('#external-events div.external-event').each(function() {
		// create an Event Object (http://arshaw.com/fullcalendar/docs/event_data/Event_Object/)
		// it doesn't need to have a start or end
		var eventObject = {
			title: $.trim($(this).text()) // use the element's text as the event title
		};
		// store the Event Object in the DOM element so we can get to it later
		$(this).data('eventObject', eventObject);

		// make the event draggable using jQuery UI
		$(this).draggable({
			zIndex: 999,
			revert: true,      // will cause the event to go back to its
			revertDuration: 0  //  original position after the drag
		});

	});

	( function($) {
		$.fn.afficheCalendar = function(jour,mois,annee,hDeb,hFin) {
			//alert(jour+" "+mois+" "+annee+" "+hDeb+" "+hFin);
			var calendar = $('#calendar').fullCalendar( {
				date:jour,
				month:mois,
				year:annee,
				header: {
					left: '',
					center: 'title',
					right: ''
				},
				columnFormat : {
					month: 'dddd',
					week: 'dddd dd',
					day: 'dddd dd MMMM yyyy'
				},
				defaultView: 'agendaDay',
				timeFormat:'H:mm{ - H:mm}',
				allDaySlot: false,
				axisFormat: 'H(:mm)',
				slotMinutes: 5, //Permet d'afficher un interval de 10 minutes au lieu de 30 par défaut
				selectHelper: true,
				weekends: false,
				monthNames : ['Janvier','F\u00e9vrier','Mars','Avril','Mai','Juin','Juillet','Ao\u00fbt','Septembre','Octobre','Novembre','D\u00e9cembre'],
				monthAbbrevs : ['Jan','Fev','Mar','Avr','Mai','Juin','Juil','Aout','Sep','Oct','Nov','Dec'],
				dayNames : ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
				dayNamesShort : ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam','Dim'],
				lazyFetching: false, //permet de ne pas réafficher les évenements en cache
				minTime: hDeb,
				maxTime: hFin,
				editable: true,
				disableResizing: false,
				selectable: true,
				droppable: true,
				theme: true,
				aspectRatio: 0,
				defaultEventMinutes: 5,
				events: function(start, end, callback) {
					mois++;
					//jour++;
					var myDate = new Date(annee+"/"+mois+"/"+jour);

					$.ajax({
						url: '/calendrier-des-commissions/recupevenementodj?start='+myDate.getTime()+"&end="+myDate.getTime(),
						data: {
							format: 'json',
							dateCommId: $("#dateCommId").val(),
						},
						success: function( result ) {
							var events = [];
							for( var x in result["items"] ) {
								//alert(result["items"][x]["start"]);
								events.push({
									id: result["items"][x]["id"],
									title: result["items"][x]["title"],
									start: result["items"][x]["start"],
									end: result["items"][x]["end"],
									allDay: result["items"][x]["allDay"],
									url: result["items"][x]["url"],
									backgroundColor: result["items"][x]["backgroundColor"],
									textColor : "black"
								});
							}
							callback(events);
						}
					});
				},
				// Lorsque l'on selectionne une ou plusieurs dates on ouvre la boite de dialogue correspondante
				select: function(start, end, allDay) {
					$(this).fullCalendar('refetchEvents');

				},
				eventClick: function( event, jsEvent, view ) {
					/*
					// Boite de dialogue
					my_dialog("/calendrier-des-commissions/dialogcomm", "idComm="+$("#commissionId").val()+"&idDateComm="+event.id+"&do=edit");
					return false;
					*/
				},
				eventDrop: function( event, dayDelta, minuteDelta, allDay, revertFunc, jsEvent, ui, view ) {
					var heureDeb = event.start;
					var heureFin = event.end;

					var hrefTab = $(this).attr('href').split("/");
					var tailleTab = hrefTab.length;
					var idDossier = hrefTab[tailleTab-1];
					//alert('event drop');
					$.ajax({
						url: "/calendrier-des-commissions/dropodj?heureDebut="+heureDeb+"&heureFin="+heureFin,
						data: {
							format: 'json',
							dateCommId: $("#dateCommId").val(),
							idDossier : idDossier,
						},
						success: function( result ) {

						}
					});

				},
				drop: function(date, allDay) {
					var idDossier = $(this).attr('id');
					var verrou = "";
					$.ajax({
						url: "/calendrier-des-commissions/affecteDossOdj?datadebut="+date,
						async: false,
						data: {
							format: 'json',
							dateCommId: $("#dateCommId").val(),
							idDossier : idDossier,
						},
						success: function( result ) {
							verrou = result;
						}
					});
					// retrieve the dropped element's stored Event Object
					var originalEventObject = $(this).data('eventObject');
					// we need to copy it, so that multiple events don't have a reference to the same object
					var copiedEventObject = $.extend({}, originalEventObject);
					// assign it the date that was reported
					copiedEventObject.start = date;
                                        copiedEventObject.end = new Date(date.getTime() + 5*60000);
					copiedEventObject.url = "/dossier/index/id/"+idDossier;
					copiedEventObject.allDay = allDay;
					if(verrou == 1){
						copiedEventObject.backgroundColor = "#83bff6";
					}else{
						copiedEventObject.backgroundColor = "#E2A420";
					}
					copiedEventObject.textColor = "black";

					// render the event on the calendar
					// the last `true` argument determines if the event "sticks" (http://arshaw.com/fullcalendar/docs/event_rendering/renderEvent/)
					$('#calendar').fullCalendar('renderEvent', copiedEventObject, true);
					// is the "remove after drop" checkbox checked?
					// if so, remove the element from the "Draggable Events" list
					$(this).remove();
				},
				//eventResize: function( event, jsEvent, ui, view ) {
				eventResize: function( event,dayDelta,minuteDelta,revertFunc) {
					var dateFin = event.end;
					//var idDossier = $(this).attr('id');

					var hrefTab = $(this).attr('href').split("/");
					var tailleTab = hrefTab.length;
					var idDossier = hrefTab[tailleTab-1];

					//alert(dateFin);
					$.ajax({
						url: "/calendrier-des-commissions/resizeodj?dateFin="+dateFin,
						data: {
							format: 'json',
							dateCommId: $("#dateCommId").val(),
							idDossier : idDossier,
							//dateFin: dateFin,
						},
						success: function( result ) {
							//alert(result);
						}
					});
				}
			});
		}
	})(jQuery);

	var date;
	var myDate = new Date($("#dateOdj").val());

	//alert($("#heureDeb").val());
	//alert(myDate.getMonth());

	$("#calendar").afficheCalendar(myDate.getUTCDate(),myDate.getUTCMonth(),myDate.getUTCFullYear(),$("#heureDeb").val(),$("#heureFin").val());

	$(".fc-agenda-allday").hide();
	$(".fc-header").hide();

	/*
		INITIALISATION ET GESTION DES BOUTONS PJ, ODJ et CONVOC
	*/

	var dialogDateCommission = $('<div style="display:none"></div>').appendTo('body');

	dialogDateCommission.dialog({
		title: "Gestion des pièces jointes",
		modal: true,
		autoOpen: false,
		width: 800,
		height: 600,
		buttons: {
			"Terminer": function() {
				dialogDateCommission.dialog("close");
				return false;
			}
		},
		close: function(event, ui){

		}
	});


	$("#commissionPj").click(function(){
		$.ajax({
			type: "POST",
			url: "/piece-jointe?type=dateCommission&id="+$("#dateCommId").val(),
			success: function(msg){
				dialogDateCommission.html(msg);
				dialogDateCommission.dialog("open");
			}
		});

	});

	$("#createConvoc").click(function(){
		if($("#external-events").children("div").children("div").length == 0){
			$.ajax({
				url: "/calendrier-des-commissions/generationconvoc",
				data: "dateCommId="+$("#dateCommId").val(),
				type:"POST",
				//async: false,
				beforeSend: function(){
					$("#infoGeneration").html("Création en cours, veuillez patienter   <img src='/images/load.gif' />");
				},
				success: function(affichageResultat){
					$("#infoGeneration").html(affichageResultat);
				},
				error: function(){
					$("#infoGeneration").html("Une erreur s'est produite");
					return false;
				}
			});
		}else{
			$("#infoGeneration").html("<span id='notif' class='ui-state-error' style='padding: 0.3em;'>Certains dossiers prévus n'ont pas été placés dans le calendrier</span><br/><br/><br/>");
		}
	});

	$("#createOdj").click(function(){
		if($("#external-events").children("div").children("div").length == 0){
			$.ajax({
				url: "/calendrier-des-commissions/generationodj",
				data: "dateCommId="+$("#dateCommId").val(),
				type:"POST",
				//async: false,
				beforeSend: function(){
					$("#infoGeneration").html("Création en cours, veuillez patienter   <img src='/images/load.gif' />");
				},
				success: function(affichageResultat){
					$("#infoGeneration").html(affichageResultat);
				},
				error: function(){
					$("#infoGeneration").html("Une erreur s'est produite");
					return false;
				}
			});
		}else{
			$("#infoGeneration").html("<span id='notif' class='ui-state-error' style='padding: 0.3em;'>Certains dossiers prévus n'ont pas été placés dans le calendrier</span><br/><br/><br/>");
		}
	});

	$("#createPv").click(function(){
		if($("#external-events").children("div").children("div").length == 0){
			$.ajax({
				url: "/calendrier-des-commissions/generationpv",
				data: "dateCommId="+$("#dateCommId").val(),
				type:"POST",
				//async: false,
				beforeSend: function(){
					$("#infoGeneration").html("Création en cours, veuillez patienter   <img src='/images/load.gif' />");
				},
				success: function(affichageResultat){
					$("#infoGeneration").html(affichageResultat);
				},
				error: function(){
					$("#infoGeneration").html("Une erreur s'est produite");
					return false;
				}
			});
		}else{
			$("#infoGeneration").html("<span id='notif' class='ui-state-error' style='padding: 0.3em;'>Certains dossiers prévus n'ont pas été placés dans le calendrier</span><br/><br/><br/>");
		}
	});

	$("#creationCompteRendu").click(function(){
		if($("#external-events").children("div").children("div").length == 0){
			$.ajax({
				url: "/calendrier-des-commissions/generationcompterendu",
				data: "dateCommId="+$("#dateCommId").val(),
				type:"POST",
				//async: false,
				beforeSend: function(){
					$("#infoGeneration").html("Création en cours, veuillez patienter   <img src='/images/load.gif' />");
				},
				success: function(affichageResultat){
					$("#infoGeneration").html(affichageResultat);
				},
				error: function(){
					$("#infoGeneration").html("Une erreur s'est produite");
					return false;
				}
			});
		}else{
			$("#infoGeneration").html("<span id='notif' class='ui-state-error' style='padding: 0.3em;'>Certains dossiers prévus n'ont pas été placés dans le calendrier</span><br/><br/><br/>");
		}
	});

	$(".heures").click(function(){
		var gestionHeures = $(this).attr('id');
		$.ajax({
			url: "/calendrier-des-commissions/gestionheures",
			data: "dateCommId="+$("#dateCommId").val()+"&gestionHeure="+gestionHeures,
			type:"POST",
			beforeSend: function(){

			},
			success: function(affichageResultat){
				//alert(affichageResultat);
				window.location.reload();
			},
			error: function(){
				return false;
			}
		});

	});

	$( ".sortable" ).sortable({
		update: function(event, ui) {
			var listeDossierUpdate = new Array();
			var num = 0;
			$(".sortable > li").each(function(){
				//on parcour les li pour récolter les changements et mettre à jour dans la base
				$(this).attr('num',num);

				//on récupere l'id du dossier
				listeDossierUpdate.push($(this).children("div").attr('id'));

				num = num + 1;
			});
			//alert(listeDossierUpdate);
			$.ajax({
				url: "/calendrier-des-commissions/changementordre",
				data: "dateCommId="+$("#dateCommId").val()+"&ordreDossier="+listeDossierUpdate,
				type:"POST",
				beforeSend: function(){

				},
				success: function(affichageResultat){
					//alert(affichageResultat);
					return false;
				},
				error: function(){
					return false;
				}
			});
		}
	});

});

</script>
<style>
.fc-event-vert {
	border-width:1px;
}
</style>
<?php

	echo "
		<div>
			<input type='hidden' id='tempVerrou' value='' />
			<input type='hidden' name='dateOdj' id='dateOdj' value='".$this->infosDateComm['DATE_COMMISSION']."' />
			<input type='hidden' name='heureDeb' id='heureDeb' value='".$this->infosDateComm['HEUREDEB_COMMISSION']."' />
			<input type='hidden' name='heureFin' id='heureFin' value='".$this->infosDateComm['HEUREFIN_COMMISSION']."' />
			<h3>".$this->infosDateComm['LIBELLE_DATECOMMISSION'];

			echo "</h3>";

	echo "	<input type='hidden' name='dateCommId' id='dateCommId' value='".$this->infosDateComm['ID_DATECOMMISSION']."' />
		";


	if(count($this->recupCommLiees) > 1){
		echo "<h4 style='margin:0px;'>Autres dates de la commission</h4>";
		$i = 0;
		echo "<br/><table><tr>";
		foreach($this->recupCommLiees as $commLiees){
			// && $this->infosDateComm['DATECOMMISSION_LIEES']
			if($commLiees['ID_DATECOMMISSION'] != $this->infosDateComm['ID_DATECOMMISSION']){
				$dateLiees =  new Zend_Date($commLiees['DATE_COMMISSION'],'yyyy-MM-dd');
				echo "<td style='width:200px;text-align:center;' ><a href='/calendrier-des-commissions/gestionodj/dateCommId/".$commLiees['ID_DATECOMMISSION']."' >".$dateLiees->get(Zend_Date::WEEKDAY." ".Zend_Date::DAY_SHORT." ".Zend_Date::MONTH_NAME_SHORT." ".Zend_Date::YEAR,'fr')."</a></td>";
			}else{
				$dateLiees =  new Zend_Date($commLiees['DATE_COMMISSION'],'yyyy-MM-dd');
				echo "<td style='width:200px;text-align:center;' >".$dateLiees->get(Zend_Date::WEEKDAY." ".Zend_Date::DAY_SHORT." ".Zend_Date::MONTH_NAME_SHORT." ".Zend_Date::YEAR,'fr')."</td>";
			}
			if($i<5){

				$i++;
			}else{
				echo "</td></tr>";
				$i=0;
			}
		}
		echo "</table>";
		echo "<br/><br/>";
	}

	echo "
                <div id='infoGeneration'></div>
                <br/>
	";

	if($this->infosDateComm['GESTION_HEURES'] == 1){
		//dans le cas ou on prend en compte les heures (cas par défaut)
		echo "
			<div class='container-fluid'>
			<div class='row-fluid'>
				<div id='calendar' name='calendar' class='span9'>
				</div>
		";
		echo "
			<span style='margin-left:45px;color:black;font-size:15px;'>
				<span style='font-weight:bold;'>Dossier :</span>
				<span class='label' style='background-color:#83bff6;color:black;font-size:15px;'>Validé</span>
				<span class='label' style='background-color:#E2A420;color:black;font-size:15px;'>En attente de Validation</span>
			</span>
		";
		echo "
				<div id='external-events' class='span3' style='margin-top:5px;color:black;border:1px solid black;text-align:center;border-radius:10px 10px;-moz-border-radius:10px 10px; -webkit-border-radius:10px 10px;'>
					<div style='' >
		";

				echo "<h3>Liste des dossiers prévus</h3>";
				if( count($this->listeDossierNonAffect) != 0 ){
					foreach ($this->listeDossierNonAffect as $dossierNonAffect){
						if($dossierNonAffect['VERROU_DOSSIER'] == 1){
							$background = "#83bff6";
						}else{
							$background = "#E2A420";
						}
						echo "
							<div class='external-event eventExtODJ' id='".$dossierNonAffect['ID_DOSSIER']."' style='padding:5px 0 5px 15px;margin:5px;text-align:left;border:1px solid #9FC6FF;background-color:".$background.";border-radius:10px 10px;-moz-border-radius:10px 10px; -webkit-border-radius:10px 10px;'>
								<a href='/dossier/index/id/".$dossierNonAffect['ID_DOSSIER']."' style='color:black;'>
						";
						if(isset($dossierNonAffect['infosEtab'])){
							//si le dossier est attaché à un établissement
							echo $dossierNonAffect['infosEtab']['informations']['LIBELLE_ETABLISSEMENTINFORMATIONS' ];
						}

						if(isset($dossierNonAffect['infosEtab']['adresses'])){
							$nbAdresse = count($dossierNonAffect['infosEtab']['adresses']);
							if($nbAdresse != 0){
								echo " (";
								foreach($dossierNonAffect['infosEtab']['adresses'] as $commune){
									echo $commune['LIBELLE_COMMUNE'];
									if($nbAdresse != 1)
										echo ", ";
									$nbAdresse--;
								}
								echo ") ";
							}
						}else{
							echo " ( adresse non renseignée )";
						}


						if(isset($dossierNonAffect['infosEtab']['parents']) && isset($dossierNonAffect['infosEtab']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'])){
							echo " - ".$dossierNonAffect['infosEtab']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'];
						}
						echo "<br/>";
						if($dossierNonAffect['LIBELLE_DOSSIERNATURE'] != "")
						{
							echo $dossierNonAffect['LIBELLE_DOSSIERNATURE']."<br/>";
						}
						if($dossierNonAffect['OBJET_DOSSIER'] != "")
						{
							echo "Objet : ".$dossierNonAffect['OBJET_DOSSIER']."<br/>";
						}

						if(isset($dossierNonAffect['listeDocUrba']))
						{
							echo "Numéro document d'urbanisme : ";
							foreach($dossierNonAffect['listeDocUrba'] as $val => $ue){
								echo $ue['NUM_DOCURBA']." . ";
							}
						}

						//affichage preventionniste(s)
						if(isset($dossierNonAffect['preventionnistes'])){
							$nbPrev = count($dossierNonAffect['preventionnistes']);
							if($nbPrev >0){
								echo "<br/><span style='font-size:10px'>";
								foreach($dossierNonAffect['preventionnistes'] as $prev){
									echo $prev['NOM_UTILISATEURINFORMATIONS']." ".$prev['PRENOM_UTILISATEURINFORMATIONS'];
									if($nbPrev > 1)
										echo ", ";
									$nbPrev--;
								}
								echo "</span>";
							}
						}

						echo "
								</a>
							</div>
						";
					}
				}else{
					echo "<h5>Tous les dossiers ont déjà été affectés</h5>";
				}
				echo "
					</div>
				</div>
			</div>
			</div>
		";
	}else if($this->infosDateComm['GESTION_HEURES'] == 0){
		//dans le cas ou on ne prend pas en compte les heures (cas par défaut)
		echo "
			<h3 style='display:inline;'>Liste des dossiers prévus</h3>
		";
		echo "
			<span style='margin-left:50px;color:black;font-size:15px;'>
				<span style='font-weight:bold;'>Dossier :</span>
				<span class='label' style='background-color:#83bff6;color:black;font-size:15px;'>Validé</span>
				<span class='label' style='background-color:#E2A420;color:black;font-size:15px;'>En attente de Validation</span>
			</span>
		";
		echo "
			<ul class='unstyled sortable' id='listeDossierNoHours'>
		";
		//Zend_Debug::dump($this->listeDossierNonAffect);
		if( count($this->listeDossierNonAffect) != 0 ){
			foreach ($this->listeDossierNonAffect as $dossierNonAffect){
				if($dossierNonAffect['VERROU_DOSSIER'] == 1){
					$background = "#83bff6";
				}else{
					$background = "#E2A420";
				}
				echo "
					<li num='".$dossierNonAffect['NUM_DOSSIER']."' >
						<div class='dossierODJ external-event' id='".$dossierNonAffect['ID_DOSSIER_AFFECT']."' style='padding:5px 0 5px 15px;margin:5px;text-align:left;border:1px solid #9FC6FF;background-color:".$background.";border-radius:10px 10px;-moz-border-radius:10px 10px; -webkit-border-radius:10px 10px;'>
							<a href='/dossier/index/id/".$dossierNonAffect['ID_DOSSIER_AFFECT']."' style='color:black;' >
								".$dossierNonAffect['LIBELLE_ETABLISSEMENTINFORMATIONS'];

				$nbAdresse = isset($dossierNonAffect['infosEtab']['adresses']) ? count($dossierNonAffect['infosEtab']['adresses']) : 0;
				if($nbAdresse != 0){
					echo " (";
					foreach($dossierNonAffect['infosEtab']['adresses'] as $commune){
						echo $commune['LIBELLE_COMMUNE'];
						if($nbAdresse != 1)
							echo ", ";
						$nbAdresse--;
					}
					echo ") ";
				}else{
					echo " ( adresse non renseignée )";
				}

				if(isset($dossierNonAffect['infosEtab']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'])){
					echo " - ".$dossierNonAffect['infosEtab']['parents'][0]['LIBELLE_ETABLISSEMENTINFORMATIONS'];
				}
				echo "<br/>";

				if($dossierNonAffect['LIBELLE_DOSSIERNATURE'] != "")
				{
					echo $dossierNonAffect['LIBELLE_DOSSIERNATURE']."<br/>";
				}
				if($dossierNonAffect['OBJET_DOSSIER'] != "")
				{
					echo "Objet : ".$dossierNonAffect['OBJET_DOSSIER']."<br/>";
				}
				if(isset($dossierNonAffect['NUM_DOCURBA']))
				{
					echo "Numéro document d'urbanisme : ".$dossierNonAffect['NUM_DOCURBA'];
				}
				//affichage preventionniste(s)
				$nbPrev = isset($dossierNonAffect['preventionnistes']) ? count($dossierNonAffect['preventionnistes']) : 0;
				if($nbPrev >0){
					echo "<span style='font-size:10px'>";
					foreach($dossierNonAffect['preventionnistes'] as $prev){
						echo $prev['NOM_UTILISATEURINFORMATIONS']." ".$prev['PRENOM_UTILISATEURINFORMATIONS'];
						if($nbPrev > 1)
							echo ", ";
						$nbPrev--;
					}
					echo "</span>";
				}
				echo "
							</a>
						</div>
					</li>
				";
			}
		}else{
			echo "<h5>Aucun dossier n'est associé à cette commission</h5>";
		}
		echo "
			</ul>
		";

	}
