

<?php

	
	echo $this->headScript()->appendFile('/js/dossier/calendrier.js','text/javascript');

	if($this->idComm){
		//lorsque l'on affiche le calendrier depuis un ordre du jour
		$_GET["id"] = $this->idComm;
	}

	if( isset($_GET["id"]) ) {
		echo "
			<script type='text/javascript'>
				$(document).ready( function() {
					//alert('');
					$('#infosCom').html('<input type=\"hidden\" name=\"commissionId\" id=\"commissionId\" value=\"".$_GET['id']."\" />');
					$('#aff_calendar').button( 'option', 'disabled', false );
					$('#ordre_jour').button( 'option', 'disabled', false );
					$('#commissionSelect').val(".$_GET['id'].");
					$('#calendar').html('').afficheCalendar(".$_GET['id'].");
					$('#selectComm').hide();
				});
			</script>
		";
	}
?>

<!-- Titre -->
<h2>Calendrier des commissions</h2>

<select id='commissionSelect' class='bigger' >
	<option value='0'>Choix d'une commission ...</option>
	<?php foreach($this->array_commissions as $array_commission) : ?>
	<optgroup label='<?php echo htmlspecialchars($array_commission["LIBELLE"], ENT_QUOTES) ?>' >
		<?php foreach($array_commission["ARRAY"] as $item) : ?>
		<option value='<?php echo $item["ID_COMMISSION"] ?>' ><?php echo htmlspecialchars($item["LIBELLE_COMMISSION"], ENT_QUOTES) ?></option>
		<?php endforeach ?>
	</optgroup>
	<?php endforeach ?>
</select>

&nbsp;

<span class="label label-info">En salle</span>
<span class="label  label-success">Visite</span>
<span class="label label-warning">Groupe de visite</span>


<div id='infosCom' style='display:none;'></div>

<!-- Calendrier -->
<div id="calendar"></div>

<!-- Boite de dialogue -->
<div id="dialogComm" title="Planification commission" class='ui-helper-hidden' ></div>

<?php
	if(isset($_GET["idComm"])){
?>
		<script type="text/javascript">
			$("#commissionSelect").change();
		</script>
<?php
	}
?>