<a href='#' class='thumbnail text-center' style='width: 75px; font-size: .7em; float: left; overflow: hidden;' >
    <?php echo $this->avatar($this->uid, 'medium') ?>
    <div class="caption" style='padding: 1px'>
        <?php echo strtoupper($this->GRADE_UTILISATEURINFORMATIONS) . ' ' . strtoupper($this->NOM_UTILISATEURINFORMATIONS). ' ' . $this->PRENOM_UTILISATEURINFORMATIONS ?>
    </div>
</a>
