<?php $this->placeholder('before_content')->captureStart() // Capture du 'before_content' ?>

<?php if($this->action == "add" || $this->do == "new" ) : ?>
    <h2 class='grid_16'>Création d'un nouveau dossier</h2>
    <h3 class='grid_16' ><div style='margin:10px;' id='infosEtablissement'></div></h3>
<?php else : ?>
    <h3 class='grid_16' >
        <span style="color: #333333"><?php echo $this->libelleType; ?></span>
        <small><br/><?php echo nl2br($this->objetDossier) ?></small>
        <div style='margin:10px;' id='infosEtabs'></div>
    </h3>
    
    <ul id='onglets_horizontaux' class='grid_16' >
    
        <li class='<?php echo ( $this->action == "index" ) ? "selection_onglets_hor" : "read" ?>'>
            <a href='<?php echo $this->url(array("action"=>"index")) ?>'>Informations générales</a>
        </li>
        
		<?php
		
		if($this->libelleType == "Étude")
		{
			echo "
				<li class='".(( $this->action == "descriptif") ? "selection_onglets_hor" : "read" )."'>
					<a href='".$this->url(array("action"=>"descriptif"))."'>Descriptif ".(( $this->natureDossier == 1 || $this->natureDossier == 2 ) ? " des travaux" : "")."</a>
				</li>
			";
		}
		//$natureDossier
		?>
        
        <?php
        if( $this->idTypeDossier == 1 || $this->idTypeDossier == 2 || $this->idTypeDossier == 3 ){
            echo "
                <li class='".( ( $this->action == "textesapplicables" ) ? "selection_onglets_hor" : "read" )."'>
                    <a href='".$this->url(array("action"=>"textesapplicables"))."'>Textes applicables</a>
                </li>
            ";
        }
        ?>
        
        <li class='<?php echo ( $this->action == "docconsulte" ) ? "selection_onglets_hor" : "read" ?>'>
            <a href='<?php echo $this->url(array("action"=>"docconsulte")) ?>'>Documents consultés</a>
        </li>
        
        <li class='<?php echo ( $this->action == "prescription" ) ? "selection_onglets_hor" : "read" ?>'>
            <a href='<?php echo $this->url(array("action"=>"prescription")) ?>'>Prescriptions</a>
        </li>
        
        <li class='<?php echo ( $this->action == "liees" ) ? "selection_onglets_hor" : "read" ?>'>
            <a href='<?php echo $this->url(array("action"=>"liees")) ?>'>Établissements et dossiers liés</a>
        </li>
        
        <li class='<?php echo ( $this->action == "contact" ) ? "selection_onglets_hor" : "read" ?>' >
            <a href='<?php echo $this->url(array("action"=>"contact")) ?>'>Contacts</a>
        </li>
        
        <li class='<?php echo ( $this->action == "piece-jointe" ) ? "selection_onglets_hor" : "read" ?>' >
            <a style='border-right: none' href='<?php echo $this->url(array("action"=>"piece-jointe")) ?>'>Pièces jointes</a>
        </li>
        
    </ul>
    
<?php endif ?>

<div class='grid_16' >

<?php echo "<input type='hidden' name='idDossier' id='idDossier' value='".$this->idDossier."' />"; ?>

<?php $this->placeholder('before_content')->captureEnd() ?>


<?php $this->placeholder('after_content')->captureStart() // Capture du 'after_content' ?>

</div>

<script>
    $(document).ready(function(){

        if($("#infosEtabs").html() == ''){
            //cas d'affichage d'un dossier
            $.ajax({
                url: "/dossier/fonction",
                data: "do=infosEtabs&idDossier="+$("#idDossier").val(),
                type:"POST",
                beforeSend: function(){
                    
                },
                success: function(affichageResultat){				
                    $("#infosEtabs").html(affichageResultat);
                },
                error: function(){
                    return false;
                }
            });
        }else if($("#infosEtablissement").html() == ''){
            //cas de création d'un dossier depuis un établissement
            $.ajax({
                url: "/dossier/fonction",
                data: "do=infosEtabs&idEtablissement="+$("#idEtablissement").val()+"&type="+$("#do").val(),
                type:"POST",
                success: function(affichageResultat) {			
                    $("#infosEtablissement").html(affichageResultat);
                },
                error: function(){
                    return false;
                }
            });
        }
    });
</script>

<?php $this->placeholder('after_content')->captureEnd() ?>


<?php echo $this->render('layout.phtml') // Rendu du layout par défaut avec les placeholders ?>