<?php if($this->action != "add" && $this->do != "new" ) : ?>
<?php $this->placeholder('lateral_navigation')->captureStart(); // Capture du 'lateral_navigation' ?>
<input type='hidden' name='ID_CREATEUR' id='ID_CREATEUR' value='<?php echo $this->idUser; ?>' />	
<ul class="nav nav-tabs nav-stacked menu_dashboard" >
    <?php /*class="nav nav-tabs nav-stacked menu_dashboard"  */ ?>
        
        <li class="<?php echo ( $this->action == "index" ) ? "active" : "read" ?>">
            <a 
               href='<?php echo $this->url(array("controller" => "dossier", "id" => $this->idDossier), false, true) ?>'><i class="icon-info-sign icon-black"></i> Informations générales</a>
        </li>
        
	<?php		
            if($this->idTypeDossier == 1 && $this->natureDossier != 3 && $this->natureDossier != 9 && $this->natureDossier != 19) {
                echo "<li class='".(( $this->action == "descriptif") ? "active" : "read" )."'>
                        <a "
                        . "href='".$this->url(array("controller" => "dossier", "action"=>"descriptif", "id" => $this->idDossier), false, true)."'><i class=\"icon-book icon-black\"></i> Descriptif ".(( $this->natureDossier == 1 || $this->natureDossier == 2 ) ? " des travaux" : "")."</a>
                    </li>";
            }

            if ($this->idTypeDossier == 1 || $this->idTypeDossier == 2 || $this->idTypeDossier == 3 ) {
                echo "<li class='".( ( $this->action == "textes-applicables" ) ? "active" : "read" )."'>
                        <a "
                        . "href='".$this->url(array("controller" => "dossier", "action"=>"textes-applicables", "id" => $this->idDossier), false, true)."'><i class=\"icon-align-center icon-black\"></i> Textes applicables</a>
                    </li>";
            }

            if ($this->idTypeDossier != 5) {
                echo "<li class='".( ( $this->action == "docconsulte" ) ? "active" : "read" )."'>
                        <a  "
                            . "href='".$this->url(array("controller" => "dossier", "action"=>"docconsulte", "id" => $this->idDossier), false, true)."'><i class=\"icon-file icon-black\"></i> Documents consultés</a>
                    </li>";
            }

            if($this->natureDossier != 3 && $this->natureDossier != 40 && $this->natureDossier != 41 && $this->natureDossier != 42 && $this->natureDossier != 44 && $this->natureDossier != 31 && $this->natureDossier != 32 && $this->idTypeDossier != 5) {
                echo "<li class='".( ( $this->action == "prescription" ) ? "active" : "read" )."'>
                        <a  "
                        . "href='".$this->url(array("controller" => "dossier", "action"=>"prescription", "id" => $this->idDossier), false, true)."'><i class=\"icon-flag icon-black\"></i> Prescriptions</a>
                    </li>";
            }
	?>
		
        <li class='<?php echo ( $this->action == "liees" ) ? "active" : "read" ?>'>
            <a  
                href='<?php echo $this->url(array("controller" => "dossier", "action"=>"liees", "id" => $this->idDossier), false, true) ?>'><i class="icon-folder-open icon-black"></i> Établissements et dossiers liés</a>
        </li>
		
	<?php
            if($this->natureDossier != 40 && $this->natureDossier != 41 && $this->natureDossier != 42 && $this->natureDossier != 44) {
                echo "<li class='".( ( $this->action == "contact" ) ? "active" : "read" )."'>
                        <a  "
                        . "href='".$this->url(array("controller" => "dossier", "action"=>"contact", "id" => $this->idDossier), false, true)."'><i class=\"icon-user icon-black\"></i> Contacts</a>
                    </li>";
            }
	?>
        
        <li class='<?php echo ( $this->action == "piece-jointe" ) ? "active" : "read" ?>'>
            <a 
               href='<?php echo $this->url(array("controller" => "dossier", "action"=>"piece-jointe", "id" => $this->idDossier), false, true) ?>'><i class="icon-share icon-black"></i> Pièces jointes</a>
        </li> 
        <li class="nav-header">Actions</li>
        <?php
                $verrou = true;
                if ($this->verrou == 1  || (isset($action) && $action == 'new')) {
                        $label = "Déverrouiller";
                        $idLink = "DEVERROU";
                } else { 
                        $label = "Verrouiller";
                        $idLink = "VERROU";
                        $verrou = false;
                }
        ?>
        <li>
            <a class="sep" id="<?php echo $idLink; ?>" style='cursor:pointer;'><i class="icon-lock icon-black"></i> <?php echo $label; ?></a>
        </li>
        <?php if (!$verrou) : ?>
            <li>
                <a href="#" id="rapport"><i class="icon-refresh icon-black"></i> Générer un document</a>
            </li>
        <?php endif ?>
        <?php if (!$verrou && ($this->idDateCommissionAffect != null)) : ?>
        <li>
            <a class="sep" href='/calendrier-des-commissions/gestionodj/dateCommId/<?php echo $this->idDateCommissionAffect; ?>'><i class='icon-calendar icon-black'></i> Afficher ordre du jour</a>
        </li>
        <?php endif; ?>
    </ul>
<?php $this->placeholder('lateral_navigation')->captureEnd();
endif; ?>

<?php $this->placeholder('page_header')->captureStart();  //$this->placeholder('before_content')->captureStart() // Capture du 'before_content' ?>

<?php if($this->action == "add" || $this->do == "new" ) : ?>
    <h2 class="page-header">Création d'un nouveau dossier</h2>
    <h3 class="page-header"><div style='margin:10px;' id='infosEtablissement'></div></h3>
<?php else : ?>
    <h2 class="page-header">
        <span style="color: #333333"><?php echo $this->libelleType; ?></span>
        <small><br/><?php echo nl2br($this->objetDossier) ?></small>
        <div style='margin:10px;' id='infosEtabs'></div>
    </h2>
<?php endif ?>

<div class='grid_16' >

<?php echo "<input type='hidden' name='idDossier' id='idDossier' value='".$this->idDossier."' />"; ?>

<?php $this->placeholder('page_header')->captureEnd(); //$this->placeholder('before_content')->captureEnd() ?>


<?php $this->placeholder('after_content')->captureStart() // Capture du 'after_content' ?>

</div>

        <!-- Modal -->
		<div class="modal hide fade" tabindex="-1" id="modal-desc" >
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">x</button>
						<h3>Descriptif de l'établissement</h3>
					</div>
					<div class="modal-body">
						Chargement des éléments...
					</div>
					<div class="modal-footer">
						<a href="#" class="btn" data-dismiss="modal">Fermer</a>
					</div>
				</div>
			</div>
		</div>

<script>


	
    $(document).ready(function(){

        if($("#infosEtabs").html() == ''){
            //cas d'affichage d'un dossier
            $.ajax({
                url: "/dossier/getetabs",
                data: "do=infosEtabs&idDossier="+$("#idDossier").val(),
                type:"POST",
                beforeSend: function(){
                    $("#infosEtablissement").html("<img src='/images/load.gif' />");
                },
                success: function(affichageResultat){
                    $("#infosEtabs").html(affichageResultat);
                },
                error: function(){
                    return false;
                }
            });
        }else if($("#infosEtablissement").html() == ''){
            //cas de création d'un dossier depuis un établissement
            $.ajax({
                url: "/dossier/getetabs",
                data: "do=infosEtabs&idEtablissement="+$("#idEtablissement").val(),
                type:"POST",
				beforeSend: function(){
                    $("#infosEtablissement").html("<img src='/images/load.gif' />");
                },
                success: function(affichageResultat) {			
                    $("#infosEtablissement").html(affichageResultat);
                },
                error: function(){
                    return false;
                }
            });
        }
		
		$("#VERROU").live('click',function(){
			$.ajax({
					url: "/dossier/verrou",
					data: "idDossier="+$("#idDossier").val()+"&ID_CREATEUR="+$("#ID_CREATEUR").val(),
					type:"POST",
					//async: false,
					beforeSend: function(){
						$("#chargement").html("<img src='/images/load.gif' />");
					},
					success: function(affichageResultat){
						window.location= affichageResultat;
					},
					statusCode: {
							401:function(){
								alert("Vous n'êtes pas autorisé à effectuer cette action");
								$("#chargement").html("");
							},
					},
					error: function(){
							return false;
					}
			});
			return false;
		});
	
		$("#DEVERROU").live('click',function(){
			$.ajax({
					url: "/dossier/deverrou",
					data: "idDossier="+$("#idDossier").val(),
					type:"POST",
					//async: false,
					beforeSend: function(){
						$("#chargement").html("<img src='/images/load.gif' />");
					},
					success: function(affichageResultat){
						window.location= affichageResultat;
					},
					statusCode: {
						401:function(){
							alert("Vous n'êtes pas autorisé à effectuer cette action");
							$("#chargement").html("");
						},
					},
					error: function(){
							return false;
					}
			});
			return false;
		});
		
	$("#rapport").live('click',function(){
		//On charge le contenu de la boite de dialogue en Ajax (liste des établissements concernés)
		$.ajax({
			url: "/dossier/dialoggenrapport",
			data: "idDossier="+$("#idDossier").val(),
			type:"POST",
			//async: false,
			beforeSend: function(){

			},
			success: function(affichageResultat){
				$("#dialogComm").html('').html(affichageResultat).dialog({
					resizable: false,
					height:550,
					width:800,
					modal: true,
					title: 'Génération des rapports',
					buttons: {
						'Annuler': function() {
							$(this).dialog('close');
							$("#dialogComm").html('');
						}
					},
					close: function(event, ui){
						$("body").css('overflow','auto');
						$("#dialogComm").html('');
					}
				});				
			},
			error: function(){
				return false;
			}
		});
		
		return false;		
	});
	
	$("#generate").live('click',function() {
		var selected = false;
		$(".etabCheck").each(function(){

			if($(this).attr('checked')){
				selected = $(this).attr('checked');
			}

		});
		
		if(selected){
			$.ajax({
				url: "/dossier/generationrapport",
				data: $("#etabRapport").serialize()+"&idDossier="+$("#idDossier").val(),
				type:"POST",
				//async: false,
				beforeSend: function(){
					$("#dialogComm").html("<img src='/images/load.gif' />");
				},
				success: function(affichageResultat){
					var successMess = "<h3>Génération effectuée avec succès</h3><br/>";
					$("#dialogComm").html(successMess+affichageResultat);
					$("#dialogComm").append("Vous pouvez retrouver ces documents dans la partie pièces jointes");
				},
				error: function(){
					$("#dialogComm").html("<h3>Erreur lors de la génération du rapport</h3><br/>Si le problème persiste veuillez contacter votre administrateur");
					return false;
				}
			});
		}
		return false;		
	});
                
    });
</script>

<?php $this->placeholder('after_content')->captureEnd() ?>


<?php echo $this->render('dashboard.phtml') // Rendu du layout par défaut avec les placeholders ?>
