<!doctype html>
<html lang="fr" >

    <head>

        <?php include(APPLICATION_PATH . DS . 'layouts' . DS . 'includes' . DS . 'header.phtml'); ?>

    </head>

    <body class="error" >

        <div class="container">

            <?php echo $this->layout()->content ?>

            <p class='text-center'>
                <a class='btn btn-default' href='/'>Revenir sur l'accueil</a>
            </p>

        </div>

    </body>

</html>
