<!doctype html>
<html lang="fr" >

    <?php echo $this->render("includes/header.phtml"); ?>

    <body>
    
        <?php echo $this->render("includes/nav-main.phtml"); ?>
    
        <div id='wrapper'>
			<div id='layout-content' >

				<div class='container_16' >
                    <?php echo $this->render("includes/notifications.phtml"); ?>
					<?php echo $this->layout()->content; ?>
				</div>
				
			</div>
		</div>
        
        <?php echo $this->render("includes/footer.phtml"); ?>

    </body>
    
</html>