<!doctype html>
<html lang="fr" >

    <head>

        <style>body { padding-top: 80px; }</style>
        <?php echo $this->render("includes/header.phtml"); ?>

    </head>

    <body>

        <?php echo $this->render("includes/nav-main.phtml"); ?>

        <div class='container-fluid' >

            <?php echo $this->render("includes/notifications.phtml"); ?>

            <?php echo $this->placeholder('before_content') ?>

            <?php echo $this->layout()->content; ?>

            <?php echo $this->placeholder('after_content') ?>

        </div>

        <?php echo $this->render("includes/footer.phtml"); ?>

        <script type="text/javascript" src="/js/jquery.stickyfooter.js"></script>

    </body>

</html>
