<?php $this->placeholder('lateral_navigation')->captureStart(); // Capture du 'lateral_navigation' ?>
        <ul class="nav nav-tabs nav-stacked menu_dashboard" >
            <li><a href='../etablissement/add'><i class="icon-plus"></i> Ajouter un établissement</a></li>
            <li><a href='../dossier/add'><i class="icon-plus"></i> Ajouter un dossier</a></li>
        </ul>
<?php $this->placeholder('lateral_navigation')->captureEnd(); ?>

<?php $this->placeholder('before_content')->captureStart() // Capture du 'before_content' ?>

<?php $this->placeholder('before_content')->captureEnd() ?>

<?php echo $this->render('dashboard.phtml') // Rendu du layout par défaut avec les placeholders ?>