<!doctype html>
<html lang="fr" >

    <head>

        <?php echo $this->render("includes/header.phtml"); ?>

    </head>

    <body class='login' >

        <div class="wrapper">
        
            <div class="block">

                <h1 class='text-center'>
                    <img src='/images/logo_prevarisc_big.jpg' alt='Prevarisc' />
                </h1>
            
                <div class='well'>

                    <?php echo $this->render("includes/notifications.phtml"); ?>

                    <?php echo $this->layout()->content; ?>  

                </div>
                
                <?php echo $this->render("includes/footer.phtml"); ?>
                
            </div>
            
        </div>
        
	</body>
    
</html>