<?php $this->placeholder('before_content')->captureStart() // Capture du 'before_content' ?>

<div class='row-fluid'>
    <div class='span2'>

        <div class="well nav-left" style="padding: 8px 0;">
            <ul class="nav nav-list">
            
                <li class="nav-header">Général</li>
                <li><a href='/admin'><i class="icon-cog"></i>Administration système</a></li>
                <li><a href='/calendrier-des-commissions' ><i class="icon-calendar"></i>Calendrier des commissions</a></li>
                <li><a href='/about/support' ><i class="icon-exclamation-sign"></i>Aide</a></li>
                
                <li class="nav-header">Paramétrage du logiciel</li>
                <li><a href='/periodicite' ><i class="icon-th-list"></i>Tableau des périodicités</a></li>
                <li><a href='/gestion-des-communes' ><i class="icon-th-list"></i>Gestion des communes</a></li>
                <li><a href='/groupement' ><i class="icon-th-list"></i>Groupements de communes</a></li>
                <li><a href='/gestion-des-commissions' ><i class="icon-th-list"></i>Gestion des commissions</a></li>
                <li><a href='/gestion-des-documents' ><i class="icon-th-list"></i>Gestion des documents</a></li>
                <li><a href='/gestion-prescriptions' ><i class="icon-th-list"></i>Gestion des prescriptions</a></li>
                <li><a href='/gestion-textes-applicables' id='gestionTextesAppl' ><i class="icon-th-list"></i>Gestion des textes applicables</a></li>
                
                <li class="nav-header">Fil d'actualités</li>
                <li class='' ><a href='/'><i class="icon-home"></i>Tous les messages<span class="count ui-helper-hidden">0</span></a></li>
                
                <li class="nav-header">Actions</li>
                <li><a href='/etablissement/add' ><i class="icon-plus"></i> Ajouter un établissement</a></li>
				<li><a href='/dossier/add' ><i class="icon-plus"></i> Ajouter un dossier</a></li>
                
            </ul>
        </div>
    </div>

    <div class='span10' >

<?php $this->placeholder('before_content')->captureEnd() ?>


<?php $this->placeholder('after_content')->captureStart() // Capture du 'after_content' ?>

    </div>
</div>

<?php $this->placeholder('after_content')->captureEnd() ?>


<?php echo $this->render('layout.phtml') // Rendu du layout par défaut avec les placeholders ?>